### PR TITLE
PR: Add single click to open files on file and project explorer

### LINKED ISSUE #8930: Single click to interact with items in Project Explorer, rather than double-click
I've recently switched from VSCode to Spyder and a minor annoyance for me is that in Spyder I have to double-click to interact with items in the Project Explorer. By "interact", I mean open and closing folders and opening documents.

In VSCode, you only have to single-click and, even though it might seem like hardly any difference, I think single-clicking is a better user experience.

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Wrote tests
* [x] Added screenshots

### Issue(s) Resolved

Fixes #8930

Screen Shot 2019-03-28 at 23 06 52

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by ccordoba12** [comment]
@goanpeca, perhaps we should add an option to control this? I mean, I'm not a fan of single clicking so I have it disabled in my laptop and all my VMs. But I understand other people likes this behavior.

**Comment by goanpeca** [comment]
Sure. I will add it. Should this be the default behavior?

**Comment by ccordoba12** [comment]
I think double-clicking should be the default behavior because it's also the default on Windows and macOS file explorers.

**Comment by goanpeca** [comment]
@ccordoba12 the explorer plugin currently does not have preferences.

Everything is defined in the context menu. Should I define it there, or is it time to have a dedicated preferences pane?

Screen Shot 2019-03-28 at 17 23 02

**Comment by goanpeca** [comment]
@ccordoba12 this one is ready. I took the liberty of making the options in the menu permanent by reading from the config on startup and updating the config on change

**Comment by goanpeca** [comment]
Ping @dbouchard3 for testing!

**Comment by ccordoba12** [comment]
@CAM-Gerlach, could you also help us to test this one? Thanks!

**Comment by goanpeca** [comment]
I will add a test!

**Comment by CAM-Gerlach** [comment]
Also, @goanpeca , you should affirm the DCO at the bottom of the PR template.

**Comment by goanpeca** [comment]
>Also, this option also makes clicking on any directory open only that directory in the File Explorer and set the working dir to that directory. Is that the intended behavior?

Yes, maybe this setting should only pally to files?

**Comment by goanpeca** [comment]
>get the following error any time I click once on anything in the File Explorer (file, directory, expand arrow) in a clean or non-clean config on both Windows 8.1 and Fedora 28, so long as I haven't modified the setting yet in the current session (after modifying it at least once, it works for both values).

Will work on a fix for this :-)

**Comment by ccordoba12** [comment]
> Yes, maybe this setting should only pally to files?

No, it has to apply to files and directories alike.

> Finally, does the config minor version need to be bumped with an added setting, or is that not needed for a non-preferences option?

No, adding options doesn't require a bump in CONF_VERSION.

**Comment by goanpeca** [comment]
Ok testing this took way longer than expected 😓  , but I think it should be working now 😅

**Comment by goanpeca** [comment]
@CAM-Gerlach could you please check the error you had is no longer there?

**Comment by goanpeca** [comment]
Thanks @CAM-Gerlach 😄!

---

@ccordoba12 any additional comments?

**Pull request merged**
