### PR TITLE
PR: Add some instructions for maintainers

### PR DESCRIPTION
**Pull request by ccordoba12**
This details several things that maintainers need to know for their job.

@dalthviz, please take a look at this one.

### CODE REVIEW

**Review by dalthviz — COMMENTED** [review]
Thanks @ccordoba12 checking maybe should be worthy to add too the handling of spyder-kernels PRs that close issue in Spyder but don't modify code inside Spyder directly? (merge in Spyder kernels, PR in Spyder to update the subrepo, etc). Also this could be the place to add the info about how to configure the automatic messages used for issues

**Comment by ccordoba12** [comment]
Thanks @dalthviz for the review. I added the instructions to perform the extra tasks you mentioned above.

**Review by dalthviz — COMMENTED** [review]
Thanks @ccordoba12 I was checking and maybe this file should be added to the [`setup.cfg`](https://github.com/spyder-ide/spyder/blob/master/setup.cfg)? Other than that this LGTM :+1:

**Comment by ccordoba12** [comment]
> Thanks @ccordoba12 I was checking and maybe this file should be added to the setup.cfg?

Good point! I did that in my last commit.

**Review by dalthviz — APPROVED** [review]
Thanks @ccordoba12 LGTM :+1:

**Pull request merged**
