### PR TITLE
don't recommand IPython below2.0

### PR DESCRIPTION
**Pull request by stonebig**

### CODE REVIEW

**Comment by ccordoba12** [comment]
Well, technically Spyder (since 2.3.3) can work with IPython 1.0...

**Comment by blink1073** [comment]
I'm with @stonebig, even if it technically does work pre-1.0, we should not limit ourselves to supporting that different of an API moving forward.

**Comment by stonebig** [comment]
`recommanded' is the word that should suggest currently well supported packages and `way of workings`. Spyder should recommand 2.4.1+, if it wants to be a good adviser

**Comment by ccordoba12** [comment]
The dependencies mentioned in our README are not suggestions, are the minimum required versions.

This is my plan for IPython:

* Spyder 2.3.3 and 2.3.4 will work with IPython 1.0+
* Spyder 2.4 will work only with IPython 3.0+ (for the notebook integration)

Since this PR is against master, I'd suggest to change the dependency for 3.0+. But for that we will have to wait until 3.0 is released :-)

**Comment by stonebig** [comment]
will the notebook integration work for qt4 ?

**Comment by ccordoba12** [comment]
Nop, it won't work. Qt5 is needed for the notebook because it has a more up to date QtWebkit module.

I don't understand what you mean by *retirement*. Qtconsole is going to be maintained (most probably) by us and the Enthought guys after the IPython repo is broken in components.

**Comment by stonebig** [comment]
ok, that's great if Qtconsole remains well maintained for 4.0

**Comment by ccordoba12** [comment]
@stonebig did you close this one because you prefer me to do the change?

**Comment by stonebig** [comment]
yes, to your timing and wording. it was rather a suggestion than an issue

**Comment by jondo** [comment]
By the way, it's "recomm**e**nd", not "recommand".

**Pull request closed without merging**
