### PR TITLE
PR: Add validation for mimedata2url in Editor's dragEnterEvent

### LINKED ISSUE #5218: Error when drag and drop file from zip
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**
Tried to drag and drop file into Spyder. Gave me error and took me here. 

**Please provide any additional information below**

  File "C:\Users\david.antonini\AppData\Local\Continuum\Anaconda3\lib\site-packages\spyder\widgets\editor.py", line 2171, in dragEnterEvent
    text = [encoding.is_text_file(url) for url in all_urls]
TypeError: 'NoneType' object is not iterable

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.6 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.1.1 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #5218

### CODE REVIEW

**Comment by dalthviz** [comment]
@ccordoba12 a preview (Windows):

zip

**Comment by ccordoba12** [comment]
What about Linux? Does it work there too?

**Comment by dalthviz** [comment]
I tried in Ubuntu but I don't manage to open a file from outside the File Explorer (with the change that this PR made or without it - current version):

zipu

**Comment by ccordoba12** [comment]
Ok, no problem. At least the error won't show up anymore and it fixes things on Windows.

**Pull request merged**
