### PR TITLE
PR: Add "find_replace" widget to qtbot in fixtures of "test_editor.py"

### PR DESCRIPTION
**Pull request by jnsebgosselin**
## Description of Changes

This is a simple proposition to make the `find_replace` widget window close automatically after each test in `test_editor.py`.

Otherwise, it looks like this after running pytest on `.\spyder\plugins\editor\widgets\tests\test_editor.py`:

image

### CODE REVIEW

**Comment by jnsebgosselin** [comment]
This is also to check if tests are passing with the latest version of master to help me debug my PR on keyboard shortcuts...

**Comment by jnsebgosselin** [comment]
I think most of the tests on Travis are failing for the error I've reported in PR #7790.

I doubt these errors are related to the very minor changes I've made in this PR...

**Comment by jnsebgosselin** [comment]
And the same tests as for my PR on keyboard shortcuts are timing out on AppVeyor as well. This is a "good news".

I'm going to propose a new PR to skip them.

**Comment by ccordoba12** [comment]
@jnsebgosselin, please rebase to see if our tests pass now.

**Pull request merged**
