### PR TITLE
PR: Fix several code snippets corner cases

### LINKED ISSUE #10230: Several errors with code snippets
### What steps will reproduce the problem?

e.g. when typing pd.cont <TAB> 
it completes the function as:
pd.concat(objs)⌷

### Traceback
```python-traceback
  File "/home/dbau/miniconda3/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 194, in _on_key_pressed
    self._process_text(text)
  File "/home/dbau/miniconda3/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 49, in wrapper
    return f(self, *args, **kwargs)
  File "/home/dbau/miniconda3/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 204, in _process_text
    self.delete_text(line, column)
  File "/home/dbau/miniconda3/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 240, in delete_text
    self._delete_token(delete_token, text_parent, line, column)
  File "/home/dbau/miniconda3/envs/spyder-beta/lib/python3.7/site-packages/spyder/plugins/editor/extensions/snippets.py", line 263, in _delete_token
    if left_node.name in MERGE_ALLOWED:
AttributeError: 'PlaceholderNode' object has no attribute 'name'
```

## Versions

* Spyder version: 4.0.0b5 
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-60-generic

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.1 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.0.2 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.6.1 (OK)
matplotlib >=2.0.0           :  3.1.1 (OK)
pandas >=0.13.1              :  0.24.2 (OK)
numpy >=1.7                  :  1.16.4 (OK)
scipy >=0.17.0               :  1.3.0 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
xdg >=0.26                   :  0.26 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

### LINKED ISSUE #10289: crash in 4.0.0b5 related to non-ascii characters and tooltips
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [X] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [X] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [X] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

The program crashes as described below. It seems to be related to the non-ascii character in the function signature; when I tried replacing `blah(λ,x)` with `blah(w,x)`, everything works fine.

### What steps reproduce the problem?

1. Copy the following into a new python file, and save it:

```
# -*- coding: utf-8 -*-

def blah(λ,x):
    return λ + x

```

2. On a new line, type "bla". The tooltip / autocomplete thing will prompt with the completion: `blah(λ,x)`.

3. Press tab to accept this suggestion.

### What is the expected output? What do you see instead?

It should fill in the missing letter "h" to make the word "blah". Instead, the program crashed.

## Versions

* Spyder version: 4.0.0b5
* Python version: 3.7.4 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 10

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  3.1.0 (OK)
pandas >=0.13.1              :  0.25.0 (OK)
numpy >=1.7                  :  1.16.4 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)

```

### PR DESCRIPTION
**Pull request by andfoy**
## Description of Changes
This PR addresses all of the code snippets errors reported on #10230 

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #10289.
Fixes #10230

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@andfoy

### CODE REVIEW

**Comment by andfoy** [comment]
@ccordoba12  @dalthviz, does this PR adresses all of your errors with code snippets?

**Comment by ccordoba12** [comment]
Thanks @andfoy! There are still some things not covered by this PR:

* `Tab` should not cycle among snippets but simply remove the snippet regions after reaching the last one.
* When you manually remove the text of a snippet, the snippet region should be removed too.

**Comment by ccordoba12** [comment]
A couple more issues:

* Pressing `Ctrl+Z` or `Crtl+X` after editing a snippet doesn't restore the snippet positions. For example, in the screenshot below I removed the `nc` characters of `func` with backspace then press `Ctrl+Z` and got this result:

Selección_017
 
* If you manually move with the left/right arrow keys out of a snippet region, then all snippet regions should be removed. That's what VSCode does and I think it's a good approach.

**Comment by ccordoba12** [comment]
One more: if enter the following code

```python
from pandas import pd
pd.concat(objs)
```

and replace `objs` by `as` and other characters in quick sucession, then Spyder freezes (it's not always reproducible, but most of the time). After unfreeze it with a `Ctrl+C` in the terminal, I've got the following traceback related to snippets:

```python-traceback
Traceback (most recent call last):
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/editor/extensions/snippets.py", line 201, in _on_key_pressed
    self._process_text(text)
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/editor/extensions/snippets.py", line 49, in wrapper
    return f(self, *args, **kwargs)
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/editor/extensions/snippets.py", line 209, in _process_text
    self.insert_text(text, line, column)
  File "/home/carlos/Projects/spyder/github-repo/spyder/plugins/editor/extensions/snippets.py", line 335, in insert_text
    tokens = tokenize(text)
  File "/home/carlos/Projects/spyder/github-repo/spyder/utils/snippets/lexer.py", line 91, in tokenize
    if regex.match(temp_word) is not None:
```

**Comment by andfoy** [comment]
> Pressing Ctrl+Z or Crtl+X after editing a snippet doesn't restore the snippet positions. For example, in the screenshot below I removed the nc characters of func with backspace then press Ctrl+Z and got this result:

I'm very aware of this case, this is due to the Ctrl+Z behaviour of the CodeEditor, as opposed to the snippets one, while the first deletes the last sequence of characters, the latter stores a tree copy for n and c keypresses. Thus, when the undo call is applied, we backtrack to the "n" tree, rather to delete the "n" and "c" trees.

Is there any way to get the length of the undo text?

**Comment by ccordoba12** [comment]
You'll have to look for it because I don't know, sorry.

**Comment by goanpeca** [comment]
@andfoy if I do the following

```
import json
# Entering snippet mode, then selecting all (while I still see the snippet squares) and delete everything I get
json.dumps(123, 123)

```
```python-traceback

    self.insert_text(text, line, column)
  File "/Users/gpena-castellanos/Google Drive/develop/quansight/spyder/spyder/plugins/editor/extensions/snippets.py", line 339, in insert_text
    if node.name == 'EPSILON':
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by andfoy** [comment]
> @andfoy if I do the following

Does this happens with this PR?

**Comment by goanpeca** [comment]
Yes, it still happens qith this Pr

**Comment by andfoy** [comment]
@goanpeca Could you please and try again?

**Comment by goanpeca** [comment]
Sure! After lunch 🥗:-)

**Comment by goanpeca** [comment]
>@goanpeca Could you please and try again?

The latest fixes the issue @andfoy

**Comment by andfoy** [comment]
@ccordoba12 Does the last commit fixes all the undo behaviour?

**Comment by ccordoba12** [comment]
@andfoy, I'm still seeing https://github.com/spyder-ide/spyder/pull/10256#issuecomment-533066206 with this PR.

**Comment by andfoy** [comment]
@ccordoba12 I cannot reproduce that one:

ezgif com-video-to-gif(12)

**Comment by ccordoba12** [comment]
@andfoy, `test_code_snippets` is hanging now.

**Comment by andfoy** [comment]
@ccordoba12 The azure test fail is unrelated to this one

**Comment by ccordoba12** [comment]
@andfoy, please skip `test_code_snippets` on Windows, that could make our test suite pass there (I don't have time right now to analyze what's the problem that that test seems to be introducing).

**Pull request merged**
