### PR TITLE
PR: Give focus to right entry in the file switcher

### LINKED ISSUE #4636: Focus doesn't go to the selected entry in file switcher when filtering
There are two minor bugs I saw after PR #4626:

1. If you write some text to filter your files/notebooks, the selected entry remains in the plugin title, instead of the file/notebook itself. This is a screenshot to show what I mean:

    seleccion_001

2. In the screenshot you can also see that there's too much padding above the **Editor** title (at least for me on Linux). Please try to remove some of that padding.

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #4636

### CODE REVIEW

**Comment by ccordoba12** [comment]
Please post a screenshot to see how things look.

**Comment by dalthviz** [comment]
Preview:

fileswitcher

**Comment by ccordoba12** [comment]
Ok, this is looking good, but now you removed all top padding from the plugin title on Linux:

seleccion_001

So, please add some padding, but not as much as before ;-)

**Comment by dalthviz** [comment]
Preview Ubuntu:

ubuntu

**Comment by ccordoba12** [comment]
Thanks @dalthviz!

**Pull request merged**
