### PR TITLE
PR: Update placeholder text in Online Help plugin

### LINKED ISSUE #13684: Differences in online help pane toolbar
## Problem Description
The toolbar of the Online Help pane has some differences in master and 4.x,

1. First the buttons are in a complete different order
**Master**
image

**4.x**
image

2. Placeholder text is different
**Master**
image

**4.x**
image

### What is the expected output? What do you see instead?
The online help pane should look the same as 4.x

### PR DESCRIPTION
**Pull request by goanpeca**
### Issue(s) Resolved

Fixes #13684

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @steff456, thanks for the feedback

https://github.com/spyder-ide/spyder/pull/13600 fixed that already. I rebased with master.

**Review by steff456 — APPROVED** [review]
@dalthviz, with the rebase now this PR is ready for merge as soon as all tests pass

Thanks @goanpeca!

**Review by dalthviz — APPROVED** [review]
Thanks @goanpeca LGTM :+1:

**Pull request merged**
