### PR TITLE
Better browse_history

### PR DESCRIPTION
**Pull request by impact27**
Prevent browse_history from returning the same text

### CODE REVIEW

**Comment by impact27** [comment]
Why do I get an email from PEP8 Speaks complaining about W293 blank line contains whitespace if the comment above doesn't say anything?

**Comment by csabella** [comment]
@impact27   Is there an open issue for this? If not, could you explain what your fix does?  I apologize if it's a dumb question, but I don't understand how to recreate it based on the description 'Prevent browse_history from returning the same text'.  Thanks!

**Comment by impact27** [comment]
Sorry, I opened  #6295

**Comment by CAM-Gerlach** [comment]
Since this is a such a small change, is a pretty big bang for your buck improvement in quality of life (at least in your case, and mine as well), and arguably fixes an annoying "bug" at least in the UX rather than adding anything truly new, is there a particular reason why it should be based against ``master`` vs. ``3.x``, given that if the former neither you nor anyone will see it for at least a year?

**Comment by CAM-Gerlach** [comment]
But seriously, @impact27 thanks for doing this! I had it deep in the queue to be completed someday as it frustrated me too, but certainly wouldn't have gotten to it for a while if it wasn't for your help.

**Comment by csabella** [comment]
@impact27   Thanks for opening the issue with the explanation.  It makes sense now.  :-)

**Comment by csabella** [comment]
@impact27   I tested this out locally and it's crashing my system on the down key, so with the current patch, that needs to be looked at.

However, I'm wondering if it would be better to just not add duplicates to the history at all instead of skipping ones that are the same.

**Comment by impact27** [comment]
That makes sense but I am unsure if the history is useful somewhere else. It is not really a history if you don't record everything?
Also should the pdb commands be saved at all? (u, d, s, n, ...) 
I am not sure if it is not something different conceptually (pdb command vs python code).
I can see it crashing too, I forgot to check if the end of history was reached (I only have the beginning). I will do that soon.

**Comment by csabella** [comment]
@impact27 In the non-debugging history of the console itself, consecutive duplicates aren't stored, so changing the debugging history would make it consistent with that.

For example, if you type the following into the console:
```
a = 5
b = 10
a = 5
a = 5
a = 5
```
and then look at the History Log tab, you'll see:
```
## ---(Thu Jan 25 08:18:15 2018)---
a = 5
b = 10
a = 5
```

So, it stored `a = 5` twice because they were non-consecutive, but the other `a = 5` after that were not recorded.  I think it would be reasonable for the debugging history to do the same.

**Comment by impact27** [comment]
I opened #6301 which prevents a same line to be added to history

**Comment by ccordoba12** [comment]
Thanks @impact27! Should we close this one then?

**Pull request closed without merging**
