### PR TITLE
PR: Check if files are text files using the binaryornot package

### LINKED ISSUE #3631: Edit context menu appears only for utf-8 files in project explorer
## Description of your problem

I created a new project from an existing folder. Some .py-files in the Project explorer had an "Edit" context menu, others only an "Open" context menu. Drag and drop into the editor would also not work. 

A short look in the sources revealed that in explorer.py line 261:
def create_file_manage_actions
only utf encoded files are accepted as editable. 

I have no problem with this behavior but it should be easy to find in the documentation. 

**What steps will reproduce the problem?**

1. Create a .py file with ANSI encoding and try the context menu

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 3.5.2
* Operating system: Win 10

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.2 (OK)
pandas >=0.13.1  :  0.19.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.3.1 (OK)
sympy >=0.7.3    :  1.0 (OK)

### LINKED ISSUE #3670: Dragging and dropping files in the Editor is failing
## Description of problem

I've just upgraded from Spyder 2.x to Spyder 3.x, and noticed it is no longer possible to drag-and-drop files to open them. Not sure if this is intentional functionality or not, but opening files on windows now has become a bit clunky.

**Try the following steps to reproduce the problem:**

1. Have Spyder 3.0.x version installed
2. Open Spyder & drag drop .py file into editor

**Expected and given output:**

Based on the previous version of Spyder, I expect dragging and dropping in a file to open that file in the editor, instead it's copying the file location.

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 3.5
* Operating system: Windows 10

### PR DESCRIPTION
**Pull request by rlaverde**
~~Add misc.is_supported_file function, and use it instead of encoding.is_text_file~~

**EDIT**
Add [binaryornot](https://github.com/audreyr/binaryornot) package  and use it to determinate if a file is text

Fixes #3631 
Fixes #3670

### CODE REVIEW

**Comment by ccordoba12** [comment]
@rlaverde, what you did is an easy workaround because the main problem is that `is_text_file` is failing for files with an encoding different from `utf-8` and with non-ascii characters on them.

The right fix (after reading the Stackoverflow post where `is_text_file` comes from) is to define a new function called `is_binary_file` (in `utils/encoding.py`):

```python
def is_binary(filename):
    """Return true if the given filename is binary.

    Taken from: http://stackoverflow.com/a/3002505

    author: Trent Mick <TrentM@ActiveState.com>
    author: Jorge Orpinel <jorge@orpinel.com>
    """
    fin = open(filename, 'rb')
    try:
        CHUNKSIZE = 1024
        while 1:
            chunk = fin.read(CHUNKSIZE)
            if b'\0' in chunk: # found null byte
                return True
            if len(chunk) < CHUNKSIZE:
                break # done
    finally:
        fin.close()

    return False
```

and redefine `is_text_file` to be

```python
def is_text_file(filename):
    """
    Test if the given path is a text-like file.
    """
    not is_binary_file(filename)
```

**Comment by ccordoba12** [comment]
On a second thought. it seems more reliable to use an external package for this. Please add this package: https://github.com/audreyr/binaryornot to `utils/external`, import its function called `is_binary` in `utils/encoding.py` and define `is_text_file` in the same way as above.

----

Note: Since this is needed for `3.x` we can't add a new dependency on that package. Besides, it's very small and it seems to move very slowly :-)

**Comment by rlaverde** [comment]
@ccordoba12 I added binaryornot and change `is_text_file` function as you suggested, should I create a PR against master adding the package as a dependency?

**Comment by ccordoba12** [comment]
> should I create a PR against master adding the package as a dependency?

Not right now because that will force Continuum and Linux distros to create `binaryornot` packages in their respective repos.

Since it's a very small package, I think we can live with it in our repo for now :-)

**Comment by rlaverde** [comment]
[chardet](https://github.com/chardet/chardet) module is missing, should I also include it? (It isn't a tiny one)

**Comment by ccordoba12** [comment]
> chardet module is missing

I didn't notice that! Thanks for noticing it ;-)

> should I also include it? (It isn't a tiny one)

Nop, please don't (especially if it's not tiny :-). What that heck, please add `chardet` to our setup.py,  conda.recipe, README.md and doc/installation.rst.

I don't think Ubuntu is going to pick up **3.1** for 17.04, so I don't see problems in adding a new dependency.

**Comment by ccordoba12** [comment]
And please also add a simple test in `utils` to verify that `binaryornot` is working correctly (i.e. that `chardet` is picked up as a dependency) by calling `is_text_file`.

**Comment by rlaverde** [comment]
> I don't think Ubuntu is going to pick up 3.1 for 17.04, so I don't see problems in adding a new dependency.

I don't think this will be a problem chardet is already available in [ubuntu](http://packages.ubuntu.com/zesty/python-chardet) (also [debian](https://packages.debian.org/jessie/python-chardet)) repositories

**Comment by ccordoba12** [comment]
Annnd by using `chardet` we could correctly report the encoding of files in the Editor!

I'll open a new issue for you to work at @rlaverde!

**Comment by rlaverde** [comment]
This is failing because a circular importing, that only happen on windows
encoding.py --> external (__init__) --> base.py --> encoding.py

https://github.com/spyder-ide/spyder/blob/master/spyder/utils/external/__init__.py#L22

**Comment by ccordoba12** [comment]
> how this could be fixed?

Just remove all code in `utils/external/__init__.py`. It's not needed anymore, I just forget to remove it in Spyder 3.0 ;-)

**Comment by ccordoba12** [comment]
Nice, good job!

Now that `chardet` is an official dep, please go on with issue #3731.

**Pull request merged**
