### PR TITLE
PR: Fix unclickable update message box

### LINKED ISSUE #3609: New release dialog is un-clickable
## Description

**What steps will reproduce the problem?**
1. Install the latest (windows) anaconda2 v4.2.9 with Spyder v3.0.0
2. Run Spyder.exe

**What is the expected output? What do you see instead?**
The "Spyder 3.0.1 is available!" QT pop-up that appears when spyder starts is un-clickable.  There are two links, "Releases", "Installation" as well as an "OK" button that all can't be clicked on.  The "X" button to kill the pop-up works fine.  

**Please provide any additional information below**
Interestingly, once the menu is clicked, the "tab" button can be used to tab to the "OK" button. The text inside the pop-up can't be highlighted.  
Windows10 Version 1607 (OS Build 14393.321)
Radeon Driver Packaging Version 16.40.2311-160916a-307101E
## Version and main components
- Spyder Version: 3.0.0 
- Python Version: 2.7.12
- Qt Versions: 5.6.0, PyQt5 5.6 on Windows
## Dependencies

```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

### PR DESCRIPTION
**Pull request by mariacamilaremolinagutierrez**
Fixes #3609

### CODE REVIEW

**Comment by goanpeca** [comment]
@mariacamilaremolinagutierrez 

Awesome :-p, some advice

A title like `found out what made the box unclickable` is not very explanatory :-p

Something like `Fix unclickable update message box` or something :-p

**Comment by mariacamilaremolinagutierrez** [comment]
I found out what what making the box unclickable. However I don't quite understand why. The box is an extension of QMessageBox called MessageCheckBox. What it does is that it situates a checkbox at the bottom on the box to know if the user whats to check updates at starup. This was not appearing before. Nos it looks like this:

image

The problem was that we were putting an Information icon: 

`box.setIcon(QMessageBox.Information)`

And this for some reason that I could not figure blocks the box and disables the checkbox (it stops appearing). And looks like the user reported in the issue: 

image

So for now and for the new release I thinks is better that it has no info icon, than that it is unclickable. However I still don't get why other methods from the super class as for example: 

`box.setDefaultButton(QMessageBox.Ok)
box.setWindowTitle(_("Spyder updates"))`

are working. This is intriguing...

**Comment by mariacamilaremolinagutierrez** [comment]
@goanpeca I think you were working on this, do you have any idea why this setIcon() function is not working properly? Could it be is a QT problem when one generates a new class that extends from QMessageBox?

**Comment by mariacamilaremolinagutierrez** [comment]
@goanpeca Haha I promise my next commit will be better! Can I change the commit message after pushing it?

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, you just removed all blank spaces from mainwindow (just to comment one line :-).

Please revert that, and just comment/remove the `box.setIcon` line :-)

**Comment by goanpeca** [comment]
@mariacamilaremolinagutierrez, the addition of a checkbox was a bit hackish, I think the best would be to create a new MessageBox from scratch that doe snot add stuff to a normal checkbox. For the moment I thin its ok to no have the info icon, but lets open an issue to keep this in the radar

**Comment by ccordoba12** [comment]
@mariacamilaremolinagutierrez, so please add a comment above the commented line saying that that line is commented because it freezes the dialog, and that it solves Issue #3609.

**Comment by mariacamilaremolinagutierrez** [comment]
@goanpeca I agree! It is still really weird why this happens but then I'll try to make the box from scratch after I finish my other issues. Thanks :) 

@ccordoba12 It has the comment now :)

**Comment by ccordoba12** [comment]
Thanks a lot @mariacamilaremolinagutierrez! Merging :-)

**Pull request merged**
