### PR TITLE
PR: Change icon and text of 'Lock Interface Action' when clicked

### LINKED ISSUE #12488: An idea to improve the visual of the 'Lock panes and toolbars' action in the View menu
This is a simple idea to maybe improve the action to lock and unlock panes and toolbars in Spyder.

I can push a PR if you like or you can close if you don't, that is ok too :)

Basically, the icon and text of the action is changed according to the locked state of the panes and toolbars.

lock_unlock_interface

For comparison, this is the current behaviour.

lock_unlock_interface_old

### PR DESCRIPTION
**Pull request by jnsebgosselin**
## Description of Changes

Change the icon and text of the `lock_interface_action` according to the locked state of the panes and toolbars.

80288305-22674180-8705-11ea-966f-fb495cf53932

### Issue(s) Resolved

Fixes #12488

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Jean-Sébastien Gosselin

### CODE REVIEW

**Comment by goanpeca** [comment]
Awesome :-) !

I think you need the latest 4.x to get those test fixes.

**Comment by jnsebgosselin** [comment]
> I think you need the latest 4.x to get those test fixes.

Ah no, I need to update the tests, I'm working on it.

**Comment by jnsebgosselin** [comment]
> 
> 
> This will affect a video that was very difficult and time consuming for @juanis2112 to film, as part of her efforts to improve our documentation.
> 
> Therefore, I think we should leave this for Spyder 5. @jnsebgosselin, do you agree with that?

I have no problem with that, I'm running Spyder on master, so this won't affect me. I will rebase the branch.

**Comment by jnsebgosselin** [comment]
mmmh, since there seems to be no conflict, do I need to rebase the branch anyway?

**Comment by jnsebgosselin** [comment]
Ok I rebased anyway since it was pretty straightforward.

**Pull request merged**
