### PR TITLE
PR: Fix LSP consumer reading block on Windows

### LINKED ISSUE #8022: KeyboardInterrupt shows up when Spyder starts
### What steps will reproduce the problem?

The IDE pops up but crashes before finishing installation.
I started 'bootstrap reset' without success as well.

I add to 'pip install autoped8 yasf' otherwise there was error in lsp_server_logfile.log. This is not in requirements.txt.

python bootstrap.py debug
Executing Spyder from source checkout
Revision 324ca58c9, Branch: master
01. Patched sys.path with C:\Contrib\spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 4.0.0.dev0
    [Python 3.6.5 64bits, Qt 5.9.3, PyQt5 5.9.2 on Windows]
04. Running Spyder
Bootstrap completed in 00:00:00.8743

### Traceback
```python-traceback
  File "C:\Contrib\spyder\spyder\plugins\editor\lsp\client.py", line 191, in on_msg_received
    @Slot()
KeyboardInterrupt
```

## Versions

* Spyder version: 4.0.0.dev0 324ca58c9
* Python version: 3.6.5
* Qt version: 5.9.3
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
pyls >=0.19.0     :  0.21.2 (OK)
nbconvert >=4.0   :  5.4.0 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.28.5 (OK)
qtconsole >=4.2.0 :  4.4.1 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.0 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

### LINKED ISSUE #8153: Spyder crashes on launch with PyLS >=0.21
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Tried basic troubleshooting (if a bug/error)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

@ccordoba12 

@bcolsen reported the following issue:

----

I installed miniconda on a virtualbox windows 10 64-bit install. I can run beta1 fine on the install.

But with latest master I get a traceback at least instead of a hard crash(like the laptop yesterday):

<details>
```
2018-10-26 10:40:04,450 [INFO] [spyder.app.mainwindow] -> Loading history plugin...
2018-10-26 10:40:04,481 [INFO] [spyder.app.mainwindow] -> Loading IPython console...
2018-10-26 10:40:04,919 [INFO] [spyder.app.mainwindow] -> Loading file explorer...
2018-10-26 10:40:04,919 [DEBUG] [spyder.plugins.editor.lsp.client] -> python response: server_ready
2018-10-26 10:40:04,919 [DEBUG] [spyder.plugins.editor.lsp.client] -> python request: initialize
2018-10-26 10:40:05,122 [INFO] [spyder.app.mainwindow] -> Loading project explorer...
Handling signal: 0
Traceback (most recent call last):
  File "C:\Users\user\spyder-dev\spyder\app\mainwindow.py", line 3336, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\user\spyder-dev\spyder\app\mainwindow.py", line 3185, in run_spyder
    main.setup()
  File "C:\Users\user\spyder-dev\spyder\app\mainwindow.py", line 943, in setup
    from spyder.plugins.projects.plugin import Projects
  File "C:\Users\user\spyder-dev\spyder\plugins\projects\plugin.py", line 30, in <module>
    from spyder.plugins.projects.widgets.explorer import ProjectExplorerWidget
  File "C:\Users\user\spyder-dev\spyder\plugins\projects\widgets\__init__.py", line 11, in <module>
    from spyder.plugins.projects.api import EmptyProject
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 788, in get_code
  File "<frozen importlib._bootstrap_external>", line 848, in _cache_bytecode
  File "<frozen importlib._bootstrap_external>", line 873, in set_data
  File "<frozen importlib._bootstrap_external>", line 118, in _write_atomic
KeyboardInterrupt
```
</details>

`conda list`
<details>
```
alabaster                 0.7.12                   py36_0
asn1crypto                0.24.0                   py36_0
astroid                   2.0.4                    py36_0
autopep8                  1.4.2                     <pip>
babel                     2.6.0                    py36_0
backcall                  0.1.0                    py36_0
bleach                    3.0.2                    py36_0
ca-certificates           2018.03.07                    0
certifi                   2018.10.15               py36_0
cffi                      1.11.5           py36h74b6da3_1
chardet                   3.0.4                    py36_1
cloudpickle               0.6.1                    py36_0
colorama                  0.4.0                    py36_0
cryptography              2.3.1            py36h74b6da3_0
decorator                 4.3.0                    py36_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3                    py36_2
future                    0.17.0                    <pip>
icu                       58.2                 ha66f8fd_1
idna                      2.7                      py36_0
imagesize                 1.1.0                    py36_0
ipykernel                 5.1.0            py36h39e3cac_0
ipython                   7.0.1            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
isort                     4.3.4                    py36_0
jedi                      0.13.1                   py36_0
jinja2                    2.10                     py36_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0            py36h7636477_0
jupyter_client            5.2.3                    py36_0
jupyter_core              4.4.0                    py36_0
keyring                   15.1.0                   py36_0
lazy-object-proxy         1.3.1            py36hfa6e2cd_2
libpng                    1.6.34               h79bbb47_0
libsodium                 1.0.16               h9d3ae62_0
markupsafe                1.0              py36hfa6e2cd_1
mccabe                    0.6.1                    py36_1
mistune                   0.8.3            py36hfa6e2cd_1
nbconvert                 5.3.1                    py36_0
nbformat                  4.4.0            py36h3a5bc1b_0
numpydoc                  0.8.0                    py36_0
openssl                   1.0.2p               hfa6e2cd_0
packaging                 18.0                     py36_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py36_1
parso                     0.3.1                    py36_0
pickleshare               0.7.5                    py36_0
pip                       10.0.1                   py36_0
pluggy                    0.8.0                     <pip>
prompt_toolkit            2.0.6                    py36_0
psutil                    5.4.7            py36hfa6e2cd_0
pycodestyle               2.4.0                    py36_0
pycparser                 2.19                     py36_0
pydocstyle                3.0.0                     <pip>
pyflakes                  2.0.0                    py36_0
pygments                  2.2.0            py36hb010967_0
pylint                    2.1.1                    py36_0
pyopenssl                 18.0.0                   py36_0
pyparsing                 2.2.2                    py36_0
pyqt                      5.9.2            py36h6538335_2
pysocks                   1.6.8                    py36_0
python                    3.6.6                hea74fb7_0
python-dateutil           2.7.3                    py36_0
python-jsonrpc-server     0.0.2                     <pip>
python-language-server    0.21.2                    <pip>
pytz                      2018.5                   py36_0
pywin32                   223              py36hfa6e2cd_1
pyzmq                     17.1.2           py36hfa6e2cd_0
QDarkStyle                2.5.4                     <pip>
qt                        5.9.6            vc14h62aca36_0
qtawesome                 0.5.1                    py36_1
qtconsole                 4.4.2                    py36_0
qtpy                      1.5.2                    py36_0
requests                  2.19.1                   py36_0
rope                      0.11.0                   py36_0
setuptools                40.4.3                   py36_0
simplegeneric             0.8.1                    py36_2
sip                       4.19.8           py36h6538335_0
six                       1.11.0                   py36_1
snowballstemmer           1.2.1            py36h763602f_0
sphinx                    1.8.1                    py36_0
sphinxcontrib             1.0                      py36_1
sphinxcontrib-websupport  1.1.0                    py36_1
spyder-kernels            1.0.1                    py36_0
sqlite                    3.25.2               hfa6e2cd_0
testpath                  0.4.2                    py36_0
tornado                   5.1.1            py36hfa6e2cd_0
traitlets                 4.3.2            py36h096827d_0
typed-ast                 1.1.0            py36hfa6e2cd_0
urllib3                   1.23                     py36_0
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1                    py36_1
wheel                     0.32.2                   py36_0
win_inet_pton             1.0.1                    py36_1
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11          py36hfa6e2cd_2
yapf                      0.24.0                    <pip>
zeromq                    4.2.5                he025d50_1
zlib                      1.2.11               h8395fce_2
```
</details>

----

I then followed up with some further testing:

0.19.0 both launched correctly and completion/introspection worked. I then installed 0.21.2 and confirmed the bug: Spyder launched and the mainwindow displayed, but then crashed, with the following relevant debug output:

<details>
```
2018-10-26 12:56:58,229 [DEBUG] [spyder.plugins.editor.plugin] -> Call LSP for C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\runtests.py
2018-10-26 12:56:58,230 [DEBUG] [spyder.plugins.editor.widgets.codeeditor] -> LSP available for: C:\Users\C. A. M. Gerlach\Documents\dev\SpyderDev\spyder\runtests.py
2018-10-26 12:56:58,230 [DEBUG] [spyder.plugins.editor.plugin] -> LSP request: 'textDocument/didOpen'
2018-10-26 12:56:58,231 [DEBUG] [spyder.plugins.editor.lsp.client] -> python request: textDocument/didOpen
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFECDD994C4  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFEEC9FD32F  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFEEE5213D2  Unknown               Unknown  Unknown
ntdll.dll          00007FFEEF4C54F4  Unknown               Unknown  Unknown
QObject::~QObject: Timers cannot be stopped from another thread
````
</details>

I then installed 0.20.0 and Spyder launched fine, but completion and introspection didn't work from the Editor. When I tried, I got no output at all or the following in the attached console, and nothing happened in the UI:

<details>
```
2018-10-26 13:12:46,193 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Added thread <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x000000DBD7A40F78> to queue
2018-10-26 13:12:46,208 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Added thread <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x000000DBD7B35708> to queue
2018-10-26 13:12:46,244 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2018-10-26 13:12:46,244 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2018-10-26 13:12:46,245 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 1
2018-10-26 13:12:46,245 [DEBUG] [spyder.plugins.editor.widgets.editor] -> ===>starting: <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x000000DBD7A40F78>
2018-10-26 13:12:46,247 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2018-10-26 13:12:46,247 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2018-10-26 13:12:46,248 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 0
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 1
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] -> ===>starting: <spyder.plugins.editor.widgets.editor.AnalysisThread object at 0x000000DBD7B35708>
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] -> Updating queue:
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     started: 0
2018-10-26 13:12:46,258 [DEBUG] [spyder.plugins.editor.widgets.editor] ->     pending: 0
```
</details>

I then installed 0.21.0, and Python crashed on startup, seemingly sooner than the before (the exact time the crash seems to happen seems to vary, as well as the exact debug output as to what Spyder's doing (so its presumably some sort of asynchronous event/thread with respect to the main Spyder setup), but it always seems to happen right around or a few seconds after the GUI first appears.

Also, I'm getting very unreliable behavior as to whether completion/introspection actually works or not. It worked when I first tested it in 0.19.0, didn't work when I upgraded to 0.20.0, crashed on 0.21.2 (obviously), didn't work when I downgraded again to 0.19.0, worked when I uninstalled and reinstalled it, didn't work again upgrading to 0.20.0, didn't work downgrading to 0.19.0 and now won't even work if I uninstall and reinstall 0.19.0, restarted Spyder twice, let it sit for several minutes, poked around the UI, ran some commands in the console, switched back and forth between help sources (and triggered help and completion from the console) and clicked my heels three times. I don't get any errors, just similar output to the above. Hopefully these are still teething difficulties...

----

UPDATE: I launched Spyder a day later (today) with the exact same commit, environment (0.19.0), even terminal window as before with zero changes (it was literally the next line in the shell I'd left open), and completion/introspection are now working again, with the typical output:

```
2018-10-27 14:50:16,836 [DEBUG] [spyder.plugins.editor.plugin] -> LSP request: 'textDocument/hover'
2018-10-27 14:50:16,836 [DEBUG] [spyder.plugins.editor.lsp.client] -> python request: textDocument/hover
```

It worked 3/3 times, whereas before with everything identical it was 0/3. Is this worth a separate issue? Or could there be something on my end that's causing it?

## Versions

* Spyder version: 4.0 master
* Python version: 3.6.6 x64
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1 x64

### LINKED ISSUE #8565: Code analysis and completion often break when the "Automatic code completion" option is checked
## Problem Description

When the option `Automatic code completion` is checked, code completion and analysis often break.

### What steps reproduce the problem?

1. Make sure the preferences `Editor > Code Introspection/Analysis > Automatic code completion` is checked
2. Type in the editor :
```python
import numpy as np
np.z
```
3. Wait for the completion results to be displayed.

Note that in step2, it is important to type the `z` before the completion results are displayed in the Editor.

### What is the expected output? What do you see instead?

For some reason, the completion results do not seem to take into account the `z`. After that, code introspection and analysis is broken and I need to restart Spyder to make it work again.

image

## Versions

* Spyder version: Spyder 4.0.0.dev0 https://github.com/spyder-ide/spyder/commit/a5ca1f20f69ba8f9bc1b85e166ce865302c06a54
* Python version: Python 3.6.6 64-bit
* Qt version: Qt 5.9.4
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10 

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
qdarkstyle >=2.6.4:  2.6.4 (OK)
sphinx >=0.6.6    :  1.8.1 (OK)
pyls >=0.19.0     :  0.19.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.4 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.5.0.dev0 (OK)
IPython >=4.0     :  7.0.1 (OK)
matplotlib >=2.0.0:  3.0.1 (OK)
pylint >=0.25     :  2.1.1 (OK)

```

### PR DESCRIPTION
**Pull request by steff456**
This change fixes the failure of LSP response on windows.

### Issue(s) Resolved

Fixes #8565.
Fixes #8153
Fixes #8022

### CODE REVIEW

**Comment by andfoy** [comment]
@ccordoba12, I certify that this PR is working!

**Comment by ccordoba12** [comment]
@steff456, this is really great, thanks!

I have a couple of comments:

1. Could you explain why this change is necessary?
2. Is it possible to add a test to verify that things are working as expected?

**Comment by ccordoba12** [comment]
@CAM-Gerlach and @jnsebgosselin, could you help us to test @steff456's work? This should solve the problem with code completions stopping to work randomly on Windows.

However, this doesn't solve the lagging issues on big files. That's a problem with Jedi and we'll report it upstream in the next days.

**Comment by ccordoba12** [comment]
> Is it possible to add a test to verify that things are working as expected?

@steff456, I forgot we can't test the PyLS on Windows, so please dismiss this part.

**Comment by CAM-Gerlach** [comment]
#8022 is the same issue, AFAIK

**Comment by jnsebgosselin** [comment]
I think this also fixes https://github.com/spyder-ide/spyder/issues/8565.

**Comment by jnsebgosselin** [comment]
And I've just tested it with pyls 21.5 and this works!

**Comment by jnsebgosselin** [comment]
> Therefore, at least for me this PR doesn't appear to fix #8565 , and I imagine doing so might be out of scope here.

I tested it again with and without applying the fix proposed in this PR and this is definitively fixing the specific issue I reported in #8565.

@CAM-Gerlach you are right about the errors and problems that you reported, I can reproduce them also, but I think this is something else to what was reported in #8565 and that would be great if you could open another issue to document them.

**Comment by CAM-Gerlach** [comment]
> I tested it again with and without applying the fix proposed in this PR and this is definitively fixing the specific issue I reported in #8565.

Okay; I couldn't get completion to work at all if Automatic Code Completion was disabled (nor re-enabled), but everything does when when Automatic Code Completion is enabled and I didn't get the same behavior as reported in this PR. I'll open a new issue. Thanks!

**Comment by ccordoba12** [comment]
@steff456, the change to pyls 0.21 seems to be causing problems on Windows and Python 3.7. Please create an environment with those requirements and see if that's causing troubles for you.

**Comment by jnsebgosselin** [comment]
> @steff456, the change to pyls 0.21 seems to be causing problems on Windows and Python 3.7. Please create an environment with those requirements and see if that's causing troubles for you.

It is working for me with this environment on Windows 10:

```
(spyder-dev) C:\Users\User>conda list
# packages in environment at C:\Anaconda3\envs\spyder-dev:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0
asn1crypto                0.24.0                   py37_0
astroid                   2.1.0                    py37_0
atomicwrites              1.2.1                    py37_0
attrs                     18.2.0           py37h28b3542_0
autopep8                  1.4.3                    py37_0
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
ca-certificates           2018.12.5                     0
certifi                   2018.11.29               py37_0
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                    py37_1
cloudpickle               0.6.1                    py37_0
colorama                  0.4.1                    py37_0
coverage                  4.5.2            py37he774522_0
cryptography              2.4.2            py37h7a1dbc1_0
cycler                    0.10.0                   py37_0
decorator                 4.3.0                    py37_0
docutils                  0.14                     py37_0
entrypoints               0.3                      py37_0
freetype                  2.9.1                ha9979f8_1
future                    0.17.1                   py37_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imagesize                 1.1.0                    py37_0
intel-openmp              2019.1                      144
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.2.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
isort                     4.3.4                    py37_0
jedi                      0.13.2                   py37_0
jinja2                    2.10                     py37_0
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0                    py37_0
jupyter_client            5.2.4                    py37_0
jupyter_core              4.4.0                    py37_0
keyring                   17.1.1                   py37_0
kiwisolver                1.0.1            py37h6538335_0
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libpng                    1.6.36               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
markupsafe                1.1.0            py37he774522_0
matplotlib                3.0.2            py37hc8f65d3_0
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37he774522_0
mkl                       2019.1                      144
mkl_fft                   1.0.10           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
more-itertools            5.0.0                    py37_0
nbconvert                 5.3.1                    py37_0
nbformat                  4.4.0                    py37_0
numpy                     1.15.4           py37h19fb1c0_0
numpy-base                1.15.4           py37hc3f5095_0
numpydoc                  0.8.0                    py37_0
openssl                   1.1.1a               he774522_0
packaging                 18.0                     py37_0
pandas                    0.23.4           py37h830ac7b_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
parso                     0.3.1                    py37_0
pickleshare               0.7.5                    py37_0
pip                       18.1                     py37_0
pluggy                    0.8.1                    py37_0
prompt_toolkit            2.0.7                    py37_0
psutil                    5.4.8            py37he774522_0
py                        1.7.0                    py37_0
pycodestyle               2.4.0                    py37_0
pycparser                 2.19                     py37_0
pydocstyle                3.0.0                    py37_0
pyflakes                  2.0.0                    py37_0
pygments                  2.3.1                    py37_0
pylint                    2.2.2                    py37_0
pyopenssl                 18.0.0                   py37_0
pyparsing                 2.3.1                    py37_0
pyqt                      5.9.2            py37h6538335_2
pysocks                   1.6.8                    py37_0
pytest                    4.1.1                    py37_0
pytest-cov                2.6.1                    py37_0
pytest-mock               1.10.0                   py37_0
pytest-qt                 3.2.2                      py_0    conda-forge
python                    3.7.1                he44a216_5
python-dateutil           2.7.5                    py37_0
python-jsonrpc-server     0.1.2                      py_0    conda-forge
python-language-server    0.21.5                py37_1000    conda-forge
pytz                      2018.9                   py37_0
pywin32                   223              py37hfa6e2cd_1
pyzmq                     17.1.2           py37hfa6e2cd_0
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.5.5                    py37_0
qtconsole                 4.4.3                    py37_0
qtpy                      1.5.2                    py37_0
requests                  2.21.0                   py37_0
rope                      0.11.0                   py37_0
scipy                     1.1.0            py37h29ff71c_2
setuptools                40.6.3                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
snowballstemmer           1.2.1                    py37_0
sphinx                    1.8.2                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
spyder-kernels            0.3.0                    py37_0
sqlite                    3.26.0               he774522_0
testpath                  0.4.2                    py37_0
tornado                   5.1.1            py37hfa6e2cd_0
traitlets                 4.3.2                    py37_0
urllib3                   1.24.1                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
wheel                     0.32.3                   py37_0
win_inet_pton             1.0.1                    py37_1
wincertstore              0.2                      py37_0
wrapt                     1.11.0           py37he774522_0
yapf                      0.25.0                   py37_0
zeromq                    4.2.5                he025d50_1
zlib                      1.2.11               h62dcd97_3
```

**Comment by CAM-Gerlach** [comment]
> the change to pyls 0.21 seems to be causing problems on Windows and Python 3.7

At least to my untrained eye, the CI failure appeared to be random and unrelated. I'm re-running the check. If it fails, I can also test it on my machine to attempt to confirm @jnsebgosselin 's results.

**Comment by steff456** [comment]
@CAM-Gerlach, @jnsebgosselin I think there is an error on the PyQt module.

image

**Comment by ccordoba12** [comment]
I don't understand the source of this error  but it's failing due to this change.

I'll add a simple fix later today.

**Comment by ccordoba12** [comment]
@steff456, please don't push more commits to this branch. I'll push a workaround so that Windows/Python 3.7 passes here.

**Comment by ccordoba12** [comment]
I decided to skip Windows/Python 3.7 in Azure until I have time to take a deeper look at it.

**Pull request merged**
