### PR TITLE
PR: Remove ipyconsole and editor attrs from the Help plugin

### LINKED ISSUE #6519: AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
### What steps will reproduce the problem?

Selected Monokai theme and clicked Apply, and then encountered an "internal problem".

### Traceback
```python-traceback
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/configdialog.py", line 223, in button_clicked
    configpage.apply_changes()
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/configdialog.py", line 104, in apply_changes
    self.apply_callback()
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/configdialog.py", line 269, in <lambda>
    self.apply_settings(self.changed_options))
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/configdialog.py", line 1187, in apply_settings
    self.main.help.apply_plugin_settings(['color_scheme_name'])
  File "/home/parichay/code/env/spyder3/lib/python3.5/site-packages/spyder/plugins/help.py", line 552, in apply_plugin_settings
    self.editor.apply_plugin_settings(options=[connect_n])
AttributeError: 'NoneType' object has no attribute 'apply_plugin_settings'
```

## Package Versions

* Spyder 3.2.7 ``
* Python 3.5.2
* Qt 5.9.3
* PyQt5 5.9.2
* Linux 4.4.0-112-generic

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  None (NOK)
numpy >=1.7      :  1.14.1 (OK)
sphinx >=0.6.6   :  1.7.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
psutil >=0.3     :  5.4.3 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #6519.

----

The problem is those plugins are initialized after Help, so we can't set a reference to them in register_plugin.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@CAM-Gerlach, could you test this PR on Windows to see if it fixes issue #6549? Thanks!

**Comment by CAM-Gerlach** [comment]
Will do in the next few hours.

**Comment by CAM-Gerlach** [comment]
Sorry for the delay; I was helping another friend with programming issues and learning to use some of Spyder's features. Unfortunately, bad news...I still get the exact same behavior with regard to #6549 .

**Comment by ccordoba12** [comment]
Ok, I was hoping for a simple fix, but no problem. We have to understand how to fix #6549 then.

**Pull request merged**
