### PR TITLE
PR: Add experimental support for PySide2

### LINKED ISSUE #6894: pyside2 support
I am trying to get spyder working with pyside2. I am using qt5.6 and pyside2 from conda-forge channel.

So far there are some problems in the initialization (qtpy) and some not available members of QtCore:
- QtCore.qround  which I replaced with pythons round
```
  File "~/conda/envs/pyside2/lib/python3.6/site-packages/qtawesome/iconic_font.py", line 24, in <module>
    from qtpy.QtCore import QObject, QPoint, QRect, qRound, Qt
ImportError: cannot import name 'qRound'

```
- QWebEngineSettings (which I simple disabled)
```
  File "~/projects/spyder/spyder/widgets/browser.py", line 18, in <module>
    from qtpy.QtWebEngineWidgets import (QWebEnginePage, QWebEngineSettings,
ImportError: cannot import name 'QWebEngineSettings'
Fatal Python error: deallocating None

```
- QRegularExpression (should be the same as QRegExpr)
```
  File "~/projects/spyder/spyder/widgets/mixins.py", line 40, in <module>
    from qtpy.QtCore import QRegularExpression
ImportError: cannot import name 'QRegularExpression'
Fatal Python error: deallocating None
```
- QAbstractItemModel.index (no idea)
```
Traceback (most recent call last):
  File "~/projects/spyder/spyder/widgets/explorer.py", line 969, in filterAcceptsRow
    index = self.sourceModel().index(row, 0, parent_index)
NotImplementedError: pure virtual method 'QAbstractItemModel.index()' not implemented.
```
depends on https://bugreports.qt.io/browse/PYSIDE-570

are there any plans to support pyside2. It seems like it is almost possible.

### PR DESCRIPTION
**Pull request by ccordoba12**
Given that PySide2 seems to be quite stable since its official release, we decided to add experimental support for it in Spyder 4.

TODOs

- [x] Fix signals connection in BasePlugin
- [ ] Fix syntax highlighter error
- [ ] Change order selection between PySide2 and PyQt5? Right now PySide2 is only used if PyQt5 is not installed, else PyQt5 is always preferred.
- [ ] Add support for PySide2 to bootstrap.py
- [ ] Add PySide2 to our CIs

Fixes #6894.

### CODE REVIEW

**Comment by stonebig** [comment]
the experiment seems to work, on at least the startup test

**Comment by stonebig** [comment]
and now after full rebuild, it doesn't finish starting and I see the dark theme... mayne I mistaken my early test

**Comment by stonebig** [comment]
you still ask for PyQt5 in the setup file ?

**Comment by ccordoba12** [comment]
> you still ask for PyQt5 in the setup file in this branch ?

Yes, that's why support for PySide2 will be experimental for the time being. In other words, we won't depend on PySide2 directly, but if it's found in your Python installation then we'll pick it up and use it.

**Comment by stonebig** [comment]
currently, my ps2 bransh is stuck at this starting step:
image

not seeing the "connecting to kernel" on the bottom right.

**Comment by ccordoba12** [comment]
@stonebig, this is going to take a while (a month or month and a half), so please don't insist for this to be ready right now.

**Comment by stonebig** [comment]
ok, will wait.

**Comment by stonebig** [comment]
small question: if Spyder-5 tries again the Pyside2 compatibility route, are this patch still in the right direction ?

**Comment by ccordoba12** [comment]
Some of them. Others will be superseded by other PRs.

**Comment by goanpeca** [comment]
Will work on this after the API migration to be done in a couple of weeks.

The work will probably be much smaller.

**Pull request closed without merging**
