### PR TITLE
PR: Make date objects editable in the object explorer

### LINKED ISSUE #13557: Date object not editable in variable explorer
### What steps will reproduce the problem?

Importing date module to create a date object but not able to change date from variable explorer. If the object is is string i can edit it but not in date object.

### Traceback
```python-traceback
  File "D:\Anaconda\lib\site-packages\spyder\plugins\variableexplorer\widgets\collectionsdelegate.py", line 201, in createEditor
    value.time()
AttributeError: 'datetime.date' object has no attribute 'time'
```

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.7
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.19.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

### PR DESCRIPTION
**Pull request by steff456**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Only try to get value.time() if the value is a date object

image

### Issue(s) Resolved

Fixes #13557 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Steff456

### CODE REVIEW

**Review by dalthviz — COMMENTED** [review]
Thanks @steff456 I think the only missing thing here is a test, otherwise this LGTM :+1:

**Comment by ccordoba12** [comment]
I agree with @dalthviz, let's add a test so that we can avoid a regression in the future.

**Review by ccordoba12 — APPROVED** [review]
Thanks a lot @steff456 for putting the extra effort to create a test for this!

It looks good to me now, but I left @dalthviz to approve and merge.

**Review by dalthviz — APPROVED** [review]
Thanks @steff456 LGTM :+1:

**Pull request merged**
