### PR TITLE
PR: Add scroll arrows fix for Qt 5.9 and 5.12

### LINKED ISSUE #13191: Missing arrows to change tab on mac
### What steps will reproduce the problem?

1 - open enough tabs that they can't fit
2 - Notice the missing arrows
Screenshot 2020-07-04 at 16 56 11

## Versions

* Spyder version: 4.2.0.dev0 3df4cb6e0
* Python version: 3.7.7
* Qt version: 5.12.6
* PyQt5 version: 5.12.3
* Operating System: Darwin 19.5.0

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.2.2 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.10.2 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.7.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.6.5 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.4.4 (OK)
pyls >=0.34.0;<0.35.0          :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.6.0 (OK)
qtconsole >=4.6.0              :  4.8.0.dev0 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
sphinx >=0.6.6                 :  2.2.1 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.10.0.dev0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.14 (OK)
matplotlib >=2.0.0             :  3.1.2 (OK)
numpy >=1.7                    :  1.17.4 (OK)
pandas >=0.13.1                :  0.25.3 (OK)
scipy >=0.17.0                 :  1.3.3 (OK)
sympy >=0.7.3                  :  1.4 (OK)
```

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #13191

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
@impact27 this is the best I could achieve that works for 5.9 and 5.12

5.9
image

5.12
image

**Comment by ccordoba12** [comment]
Thanks @goanpeca! One question: why do the arrows look different in Qt 5.12?

**Comment by goanpeca** [comment]
>Thanks @goanpeca! One question: why do the arrows look different in Qt 5.12?

I have no idea, maybe the CSS parser changed.  On Qt 5.12 there is an extra padding so the arrows look smaller, but the same asset/image is being used. Not sure what changed. Also the corner buttons looks different somehow 🤷.

To be sure, @impact27 @steff456 and @juanis2112 should check if they look ok on their respective systems.

**Comment by impact27** [comment]
Screenshot 2020-07-07 at 08 07 00
I still have the same issue

**Comment by goanpeca** [comment]
@impact27 could you tweak the QSS here and see what might be making the arrows disappear on your case ?https://github.com/spyder-ide/spyder/blob/master/spyder/app/mac_stylesheet.qss

**Comment by impact27** [comment]
Screenshot 2020-07-08 at 08 06 18

`margin-right: 8px;` -> `margin-right: 0px;`

**Comment by impact27** [comment]
With your changes + 
```
QTabBar#plugin-tab QToolButton::left-arrow {
    background: #b7b9b7;
    background: #d2d3d2;
    image: url($IMAGE_PATH/chevron-left.png);
    border: 1px solid #a8a9a8;
    border-bottom: 0px solid #a8a9a8;
    margin-right: 0px;
}

QTabBar#plugin-tab QToolButton::right-arrow {
    background: #b7b9b7;
    background: #d2d3d2;
    image: url($IMAGE_PATH/chevron-right.png);
    border: 1px solid #a8a9a8;
    border-bottom: 0px solid #a8a9a8;
    margin-right: 0px;
}
```
I get:
Screenshot 2020-07-08 at 08 25 35

But as you can see when I hover over the buttons the last tab is selected.

**Comment by goanpeca** [comment]
>But as you can see when I hover over the buttons the last tab is selected. (But this is a minor problem)

Yeah that is simply unavoidable 🤷 qt issue.

Ok will update the PR to include your changes and we should be good to go. Thanks for testing @impact27 !

**Comment by goanpeca** [comment]
@impact27 how does it look for you if you use this

```
/* Scroll arrow buttons in tabbar */

QTabBar#plugin-tab QToolButton::left-arrow {
    background: #b7b9b7;
    background: #d2d3d2;
    image: url($IMAGE_PATH/chevron-left.png);
    border: 1px solid #a8a9a8;
    border-bottom: 0px solid #a8a9a8;
    margin-right: 0px;
    padding: 0px 3px;
}

QTabBar#plugin-tab QToolButton::right-arrow {
    background: #b7b9b7;
    background: #d2d3d2;
    image: url($IMAGE_PATH/chevron-right.png);
    border: 1px solid #a8a9a8;
    border-bottom: 0px solid #a8a9a8;
    padding: 0px 3px;
}

QTabBar::scroller#plugin-tab { /* the width of the scroll buttons */
    width: 16px;
}
```

**Comment by impact27** [comment]
On windows:
image

Could we not stop the tabs widgets before the arrows? it looks like the arrows are over the tabs and not next to them.

**Comment by goanpeca** [comment]
>it looks like the arrows are over the tabs and not next to them.

I can try, but I think I tried this before and CSS this not allow for me to do it. Will try again.

**Comment by impact27** [comment]
Isn’t that something that should be solved in the code somewhere? I don’t think you can do that with css. Where is the arrows widget in the code base?

**Comment by goanpeca** [comment]
>Isn’t that something that should be solved in the code somewhere? I don’t think you can do that with css. Where is the arrows widget in the code base?

Nope, the arrows are tool buttons, but they are not exposed in the QTabWidget class.

**Comment by goanpeca** [comment]
I updated with the changes that work on Mac Qt 5.9 and Qt 5.12.

**Comment by impact27** [comment]
Screenshot 2020-07-10 at 10 13 54

I have the buttons now but there are no arrows

**Comment by ccordoba12** [comment]
@impact27, could you open a PR asap with a fix that works for you? The problem is @goanpeca is working blindly because he can't reproduce your problem, but I need to release 4.1.4 today.

**Pull request merged**
