### PR TITLE
Showing time units on the profiler

### PR DESCRIPTION
**Pull request by malliwi88**
Maybe it is necessary to do a little cleaning to the profiler, I found a lot of code not functional inside profiler.

The final result looks like this
spyder 3 1 0 dev0 python 3 5 _001

### CODE REVIEW

**Comment by ccordoba12** [comment]
What's the difference between *Total time* and *Local time*?

**Comment by ccordoba12** [comment]
@malliwi88, please merge with master to fix the errors in Travis. For that, you need to first checkout your branch, then run

    git merge master

and commit your changes.

**Comment by ccordoba12** [comment]
Sorry, the merge is against the 3.x branch, so the command is

    git merge 3.x

**Comment by Nodd** [comment]
@ccordobat Local time is roughly equivalent to the total time of the function minus the total time of all the subfunctions. It represents the time actually spent in the function and the builtins.

**Comment by ccordoba12** [comment]
Thanks for the explanation @Nodd :-)

**Pull request closed without merging**
