### PR TITLE
PR: Fix out-of-order insertion of mixed stdin and stdout streams on macOS (IPython console)

### LINKED ISSUE #19888: Spyder 5.3.3 IPython-console not properly doing `input()` on Mac
## Problem Description
In spyder 5.3.3 the execution of input() on silicon Macs does not work properly
->spyder 5.2.2 is working perfect

### What steps reproduce the problem?

```python
while True:
    print(input("Enter something:"))
```

### What is the expected output? What do you see instead?

EXPECTED:
```
Enter something:1
1

Enter something:1
1

Enter something:1
1
```

WHATS HAPPENING:

```
Enter something:1
1Enter something:
111
```

### Paste Traceback/Error Below (if applicable)
no errors

## Versions

* Spyder version: 5.2.2
* Python version: 3.9
* Qt version: 5.15.2
* PyQt version: PyQt5 5.15.7
* Operating System name/version: MacOS 12.5.1

### Dependencies

```
PASTE DEPENDENCIES HERE
```

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

- This was fixed before for Windows and Linux in #18439.

### Issue(s) Resolved

Fixes #19888

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @ccordoba12

### CODE REVIEW

**Comment by ccordoba12** [comment]
@mrclary, could you check if this PR fixes issue #19888? It should, but I'd like to be sure. Thanks!

**Review by mrclary — APPROVED** [review]
@ccordoba12, It does appear to be resolve for macOS with this PR.

**Comment by mrclary** [comment]
@ccordoba12, don't worry about the failing conda-based installer workflows. After this PR is merged, I'll investigate those separately.

**Comment by mrclary** [comment]
Aahh! I see what's happening. the `qtconsole` build is failing because the commit 03af737 does not exist on the remote https://github.com/jupyter/qtconsole.git. git-subrepo updates the commit but not the remote (which should be https://github.com/ccordoba12/qtconsole).

Is there a way to ensure that git-subrepo updates the remote as well?

```
[subrepo]
 	remote = https://github.com/jupyter/qtconsole.git
 	branch = fix-print-input-mac                       # <- does not exist on remote
 	commit = 03af737385baa58bea6c9b17ce3e2df6c56cb16c  # <- does not exist on remote
 	parent = 6b211843a99a534331d443ffe17cb2a72458da83
```

Of course, after the relevant PR is merged in `qtconsole` and our subrepo is updated accordingly, then this will go away. But every time we have parallel PRs in `qtconsole`, `spyder-kernels`, `python-lsp-server`, or `qdarkstyle`, this will happen.

**Comment by ccordoba12** [comment]
> Is there a way to ensure that git-subrepo updates the remote as well?

I don't know, but I guess it should be. Please consult the [git-subrepo](https://github.com/ingydotnet/git-subrepo) docs and update our Contributing guide if you find one.

**Pull request merged**
