### PR TITLE
Start testing with PyQt5

### PR DESCRIPTION
**Pull request by ccordoba12**
More testing :-)

### CODE REVIEW

**Comment by ccordoba12** [comment]
The only way to keep going with this is to compile qt5 and pyqt5 ourselves. The conda versions I've found are old and with too much deps on system libraries.

**Comment by ccordoba12** [comment]
Success!! We are now testing PyQt5 with PY 2.7 and 3.5, but not 3.4. The idea is too quickly drop support for 3.4 (in a month or two :-)

This is another great step to move forward to 3.0 final ;-)

**Comment by Nodd** [comment]
Why drop 3.4 ? It's quite recent, and not everyone uses Anaconda...

**Comment by ccordoba12** [comment]
I thought we only had a limited number of slots in Travis, but that doesn't seem to be the case :-)

I'll leave it then until 3.5 is adopted more broadly.

**Comment by SylvainCorlay** [comment]
Does anaconda ship PyQt5? If yes, this is great news for retina display users.

**Comment by ccordoba12** [comment]
Nop, not yet. I created packages for Linux (for now). They are available in our official Anaconda channel:

http://anaconda.org/spyder-ide

I hope to create Mac and Windows packages later on :-)

But that's another reason for making PyQt5 the default in Spyder 3.

**Comment by goanpeca** [comment]
@SylvainCorlay can you register at anaconda.org

**Comment by SylvainCorlay** [comment]
Done! I am also @SylvainCorlay on anaconda.org.

**Comment by goanpeca** [comment]
Cool, I will add you to the list of owners, now need @Nodd and @blink1073 to follow your steps :wink:

**Comment by goanpeca** [comment]
@blink1073 is this you https://anaconda.org/blink1073 ?

**Comment by blink1073** [comment]
Yep

**Pull request merged**
