### PR TITLE
Add helper functions to determine os

### PR DESCRIPTION
**Pull request by goanpeca**
The idea is to use a unified helper function located in `spyderlib.utils.system` to check OS.

I could include in this PR or in a separate one the changes to the files where the OS is determined in another way.

### CODE REVIEW

**Comment by goanpeca** [comment]
Do you prefer these are defined as constants instead?

IS_WIN, IS_UBUNTU... etc so they only run once?

**Comment by ccordoba12** [comment]
I don't think we need this :-) I mean, we should move the entire codebase to use these helper functions, else what would be the point of adding them?

IMHO, using `sys.platform` for Linux and Mac, and `os.name` for Windows is perfectly fine.

**Comment by goanpeca** [comment]
I can move the codebase, it would make the code much cleaner...

**Comment by ccordoba12** [comment]
> I can move the codebase, it would make the code much cleaner

Nop, it won't. Using `sys.platform` and `os.name` are the standard ways to check for the operating system type, known by Python programmers at large and present in the standard library.

We don't need to reinvent the wheel here. It doesn't make any sense to me.

**Comment by goanpeca** [comment]
It would not be the first time we disagree on something :wink:, @blink1073 thought it was a good idea.

**Comment by ccordoba12** [comment]
I know!! Still, I'm pretty -1 on this one. Could you explain what would be the point for Spyder code to override the standard library?

At the end, things will inevitably diverge because new contributors will use `sys.platform` and `os.name` for their code.

**Comment by goanpeca** [comment]
1. I am not overriding the standard library.I am using it and refactoring the code so it is shorter cleaner and unified.

2 Refactoring is done all over spyder and on every project that gets big.

**Comment by goanpeca** [comment]
Is just like having the `PY3` constant.

**Comment by ccordoba12** [comment]
But all other Python programmers in the world know about `sys.platform` and `os.name`. This just breaks compatibility with the collective Python community mindset.

**Comment by blink1073** [comment]
@ccordoba12, I see different ways of handling this all the time, often with subtle problems like checking for `linux2` vs `linux`.

**Comment by goanpeca** [comment]
If there was a consensus on this...

Why?

@ccordoba12 really it is a pointless discussion when we have in the codebase things like this:

```python

PY2 = sys.version[0] == '2'
PY3 = sys.version[0] == '3'
```

And suddenly in the code editor we also have things like this...

```python
    def refresh_eol_chars(self, os_name):
        os_name = to_text_string(os_name)
        self.__set_eol_chars = False
        if os_name == 'nt':
            self.win_eol_action.setChecked(True)
        elif os_name == 'posix':
            self.linux_eol_action.setChecked(True)
        else:
            self.mac_eol_action.setChecked(True)
        self.__set_eol_chars = True
```

Why?

http://stackoverflow.com/questions/4553129/when-to-use-os-name-sys-platform-or-platform-system

**Comment by ccordoba12** [comment]
@blink1073, so you agree with @goanpeca?

The problem with linux is solved by using

```
if sys.platform.startswith('linux')
```

This was suggested years ago in the official docs when Linux moved from 2.6.x to 3.x.x

Are there other subtleties we should need to tackle by using these new helper functions?

**Comment by ccordoba12** [comment]
@goanpeca, the code is perfectly understandable. What's else can I say?

**Comment by goanpeca** [comment]
My suggestion is shorter, more  understandable (win, linux, max... darwin? nt??), is still standard (just refactored) and is faster.

What else can I say?

**Comment by blink1073** [comment]
I agree with @goanpeca, for those who do not deal with cross-platform on a daily basis, this is not an intuitive concept, and deserves an abstraction.

**Comment by ccordoba12** [comment]
@blink1073, but you didn't answer my question. What other thing we need to be aware of to add to these functions besides the `startswith('linux')` one.

----

At the end, I don't understand why @goanpeca is so picky about these things. These are my main points for not liking changes like this one:

1. Maybe it feels like progress to him but to me it doesn't. I have discussed at length with him about it, and I really don't like to get dragged to this kind of discussions. I spent almost two hours with this one (instead of trying to fix #2308, which is a really serious one).

2. I wonder how much progress I would have made during these years as a maintainer, if I tried to fix all shortcomings in Pierre's code :-) There is not a single project which could have been written better, but as I read these days, 87% (!!) of development time is spent on maintaining code, not on creating new one. Trying to rewrite things from scratch is also what made Netscape to disappear, when they had created a fully functional browser in like 10 months (You can read Jamie Zawinski talking about it in *Coders at work*). I just won't let Spyder to follow that path when we have a fully functional open source IDE that doesn't have that many bugs :-) Do you know how many projects like Spyder are around that are not backed by a company? And how many other very good Python open source IDEs have disappeared during the last 6-8 years because their main authors stopped maintaining them? And that could have been very well Spyder destiny's too, when Pierre did that almost two years ago :-)

2. I'm very pragmatic and I don't care too much about code. Code is just a means for an end, not an end in itself. What I want is to give our users a platform that works to the best of our possibilities, and (to me) that means: a) sitting down and fixing bugs, and b) giving them what they find missing (like code folding or integration with the IPython notebook). IMO, things like this PR doesn't help the project to move in any of those directions. It's just (again) correctness for the sake of correctness....

**Comment by blink1073** [comment]
@ccordoba12, I believe that covers all the permutations.  My point is, it wasn't intuitive to two of your core devs how to do this, so it makes sense to add this to ease you from having to intervene on all instances of checking the platform appropriately in the future.   If you disagree, you are the lead dev, and we will concede.

**Comment by goanpeca** [comment]
@ccordoba12 my reasoning is quite simple. I started with Python not so long ago... I started with Spyder in September last year, and there was a lot of time I lost trying to figure things out in Spyder even when receiving comments from all of you. 

It takes time to know why thing are the way the are, and every time I find something like this I try to write it down (in a yet to be published documentation for development). Code is most of the time read, and not written (you can ask Guido) so probably out of that 87% a great deal is just reading the code to learn how to fix something , good documentation and code that tries to be consistent helps in learning, help in coding in helps in maintaining. 

I understand your pragmatism on giving priority to bugs and things that need to be fixed as a result (I guess) of you being the main maintainer from some time, and it is ok, is your position and is fine, but you are not alone in this thing anymore, and there is people trying to help to make things better. You have priorities, and so do I, mine is to increase the outreach (with new communications channels and a website still under construction...) and making it as easy as possible for non hackers/coders to use Spyder in a friendly way that does not require to use a command line etc. Also I want to lower the barrier of entry to help in Spyder as much as possible and this PR goes in that direction.

I feel you are being too dismissive of my suggestions and not really considering how hard it is for someone without too much background in Programming or Programming Theory to help in an open source project.

**Comment by Nodd** [comment]
I see good points given by everyone, but another argument against changing this is that this helper function would be hard to discover anyway, while sys.* would show up in any google search.
However adding this recipe in the wiki would add an easy way for referencing when reviewing code.

**Comment by goanpeca** [comment]
Yes, I will add the "standard way of checking" in the wiki

**Comment by goanpeca** [comment]
I started a cookboo under the development section.

https://github.com/spyder-ide/spyder/wiki/Dev:-Cookbook

**Comment by Nodd** [comment]
Thanks !

**Comment by ccordoba12** [comment]
Ok, I think I overreacted with this PR and I have to apologize with you for that, specially with @goanpeca.

I didn't want to look at this PR again not because I was totally opposed to it, but because i didn't want to be engaged in a another discussion.

After giving some more thought to this, I think my true reasons to be opposed to this work are:
1. This would slow me down :-) Yes, I'm still the main bug fixer around and since I know what are the main ways to check for an OS, I really don't need this work.
1. This can introduce subtle bugs I wouldn't want to deal with :-)

But @goanpeca is right: this is now a team's work, and I have to accept that :-) So if you still think this is a really important endeavor, please reopen this PR and finish it :-)

**Comment by goanpeca** [comment]
@ccordoba12, this is not important, that is why I close it ;-).

And yes it is not worth wasting time on discussions of this sort... and I perfectly understand your position.

No apologies needed, just remember we are "many" now so you do not have to carry all the weight on your shoulders

**Pull request closed without merging**
