### PR TITLE
PR: Split Projects module

### PR DESCRIPTION
**Pull request by rlaverde**
```
projects/
├── api.py
├── confpage.py
├── __init__.py
├── plugin.py
├── projectstypes
│   ├── __init__.py
│   └── python.py
├── utils
│   ├── config.py
│   └── __init__.py
└── widgets
    ├── explorer.py
    ├── __init__.py
    ├── projectdialog.py
    └── tests
        ├── __init__.py
        ├── test_configdialog.py
        ├── test_projectdialog.py
        └── test_project_explorer.py

```

~I'm not sure where is the best place  to put `type` folder~, I put it in the root and move its `__init__.py` to `apy.py`

### CODE REVIEW

**Comment by goanpeca** [comment]
>I'm not sure where is the best place to put type folder

Well they are not really widgets, so maybe at the same level as the widgets folder? or with the api?

**Comment by rlaverde** [comment]
>Well they are not really widgets, so maybe at the same level as the widgets folder? or with the api?

I think that at the same level of the widget folder. (as in outlineexplorer)

Also the `types/__init__` contains the `EmptyProject`  I think that should be part of the api

**Comment by goanpeca** [comment]
>Also the types/__init__ contains the EmptyProject I think that should be part of the api

Yeah, not sure how this goes, but the base project needs to be extendable by other type of projects

**Comment by ccordoba12** [comment]
`type` is a Python keyword, so we shouldn't use it as a module name.

What about `projectstype` or `projtypes`?

**Comment by rlaverde** [comment]
Maybe languages? although we will need a more general word

@goanpeca do you remember the word that we think that could work for the api?

**Comment by ccordoba12** [comment]
@rlaverde, please rebase and finish this one.

**Comment by rlaverde** [comment]
I'll use `projectstypes`. Although we need yo unify this names, In `OutlineExplorer` a file with a similar function is called `languages.py`

**Comment by ccordoba12** [comment]
This looks good to me. I just a minor suggestion: renaming `projectstypes` to `projecttypes` (two plural words in English is rarely used).

Then I'll merge.

**Comment by rlaverde** [comment]
>I just have a minor suggestion: renaming projectstypes to projecttypes

Done

**Pull request merged**
