### PR TITLE
 PR: Add CircleCI to run pytest, ciocheck and coveralls

### PR DESCRIPTION
**Pull request by ccordoba12**
Continuation of PR #3298.

### CODE REVIEW

**Comment by ccordoba12** [comment]
This is ready (it was quite easy by the way :-)

**Comment by goanpeca** [comment]
Cool thanks ;-). I am adding a pre commit hook to run ciocheck linters as a ciocheck command for easy installation.

**Comment by ccordoba12** [comment]
To run ciocheck locally?

**Comment by goanpeca** [comment]
Yep, what do you think?

**Pull request merged**
