### PR TITLE
PR: Use a single main window instance to run all its tests

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes

Reuse same window for all test_mainwindow tests

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
This seems very interesting @impact27! I think we need to close all consoles for the tests that depend on the IPython console, in order to not have conflicts due to the state of previous consoles.

**Comment by impact27** [comment]
The tests now pass in 20 min!

**Comment by impact27** [comment]
> This seems very interesting @impact27! I think we need to close all consoles for the tests that depend on the IPython console, in order to not have conflicts due to the state of previous consoles.

I am just closing the front console, but that seems to work.

**Comment by impact27** [comment]
This is the code that "Cleans" spyder.  Anything you would add/change?
```
            # Close everything we can think of
             window.editor.close_file()
             window.projects.close_project()
             if window.console.error_dlg:
                 window.console.close_error_dlg()
             window.switcher.close()
             client = window.ipyconsole.get_current_client()
             window.ipyconsole.close_client(client=client)
             # Reset cwd
             window.explorer.chdir(get_home_dir())
```

**Comment by goanpeca** [comment]
Amazing work @impact27  :-) !

**Comment by ccordoba12** [comment]
This is terrific @impact27!! Please don't add more commits here, I'm going to tidy up this PR so we can merge it ASAP!

**Pull request merged**
