### PR TITLE
Spyder crashed during last session.

### PR DESCRIPTION
**Pull request by ChandanNishad**
After installation of the Spyder by ubuntu software center, i am getting the error  "Spyder crashed during last session."

please suggest what to do to fix the error.

Chandan

### CODE REVIEW

**Comment by ccordoba12** [comment]
I don't understand what you've done....

**Comment by ccordoba12** [comment]
So you're trying to merge master with 2.3. Sorry, that's not going to happen!

2.3 is our stable branch and master is not ready to be released yet.

**Comment by ChandanNishad** [comment]
hi,

after installation the spyder i am not able to run the spyder. getting
error while opening the spyder.

attached the error screen shot for your kind information.

chandan

On Fri, Jan 29, 2016 at 3:36 AM, Carlos Cordoba <notifications@github.com>
wrote:

> So you're trying to merge master with 2.3. Sorry, that's not going to
> happen!
>
> 2.3 is our stable branch and master is not ready to be released yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/pull/2960#issuecomment-176442797>.
>



-- 
*CHANDAN*

**Comment by ccordoba12** [comment]
Github doesn't receive attachments through email, you need to drag and drop your screenshot inside this dialog (on the webpage) to upload the image to Github server.

**Comment by ChandanNishad** [comment]
fyi
 i am not able to upload the error screen shot on server.

PFA with this mail.


On Fri, Jan 29, 2016 at 5:43 AM, Carlos Cordoba <notifications@github.com>
wrote:

> Github doesn't receive attachments through email, you need to drag and
> drop your screenshot inside this dialog (on the webpage) to upload the
> image to Github server.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spyder-ide/spyder/pull/2960#issuecomment-176492109>.
>



-- 
*CHANDAN*

**Pull request closed without merging**
