### PR TITLE
PR: DataFrame viewer now displays tooltip for column headers

### LINKED ISSUE #3721: DataFrame viewer should display tooltips for truncated column headers
When a DataFrame with long column names is viewed, the column names are truncated. It would be useful to have the full column names displayed as tooltips when pointing at them.

I my case, I have got many columns with long names, so I want to avoid pressing the Resize button to keep the data compact.

(Seen in WinPython-64bit-3.5.2.3 with "Spyder 3.1.0.dev0".)

### PR DESCRIPTION
**Pull request by camendoza94**
Fixes #3721

----

second issue

### CODE REVIEW

**Comment by ccordoba12** [comment]
Great work @camendoza94! Don't worry about the tests failure. That's something we need to fix in our side :-)

**Comment by ccordoba12** [comment]
@jitseniesen, could you review this one?

**Comment by jitseniesen** [comment]
Is it possible to display the tooltip only if the column name is so long that it does not fit in the column header? It seems unnecessary to display the tooltip if the user can already see the whole name.

In the previous version, `headerData()` always returned something, but in your version, it does not return anything (technically, it returns `None`) if `role` is neither `DisplayRole` nor `TooltipRole`. Why did you change this?

**Comment by Prikers** [comment]
I think this can be closed  as it is already covered as part of @dalthviz work in #3873
image

**Pull request closed without merging**
