### PR TITLE
PR: Add API entry for translation utilities

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
When working with the Autopep8 plugin update I noticed on the imports:

```python
# Spyder imports
from spyder.api.plugins import SpyderPluginWidget
from spyder.api.preferences import PluginConfigPage
from spyder.config.base import get_translation
from spyder.config.manager import CONF
from spyder.py3compat import to_text_string
from spyder.utils import icon_manager as ima
from spyder.utils.qthelpers import create_action, get_icon
```

Ideally I would like to aim that needed import should be in the form of 

`from spyder.api ... import X`for global things

And

from spyder.plugins.editor.api ... import X` for "internal" plugin specific things 

And

`from spyder_some_external_plugin.api ... import X`  for "external" plugin specific things

**Comment by ccordoba12** [comment]
> from spyder.plugins.editor.api ... import X for "internal" plugin specific things

Agreed.

> I think that moving apis of internal plugins and expose them in spyder.api is not a great idea (I may have suggested that in the past). spyder.api should be for global spyder things, and not plugin specific ones (editor, varexp etc...). Global like preferences, translation, menu/action/statusbar management, icons and themes, or creating a plugin.

I also agree with this design choice.

**Comment by goanpeca** [comment]
> translations

Was my first thought also :-p. but you suggested i18n :-p . I will make it translations then

**Comment by ccordoba12** [comment]
> Was my first thought also :-p. but you suggested i18n :-p . I will make it translations then

Me? Hehe, I didn't remember that, but it seems I changed my mind.

**Pull request merged**
