### PR TITLE
PR: Fix automatic insertion of colon

### LINKED ISSUE #872: Quotes and colons autocompletion
_From [nunoport...@gmail.com](https://code.google.com/u/108617919618299841919/) on 2011-12-07T06:58:36Z_

Hi,

How can i edit Spyder autocomplete feauture? I can't seem to find in preferences a way to do this...

thanks

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=872_

### PR DESCRIPTION
**Pull request by jitseniesen**
This PR prevents the automatic insertion of a colon at the end of one-line if statements like:
````python
if True: print "Yes!"
````
It also prevents the automatic insertion of a colon at the second line of two-line list comprehensions like:
```python
yes_list = [x for x in [None, None, None, "Yes!"]
            if x is not None]
```
Fixes #872

### CODE REVIEW

**Comment by jitseniesen** [comment]
This does not fix all issues. For instance, even after this is merged, a colon is still erroneously added after the second line of:
```python
yes_list = [x for x in [None, None, None, "Yes!"]
            if x is not None
            or x.startswith("N")]
```
And I'm pretty sure there are other cases in which a colon is either added when it shouldn't be or it is not added where it should. I guess at some point we need to move from ad-hoc implementation to a more complete parsing. Maybe it's better to combine with other parts of the Spyder code base; e.g. automatic indentation?

If #3095 is merged, then we can similarly write tests for automatic insertion of colons.

**Comment by ccordoba12** [comment]
@jitseniesen, thanks so much for looking into this one!! I've been unable to find time to fix it myself :-)

To fix tests in Travis, please merge with master :-)

----

@goanpeca, how coverails works? We can have PRs failing because of it :-)

**Comment by goanpeca** [comment]
@ccordoba12 coverage decreased so we get an "error", but it was marginal, so we can round the value to it does not complain.

**Comment by ccordoba12** [comment]
Could we deactivate that feature of coverails? Or change it to big decrease (say 10% or 20%)?

**Comment by goanpeca** [comment]
We are on 4%, I think a 1% decrease is already very alarming.

**Comment by goanpeca** [comment]
I changed it, so if it decreases 1% it will fail ;-)

**Comment by ccordoba12** [comment]
> We are on 4%, I think a 1% decrease is already very alarming.

Ok, fair enough :-)

**Comment by jitseniesen** [comment]
> To fix tests in Travis, please merge with master :-)

Done. Actually, I rebased instead of merged; I think you guys prefer that.

**Comment by goanpeca** [comment]
@jitseniesen whatever the dev feels better with. Megre is safer, rebase can lead to trouble if done incorrectly. I prefer rebase in general, but sometimes conflicts are very tedious to fix so I go the merge way :-p

**Comment by Nodd** [comment]
Recently a PR was merged to enable testing with pytest. It would be great if you had the motivation to add tests for this, including failing tests (marking them as known fail).

**Comment by jitseniesen** [comment]
@Nodd, I was planning to wait until you finished PR #3095 for testing automatic indentation and use that as a template. :)

I don't know the best way to test the automatic insertion of colons because the code is very tightly coupled to the UI - it's part of the class `CodeEditor` which inherits from a Qt class, and it uses Qt functionality for stuff like finding the start of line. You probably struggled with this yourself and so know all about it.

One possibility would be for me to try and (partially) decouple the automatic insertion of colons from the `CodeEditor` class. This would allow for cleaner testing. Another possibility is to take your work, convert it to pytest, and add testing for the colon stuff. And then of course there is my original plan, to wait for you.

What are your plans and what do you think about this?

**Comment by goanpeca** [comment]
@jitseniesen the idea is to use pytest-qt to test UI widgets, that was the point @Nodd was probably trying to make.

It is very difficult to test this type of code in a decoupled way, cause it is code that works in the actual UI/codeeditor.

You can take a look at https://github.com/spyder-ide/spyder/blob/master/spyderlib/widgets/tests/test_array_builder.py to get the general idea. Basically you can create a fixture that returns a Codeeditor widget and then you test the actual interaction via qtbot (sendclicks and sendkey) and then check that the content you get includes the colon.

If you need some guidance, let me know.

**Comment by Nodd** [comment]
I don't know how exactly is the code layout for colon insertion, but if it's like autoindent you don't need pytest-qt as you can change the text and call the functions directly.
@jitseniesen Well played, you forced me to do it ! :wink: Have a look at #3095

**Comment by jitseniesen** [comment]
Thank you both for your explanations. As you can see, I added some tests for the colon insertion.

**Comment by ccordoba12** [comment]
@jitseniesen, this is really great, not only the fix itself but also the tests!

Merging because everything is green :-)

**Pull request merged**
