### PR TITLE
Fixed typo in german msgstr in spyder.po

### PR DESCRIPTION
**Pull request by MarioKrenn6240**
Fixed typo in german spyder msgstr

## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @MarioKrenn6240, thanks a lot for your contribution! We don't edit our translation files directly; instead we use Crowdin to synchronize our translations:

https://crowdin.com/project/spyder

So you'd need to subscribe and make your change there. If that's too much for you, considering this is such a small change, we could do it for you.

Also, @bnavigator, what do you think about this one?

**Comment by bnavigator** [comment]
The fix is correct, and I used my crowdin account to make the small change. Thank you @MarioKrenn6240!

**Comment by ccordoba12** [comment]
Ok, great! Thanks for your help @bnavigator!

**Comment by ccordoba12** [comment]
Closing this one then.

**Pull request closed without merging**
