### PR TITLE
PR: Handle 'unlocked panes' state for undocking without generating a new window

### LINKED ISSUE #5486: Spyder crash when dragging a plugin with the mouse
## Description of your problem

**What steps will reproduce the problem?**

1. In `Views` uncheck `Lock panes`
2. Try to move a plugin with the mouse
3. Python is crashing systematically

moving_plugins_around

**Please provide any additional information below**

I think this bug was introduced in PR #3824. This is reproducible only in Spyder 4.0.0.dev0 (Commit: 777015f80) and not in Spyder 3.2.4.dev0 (Commit: 7b8042c0e).

## Versions and main components

* Spyder Version: Spyder 4.0.0.dev0 (Commit: 777015f80)
* Python Version: 3.6.2
* Qt Version: 5.9.1
* PyQt Version: 5.9
* Operating system: Windows 7 64 bits

## Dependencies

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.5.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.1 (OK)
qtconsole >=4.2.0:  4.4.0.dev (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
sympy >=0.7.3    :  None (NOK)

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #5486

### CODE REVIEW

**Comment by jnsebgosselin** [comment]
Thanks for the quick fix @dalthviz. I've tested your solution locally and it is working for all plugins, but it is still crashing with the Editor.

moving_plugins_around2

**Comment by dalthviz** [comment]
Thanks a lot for the testing and feedback @jnsebgosselin :+1:

**Comment by ccordoba12** [comment]
@jnsebgosselin, please approve so I can merge this one :-)

**Comment by jnsebgosselin** [comment]
I confirm that Spyder is not crashing anymore when dragging plugins with the mouse when `Lock panes` is unchecked :tada:

Just to be sure everyone understands the implications of these changes before merging, **new windows will now be created** when undocking plugins **only** when `Lock panes` is checked. Spyder will revert to the old behaviour when `Lock panes` is unchecked, i.e. Spyder will never create new windows when undocking plugins, even when undocking with the buttons. 

I think this make sense and I vote :+1:  for this change.

undocking_behave

**Comment by ccordoba12** [comment]
> Some other observations

Thanks Jean for your observations. Please open a new issue about them, so we can discuss them there.

**Pull request merged**
