### PR TITLE
PR: Fix showing spaces for generic files

### LINKED ISSUE #7998: "Show blank spaces" refuses to work on files without officially "supported" extensions
### What steps will reproduce the problem?

The "Show blank spaces" toggle refuse to work on files with "unsupported" extensions (dotfiles, plain text, lektor, etc), even in the latest ``master``. There appears to be absolutely no logical reason for this, nor does any other editor or IDE refuse to do this, so this is presumably a bug and should be fixed. Presumably Spyder is unnessesarily checking if a file is one of the "supported" extensions before allowing blank spaces to be shown, which of course it shouldn't, but I'd have to look into it further to figure out where or why.

## Versions

* Spyder version: 4.0.0.dev0 324ca58c9
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 8.1

### Dependencies

```
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
pyls >=0.19.0     :  0.19.0 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  None (NOK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.2.0 :  4.4.0 (OK)
IPython >=4.0     :  6.5.0 (OK)
matplotlib >=2.0.0:  None (NOK)
pylint >=0.25     :  2.1.1 (OK)
```

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Screen Shot 2019-11-29 at 20 53 08

### Issue(s) Resolved

Fixes #7998

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) lic@goanpeca e.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
@CAM-Gerlach could you check this works as expected?

**Comment by CAM-Gerlach** [comment]
@goanpeca In work now, thanks.

**Comment by ccordoba12** [comment]
We should add a simple test for this so we don't lose it in a refactoring or something.

**Comment by goanpeca** [comment]
>We should add a simple test for this so we don't lose it in a refactoring or something.

I have no idea how to test this.

**Pull request merged**
