### PR TITLE
PR: Give focus to Plots pane when switching to it by shortcut if it's visible

### PR DESCRIPTION
**Pull request by ok97465**
## Description of Changes
I added funtionality for focus on plots pane when pressed the shortcut for switching to plot pane (ctrl + shift + G) if plots pane is visible.
If users pressed the switching shortcut and plots pane is visible, the thumbnail list of plots pane is controlled by arrow key. 

- visible is False
not_visible

- visible is True
visible

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: ok97465

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for your contribution @ok97465! But do we really need an option for this? I mean, in what situations do you need to go to Plots but not have focus on it?

**Comment by ok97465** [comment]
[#9036 comments](https://github.com/spyder-ide/spyder/pull/9036#issuecomment-477373882)
I think that some users don't like sudden change in UX that lasted for about a year.

**Comment by jnsebgosselin** [comment]
> 
> But do we really need an option for this? I mean, in what situations do you need to go to Plots but not have focus on it?

Maybe instead of adding an option, we could give focus to the Plots pane only when it is already visible, else we only switch to it without giving it focus. One would have to press the shortcut twice to switch to the Plots pane and give focus to it.

**Comment by ccordoba12** [comment]
@jnsebgosselin, please approve if you consider this one is ready.

**Comment by jnsebgosselin** [comment]
I've reviewed the code and everything LGTM and I've tested this locally and this is working as expected. Thanks @ok97465, this is a great improvement!

**Pull request merged**
