### PR TITLE
PR: Update continuation prompt

### LINKED ISSUE #14476: Make Pdb continuation prompt consistent
I don't know if there's some profound reason for this but it sure interferes with smooth text manipulation:

image

I can't `Shift + Arrow Up` or `NumLock: 7, 1`, or even simply `Arrow Up` (or any direction) consistently, always have to adjust for that first line differing from rest. Would help if they were all vertically aligned just like in Editor.

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #14476

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by OverLordGoldDragon** [comment]
Excellent, thanks.

**Review by ccordoba12 — APPROVED** [review]
This works as expected. Thanks @impact27!

**Comment by OverLordGoldDragon** [comment]
I pasted [these](https://github.com/spyder-ide/spyder/pull/14478/files#diff-db6e310dc16edb4165c9c18462c0d9789b96df21f34ec72c14efc69c8ac0d4f9R474-R477) into the file, [didn't work](https://user-images.githubusercontent.com/16495490/102837079-810bc900-4414-11eb-80c6-048ae2d9800e.png); maybe I'm missing intermediate commits. If it's fixed for you on Windows 10, guess I'll check in 4.2.2.

**Comment by ccordoba12** [comment]
Did you restart Spyder after applying the change?

**Comment by OverLordGoldDragon** [comment]
Restarted kernel, apparently didn't suffice. Can confirm alignment and all hotkeys work as expected; +30 WPM

**Comment by ccordoba12** [comment]
The change was not done on the kernel side. That's why this PR was opened here and not in the spyder-kernels repo.

**Comment by OverLordGoldDragon** [comment]
Congrats on Spyder 5! Prepare for bug reports.

**Pull request merged**
