### PR TITLE
Re-include plugins in setup.py packages

### PR DESCRIPTION
**Pull request by Nodd**
Fixes https://github.com/spyder-ide/spyder/pull/3210#issuecomment-232092226

I forgot this change when switching to flask model.

### CODE REVIEW

**Comment by goanpeca** [comment]
Joselito, could you go to gitter?

**Comment by Nodd** [comment]
I'm trying, but the network is really bad here so I'm not sure if it will work at all :disappointed:

**Comment by ccordoba12** [comment]
@Nodd, you also need to change this line:

https://github.com/spyder-ide/spyder/blob/master/MANIFEST.in#L2

*Note*: The Appveyor failure is unrelated to this change ;-)

**Comment by ccordoba12** [comment]
There are also a couple of other references to `spyplugins`. Please remove them too.

**Comment by Nodd** [comment]
I removed some preferences, and used `plugins` instead of `spyplugins` for the user directory (the wiki will have to be updated).

What's left:
* continuous_integration/appveyor/modules_test.bat:124 : I don't know what it's doing exactly. I'm not sure that it's needed.
* `.pot` and `.po` files : I'm not sure if I can simply use `sed` to update these or will it mess things up ?

**Comment by ccordoba12** [comment]
> continuous_integration/appveyor/modules_test.bat

I'll fix this, don't worry about it.

> I'm not sure if I can simply use sed to update these or will it mess things up ?

Yeah, please use `sed` to update them.

**Comment by Nodd** [comment]
I updated the files but the translations are not loaded. :disappointed:

**Comment by Nodd** [comment]
Everything seems to work now, except the appveyor thing.

The testing error is unrelated to my changes::
```
Error: HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/free/linux-64/sqlite-3.13.0-0.tar.bz2: https://repo.continuum.io/pkgs/free/linux-64/sqlite-3.13.0-0.tar.bz2
```

**Comment by ccordoba12** [comment]
Failures seem related to internal problems with conda.

**Comment by Nodd** [comment]
No failures anymore !

**Pull request merged**
