### PR TITLE
WIP: Update pyqt requirements

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
With pyqt 5.14 all seems to work but the test suite finished with

```
2020-06-02T00:18:49.8744988Z ===End Flaky Test Report===
2020-06-02T00:18:49.8745239Z ========================== slowest 10 test durations ===========================
2020-06-02T00:18:49.8745515Z 46.06s setup    spyder/app/tests/test_mainwindow.py::test_run_static_code_analysis
2020-06-02T00:18:49.8745625Z 46.04s setup    spyder/app/tests/test_mainwindow.py::test_move_to_first_breakpoint[True]
2020-06-02T00:18:49.8745734Z 45.86s setup    spyder/app/tests/test_mainwindow.py::test_set_new_breakpoints
2020-06-02T00:18:49.8745842Z 45.75s setup    spyder/app/tests/test_mainwindow.py::test_runfile_from_project_explorer
2020-06-02T00:18:49.8745951Z 26.98s call     spyder/plugins/editor/widgets/tests/test_introspection.py::test_completions
2020-06-02T00:18:49.8746044Z 20.91s call     spyder/app/tests/test_mainwindow.py::test_preferences_change_interpreter
2020-06-02T00:18:49.8746166Z 20.66s call     spyder/app/tests/test_mainwindow.py::test_preferences_change_font_regression
2020-06-02T00:18:49.8746452Z 17.61s call     spyder/plugins/editor/widgets/tests/test_introspection.py::test_automatic_completions
2020-06-02T00:18:49.8746570Z 14.91s setup    spyder/app/tests/test_mainwindow.py::test_run_static_code_analysis
2020-06-02T00:18:49.8746682Z 13.02s setup    spyder/app/tests/test_mainwindow.py::test_edidorstack_open_symbolfinder_dlg
2020-06-02T00:18:49.8746772Z ============ 131 passed, 926 skipped, 15 warnings in 793.85 seconds ============
2020-06-02T00:18:49.9440417Z Fatal Python error: Aborted
2020-06-02T00:18:49.9440850Z 
2020-06-02T00:18:49.9441144Z Thread 0x00007ffa4a6d7700 (most recent call first):
2020-06-02T00:18:49.9442050Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jupyter_client/manager.py", line 327 in finish_shutdown
2020-06-02T00:18:49.9443078Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jupyter_client/manager.py", line 377 in shutdown_kernel
2020-06-02T00:18:49.9443400Z 
2020-06-02T00:18:49.9443657Z Thread 0x00007ffa4aed8700 (most recent call first):
2020-06-02T00:18:49.9443944Z   File "/usr/share/miniconda/envs/test/lib/python3.7/threading.py", line 300 in wait
2020-06-02T00:18:49.9444883Z   File "/usr/share/miniconda/envs/test/lib/python3.7/threading.py", line 552 in wait
2020-06-02T00:18:49.9445438Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jupyter_client/channels.py", line 161 in run
2020-06-02T00:18:49.9446093Z   File "/usr/share/miniconda/envs/test/lib/python3.7/threading.py", line 926 in _bootstrap_inner
2020-06-02T00:18:49.9446599Z   File "/usr/share/miniconda/envs/test/lib/python3.7/threading.py", line 890 in _bootstrap
2020-06-02T00:18:49.9446813Z 
2020-06-02T00:18:49.9447236Z Thread 0x00007ffa885d2700 (most recent call first):
2020-06-02T00:18:49.9447501Z   File "/usr/share/miniconda/envs/test/lib/python3.7/selectors.py", line 468 in select
2020-06-02T00:18:49.9447824Z   File "/usr/share/miniconda/envs/test/lib/python3.7/asyncio/base_events.py", line 1750 in _run_once
2020-06-02T00:18:49.9448096Z   File "/usr/share/miniconda/envs/test/lib/python3.7/asyncio/base_events.py", line 541 in run_forever
2020-06-02T00:18:49.9448647Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149 in start
2020-06-02T00:18:49.9449230Z   File "/usr/share/miniconda/envs/test/lib/python3.7/site-packages/jupyter_client/threaded.py", line 187 in run
2020-06-02T00:18:49.9449733Z   File "/usr/share/miniconda/envs/test/lib/python3.7/threading.py", line 926 in _bootstrap_inner
2020-06-02T00:18:49.9450224Z   File "/usr/share/miniconda/envs/test/lib/python3.7/threading.py", line 890 in _bootstrap
2020-06-02T00:18:49.9450437Z 
2020-06-02T00:18:49.9450677Z Thread 0x00007ffaef7f6700 (most recent call first):
2020-06-02T00:18:49.9450926Z   File "/usr/share/miniconda/envs/test/lib/python3.7/socket.py", line 212 in accept
2020-06-02T00:18:49.9462654Z   File "/home/runner/work/spyder/spyder/spyder/app/mainwindow.py", line 3303 in start_open_files_server
2020-06-02T00:18:49.9463166Z   File "/usr/share/miniconda/envs/test/lib/python3.7/threading.py", line 870 in run
2020-06-02T00:18:49.9463490Z   File "/usr/share/miniconda/envs/test/lib/python3.7/threading.py", line 926 in _bootstrap_inner
2020-06-02T00:18:49.9463817Z   File "/usr/share/miniconda/envs/test/lib/python3.7/threading.py", line 890 in _bootstrap
2020-06-02T00:18:49.9464070Z 
2020-06-02T00:18:49.9464328Z Current thread 0x00007ffb7cfad740 (most recent call first):
2020-06-02T00:18:50.1338796Z Aborted (core dumped)
2020-06-02T00:18:50.1343032Z ##[error]Process completed with exit code 134.
2020-06-02T00:18:50.1469204Z Post job cleanup.
2020-06-02T00:18:50.3463357Z [command]/usr/bin/git version
2020-06-02T00:18:50.3466394Z git version 2.26.2
2020-06-02T00:18:50.3472643Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-06-02T00:18:50.3480764Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2020-06-02T00:18:50.3481215Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-06-02T00:18:50.3481383Z http.https://github.com/.extraheader
2020-06-02T00:18:50.3481749Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2020-06-02T00:18:50.3482491Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2020-06-02T00:18:50.3487802Z Cleaning up orphan processes
2020-06-02T00:18:50.3765492Z Terminate orphan process: pid (18058) (python)
```

Thoughts @impact27 @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yeah, it seems there is a segfault while shutting down the kernel.

@impact27, do you have any insight about it?

**Comment by impact27** [comment]
> Yeah, it seems there is a segfault while shutting down the kernel.
> 
> @impact27, do you have any insight about it?

Well I would say there is a segfault while waiting for the kernel to shut down. 
`Terminate orphan process: pid (18058) (python)` This might be the kernel that was shutting down

The segfault itself is not happening in python code, because there is no lines between:
```
2020-06-02T00:18:49.9464328Z Current thread 0x00007ffb7cfad740 (most recent call first):
2020-06-02T00:18:50.1338796Z Aborted (core dumped)
```

Ideally we would have access to a C traceback. I am not sure how to do that in linux. (I wouldn't even be sure how to do that in mac, as usually macOS kindly opens a window with a trackback when an app crashes. Maybe gdb?)

**Comment by impact27** [comment]
The solution would be to, in order of preference:
 - Find a way of showing C trackbacks
 - Find a way of reproducing this locally
 - Guess what was prematurely released (I would guess a QThread object?)

**Comment by impact27** [comment]
On linux: https://www.unix.com/man-page/linux/1/catchsegv/

**Comment by goanpeca** [comment]
Thanks for looking into it @impact27 ! 

It seems the PR now is ERRORing on the timeout issue.

**Comment by impact27** [comment]
> 
> 
> Thanks for looking into it @impact27 !
> 
> It seems the PR now is ERRORing on the timeout issue.

The timeout issue will likely go away when https://github.com/spyder-ide/spyder/pull/12457 is merged. But that doesn't solve the underlyinging issue of the kernel crashing.

**Pull request closed without merging**
