### PR TITLE
PR: Extend Find in Files to select other search directories

### LINKED ISSUE #4814: Extend Find in Files to select other directories
As suggested by @jnsebgosselin and @avylove on #4809

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #4814 

## Preview
peek 27-07-2017 17-05

### CODE REVIEW

**Comment by andfoy** [comment]
@ccordoba12 I have some problems choosing a directory using ``qtpy.compat.getexistingdirectory``. When the folder selection window is closed, it keeps reappearing instead of closing, this happens for both Cancel and Accept options. After that, Spyder cannot be closed unless is killed with a ``SIGKILL`` signal.

**Comment by andfoy** [comment]
@ccordoba12 Does it look right?

**Comment by ccordoba12** [comment]
I like it, a lot!

@jnsebgosselin, @avylove, what do you think?

**Comment by ccordoba12** [comment]
Questions:

1. How many paths are we saving in the drop-down menu?
2. Are those paths saved among sessions?

**Comment by ccordoba12** [comment]
In point 2. I meant, are those paths saved when Spyder is closed and open again?

**Comment by andfoy** [comment]
On a single session we're storing all paths as the user would like, however, between sessions, we're just storing the 15 most recent entries.

**Comment by goanpeca** [comment]
Looks pretty good @andfoy :+1:

**Comment by ccordoba12** [comment]
> On a single session we're storing all paths as the user would like

That could cause problems. Please limit that to the 15 most recent paths too.

**Comment by goanpeca** [comment]
@andfoy do we have a 'search in current project' option ?

**Comment by andfoy** [comment]
@goanpeca Yes, I forgot to show it on the preview GIF. The option is only enabled when a project is opened

**Comment by jnsebgosselin** [comment]
@andfoy This looks great and very intuitive. I like it. Good job.

**Comment by avylove** [comment]
@andfoy Looks great! Good solution!

**Comment by ccordoba12** [comment]
@andfoy, this requires now a merge with 3.x to fix conflicts.

**Comment by andfoy** [comment]
@ccordoba12 I think this one is ready

**Pull request merged**
