### PR TITLE
PR: Create Completions Plugin Statusbar Widget

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

Created a statusbar widget for the completions plugin. This replaces the status bar widget for the MainInterpreter.
* MainInterpreter plugin still handles all interpreter related manipulations, but simply does not display on the StatusBar
* Completion plugin now has a status bar widget that displays the completion environment.
* The interpreter-changed signal no longer routes through the MainWindow. Any services requiring it should access `sig_interpreter_changed` from the MainInterpreter plugin.

### Issue(s) Resolved

Fixes spyder-ide/ux-improvements#38

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@mrclary

### CODE REVIEW

**Comment by mrclary** [comment]
@ccordoba12, I think this reflects what we discussed at our last meeting.
We can, of course, change any of the class/function names and update documentation as needed.

**Review by isabela-pf — DISMISSED** [review]

**Comment by isabela-pf** [comment]
Sure thing! Since we're using (mostly) [Material Design Icons](https://pictogrammers.github.io/@mdi/font/5.4.55/) now, I think `mdi-close` and `mdi-check` seem like good options for the simple options.
Screen Shot 2021-08-30 at 2 02 37 PM
Screen Shot 2021-08-30 at 2 02 22 PM

**Comment by mrclary** [comment]
Okay, @isabela-pf, @ccordoba12, and @steff456,
I've fixed up the LSP status widget, also. Let me know what you think.

**Comment by mrclary** [comment]
status

**Comment by isabela-pf** [comment]
Thanks for the updated screen shot! That makes it so easy to review. Looks good to me! 🌻

**Review by isabela-pf — APPROVED** [review]

**Comment by mrclary** [comment]
@ccordoba12 @isabela-pf @steff456 any chance of moving forward on this soon?

**Review by isabela-pf — APPROVED** [review]
@mrclary thanks for the tag! This looks good to me, so no blockers on my part. Major kudos for sticking with this for so long.

**Comment by mrclary** [comment]
@isabela-pf, it looks like I'm able to merge this, but I didn't do so before because I didn't know if I needed to wait for any other reviewers. Should I merge this or wait?

**Comment by isabela-pf** [comment]
I'd personally merge it! @steff456 or @ccordoba12 any last thoughts since you also reviewed?

**Review by steff456 — APPROVED** [review]
I think this is ready to merge, thanks for working in this!

**Comment by mrclary** [comment]
Okay, I'll go ahead and merge.

**Comment by mrclary** [comment]
Hmm... the maininterpreter status bar widget is still visible. It was not visible last time I checked. I'll have to investigate and make a followup PR.

**Comment by mrclary** [comment]
Okay, it looks like the interpreter status bar is added to the status bar from the maininterpreter plugin (makes sense). This must have been a change since after I started working on this PR and I just missed it. Nevertheless, I know that we had discussed removing the interpreter status bar widget in favor of putting that information in the Console tab (see spyder-ide/ux-improvements#10) so maybe it's good to leave it until that information is put into the Console tab.

**Comment by ccordoba12** [comment]
Since I was requested to give a review, I'd have preferred if you waited to hear my opinion before merging. I'm sorry for not doing it before, but I'm really busy these days with personal and family issues, so I have very little time for Spyder (i.e. I'm only responding issues and fixing bugs for 5.3.0).

Besides, we try not to merge our own PRs. Yes, I know I do it all the time but that's when I'm basically the only one who understands what the PR is doing or it's very simple. However, I try to ask for a review when I submit big modifications or things I'm unsure about.

My main concern about your work (when I saw the initial implementation some months ago) is that it is mainly about moving the widget from the `maininterpreter` plugin to `completions`, which (to me) seems to give us a very little gain.

Furthermore, you say in your description

> The interpreter-changed signal no longer routes through the MainWindow. Any services requiring it should access sig_interpreter_changed from the MainInterpreter plugin.

So, it seems you're implementing a design pattern similar to the one in PR #15629. The problem with that is that we discussed about it with @andfoy some months ago and agreed that we should revert it because, now that plugins can be turned off easily, the logic is much simpler and easier to follow if the main window is the one that emits a restart signal and other plugins connect to it. That the Application plugin handles that is an implementation detail that external developers don't need to be aware of (that's what I can recall right now, I could be a bit mistaken though).

Sorry for leaving you hanging for so long here, but the team has been very busy during the last months with updating Qt/PyQt to 5.15 in conda-forge (which is a huge undertaking), making Spyder work with that version (also very hard) and trying to improve engagement with our community (quite time consuming as well). The first two are requirements from our main sponsor (TDK), so we really to address them asap. Besides that, I've been in bug fixing mode, merging PRs that I understand well and don't need too much back and forth (for which I don't have time, as I said in another issue), and writing and reviewing proposals for conferences and grants.

Finally. all this is to say: I don't know if it'd be better to revert this PR and discuss about it a bit more. What do you think?

**Comment by mrclary** [comment]
@ccordoba12, I completely understand that you and many other developers are busy with higher priority items. I apologize for prematurely merging this PR. I think we should revert this PR and discuss it more when you have time.

**Comment by isabela-pf** [comment]
I'd rather take the blame here since, when asked, I said I'd personally merge it. @mrclary has taken a lot of feedback on this very readily, but he can't take feedback that hasn't been communicated any more than I can know to watch for review I'm unaware of. 

I don't think @mrclary stepped out of line at all. He's been tagging us and asking for review respectfully, patiently, and regularly for almost a year (April 2021 to March 2022). I do know it's not common practice in open source to merge one's own PRs, and I generally support that. In this case I wasn't clear on another way to help move this PR forward.

In trying to learn from this, is there any documentation about these kind of expectations? Since there is sometimes self-merging happening on this repo, it makes it look like a viable option when it sounds like that may not be the case.

**Comment by ccordoba12** [comment]
Thanks @mrclary and @isabela-pf for your answers. I'm a bit tired to give you an answer now (it's midnight in my timezone), but I'll try to do it tomorrow.

I also apologize with you again for taking so long to respond to your pings. I'll let you @mrclary and the other volunteers know the reasons in an email (they are not super personal stuff, just private).

**Comment by steff456** [comment]
I did review this PR yesterday and I didn't find any issue like the ones @ccordoba12 is commenting on and I have a couple of things that I don't agree.

> Besides, we try not to merge our own PRs.

As I already stated, I did review and approve this PR yesterday, so Ryan didn't merge his own work without any opinion or approval.

> I try to ask for a review when I submit big modifications or things I'm unsure about.

Ryan asked for review and none of us were able to deliver our opinions in a reasonable timing. So again, this doesn't apply here.

> My main concern about your work (when I saw the initial implementation some months ago) is that it is mainly about moving the widget from the maininterpreter plugin to completions, which (to me) seems to give us a very little gain.

Thanks to the new API, we are able to do this modifications. For me, it makes sense to have the completions statusbar widget in the actual completions plugin since the component is dependent on it and it modifies what's displayed, which is not the case of having the widget in the maininterpreter plugin. 

Just a heads up of the editor migration, we are going to move several widgets that aren't in the most logical position to one that makes the structure of the code more organized. So I don't agree that this is a _little gain_ PR. And I just wanted to highlight that we shouldn't be using this language becase every PR is a gain.

> So, it seems you're implementing a design pattern similar to the one in PR https://github.com/spyder-ide/spyder/pull/15629.

@ccordoba12 this PR is just a refactor of the widget rather than a change in the design pattern and it will not have any effect on the turn off of the plugins. 

> Finally, all this is to say: I don't know if it'd be better to revert this PR and discuss about it a bit more. What do you think?

Finally, I don't agree with reverting this PR. @mrclary has put a lot of effort into this, we finally merge it and there's nothing else to discuss.

**Comment by ccordoba12** [comment]
My comments:

To Ryan:

>  I apologize for prematurely merging this PR.

Thanks for understanding @mrclary!

> I think we should revert this PR and discuss it more when you have time.

We'll see, but thanks for being ok with the idea.

----

To Isabela:

> I'd rather take the blame here since, when asked, I said I'd personally merge it.

Don't worry. I think no one is to blame here.

> @mrclary has taken a lot of feedback on this very readily, but he can't take feedback that hasn't been communicated any more than I can know to watch for review I'm unaware of.

I totally agree. This was my fault.

> I don't think @mrclary stepped out of line at all.

I agree too. That's why I tried to be as polite as possible in my comment above.

> He's been tagging us and asking for review respectfully, patiently, and regularly for almost a year (April 2021 to March 2022).

I agree, the problem is that (due to the commitments and work I mentioned above) no one has had time to review it.

> I do know it's not common practice in open source to merge one's own PRs, and I generally support that. In this case I wasn't clear on another way to help move this PR forward.

Right, the thing is I had some things to say about the design before merging, that's all.

> In trying to learn from this, is there any documentation about these kind of expectations? Since there is sometimes self-merging happening on this repo, it makes it look like a viable option when it sounds like that may not be the case.

No, there isn't. But we could add some instructions to the review PR guidelines.

----

To Stephannie:

> As I already stated, I did review and approve this PR yesterday, so Ryan didn't merge his own work without any opinion or approval.

I know. What I meant is that Ryan didn't wait to hear from me yesterday (when I received another ping to look at this).

To be more specific, I was thinking of QtPy yesterday when I wrote that, where @dalthviz, @CAM-Gerlach and I have been successfully working on reviewing and merging work for the last months. There we try to wait for all developers asked for a review before merging, unless it's something urgent and some of us (usually me) fail to respond; and we don't merge our own PRs, i.e. someone else on the team does it.

> Thanks to the new API, we are able to do this modifications. For me, it makes sense to have the completions statusbar widget in the actual completions plugin since the component is dependent on it and it modifies what's displayed, which is not the case of having the widget in the maininterpreter plugin.

That's a difference of opinions and I'm fine with it. But that's why (for me) this required more discussion.

> So I don't agree that this is a little gain PR. And I just wanted to highlight that we shouldn't be using this language becase every PR is a gain.

Again, the little gain is my opinion. And I disagree that all PRs are a gain. For instance, you can take a look at this PR of mine in QtPy, which was rejected by @dalthviz and @CAM-Gerlach: https://github.com/spyder-ide/qtpy/pull/295.

They had strong arguments against my proposed changes, so we all agreed that it was best to close it.

> this PR is just a refactor of the widget rather than a change in the design pattern and it will not have any effect on the turn off of the plugins.

I disagree too and Ryan made it clear on the description above:

> > The interpreter-changed signal no longer routes through the MainWindow. Any services requiring it should access sig_interpreter_changed from the MainInterpreter plugin.

So Ryan removed `sig_interpreter_changed` from the MainWindow and moved it to the MainInterpreter plugin. As I said in my previous comment, this is very similar to the pattern followed in PR #15629. At the moment I agreed with Ryan that that was fine. However, after the new teardown mechanism landed, @andfoy and I said that we'd like to revisit that implementation at some point and revert it to using signals emitted by the MainWindow.

> Finally, I don't agree with reverting this PR. @mrclary has put a lot of effort into this, we finally merge it and there's nothing else to discuss.

I'm fine with the refactoring of the status bar widget, if the rest of the team agrees on that too. However, I think we should talk more about the removal of `sig_interpreter_changed` from MainWindow.

**Comment by mrclary** [comment]
@ccordoba12 @isabela-pf @steff456,
Thank you for your kind comments.

The changes to `sig_interpreter_changed`, as Carlos pointed out, were made in good faith following a previously agreed upon pattern. However, since that pattern has subsequently been reverted or changed, then we should certainly discuss what should be done to restore `sig_interpreter_changed` to compliance and make a follow-up PR.

I also agree that we could add some guidance to the PR guidelines and I'll make a few suggestions in a comment at #16789 .

**Comment by mrclary** [comment]
@ccordoba12, please don't be alarmed by the recent removal/request to review this PR. I was just testing GitHub's interface.

**Comment by ccordoba12** [comment]
Ok, no problem. Thanks for letting me know about it 👍🏽

**Comment by ccordoba12** [comment]
> The changes to sig_interpreter_changed, as Carlos pointed out, were made in good faith following a previously agreed upon pattern. However, since that pattern has subsequently been reverted or changed, then we should certainly discuss what should be done to restore sig_interpreter_changed to compliance and make a follow-up PR.

Ok, so are you ok with reverting that change so we can discuss about it later? Just checking with you before taking a decision here.

> I also agree that we could add some guidance to the PR guidelines and I'll make a few suggestions in a comment at https://github.com/spyder-ide/spyder/pull/16789 .

That's fine for me too. I'll leave my comments there.

**Pull request merged**
