### PR TITLE
PR: Implement dynamic variable explorer window size

### PR DESCRIPTION
**Pull request by jsh9**
Original PR: https://github.com/spyder-ide/spyder/pull/10880

(I incorrectly set the original PR to merge to the master branch, so I created a new PR here to point to branch "4.x".)

### Issue(s) Resolved

Fixes https://github.com/spyder-ide/spyder/issues/10745

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: jsh9

### CODE REVIEW

**Comment by jsh9** [comment]
@dalthviz @ccordoba12 Could you review this PR? Thanks!

**Comment by jsh9** [comment]
Hi @dalthviz , I saw that you found some errors. Is there anything I need to do? If it is easier for you to fix those two lines with "`width=xxx`", maybe you want to take over?

**Comment by dalthviz** [comment]
Well @jsh9 the idea will be to check and update lines such as the ones I remarked above (which could be more) that aren't taking into account the changes made to the dialogs (removing lines that call such dialogs the extra `kwargs`). If you can help us with that it would be great but I could also wrap up this one by doing that. Let us know what works better for you :)

**Comment by jsh9** [comment]
Hi @dalthviz , I'm less familiar with the whole code base than you do, so I think maybe it's better if you do it.

Thank you again for your help!

**Comment by ccordoba12** [comment]
@dalthviz, is this PR ready to be merged?

**Comment by dalthviz** [comment]
@ccordoba12 yep I think so :+1:

**Pull request merged**
