### PR TITLE
PR: Fix issues with expanded symbols when cursor is not being followed up

### LINKED ISSUE #14152: Items are collapsed in the outline explorer after a change was made in the editor when the option "Follow cursor position" is unchecked.
## Problem Description

In the outline explorer, items are collapsed after a change was made in the editor when the option `Follow cursor position` is unchecked.

outline_explorer_collapse

I believe this is a regression compared to the old behaviour. Here is an animation showing how it was working before the migration.

outline_explorer_collapse_before

## Versions

* Spyder version: 4.2.0.dev0 b7e9cf9b1
* Python version: 3.7.6 64-bit
* Qt version: 5.12.5
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### PR DESCRIPTION
**Pull request by andfoy**
## Description of Changes
This PR fixes some issues where symbols were collapsed when the `Follow cursor` option is disabled.

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Peek 16-11-2020 18-14

### Issue(s) Resolved

Fixes #14152

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by andfoy** [comment]
@jnsebgosselin Could you please check if this PR fixes your issue?

**Comment by ccordoba12** [comment]
@jnsebgosselin, I think @andfoy fixed the issues you raised on issue #14152, except for one thing. We can't maintain (due to a technical limitation) the selection in a symbol that is renamed because that corresponds to a new node in the tree, so we can't tell Qt to select it (because the previous node was a different object).

Other than that, the tree structure and the currently selected symbol are preserved when `Follow cursor position` is deactivated.

Therefore, I'm going to merge this PR to keep the backlog moving. Thanks for understanding.

**Review by ccordoba12 — APPROVED** [review]
Thanks @andfoy, great work here!

**Comment by jnsebgosselin** [comment]
This is excellent, thank you very much for working on this and sorry for the late feedback...

**Comment by jnsebgosselin** [comment]
> We can't maintain (due to a technical limitation) the selection in a symbol that is renamed because that corresponds to a new node in the tree. So we can't tell Qt to select it (because the previous node was a different object)

Just a little comment regarding this limitation. If a fix is implemented for Issue #14134, I think this would solve that.

This is just for the sake of documenting. This is really not a big deal.

**Pull request merged**
