### PR TITLE
PR: Fix extra blank line added to qtconsole when plotting

### LINKED ISSUE #10897: Blank line printed on console for each chart plotted
Small issue: an extra blank line is printed on the console every time I print a chart. You can see below on the Plots pane that I have plotted a few charts. Although there is no "print"  function on the section of the code that prints the charts, a new blank line is printed every time I new chart is plotted. Again, not a big issue but it messes up with the console formatting if the code prints some info during execution (which I always do).

Annotation 2019-12-01 121346

### PR DESCRIPTION
**Pull request by jnsebgosselin**
## Description of Changes

image

### Issue(s) Resolved

Fixes #10897

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Jean-Sébastien Gosselin

### CODE REVIEW

**Comment by jnsebgosselin** [comment]
The only thing I'm not sure is if we need to add a `self.log.debug("display_data: %s", msg.get('content', ''))` under the `if (self.figurebrowser is not None and self.figurebrowser.mute_inline_plotting):` condition.

**Comment by jnsebgosselin** [comment]
We may also need to call a `self.flush_clearoutput()` also.

**Comment by goanpeca** [comment]
Are the test fails related to this PR @jnsebgosselin ?

**Comment by jnsebgosselin** [comment]
> 
> 
> Are the test fails related to this PR @jnsebgosselin ?

I dont think so. It seems to be related to lsp and completion.

**Comment by ccordoba12** [comment]
Note: The failure in Azure is an spurious one (I don't understand how it got generated).

**Pull request merged**
