### PR TITLE
Added sorting to Keyboard Shortcuts (Fixes #2475)

### LINKED ISSUE #2475: Allow sorting by column of Keyboard Shortcuts.
It would be convenient if we could sort the Keyboard Shortcuts by column.

It would make it a lot easier to see if a given key is already used. For example, I could see all the items that are bound to F12 just by scrolling down to F12.

It was pretty easy to add, only having to change the plugins/shortcut.py module. I'll submit a PR soon, once I figure out how to do it... :-P

### PR DESCRIPTION
**Pull request by dougthor42**
Added ability to sort the Keyboard Shortcuts table. Fixes #2475.

### CODE REVIEW

**Comment by dougthor42** [comment]
Oh, and removing the end-of-line whitespace caused a whole bunch of deletions to be logged. Sorry about that!

In reality, the only actual change is +20 lines of code.

**Comment by goanpeca** [comment]
Hi @dougthor42, thanks for working on this. 

This PR will have to wait for #2367, as we are making a major revamp of the shortcuts table management. On a quick look of the code on this PR, it will not be compatible with the changes.

Cheers

**Comment by dougthor42** [comment]
Ah darn. Not a problem. I'll wait till #2367 is committed (btw, it looks awesome, kudos to blink1073) and come back at that time.

Thanks!

**Comment by goanpeca** [comment]
Hi @dougthor42, so now that the new shortcuts finder is in place, this PR is no longer needed. I have included sorting in the new changes being fixed over https://github.com/spyder-ide/spyder/pull/2523.

Thanks for workign on this though. Maybe you would like to work on https://github.com/spyder-ide/spyder/issues/2524 ? ;-)

Cheers

**Comment by ccordoba12** [comment]
Let's close it ourselves given that what this PR tried to achieved is obsolete now :-)

**Comment by goanpeca** [comment]
(I was trying to be nice :-), but ok)

**Comment by dougthor42** [comment]
> Maybe you would like to work on #2524 ? ;-)

Haha sadly no, not right now at least. Maybe if I get bored again at work :-P

**Pull request closed without merging**
