### PR TITLE
PR: Update workflows to accommodate GitHub deprecation of macos-12 runners (CI)

### PR DESCRIPTION
**Pull request by mrclary**
See https://github.com/actions/runner-images/issues/10721

### CODE REVIEW

**Comment by mrclary** [comment]
@ccordoba12, macos-13 runner does not have Miniconda preinstalled, causing the tests to fail. I don't know if we want to install that in addition to micromamba or change from `setup-micromamba` to `setup-miniconda`.

**Comment by ccordoba12** [comment]
> macos-13 runner does not have Miniconda preinstalled, causing the tests to fail.

Ok, that's not good.

> I don't know if we want to install that in addition to micromamba or change from setup-micromamba to setup-miniconda

There's no need to use to `setup-miniconda`. What's necessary is to set the `CONDA` env var to a certain directory in the Mac workflow file and then install Miniconda in `$CONDA` (I think it's better to do that in `install.sh`).

**Comment by ccordoba12** [comment]
Leaving this for 6.0.3 (or maybe even 6.0.4) to not affect the minimal Mac version supported by our installers in the 6.0 cycle.

**Comment by mrclary** [comment]
@ccordoba12, I recommend including this in 6.0.3 and merge as soon as is convenient as we are now experiencing the brown out for macOS 12. I don't think this will immediately impact any macOS 12 users, since this should only impact our CI environment and restricting macOS in our installer does not work yet.

**Comment by ccordoba12** [comment]
> I recommend including this in 6.0.3 and merge as soon as is convenient as we are now experiencing the brown out for macOS 12.

Yep, I noticed that in another PR and I think it's a good idea.

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary!

**Comment by ccordoba12** [comment]
@meeseeksdev please backport to 6.x

**Pull request merged**
