### PR TITLE
PR: Update links to docs when they are ready 

### LINKED ISSUE #5986: Move online documentation to Github Pages
The old PyPI doesn't allow to upload new documentation to pythonhosted.org, so we need to remove the docs hosted there and move them to readthedocs.

CAM-Gerlach Edit:

- [x] Move docs from both repo branches
- [x] Create/add other key files
    - [x] README
    - [x] CONTRIBUTING
    - [x] LICENSE
    - [x] AUTHORS
    - [x] .gitignore
    - [x] .gitattributes
- [x] Minor fixes to existing docs
    - [x] Harmonize line endings to LF
    - [x] Remove extra spaces
    - [x] Fix build warnings
 - [x] Add sphinx building and enable Travis
    - [x] Add/Setup sphinx makefiles
    - [x] Create/setup ``.travis.yml``
    - [x] Enable Travis and test builds
- [x] Setup repo settings
    - [x] Permissions
    - [x] Tags
    - [x] Description
    - [x] Protected branches
    - [x] Other settings as needed
- [x] Setup and enable doctr deployment
    - [x] Create ``gh-pages`` and ``.nojekyll``
    - [x] Configure doctr settings and keys
    - [x] Add doctr deployment to Travis
    - [x] Test functionality and deploy
- [x] Other work items
    - [x] Update conf.py with modernization and fixes
    - [x] Minor doc updates
- [ ] Before initial public release
    - [x] Update out of date screenshots
    - [x] Baseline editing pass to update and copyedit
        - [x] Initial cross-file changes
        - [x] Per-file updates, copyediting, line breaks and minimal expansion
        - [x] Apply remaining cross-file style guide formatting and fix links
    - [x] Decide on modern theme
    - [ ] Add Profiler doc: PR REVIEW
- [ ] Final steps to release
    - [x] Decide on what to do about multiple branches and implement
    - [x] Redirect to ``docs.spyder-ide.org`` subdomain
    - [x] Add banner and fonts, etc. from our main website
    - [ ] Final layout and link fixes: PR REVIEW
    - [ ] Font size harmonization: PR REVIEW
    - [ ] Add common footer (?)
    - [ ] Update other links throughout Spyder to point to new docs instead of PyHosted: PR REVIEW
- [ ] Following release
    - [ ] Inform/submit PRs to other sources to add/update Spyder website and doc links
    - [ ] Redirect or eventually remove PyHosted docs???

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Closes #5986

In preparation for the official public release of our new docs, this PR updates the links to them from PythonHosted to our own site. Currently blocked by 

* [x] ~~spyder-ide/spyder-docs#13~~
* [x] ~~spyder-ide/spyder-docs#14~~
* [x] ~~spyder-ide/spyder-docs#19~~
* [ ] spyder-ide/spyder-docs#26

so presumably shouldn't be merged until those are ready.

### CODE REVIEW

**Comment by ccordoba12** [comment]
This needs a merge with 3.x now.

**Comment by CAM-Gerlach** [comment]
I assume you mean ``rebase``. Yeah, thanks—it was something in #7169 . I'll do it as soon as I post the PR for spyder-ide/spyder-docs#13 , which I'm on the absolutely very last style change on and should be up within about 30 mins.

**Comment by ccordoba12** [comment]
> I assume you mean rebase

I really prefer merges unless there's a strong reason not to do it. In the case of #7141, I asked for a rebase because it's really odd to start a PR in 3.x and then merge it with master.

> which I'm on the absolutely very last style change on and should be up within about 30 mins.

Really great to know!

**Comment by CAM-Gerlach** [comment]
Oh, okay...I guess I assumed that because before I always recall you asking for a rebase when a PR needed to be updated for one reason or another, and I figured you wouldn't want to pollute the mainline's history with a pointless merge.

**Comment by ccordoba12** [comment]
It's easier to handle merges for developers and newcomers alike. Besides, rebases usually tamper with history.

I usually ask for rebases when the rebase is very simple to do (e.g. to pick up a change in our CIs done the same day or so).

**Comment by ccordoba12** [comment]
@CAM-Gerlach, I'm going to merge this even if the footer is not ready. I hope @dalthviz can finish it next week.

**Pull request merged**
