### PR TITLE
PR: Add an option to ignore installed Python libraries while debugging

### LINKED ISSUE #3232: Add "step into my code" option to the debugger
Dear developers,

Bug: There is a bug in "Debug": I set up break points (bps) in 2 files (A & B,  same directory), "A" stop in the bp line and a "step into" calls a function into file "B", this function has several bps, but no one is respected (bp only works in file A, not in file B).

If I remove the bps from A, Spyder doesn't stop into file B bps.

Suggestions: There are several commands for pdb / ipdb (https://docs.python.org/3/library/pdb.html)

1) unt(il) [lineno] is very useful to run a loop without step inside (think about big loops).

I suggest that this command stops in the Next Line After the Loop or stops in the Next Break Point (or both).

2) "step into my code" (from PyCharm) "helps skip stepping into library sources and keep focused on your own code", very useful to avoid enter into functions from python and other modules.

3) "ipdb" is colorized only if manually called "import ipdb; ipdb.set_trace()", the highlights are very useful in a debug process.

4) will be very nice to see the variable values directly in the code editor (like comments beside the variables) [screenshot](https://s31.postimg.org/kbna9dla3/2016_06_18_17_26_58.png)

5) in the "Variable explorer" add a new column "#" to sort by Declaration order (is useful to see the variables sorted by creation order)

Thank you very much for doing one of the best Python IDEs.

ps.: I'm using version 2.3.9 in ArchLinux.

John

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes

Add an option to skip libraries while debugging.
Solve part of https://github.com/spyder-ide/spyder/issues/3232:

>  2. "step into my code" (from PyCharm) "helps skip stepping into library sources and keep focused on your own code", very useful to avoid enter into functions from python and other modules.

see https://github.com/spyder-ide/spyder-kernels/pull/152

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #3232 (Partial)

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by impact27** [comment]
Updated spyder-kernels PR

**Comment by impact27** [comment]
This is ready for review

**Comment by ccordoba12** [comment]
@impact27, I updated both PR spyder-ide/spyder-kernels#152 (should be ready to be merged) and this one, but now tests are failing here.

Please take a look at the failure to see if we can merge them for 4.0rc, to be released tomorrow.

**Comment by impact27** [comment]
You merged the master in spyder but not in spyder-kernels

**Comment by impact27** [comment]
travis doesn't restart?

**Comment by ccordoba12** [comment]
@impact27, this now requires a merge with master to fix a merge conflict. Please also revert the changes to our installation scripts because I now spyder-ide/spyder-kernels#152 is in master of spyder-kernels.

**Pull request merged**
