### PR TITLE
PR: Don't convert values to text strings and fix sorting issues in the Variable Explorer

### LINKED ISSUE #9516: Variable Explorer bug when sorting by 'size'
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The variable explorer bugs when sorting variables by size.
spider
Here I ran my script and the variable explorer shows all my variables correctly.
spider 2
Here, I sorted the variables by type and everything is still fine.
spider 3
Here, I sorted the variables by size and the sorting is messed up.
As we can see in the first picture, my 'data' variable is a (32,117) Dataframe. On the second picture, everything is still ok, but in the third picture, when I sorted them by size, it shows that 'data' is (32,) size, while the correct size is attached to the 'conf_games' variable.

### What steps reproduce the problem?

1. Sort the variables by type and then by size.
2. 
3. 

### What is the expected output? What do you see instead?
Explained above.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 3.3.4
* Python version: 3.7.3
* Qt version: 5.9.2
* PyQt version: 5.9.6
* Operating System name/version: Windows 10

### Dependencies

```
PASTE DEPENDENCIES HERE
```

### LINKED ISSUE #9973: Sorting is not right when viewing a list in the Variable Explorer
Problem Description:
Produced a simple list the list shows up in the variable explorer in the order produced. When looking at the list in the console the order is maintained when opening the list from within the variable explorer to view the elements the order is not maintained. 

What steps to reproduce the problem?
1. in the console x = list(range(0,100))
2. x enter in the console shows the number in order
3. x shows in the variable explorer in order
4. when selecting x in the variable explorer to be viewed in a table the order is not maintained index numbers are all over the place.

What is the expected output? What do you see instead?
the ordered list

Versions
Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10
* Spyder version: Spyder 4.0.0b4 

Dependencies
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Fix sorting when using non text indexes (numbers for example)

ves

### Issue(s) Resolved

Fixes #9973 
Fixes #9516 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, please also try to solve here issue #9516.

**Comment by dalthviz** [comment]
@ccordoba12 the sorting by size is working for me here:

ves

**Comment by ccordoba12** [comment]
> the sorting by size is working for me here

Ok, then please add a test for it here that includes series, dataframes and lists, as in this screenshot:

spider

and verifies that sorting by size works as expected. Thanks!

**Comment by ccordoba12** [comment]
Note: The failures in Travis and Azure are unrelated to this.

**Pull request merged**
