### PR TITLE
PR: Fix restart for interactive backends

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

* We were not asking for a kernel restart when users first set the Qt5 backend, then the Interactive one and finally Tk. Apparently the last backend was set (because no message is shown to users) but that was not the case. Now we show a restart message to users.
* Increase minimal Matplotlib required version to `3.0.0` because we need functionality added to that version for this.
* Depends on spyder-ide/spyder-kernels#376.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @ccordoba12

### CODE REVIEW

**Comment by ccordoba12** [comment]
Yep, I resynced the subrepo again in my last commit.

**Review by dalthviz — COMMENTED** [review]
Thanks @ccordoba12 ! Checking this locally on WIndows I got this traceback changing from Qt5 to Tk (backend changes that require a restart and when I choose to restart the current kernel):

```python
Traceback (most recent call last):
  File "E:\Acer\Documentos\Spyder\Spyder otros\carlos\spyder\spyder\plugins\ipythonconsole\widgets\client.py", line 670, in _restart_thread_main
    self.shellwidget.kernel_manager.restart_kernel(
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\manager.py", line 530, in _async_restart_kernel
    await ensure_async(self.start_kernel(**self._launch_args))
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\manager.py", line 79, in wrapper
    raise e
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\manager.py", line 71, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\manager.py", line 380, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\manager.py", line 300, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 179, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\launcher.py", line 169, in launch_kernel
    raise ex
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\launcher.py", line 157, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\subprocess.py", line 808, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\subprocess.py", line 1178, in _get_handles
    c2pwrite = msvcrt.get_osfhandle(stdout.fileno())
ValueError: I/O operation on closed file

```

And messages in the console as errors like (dependning if you are going from Tk to Qt5 or Qt5 to Tk):

```
Tcl_AsyncDelete: async handler deleted by the wrong thread error in background error handler:
attempt to call eval in deleted interpreter
while executing
"::tcl::Bgerror {attempt to call eval in deleted interpreter} {‑code 1 ‑level 0 ‑errorstack {INNER {invokeStk1 bind TNotebook { ..."
```

```
[SpyderKernelApp] ERROR | KeyboardInterrupt caught in kernel.
```

**Comment by ccordoba12** [comment]
Thanks for checking @dalthviz! Please update to ipykernel 6.9.2, which includes some changes of mine that should fix that problem.

**Comment by dalthviz** [comment]
@ccordoba12 updated to ipykernel 6.9.2 but I still get the errors when changing and accepting to restart the kernel(s)

**Comment by ccordoba12** [comment]
Ok, the mechanism to run the Tk backend on Windows is different than the one from Linux/Mac, so I'll have to check.

But what if you add `ValueError` to `RuntimeError` here?

https://github.com/spyder-ide/spyder/blob/8026178de3bbab391c917c01f8c4e887a6ad8315/spyder/plugins/ipythonconsole/widgets/client.py#L667-L674

That could solve the bug and allow a successful restart.

**Comment by dalthviz** [comment]
@ccordoba12 doing that gives me this:

imagen

And a traceack in the anaconda prompt from where I launched spyder:

```
ERROR:traitlets:Failed to run command:
['C:\\Users\\dalth\\anaconda3\\envs\\spy5\\python.exe', '-m', 'spyder_kernels.console', '-f', 'C:\\Users\\dalth\\AppData\\Roaming\\jupyter\\runtime\\kernel-982ab15e1c4d.json']
    PATH='C:\\Users\\dalth\\anaconda3\\envs\\spy5;C:\\Users\\dalth\\anaconda3\\envs\\spy5\\Library\\mingw-w64\\bin;C:\\Users\\dalth\\anaconda3\\envs\\spy5\\Library\\usr\\bin;C:\\Users\\dalth\\anaconda3\\envs\\spy5\\Library\\bin;C:\\Users\\dalth\\anaconda3\\envs\\spy5\\Scripts;C:\\Users\\dalth\\anaconda3\\envs\\spy5\\bin;C:\\Users\\dalth\\anaconda3\\condabin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Windows\\System32\\OpenSSH;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Git\\cmd;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Users\\dalth\\.pyenv\\pyenv-win\\bin;C:\\Users\\dalth\\.pyenv\\pyenv-win\\shims;C:\\Users\\dalth\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\dalth\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Program Files (x86)\\GnuWin32\\bin;.'
    with kwargs:
{'stdin': -1, 'stdout': <codecs.StreamReaderWriter object at 0x0000019731A371F0>, 'stderr': <codecs.StreamReaderWriter object at 0x0000019731A37310>, 'cwd': None, 'close_fds': False}

ERROR:traitlets:I/O operation on closed file
Traceback (most recent call last):
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\manager.py", line 71, in wrapper
    out = await method(self, *args, **kwargs)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\manager.py", line 380, in _async_start_kernel
    await ensure_async(self._launch_kernel(kernel_cmd, **kw))
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\utils.py", line 26, in wrapped
    raise e
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\utils.py", line 23, in wrapped
    return loop.run_until_complete(future)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\nest_asyncio.py", line 81, in run_until_complete
    return f.result()
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\asyncio\tasks.py", line 280, in __step
    result = coro.send(None)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\manager.py", line 300, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\provisioning\local_provisioner.py", line 179, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\launcher.py", line 169, in launch_kernel
    raise ex
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\site-packages\jupyter_client\launcher.py", line 157, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\subprocess.py", line 808, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "C:\Users\dalth\anaconda3\envs\spy5\lib\subprocess.py", line 1178, in _get_handles
    c2pwrite = msvcrt.get_osfhandle(stdout.fileno())
ValueError: I/O operation on closed file

```

**Comment by dalthviz** [comment]
I think I saw a similar traceback on the test with PyQt 5.15 and I ended up changing this line:

https://github.com/ccordoba12/spyder/blob/e67a169bcadb0de06d8cf97c3e73955f145f35b6/spyder/plugins/ipythonconsole/widgets/client.py#L518-L519
```python
        self.remove_std_files()
```


To be:

```python
        self.remove_std_files(is_last_client=False)
```

I tested it and I can not see a traceback now but the error messages in the console still appear:

From Qt5 to Tk:

imagen


From Tk to Qt5:

imagen

**Comment by dalthviz** [comment]
Checking the Tk to Qt5 backend message I found this: https://bugs.python.org/issue39093

**Comment by ccordoba12** [comment]
Great! Thanks for your thorough review @dalthviz!

I think I know how to fix those problems, so I'll take a look at them later this week.

**Comment by ccordoba12** [comment]
@dalthviz, commit 8ed58fc should fix the errors you reported above. Please test again and let me know if it works for you.

**Pull request merged**
