### PR TITLE
Pr1962 rename ipython consoles

### PR DESCRIPTION
**Pull request by tjolive**
- Aligned with comments
- Corrected missing blinking cursor when editing tab name

### CODE REVIEW

**Comment by ccordoba12** [comment]
Why did you open this new PR? Can we close it?

**Comment by ccordoba12** [comment]
Closing. Please continue your work on your previous PR.

**Comment by tjolive** [comment]
Hi @ccordoba12 ,

Sorry for the delayed response. You are right in closing this PR, my intension was to commit the changes reflecting your comments on the the original PR and ended up creating a new one.

Cheers,
T

**Comment by tjolive** [comment]
...intention...

**Pull request closed without merging**
