### PR TITLE
PR: Update French translation for 3.2

### PR DESCRIPTION
**Pull request by goanpeca**
As always, there are probably mistakes or funny wording so it is @Nodd's and @SylvainCorlay's fault :-p

### CODE REVIEW

**Comment by ccordoba12** [comment]
@SylvainCorlay or @Nodd, do you have any comments on Gonzalo's translation?

**Comment by ccordoba12** [comment]
@afvincent, we forgot about you. Would you mind to take a look at @goanpeca's translation?

**Comment by goanpeca** [comment]
>Would you mind to take a look at @goanpeca's translation?

And be gentle :-|

**Comment by afvincent** [comment]
I´ll try to have a look at it tonight. And @goanpeca, don´t worry too much ;).

**Comment by ccordoba12** [comment]
Thanks!

**Comment by afvincent** [comment]
Work in progress but @goanpeca worked too much ^^: I have to stop for tonight. Hopefully I will be able to finish tomorrow. In overall, there is likely to be a few dozens of *minor* comments, which is possible because the translations are already quite good ;).

**Comment by ccordoba12** [comment]
@afvincent, I have to do the the release today, so we can't wait longer for your feedback. Please open a new PR with your corrections and we'll merge it for 3.2.1

Thanks for understanding.

**Pull request merged**
