### PR TITLE
PR: Add Hungarian translation

### PR DESCRIPTION
**Pull request by martindurant**
This includes https://github.com/spyder-ide/spyder/pull/4326 , but for the 3.x branch, plus additional edits and completions.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@martindurant, thanks a lot for this!! Is there something else you want to add to the translation or can we merge this?

**Comment by martindurant** [comment]
There is a lot a potential work here yet (which is why I titled this WIP), so it depends how urgent merging is. Many phrases in spyder.po are either missing or done by blackpanther using some automated tool that is frequently wrong.

**Comment by ccordoba12** [comment]
Ok, Spyder 3.2 is planned for mid or late June at most, so you still have time to improve the translation.

Thanks a lot for helping us with this!

**Comment by ccordoba12** [comment]
@martindurant, please rebase in top of our latest 3.x to fix the test errors.

I moved your PR to 3.2.1 (to be released in a couple of months) so you can finish this without rushes. However, if you want this to be included in 3.2.0, you need to hurry because we're going to release it next week ;-)

**Comment by martindurant** [comment]
I think it can go in, and with luck, others will provide corrections/completions.

**Comment by ccordoba12** [comment]
Martin, the first pass is really the hardest one. After that, it's just a matter of translating very few (usually no more than 10) strings per release.

So I'd really prefer that you would help us to finish this one before merging. As I said, you could do it for 3.2.1, so there's no rush.

**Comment by martindurant** [comment]
It's fine with me, whichever you prefer. I am hoping to get some input from others, though, because my technical writing in Hungarian is certainly novice (it's not the same as conversational language, of course). 
With scipy and other things coming up, I can't promise many hours at all for a while.

**Comment by ccordoba12** [comment]
Closing because this is not finished.

**Comment by martindurant** [comment]
@ccordoba12 : I actually think this was complete enough to be useful, and promote other people to get involved to fix the parts I missed or didn't know how to translate.

**Comment by ccordoba12** [comment]
Hey @martindurant! I thought it was missing some more work. So do you think we should merge it as it is?

Also, Spyder 4 will bring more translation strings. Could you help us to update them when the time comes?

**Comment by martindurant** [comment]
Yes, I would merge it. I will *try* to get translation time in the morning, but I don't know what I can promise :|

**Comment by ccordoba12** [comment]
> I will try to get translation time in the morning, but I don't know what I can promise :|

Thanks Martin! I'll update our translation strings for beta2, so you and our translators can start working on them, instead of doing all that work in a very short amount of time.

**Pull request merged**
