### PR TITLE
PR: Add flag to prevent adding initial empty QAction on Mac for non-migrated menus

### LINKED ISSUE #14661: There's a blank space in the menus in the top in macOS
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
In the current master, when navigating through the menus a blank entry is shown

image

image

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Flag to preserve UI even with a mix of migrated and non-migrated menus

Preview:
menuMac

### Issue(s) Resolved

Fixes #14661 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by dalthviz** [comment]
Note: Also, @ccordoba12 @steff456, seems like there is a bug with the `menuBar` on Mac. You need to make it disappear and appear again (for example changing to another application and going back to Spyder) to be able to interact with it. Seems like this issue is also present in `4.x` as far as I could test. Is there an issue created already for that?

**Comment by ccordoba12** [comment]
> Seems like this issue is also present in 4.x as far as I could test. Is there an issue created already for that?

I think this happens because we use `python` instead of `pythonw` to start Spyder in development mode. I think @steff456 and @juanis2112 reported it before, but it shouldn't be an issue for our Mac app or when you install Spyder with `conda install spyder`.

Could you test that to be sure?

**Comment by steff456** [comment]
This PR fixes the empty menu entry 🎉

image

The other issue we haven't been able to fix it, but I think that we are accustomed to changing the app once it opens for now.

**Review by steff456 — APPROVED** [review]
This PR is ready for merge!!

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @dalthviz!

**Comment by dalthviz** [comment]
>Could you test that to be sure?

Seems like this only happens indeed when running with `python` instead of `pythonw` (when running `pythonw bootstrap.py` the menus work without the need to change the focus from the application)

**Comment by ccordoba12** [comment]
Great! Thanks @dalthviz for the confirmation.

@steff456, I thought you said running `pythow bootstrap.py` generated an error for you. Could you verify that again?

**Pull request merged**
