### PR TITLE
PR: Introduce completions correctly for autocompletion characters and improve file completions (Editor)

### LINKED ISSUE #20331: Fix on dot completion leads to dot replacement
on this 2023-01-08 early morning master of 5.X  https://github.com/spyder-ide/spyder/commit/da661ccfe2f0355459f4e18f87d22337e4cd36dc

the dot completion works again, but if we validate a choice, the dot is replaced also, if we don't type a first letter of the world choosen

GIF_dot_completion_20230108

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

- Completions were not introduced correctly when one was selected in the completion widget after they were triggered automatically next to a dot.
- Fix introducing completions for files and directories that start with a dot (they were not introduced correctly either).
- Fix introducing completions for files and directories in empty strings, i.e. you can hit `Tab` in a empty string (`"<Tab>"`) and Jedi will provide file completions in that case. The problem was the selected entry was not placed correctly in the editor either.
- Fix introducing file and directory completions next to a path separator (i.e. `os.sep`).
- Expand tests to cover all those cases.
- Depends on https://github.com/python-lsp/python-lsp-server/pull/337

### Issue(s) Resolved

Fixes #20331 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
@mrclary, the conda-based installer for Mac is failing (I don't understand why). Could you check at that? Thanks!

**Comment by ccordoba12** [comment]
Great! Thanks a lot for your help with that 👍🏽

**Comment by mrclary** [comment]
@ccordoba12, looks like work I already had in the pipeline (PR #20319) will fix the failing conda-based installers.

**Comment by ccordoba12** [comment]
Ok, great news! I'll review it right away so we can include it in 5.4.2 then.

**Review by dalthviz — COMMENTED** [review]
Thanks @ccordoba12 ! Checking this locally the only thing I manage to see that I'm not totally sure if it is correct is that the dot completion for filenames gives back the filename again instead of the extension for filename completions:

completion

Also, I left a suggestion in a comment for a typo and as we discussed, this needs a rebase to get the fixes done to the conda-based installers workflows

**Comment by ccordoba12** [comment]
> Checking this locally the only thing I manage to see that I'm not totally sure if it is correct is that the dot completion for filenames gives back the filename again instead of the extension for filename completions

Good catch @dalthviz! I fixed that use case in my last commit and added a test for it.

**Review by dalthviz — COMMENTED** [review]
Checked again but seems like there are still some cases not being correctly handle like a double dot for files:

completion2

**Comment by ccordoba12** [comment]
@mrclary, I don't understand why the conda-based installers started to fail again. Could you take a look at that?

**Comment by mrclary** [comment]
> @mrclary, I don't understand why the conda-based installers started to fail again. Could you take a look at that?

So, the real issue is that I should be using `git diff` instead of `git format-patch` to generate the patch. I'll submit a PR for the change. I don't know why this only plagued Linux and not macOS... 🤷🏼‍♂️

**Comment by mrclary** [comment]
@ccordoba12 #20376 should resolve the failing conda-installers

**Comment by mrclary** [comment]
Actually, that resolved the initial patch issue when building Spyder. But now I see a package conflict error when building the installer...

**Comment by mrclary** [comment]
Nevermind, I was normalizing the version, which apparently is not good.
So, all should be good now.

**Comment by ccordoba12** [comment]
@dalthviz, this should be ready for another review. I fixed the last problem you reported, fixed several issues with file completions next to path separators (i.e. `os.sep`), and added `os.sep` at the end of directory completions in the pylsp to ease introducing additional file completions.

**Comment by dalthviz** [comment]
Checked again and the last issue is fixed :+1:, however, with further testing, there is still a strange behavior for the completion of files names:

completion3

**Comment by ccordoba12** [comment]
> however, with further testing, there is still a strange behavior for the completion of files names

Yeah, I found that too while testing but there's no easy solution for it. The thing is we select the word under the cursor (using Qt) and send it to pylsp for completions. But in this case:

    part.0.parq<Tab>

the selected word is `parq` because Qt considers that a word goes up to a dot. And pylsp can find no completions for it.

To solve this, we should override Qt and extend the search for current words to go up to `part` (the file name). But that's not so simple and it could introduce more corner cases and regressions. So, I think for now this is the best we can do to provide good enough file completions.

**Review by dalthviz — APPROVED** [review]

**Comment by luistrotta19** [comment]
Buenas tardes, qusiera que spyder proporcione detalles de los metodos al colocar el cursor encima del objeto, como lo hace VSC, antes se podía instalar kite, pero ahora no está disponible, hay algún sustituto?, gracias, saludos

**Pull request merged**
