### PR TITLE
remove pinning of Jedi and Parso

### PR DESCRIPTION
**Pull request by bnavigator**
as adviced in #11975

### CODE REVIEW

**Comment by ccordoba12** [comment]
You need to remove first the pinning in the python-language-server first:

https://github.com/palantir/python-language-server

Unpinning things here will simply fail, so closing this for now so you don't wast resources in our CIs.

**Comment by bnavigator** [comment]
okay, wasting resources on Travis on my own repo for now:
https://github.com/bnavigator/spyder/tree/jedi-ease \[[Travis](https://travis-ci.org/github/bnavigator/spyder/branches?utm_medium=notification&utm_source=github_status)\]

Seems that a Jedi test is failing, but the Traceback is not very useful.
Did not activate the other CIs, not bothering to sign up yet.

**Comment by ccordoba12** [comment]
@bnavigator, please don't waste your time either and make first the PR I told you about in the python-language-server. Due to the constraint there on Jedi (`>=0.14.1,<0.16`) none of the tests here are going to pass because setuptools is going to fail when checking for that constrain before starting the server.

**Comment by bnavigator** [comment]
Have you looked at the branch? I forked python-language-server and unpinned the jedi and parso constraints. Installing from bnavigator/python-language-server@jedi-unpin in travis/install.sh

**Pull request closed without merging**
