### PR TITLE
PR: Change from pep8 to pycodestyle for style analysis  

### LINKED ISSUE #3197: Use pycodestyle instead of pep8
PyCQA/pycodestyle#466

### PR DESCRIPTION
**Pull request by rlaverde**
Fixes #3197
 
---------------
I change only the necessary in the code, I didn't change variables, classes, or config options names.

When checking dependencies, is required 0.6  version of pycodestyle, this is a bit outdated, should we updated it?
`PEP8_REQVER = '>=0.6'`

### CODE REVIEW

**Comment by ccordoba12** [comment]
> When checking dependencies, is required 0.6 version of pycodestyle, this is a bit outdated, should we updated it?

Sure, please update it to a more recent version.

**Comment by rlaverde** [comment]
>Sure, please update it to a more recent version.

Done 😄

**Comment by ccordoba12** [comment]
Could you add a test to verify that CodeEditor is showing pep8 warnings? That's something that's not tested at the moment, and given the importance of this change, I think we should start doing it :-)

**Comment by ccordoba12** [comment]
`test_codeanalysis` is now failing @rlaverde, please review that.

**Comment by rlaverde** [comment]
The new version of pycodestyle now detect one more style error than the previous version, I updated the `num_results`

`spyder/utils/tests/data/example.py:53:1: E305 expected 2 blank lines after class or function definition, found 1`

**Comment by ccordoba12** [comment]
Thanks @rlaverde!

**Comment by ccordoba12** [comment]
Thanks @rlaverde!

One missing thing: Please update our Readme too.

**Pull request merged**
