### PR TITLE
PR: Improving Spyder 3 icon theme

### PR DESCRIPTION
**Pull request by SylvainCorlay**
- This changes the run-cell icons:
    - The red arrow in the `run-cell-and-advance`icon now has the same shape as for `step-out` which is pixel perfect
    - there is no white background anymore for the page on the `run-cel`l icons
    - page border and cell border are merged in a single layer
    - Here are the old and new versions:
          - before
          - after
- The icon indicating an error in the line in the editor margin is now dark red.
- The quit icon is now dark red.
- The a-propos icon ("i") is now blue.
- The stop icon on consoles is now dark red (when active).

stop

- The cog (tooloptions) icons are (dark) gray. It still has to be really dark to be visible on the gray background in OS X.
- The restart icon is now blue.
- The private method icon has been redesigned. Rather than a circled minus, we have a circled underscore. Besides, it is light red to make it more easily distinguished from the default method icon.

private

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Remains to do
- [ ] The icons for both private and public methods in the Outline are both round, white on green. It's harder to distinguish between the to with a quick glance. Also the icon for private methods looks like a green no entry sign, that's disturbing. The hyphen could be at least a bit to the bottom so that it looks more like an underscore.
- [ ] The parameter icons could be dark grey instead of full black
- [ ] Checkmarks in the margins have the same orange as the warning icon. The blue of the old icons was good.
- [ ] Documentation should be red (the buoy)
- [ ] The rotation arrow for reboot is usually blue

**Comment by Nodd** [comment]
Those remarks are from me so i'll answer:
* The reboot icon is just above Quit in the File menu
* The documentation icon is the first entry in the help menu

**Comment by SylvainCorlay** [comment]
@Nodd thanks. Will update these tonight.

**Comment by goanpeca** [comment]
@SylvainCorlay dont forget the screenshot :-p

**Comment by SylvainCorlay** [comment]
What is the parameter icon?

**Comment by Nodd** [comment]
The cog wheels. Having them dark gray rather than black would give a more metallic look, and differentiate it from all the other black icons. There is one in the console widget and one in the help widget.
There is one for the dependencies entry in the help menu, but I feel like it's the wrong icon here. I don't know which one would be better...

**Comment by SylvainCorlay** [comment]
> Those remarks are from me so i'll answer:
> * The reboot icon is just above Quit in the File menu
> * The documentation icon is the first entry in the help menu

OK, So for the reboot icon, there was another comment asking for it to be red, which is what I did.

**Comment by SylvainCorlay** [comment]
Btw, I still *really* prefer the font-awesome bug http://fortawesome.github.io/Font-Awesome/icon/bug/ for the debug icon rather than the play/pause icon.

**Comment by goanpeca** [comment]
DE-BUG, why no mixing 

http://fortawesome.github.io/Font-Awesome/icon/ban/

and

http://fortawesome.github.io/Font-Awesome/icon/bug/ 

I agree with @SylvainCorlay that play/pause is not good enough.

**Comment by goanpeca** [comment]
@SylvainCorlay also, please post screenshots so we can get a quick idea of the status

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay also, please post screenshots so we can get a quick idea of the status

See updated description above. For more, you will really need to run the branch because aspect depends on the platform and context menu icons are not displayed on OS X.

**Comment by goanpeca** [comment]
Cool thanks

> See updated description above. For more, you will really need to run the branch because aspect depends on the platform and context menu icons are not displayed on OS X. (I am travelling in Europe since yesterday and I don't have a windows machine with me.)

I know, but for PRs that are about look changes a screenshot is really necessary (should be mandatory...if you ask me!).

**Comment by SylvainCorlay** [comment]
@goanpeca I have been posting a lot of screenshots for the icon work including for this PR. It is just that I cannot do the context menu ones *right now*.

**Comment by Nodd** [comment]
A bug only looks like a bug report to me. Maybe a play button over the bug (better than the ban in my opinion) ? It's still a play button, but the code is run after all...

**Comment by SylvainCorlay** [comment]
That said, eclipse uses such a bug icon for a debug button :)

**Comment by ccordoba12** [comment]
I don't like a bug for the Debug button (as I said it before :-). I used debug a lot in Octave and almost always it meant to me `run and pause`, i.e. I used not to find bugs but to pause my code at a particular place and inspect what was the state of my variables there, or to plot something at that point.

**Comment by SylvainCorlay** [comment]
This is ready IMO. If want to separate this from the change of shape of the run-cell icons which might trigger more debate.

**Comment by ccordoba12** [comment]
The new cell icons are great!! Thanks @SylvainCorlay for the changes :-)

----

These are the things you still need to address before merging:

- [ ] Change IPython icon to the Jupyter one (the `IP:` one to be the favicon on try.jupyter.org)
- [ ] Remove the plus sign from the *New file* icon. I don't like it, I think it's fine without that sign.
- [ ] `TODO`, `XXX` check signs are still in orange instead of light blue.

**Comment by SylvainCorlay** [comment]
Test failures seem unrelated.

**Comment by ccordoba12** [comment]
Please merge with master to have that error fixed.

**Comment by ccordoba12** [comment]
Sorry, the IPython icon should be left as it is because it's the icon shown on the taskbar by the Jupyter qtconsole application when you start it independently.

However, that doesn't look good. The `IP` letters are blurred, so you can't easily read them. Is there a way to improve it @SylvainCorlay?

**Comment by SylvainCorlay** [comment]
Rebased. I am surprised that the IP: icon is blurred. It should be pixel-perfect.

**Comment by SylvainCorlay** [comment]
@ccordoba12 do you have a screenshot of the blur IP: icon?

**Comment by ccordoba12** [comment]
This is what I'm seeing in my computer:

seleccion_001

So the `IP:` text is hardly readable. Your screenshot above (in your initial comment) is very similar too. What if the try the icon with the letters in black and a transparent background? It could be more readable that way :-)

----

Besides, I'm seeing a kind of an shadow in the lower border of the new cell icons:

seleccion_002

That could solved (I think) by making cell icons borders a bit thicker, for example of the same thickness as the *New File* icon.

All the other icons look pretty good by the way ;-)

**Comment by SylvainCorlay** [comment]
- The `IP:` icon is pixel perfect at standard icon size (16px) which corresponds to font-size 14. The tab icon in the ipython console is 12px wide, which is not a pixel perfect size, so there is not much we can do about it by changing the icon, but we could make the TabWidget's iconSize attribute equal to 16px.

- The run-cell icons are *not* pixel perfect. I kept the design we made at scipy for now. Making them pixel perfect indeed requires having borders twice has thick.
As mentioned in the discussion of #2490 . 
I would prefer to do this in a different PR because I foresee a lot of different opinions on this.

**Comment by goanpeca** [comment]
@SylvainCorlay for the tab change I think is fine, but it should check first the actual TabWidget's icons size and only change it if it is smaller than what its needed.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay for the tab change I think is fine, but it should check first the actual TabWidget's icons size and only change it if it is smaller than what its needed.

The smallest pixel perfect icon size is 16px. The default TabWidget icon size is style-dependent, so that should probably be fixed globally for the entire app.

**Comment by SylvainCorlay** [comment]
merge?

**Comment by ccordoba12** [comment]
Yes, so you can finish the cell icons :-)

**Pull request merged**
