### PR TITLE
spyder_io_hdf5 plugin not available (Issue #4487)

### PR DESCRIPTION
**Pull request by smjorda**
This code change apparently fixes it (line 51 and down of otherplugins.py):

for name in os.listdir(plugin_path):
    # Is this a Spyder plugin?
    if not name.startswith(PLUGIN_PREFIX):
        continue
    # Ensure right type of plugin
    if is_io != name.startswith(IO_PREFIX):
        continue

    # Import the plugin
    _import_plugin(name, plugin_path, modnames, modlist)

### CODE REVIEW

**Comment by ccordoba12** [comment]
I'm afraid your pull request went wrong. It seems you merged master to 3.x, and there's no need for that.

So I'm going to close this PR and kindly ask you to open a new one.

**Comment by smjorda** [comment]
Sorry. I'm new to Github. I'm still on svn. Will try again.SimonOn 19 May 2017 6:54 p.m., Carlos Cordoba <notifications@github.com> wrote:I'm afraid your pull request went wrong. It seems you merged master to 3.x, and there's no need for that.
So I'm going to close this PR and kindly ask you to open a new one.

**Comment by ccordoba12** [comment]
No problem, don't worry about it :-)

**Comment by ccordoba12** [comment]
@dalthviz used your proposed changes in PR #4521. Thanks for your contribution!

**Pull request closed without merging**
