### PR TITLE
PR: Add ability to show plots for dataframes (Variable Explorer)

### LINKED ISSUE #21743: Enhancement proposal: create a plot button in variable explorer to visualize numerical data
Hello guys, I would like to propose a plot button in variable explorer to visualize numerical data of tables, lists, dataframes, etc as in my group we deal daily with this issue, when we need to understand the meaning of some amount of data in scientific notation for example in a table, that does not make much sense in table format, but so in a graph.
I know we could use "Plots" pane in IPython console or running the code to visualize it, but would be very useful to have this implemented in a button and menu of variable explorer directly.
We did something similar to this in our internal plugin, to plot table files as you can see bellow, so if you agree _I can work on this enhancement_.
Please let me know your opinion.
graph

### PR DESCRIPTION
**Pull request by dpturibio**
## Description of Changes

* [X] Wrote at least one-line docstrings (for any new functions)
* [X] Added unit test(s) covering the changes (if testable)

* [X] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Enables "plot" item for dataframes following the same structure of code used for plotting arrays, that redirects the plot to IPython console at the end, using %varexp --plot [variable_name]

### Issue(s) Resolved

Fixes #21743 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @dpturibio

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @dpturibio, thanks for your work on this! For now, please rebase on top of or merge with our latest master to get the fixes we did last week to our tests.

**Comment by dpturibio** [comment]
Thank you @ccordoba12.
I was wondering why so many tests were failing, and that's why...

**Comment by dpturibio** [comment]
@ccordoba12 let me know if code is ok to merge

**Review by ccordoba12 — COMMENTED** [review]
Thanks for your contribution @dpturibio! I left two small suggestions for you, the rest looks good to me.

**Comment by dpturibio** [comment]
> Thanks for your contribution @dpturibio! I left two small suggestions for you, the rest looks good to me.

Thank you @ccordoba12 for the inputs on the small but well-pointed suggestions. If everything is ok for you, please proceed with the MR. Thank you again for all the support.

**Review by ccordoba12 — APPROVED** [review]
Looks good to me now, thanks @dpturibio!

**Pull request merged**
