### PR TITLE
PR: Various Fixes to improve compatibility with PySide2. 

### PR DESCRIPTION
**Pull request by rear1019**
## Description of Changes

Various fixes to improve compatibility with PySide2. Notes
* `pyside2: Fix usage of keyword argument in QSpacerItem`: It should be possible to fix this globally via monkey patching in `qtpy`, similar to spyder-ide/qtpy#341. Please let me know if this is desired.
* `pyside2: Fix QObject.disconnect() calls`: Unfortunately, this cannot be fixed globally via monkey patching in `qtpy`.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

rear1019

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @rear1019, thanks again for your help improving our PySide2 support! You said:

> It should be possible to fix this globally via monkey patching in qtpy

I think that's a good idea. @dalthviz, what do you think?

**Comment by ccordoba12** [comment]
> Please let me know if this is desired.

Since @dalthviz agreed with your suggestion, could you monkey patch `QSpacerItem` in `qtpy` and then go back here and update this PR? Thanks @rear1019!

**Comment by ccordoba12** [comment]
@rear1019, let us know if you want to make the changes in `qtpy` or not. If you're too busy these days, we can merge this one as it is.

**Comment by rear1019** [comment]
> @rear1019, let us know if you want to make the changes in `qtpy` or not. If you're too busy these days, we can merge this one as it is.

Hi @ccordoba12, please merge as is. Unfortunately, I haven’t been able to work on Spyder over the last few weeks. I will try to make a patch for `qtpy` next week.

**Review by ccordoba12 — APPROVED** [review]
Thanks @rear1019!

**Pull request merged**
