### PR TITLE
PR: Set parent for Variable Explorer editors so Spyder closes properly

### LINKED ISSUE #5696: Variable Explorer windows don't close when Spyder exits; prevents it from reopening until manually closed
## Description

Recently, I've experienced issues on my Windows 8.1 Pro x64 and Windows 10 Ent x64 machines where Spyder will mysteriously not launch (from the start menu icon) with no indication as to why, only on close inspection to find a variable explorer window hidden somewhere that hasn't closed when Spyder exits (as it presumably should). As far as I'm aware, _any_ open variable explorer window, regardless of type, on Spyder exit will stay open and trigger this behavior; Spyder will only launch after every such window is manually tracked down and closed. 

As the windows have little to no function when Spyder is not open, it seems they should be terminated along with their parent application. Perhaps something to do with them have a dialog-type UI, rather than a normal window? No clue; not a GUI programmer.

**What steps will reproduce the problem?**

1. Double click on a suitable variable name in the main variable explorer to open a variable explorer window,
2. Close Spyder.
3.  Attempt to relaunch via start menu shortcut without closing variable explorer sub windows

**What is the expected output? What do you see instead?**

Expected: Variable explorer windows close along with Spyder, and the latter is able to then launch normally after doing so.

Actual: Variable explorer windows do not close with spyder and stay in the background, often hidden, and prevent Spyder from relaunching. 

**Please provide any additional information below**

Reproduced on multiple OS versions/Spyder installs/physical machines.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 8.1 Pro x64 and Windows 10 Ent x64

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
Fix #5696 .

Currently, any window launched from the Variable Explorer (Dataframe Editor, Collections Editor, etc) will cause Spyder to stay open even if the main window is closed, leading to extra resources and cluter, user confusion and general sub-optimal Ux. Therefore, this PR sets that properly to fix it, and additionally adds a specific test for this as well as improves the existing ones to make them less brittle (as this change broke one of them, my own). Also, updated file/section headers to the consistent standard and did a few bits of minor cleanup around lines that were changed.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@CAM-Gerlach, now this one needs a rebase :-)

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Done. FYI, ``test_elapsed_time`` failed several times on the Python 3.6 builds of both AppVeyor and Travis; the AppVeyor build eventually passed while the Travis one failed all three times and I had to restart it, whence it eventually succeeded. Should I submit a PR to play with the timeouts, etc or if necessary just skip it on Py3.6, or do you have a better fix in mind?

**Comment by ccordoba12** [comment]
I think increasing the timeouts should be enough. Thanks!

**Comment by CAM-Gerlach** [comment]
> I think increasing the timeouts should be enough. Thanks!

@ccordoba12 Done, as a separate PR of course ( #6714 ). Did so on the two tests that were causing issues, along with related tweaks to a few other tests known to be flaky on Linux locally per you and jitseniesen .

Is there anything you need me to change/do on this one, or is it ready to merge?

**Pull request merged**
