### PR TITLE
PR: Change pep8 check_executable for pycodestyle.

### LINKED ISSUE #5791: "Real-time code style analysis" checkbox in Prefs > Editor > Introspection checks for pep8, not pycodestyle
## Description of your problem

In examining the code relevant to #5770 I noticed the following apparent bug, which I was able to reproduce cleanly in actual use. The "Real-time code style analysis" checkbox apparently in both `master` and `3.x` checks for the presence of `pep8` (`is_pep8 = get_checker_executable("pep8")`) and not `pycodestyle`; the former is not listed in requirements.txt for Spyder in either branch, and thus the user cannot enable `pep8` checking unless they separately install `pep8` for `get_checker_executable` to find it, even though Spyder's real time code style checking is now done by `pycodestyle`, not `pep8` anymore.

To verify this was an actual issue in real world use, I modified the relevant line in the file [plugins/editor.py](https://github.com/spyder-ide/spyder/blob/8397cfbc4acc0803fb0570c9bca7e529435203f3/spyder/plugins/editor.py) in a build forked from the `master` branch to read `get_checker_executable("pycodestyle")`. With the installation of the default requirements.txt into a fresh enviroment, i.e. `pycodestyle` and not , the option's checkbox was disabled in the GUI, but if I enabled in manually in the preferences file, code style checking worked fine. Conversely, when I removed pycodestyle and installed pep8, the checkbox was enabled, but checking was not performed if it was checked. 

Therefore, either I'm missing something (quite possible), or the line should be checking for "pycodestyle" and not "pep8" to fix the issue. This problem doesn't happen by default in Spyder 3.2.x installed with full fat Anaconda as it includes both packages, but is likely to be an issue for those with miniconda, custom/conda-env github dev installs, or installed using pip that don't otherwise happen to have pep8 installed as code style checking will erroneously disable itself.

**What steps will reproduce the problem?**

1. Create a a fresh conda-env (or virtualenv)
2.  Install requirements from requirements.txt
3. Open spyder, go to preferences and try to enable code style analysis

**What is the expected output? What do you see instead?**

Checkbox is enabled, style checking works if pycodestyle installed; inverse if not.

Checkbox greyed out; style checking works if manually enabled. If pycodestyle uninstalled and pep8 installed, checkbox enabled but checking does not work.

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.2.5, 4.0 dev (master)
* Python Version: 3.6.3
* Qt Version: 5.6.2
* PyQt Version: 5.6
* Operating system: Win 8.1 Pro x64

## Dependencies

Default specified in `requirements.txt`, or otherwise as specified above.

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #5791 

-------------------------

Thanks to @CAM-Gerlach for pointing this out :+1:

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
I see `pep8` doesn't take too kindly to being replaced, haha...

Thanks for doing up the PR, @dalthviz . I wasn't sure if @ccordoba12 had direct push access to the repo and could thus just commit it directly, or if there was anything else silly I was missing, otherwise I wouldn't have wanted to waste your time actually doing the work for me...gotta make that big first PR sometime, and you can't start much smaller than this, heh.

**Comment by dalthviz** [comment]
No problem @CAM-Gerlach, if it fixes something it has value :+1: (even if it's something that only needs the change of a line). Also, normally we always do a PR, we never push directly to any branch (you could say this is kind of a standard practice for us). Furthermore, all the help you can give us is really appreciated! so if you want to do some fixes let us know :) . Basically just open a PR taking as base the branch where the problem is showing (`3.x` if is a bug present in `3.2.x` and `master`, or `master` for bugs only present there).

**Comment by CAM-Gerlach** [comment]
Thanks ^_^. I feel bad submitting all these long and detailed issues and not actually pitching in to help; I've never done GUI/Qt anything so there's a lot to figure out there, and I'm not even anywhere near being a Python whiz, coming from a heavy R background. However, I've been working at it and actually was putting the finishing touches on a PR for my own issue when #5771 beat me to it. However, despite my n00bness my solution was essentially line for line what was in the PR, so that was a pretty encouraging start. Looking at some Community:Easy things right now, maybe starting with #5770 , and we'll see where it goes...I have quite a few different research and final projects on my plate at the moment as a grad student. In the meantime, I'm trying to do my part triaging and responding to the many issues reported here, most non-Spyder related it seems or lacking the information necessary to act on them. Cheers!

**Comment by ccordoba12** [comment]
Thanks @CAM-Gerlach for your wanting to help us! As you said, it's a lot of work to respond to all the reported issues here.

**Comment by CAM-Gerlach** [comment]
Its the least I can do, @ccordoba12 ; the more regular folks like me can help deal with the perpetual daily grind of (mostly user-specific or non-Spyder) issues, writing/improving docs and (hopefully soon) simple PRs, the more time folks like you and @dalthviz have to build the really awesome stuff.

**Pull request merged**
