### PR TITLE
PR: Only show removal message in Python consoles

### LINKED ISSUE #4284: The message about the removal of the Python console is also shown on the Internal console
@dalthviz, please fix this one. The message must only appear on the Python console (of course).

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #4284

### CODE REVIEW

**Comment by dalthviz** [comment]
Preview:
imagen

**Comment by goanpeca** [comment]
@dalthviz since we plan to remove the python console, isnt it better to use the logic based on a keyword argument called, `internalconsole`, that way when we remove it we dont have to change that argument

**Comment by dalthviz** [comment]
@goanpeca you are right. Also thinking about this, the message in the ShellBaseWidget should be a parameter and not be wrote there, I going to take a different aproach passing the message by the keyword argument.

**Comment by goanpeca** [comment]
@dalthviz much much better, thanks for the update :-)

**Comment by ccordoba12** [comment]
@dalthviz, you didn't change the base of this PR, so it went against master and I now have to backport it to `3.1.x`.

Please be more careful for next time.

**Comment by dalthviz** [comment]
@ccordoba12 I'm really sorry, I will be more careful for sure.

**Comment by ccordoba12** [comment]
No worries, you've done it fine so far. Just be more careful ;-)

**Pull request merged**
