### PR TITLE
changed abcd..z to ascii_lowercase in baseshell.py

### PR DESCRIPTION
**Pull request by thewhitetulip**
A minor change from "abcd...z" to string.ascii_lowercase.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Sorry if I sound naive, but for what's useful this change?

**Comment by thewhitetulip** [comment]
ascii_lowercase is a string already defined in the string library, we need not have a string 'abc..z'. I believe it is called Magic numbers? I thought using a predefined variable would be better?

**Comment by ccordoba12** [comment]
Thanks for the explanation, but is this useful to solve a bug or a current shortcoming that you've detected when using Spyder?

If not, I'd be hesitant to touch something that it's working well already :-)

**Comment by thewhitetulip** [comment]
I agree that it doesn't solve a bug, but I know it won't cause any problems at all because instead of a user defined string, we are using a version defined by the `string` library! Jut the referencing of the variable will change nothing else :)

**Comment by Nodd** [comment]
It's a bit equivalent to replacing an error number by it's defined constant. It doesn't change program's behavior bug can make the program clearer to understand.
In this case however, I think that ```"abcdefghijklmnopqrstuvwxyz"``` is clearer than ```ascii_lowercase``` because I would have to check the documentation to be sure of what is this constant.
It would be a bit clearer to only ```import string``` and use ```string.ascii_lowercase```, but I'm with @ccordoba12 and think that the raw string is clearer.

Sorry @thewhitetulip, if I'm not mistaken it's your first try at a PR for spyder but I'm sure you can find something else to improve ! Maybe have a look at the ```Easy``` label: https://github.com/spyder-ide/spyder/issues?q=is%3Aopen+is%3Aissue+label%3AEasy

**Comment by thewhitetulip** [comment]
@Nodd Indeed it was my first PR, but won't be the last :)
I am working on #306 currently.

**Comment by Nodd** [comment]
Closing it then.

**Pull request closed without merging**
