### PR TITLE
PR: Fix negative deltas on profiler

### LINKED ISSUE #6032: When comparing a generated and loaded profile, any negative deltas show (actual_value - ?) 1h:60min, not actual value
Load data to compare when the loaded data is faster it shows 1h60min,espically the figure is so small,for example 5 ms compare to 3ms,it shows -1h:60min
default
**u can easily reproduce it by doing some quick things**

```python
import time
def delay(howlong):
    time.sleep(howlong)
delay(0.005)
print('delay finish')
```

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.9.3, PyQt5 5.9.2 on Windows

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.21.0 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.5 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.1 (OK)

```

### PR DESCRIPTION
**Pull request by csabella**
Fixes #6032

### CODE REVIEW

**Comment by csabella** [comment]
@ccordoba12   In the first commit, I fixed the issue without making many other changes.  However, I noticed that some of the code was no longer needed because the formatting was being handled differently, so in the second commit, I refactored to remove some of the unneeded code.  If you don't want those changes, I can remove the second commit.  Thanks!

**Comment by ccordoba12** [comment]
> If you don't want those changes, I can remove the second commit. Thanks!

Don't worry, ti's fine. But I'd like to see some tests for this feature, if it's not much too ask :-)

**Comment by csabella** [comment]
@ccordoba12   I've added some tests, but just for the methods that I modified.    I had trouble calling this routine since it was in `spyder_profiler` and not `spyder`.  I was able to run it (from within Spyder) to make sure the tests worked, but I didn't know how to get it to work from the command line.

Thanks!

I can also work on tests for the rest of the class, but I thought you might want to this in the new release, so I wanted to get it to you.

**Comment by ccordoba12** [comment]
@csabella, I pushed one commit here to include the `spyder_profiler` directory among our tests.

**Pull request merged**
