### PR TITLE
PR: Remove font groups from plugins and move to general preferences

### LINKED ISSUE #2438: Use a single font for all panes
image

Just like the image above, I want to change the font in the right side to some better fonts( now it is hard to read), how should I do that?

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #2438

----

# Description
AFAIK Spyder aimed to be in its origin a collection of loosely coupled plugins working together to make up for a coherent scientific and development environment. This decoupling is evident in the large (I would even say massive) amount of configuration options that a Plugin has.

We should strive to make the preferences dialog in Spyder more accessible by reducing redundant options.

PR #2861, was a step in that direction and this is the continuation.

# Screenshots
The fonts should be set now globally in the general preferences. 

### General / General (it can use a better name :-)  )
image

### General / Theme (Appearance?)
image

# Todo
- [x] Remove font groups preferences from other plugins (Console, IPython, Help, Editor, History)
- [x] Split general preferences in two tabs
- [x] Add fonts to general preferences
- [x] Update logic to update the plugins font on font update

### CODE REVIEW

**Comment by goanpeca** [comment]
Screenshots for the new organization of the general menu

# General / General (it can use a better name :-)  )
image

# General / Theme (Appearance?)
image

**Comment by goanpeca** [comment]
I guess @Nodd has something (or a lot) to say in this regard so please go for it

**Comment by goanpeca** [comment]
@ccordoba12 please take a look and let me know what you think

**Comment by goanpeca** [comment]
@ccordoba12 at the end I preferred removing all the unnecessary options from the .ini file and defaults in the `config/main.py`,

**Comment by goanpeca** [comment]
@Nodd (a.k.a M. Nitpick) we need your nitpicking! (Happy new year by the way)

**Comment by ccordoba12** [comment]
My suggestions:

1. The *Appearance* tab should be the first one from left to right.
2. The *General* tab should be renamed to *Advanced settings* (because most of the things there are, well, advanced).

**Comment by ccordoba12** [comment]
@goanpeca, do you mind to do my proposed changes, and a rebase, so I can merge this one?

**Pull request closed without merging**
