### PR TITLE
PR: Code sign

### PR DESCRIPTION
**Pull request by mrclary**
This is a duplicate of #16490, but triggered from the spyder/spyder-ide repo. This is intended to test the code signing, since github secrets are not passed to runners of PRs triggered from forked repos.

### CODE REVIEW

**Comment by mrclary** [comment]
Hypothesis confirmed. The keychain step successfully completes. For reference the successful log looks like this:
```
Run ./certkeychain.sh "${MACOS_CERTIFICATE}" "${MACOS_CERTIFICATE_PWD}"
  ./certkeychain.sh "${MACOS_CERTIFICATE}" "${MACOS_CERTIFICATE_PWD}"
  shell: /bin/bash -l {0}
  env:
    LITE_FLAG: 
    DMGNAME: Spyder.dmg
    DISTDIR: /Users/runner/work/spyder/spyder/dist
    MACOS_CERTIFICATE: ***
  
    MACOS_CERTIFICATE_PWD: ***
    APPLICATION_PWD: ***
2022-07-01 00:18:38 [INFO] [keychain] -> Decoding Certificate...
2022-07-01 00:18:38 [INFO] [keychain] -> Creating keychain...
2022-07-01 00:18:38 [INFO] [keychain] -> Importing certificate...
1 identity imported.
keychain: "/Users/runner/Library/Keychains/build.keychain-db"
version: 512
class: 0x00000010 
attributes:
    0x00000000 <uint32>=0x00000010 
    0x00000001 <blob>="Spyder-IDE certificate"
    0x00000002 <blob>=<NULL>
    0x00000003 <uint32>=0x00000001 
    0x00000004 <uint32>=0x00000000 
    0x00000005 <uint32>=0x00000000 
    0x00000006 <blob>=0xE8DE7F4FB809E4CD854A80EC7D3750EE64E86F7B  "\350\336\177O\270\011\344\315\205J\200\354}7P\356d\350o{"
    0x00000007 <blob>=<NULL>
    0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
    0x00000009 <uint32>=0x0000002A  "\000\000\000*"
    0x0000000A <uint32>=0x00000800 
    0x0000000B <uint32>=0x00000800 
    0x0000000C <blob>=0x0000000000000000 
    0x0000000D <blob>=0x0000000000000000 
    0x0000000E <uint32>=0x00000001 
    0x0000000F <uint32>=0x00000001 
    0x00000010 <uint32>=0x00000001 
    0x00000011 <uint32>=0x00000000 
    0x00000012 <uint32>=0x00000001 
    0x00000013 <uint32>=0x00000001 
    0x00000014 <uint32>=0x00000001 
    0x00000015 <uint32>=0x00000001 
    0x00000016 <uint32>=0x00000001 
    0x00000017 <uint32>=0x00000001 
    0x00000018 <uint32>=0x00000001 
    0x00000019 <uint32>=0x00000001 
    0x0000001A <uint32>=0x00000001 
2022-07-01 00:18:38 [INFO] [keychain] -> Verifying identity...
  1) AA5DF64B2C963B55686663B4362F4F986D5A298A "Developer ID Application: Ryan Clary (6D7ZTH6B38)"
     1 valid identities found
```
and the unsuccessful log looks like this:
```
Run ./certkeychain.sh "${MACOS_CERTIFICATE}" "${MACOS_CERTIFICATE_PWD}"
  ./certkeychain.sh "${MACOS_CERTIFICATE}" "${MACOS_CERTIFICATE_PWD}"
  shell: /bin/bash -l {0}
  env:
    LITE_FLAG: 
    DMGNAME: Spyder.dmg
    DISTDIR: /Users/runner/work/spyder/spyder/dist
    MACOS_CERTIFICATE: 
    MACOS_CERTIFICATE_PWD: 
    APPLICATION_PWD: 
2022-06-30 22:53:25 [INFO] [keychain] -> Decoding Certificate...
2022-06-30 22:53:25 [INFO] [keychain] -> Creating keychain...
2022-06-30 22:53:25 [INFO] [keychain] -> Importing certificate...
security: SecKeychainItemImport: One or more parameters passed to a function were not valid.
Error: Process completed with exit code 1.
```

Notice the difference between the secrets: successful run shows masked secrets while the failed one shows empty secrets.

**Comment by ccordoba12** [comment]
> Hypothesis confirmed. The keychain step successfully completes

Ok, so what do you propose to do?

**Comment by mrclary** [comment]
> > Hypothesis confirmed. The keychain step successfully completes
> 
> Ok, so what do you propose to do?

So, this means that PRs from forked repos (most I imagine) cannot run any code signing steps. I was going to condition these steps on release, which is triggered by the main repo, so that shouldn't be a problem.

I'll close this PR, and make the final changes to #16490 that condition on release. Then, that PR should pass all checks, but it won't have signed code. But we should have signed code on the next release 🤞 .

**Comment by ccordoba12** [comment]
> Then, that PR should pass all checks, but it won't have signed code. But we should have signed code on the next release

That's great to hear! We could also make one or more beta releases to test that signing the app works on releases. I think that would be better than just hoping for the best.

**Pull request closed without merging**
