### PR TITLE
PR: Refactor completion architecture to support multiple sources

### PR DESCRIPTION
**Pull request by andfoy**
## Description of Changes
This PR enables Spyder to have multiple completion/introspection sources by decoupling and extending the current LSP communication architecture by introducing a higher-level completion plugin that communicates not also with the LSP servers, but additionally with other sources, such as Fallback completions and eventually Kite.

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@andfoy

### CODE REVIEW

**Comment by ccordoba12** [comment]
Please rebase this PR on top of master to keep going.

**Comment by andfoy** [comment]
@ccordoba12 Travis tests are running on a old commit version of this PR, do you have any ideas about this?

**Comment by andfoy** [comment]
@ccordoba12 I'm having a strange ZMQ error on Windows using Python 3.7 on Azure, can I have some help with this one?

**Comment by andfoy** [comment]
@ccordoba12 I'm having some icon-related errors for the tests on this one

**Pull request merged**
