### PR TITLE
PR: Add a reviewed German translation

### PR DESCRIPTION
**Pull request by alexschw**
### Issue(s) Resolved

Related to #10672
Based on PR #10813

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
alexschw

### CODE REVIEW

**Comment by alexschw** [comment]
Okay, now the spyder.pot and german translation are up to date. I think this might be interesting for the other translators too. I'm done.

**Comment by goanpeca** [comment]
Merging @ccordoba12 ?

**Comment by ccordoba12** [comment]
> Merging @ccordoba12 ?

Not yet. There are some new strings we added in rc3 that need to be translated too.

@alexschw, I uploaded new translation files just now. So please merge this branch with master and fix the merge conflicts. For that you need to install first programs such as kdiff3 or meld, which will solve the conflicts automatically.

**Comment by ccordoba12** [comment]
Sorry, my last comment seems more complex than I thought. So I solved the conflicts for you.

To bring my commits to your clone, you need to do:

- `git checkout trans/de`
- `git pull`

**Comment by ccordoba12** [comment]
And after that you can translate the strings added in rc3.

**Pull request merged**
