### PR TITLE
PR: Copy/cut entire line if nothing is selected (Editor)

### LINKED ISSUE #8574: Feature Suggestion: Cut current line
This is a function I have been missing since a long time (since I first used it in other IDEs e.g VBStudio back in 2005).
Often I want to duplicate the current line elsewhere. Right now I have to select the line with my mouse and press CTRL+X to cut it.

Do you think it would be possible to add a keyboard-shortcut for cutting the current line in the editor/console?

Once again props for this very good yet simple IDE, I've been using very extensively!

### LINKED ISSUE #21264: Request: copy entire line with CTRL+C and no selection
Many code editors, such as Visual Studio Code, Sublime Text, any JetBrain IDE, etc, will copy an entire line of code if you press Ctrl+C with the cursor on a line but nothing selected. I find this very useful and use it all the time. It would be nice to have this in Spyder, perhaps as a settable preference in Preferences/Editor, not the least because it is in muscle memory and I keep trying to do it over and over!

### PR DESCRIPTION
**Pull request by The-Ludwig**
## Description of Changes
* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

[Video pasting and copying whole lines](https://github.com/user-attachments/assets/0ee2934d-eb40-44d4-b2fd-7b573479ba8b)

This addition allows to copy and cut a whole line in the editor, with `Ctr+C` and `Ctr+X` as suggested in #21264.
This is similar to the behavior e.g. VSCode has.

### Why `select_current_line_and_sep` is needed.
The most basic implementation is very straightforward (look after my first two commitss e08c0760d7782ea and fdfd925e82fbaf99c). This PR is a bit longer, since we usually want to include the lineseperator from the current line, not the lineseperator from the previous line when copying/cutting whole lines. The exception there is if there is only one line or we are at the last line of the document.

### Differences to standard editors like VSCode
This feature is already quite usable and improves my personal workflow greatly. To get exactly the same behavior as VSCode, [`CodeEditor.Paste`](https://github.com/spyder-ide/spyder/blob/a89ee75aa5a56da624a97e05cb0bb7c8ff776dd9/spyder/plugins/editor/widgets/codeeditor/codeeditor.py#L1827) needs to be modified. VSCode remembers if the clipboard was filled by not having anything selected and then selecting the whole line, and then on pasting inserts the line above the current line and adds the lineseperator at the end correctly. 
I do not know what best-practise to save a state in this codebase is and the implementation of `CodeEditor.Paste` is a bit above my head right now. I need more experienced spyder developers to look at this in an upcoming PR.

### Issue(s) Resolved

Fixes #21264
Fixes #8574

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
Ludwig Neste

### CODE REVIEW

**Comment by The-Ludwig** [comment]
I do not understand why the fast linux tests pass, while the slow one don't. Any idea?

**Comment by ccordoba12** [comment]
Hey @The-Ludwig, thanks a lot for your contribution! And sorry for the late reply, we were quite busy fixing several bugs that surfaced after releasing 6.0.0.

@dalthviz, could you review this one give @The-Ludwig a hand with our tests? Thanks!

**Comment by dalthviz** [comment]
So, I gave the CI failure a check and seems like the failing test was being forced to pass by setting text in the clipboard directly. The test fails since the changes here cause that calling `copy` without a selection actually copy things. Created #22618 to fix the failing test. When that gets merged, this PR can be updated with latest `master` and hopefully all tests should pass

**Comment by ccordoba12** [comment]
@The-Ludwig, please merge with master to get the fix done by @dalthviz in PR #22618.

**Comment by The-Ludwig** [comment]
> @The-Ludwig, please merge with master to get the fix done by @dalthviz in PR #22618.

Did so! :)

**Comment by The-Ludwig** [comment]
@dalthviz @ccordoba12 is this mergeable?

**Comment by ccordoba12** [comment]
@dalthviz, please give @The-Ludwig's work a look to see if we can merge it.

**Review by dalthviz — APPROVED** [review]
Thank you @The-Ludwig for all your work here and sorry for the late review! Gave a check locally to this and I would say it works nicely :+1:

The only nitpick I have is to add in the new `select_current_line_and_sep` method docstring a description of its params (`cursor` and `set_cursor`). Other than that, and since the docstring is quite descriptive as it is, this LGTM so leaving approved :+1:

If you think is ready from your side, feel free to merge this @ccordoba12

**Comment by ccordoba12** [comment]
> If you think is ready from your side, feel free to merge this @ccordoba12

I'm ok with it, so let's merge it! Thanks @The-Ludwig for this great contribution!!

**Comment by The-Ludwig** [comment]
Thanks for merging this and also for the support during development!

**Comment by hprodh** [comment]
During some heavy-lifting copy-pasting operations, Ctrl+C is very close to Ctrl+V, so the buffer is easily dropped by accidentally pressing Ctrl+C with this feature.
One workaround would be to provide a checkbox in the settings to disable this feature. But what I can report from my usage is that this "accidental" Ctrl+C usually happens when the cursor is on an empty line. 
So basically, a second "in-between" workaround would be to disable this feature when the cursor is on an empty/blank line, this would not require an additional option in the settings menu.

**Pull request merged**
