### PR TITLE
Multiple rst tutorial menu

### PR DESCRIPTION
**Pull request by EnricoGiampieri**
With this pull request the help menu get a nuw submenu, just below the spyder introduction, that contains link to other tutorial, that are indexed by the name of the rst tutorial file.

This pull request is connected to [SEP2: Interactive Tutorial Content](https://github.com/spyder-ide/spyder/wiki/SEP-2:-Interactive-Tutorial-Content).

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for your contribution. I want to say two things:

1. Could you post a screenshot of what you've achieved so far?

2. I think @goanpeca had a different idea for the SEP you're referencing. What do you say @goanpeca?

**Comment by EnricoGiampieri** [comment]
I'm sorry for the confusion.
I restored the old SEP, created a new one (number 6) and modified the commit accordingly (renaming the function call to the old *show_tutorial*)

**Comment by EnricoGiampieri** [comment]
This is a preview of the resulting menu and reproduction of the bare tutorial in rst

spyder_results_1

**Comment by ccordoba12** [comment]
I have other idea to tackle this: I'd like to add a home page to the Object Inspector with links to several resources, instead of adding them to the Help menu.

What do you think @EnricoGiampieri?

**Comment by goanpeca** [comment]
@ccordoba12 that sounds great:-), but then we would need to add a `Home` button to the object inspector to go there right?

**Comment by EnricoGiampieri** [comment]
It sounds like a very good idea to me, @ccordoba12. Another great improvement would be a search function for classes and syntax. I teach python classes and an inline help is one of the most requested things that I encounter.

**Comment by ccordoba12** [comment]
@goanpeca, yes, the code is already there (look at the *Online help* plugin). We just need to use it for the Object Inspector.

Obviously, if we do that, we should also add tabs to the Object Inspector, so people can read several things at the same time. I've been thinking to do that for a long time but haven't found time to make it a reality :-) Maybe for 2.4...

@EnricoGiampieri, adding search functionality is also planned. It's just tricky to do it right but there is a very good Python library on which we can rely, called *Whoosh*

**Comment by ccordoba12** [comment]
Since we all agree that creating a home page for the Object Inspector is the better option here, I'd like to know if it's ok for @EnricoGiampieri to close this PR.

@EnricoGiampieri, what do you think?

**Comment by EnricoGiampieri** [comment]
I will gladly close it. There is any way I can help with the new design?

**Comment by Nodd** [comment]
I'm all for improving the object inspector and adding a Home page, but for tutorials the Help menu seems mode discoverable ?
To limit the length of the menu all the tutorials could go in the same submenu. Having tutorials is great but they're not used that often.

**Comment by Nodd** [comment]
Since everyone agree, I'm closing it.

**Pull request closed without merging**
