### PR TITLE
Add "close all but this" and "close all to the right" entries to the Editor context menu

### LINKED ISSUE #2354: Context menu for tabs in editor should allow "close all but this" and "close all to the right"
Similar to Chrome and Sublime Text, this is very useful after working on many files at the same time and needing to clean house!

### PR DESCRIPTION
**Pull request by igordsm**
Fixes #2354

screenshot from 2015-07-05 16 40 07

---

The menu items were added before the "new window" action.

### CODE REVIEW

**Comment by goanpeca** [comment]
@igordsm thanks for working on this :).

Can you please post a screenshot of how the menu looks?

Cheers

**Comment by petebachant** [comment]
Nice! 

However, I just ran @igordsm's version via `bootstrap.py` and these menu items did not work as expected. "Close all to the right" works more like "Close all to the left". Both "Close all to the right" and "Close all but this" do not keep the clicked tab, but instead keep the one that was in focus. 

Could a test be written to mimic this error?

**Comment by igordsm** [comment]
Hey @petebachant , I just notice the left/right thing and will update the PR in a few moments.

About the behaviour of clicked vs selected tab, the same happens with the "Go to line" option. Is this expected?

**Comment by igordsm** [comment]
screenshot from 2015-07-05 16 40 07

**Comment by goanpeca** [comment]
Hmmm funny, I think the correct behavior should be to affect the right clicked tab... so maybe we need to file a bug for the gotoline @ccordoba12?

**Comment by igordsm** [comment]
As far as I understand, both the code that I made and the code in gotoline depend on the currently selected tab. Maybe the solution could be activate the tab when using the right click?

**Comment by ccordoba12** [comment]
@igordsm, this needs a rebase or a merge with master.

**Comment by igordsm** [comment]
@ccordoba12 I just merged with master and added a commit to activate tabs on right click. This way both gotoline and the new commands will affect the clicked tab.

**Comment by ccordoba12** [comment]
Please merge again with `master`. We had some problems with our testing machinery on Windows, but I think that's fixed now :-)

**Comment by igordsm** [comment]
@ccordoba12 Remerged and both checks passed.

**Comment by igordsm** [comment]
Can someone merge or look at this again, please?

**Comment by goanpeca** [comment]
@igordsm 

What happenned with 
>As far as I understand, both the code that I made and the code in gotoline depend on the currently selected tab. Maybe the solution could be activate the tab when using the right click?

Also, why not make `Close all to the left`?, just curious,...

**Comment by igordsm** [comment]
@goanpeca The tabs are activated on right-click, so now "go to line" and the new options affect the clicked tab. 
For some reason I never found a "close all left" option in other programs...

**Comment by goanpeca** [comment]
@igordsm I see that you are making a PR from your master into spyder master.

We normally work using branches. Did you take a look at [these instructions](https://github.com/spyder-ide/spyder/wiki/Dev%3A-Github-Workflow)?

**Comment by goanpeca** [comment]
@igordsm ?

**Comment by goanpeca** [comment]
@ccordoba12 , @Nodd @igordsm ?

**Comment by ccordoba12** [comment]
Looks good to me.

**Pull request merged**
