### PR TITLE
PR: Update Japanese translation for 4.0.0

### PR DESCRIPTION
**Pull request by sohnishi**
## Description of Changes
Update of Japanese translation for 4.0.0

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Seiki Ohnishi @sohnishi

### CODE REVIEW

**Comment by ccordoba12** [comment]
@sohnishi, thanks a lot for your help with this! There are some new strings we added in rc3 that need to be translated too.

I uploaded new translation files just now. So please merge this branch with master and fix the merge conflicts. For that you need to install first programs such as kdiff3 or meld, which will solve the conflicts automatically.

**Comment by ccordoba12** [comment]
Sorry, my last comment seems more complex than I thought. So I solved the conflicts for you.

To bring my commit to your clone, you need to do:

- `git checkout jp_branch`
- `git pull`

And after that you can translate the strings added in rc3.

**Comment by ccordoba12** [comment]
> Hopefully you can update the missing strings this weekend (we plan to release Spyder 4 next Tuesday).

For this you need to create a new PR directly from our latest HEAD in master.

**Comment by sohnishi** [comment]
@ccordoba12  
I'm sorry for my absence. I took winter vacation.
I can update the translation for rc3 now.
Please tell me which method should I use, conventional git or web base crowdin.

**Comment by ccordoba12** [comment]
No worries and thanks for your help! Please use Crowdin from now on.

**Pull request merged**
