### PR TITLE
PR: Update QtAwesome version constraint to `>=1.3.1,<1.4.0`

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

Update QtAwesome version constraint to `>=1.3.1,<1.4.0` and get fix for font issue installation error on Windows

### Issue(s) Resolved

Part of #21936

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, it seems you need to include the `boltons` package in `installers-conda/build-environment.yml` to fix the error when building our Linux installer.

It seems that's a `boa` dependency but it's weird it's not pulled by it.

**Comment by dalthviz** [comment]
Note: The missing `boltons` error seems related with this commit message mentioning that for `conda` 23.4+ `boltons` will not be part of the vendored packages (https://github.com/mamba-org/boa/commit/776609b38ccf5e8fd1cd39ae38d011136cc367fc). Also, seems like there is already an issue related with the missing update of the package recipe in conda-forge (https://github.com/conda-forge/boa-feedstock/issues/81). Seems like boa version 1.7.0 from conda-forge doesn't have the updated dependency on `boltons`

**Comment by ccordoba12** [comment]
> Note: The missing `boltons` error seems related with this commit message mentioning that for `conda` 23.4+ `boltons` will not be part of the vendored packages ([mamba-org/boa@776609b](https://github.com/mamba-org/boa/commit/776609b38ccf5e8fd1cd39ae38d011136cc367fc)). Also, seems like there is already an issue related with the missing update of the package recipe in conda-forge ([conda-forge/boa-feedstock#81](https://github.com/conda-forge/boa-feedstock/issues/81)). Seems like boa version 0.17.0 from conda-forge doesn't have the updated dependency on `boltons`

I saw that too and send them conda-forge/boa-feedstock#82 to fix that.

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz!

**Pull request merged**
