### PR TITLE
PR: More UI fixes in several places

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

- Make width and height of the FindReplace and FinderWidget the same, so the layout doesn't break when switching between plugins.

    **Before**

    no-matching-find-widget-sizes

    **After**

    matching-find-widget-sizes

- Make match the width of the "Exclude" and "Search in" comboboxes present in Find

    **Before**

    find-comboboxes-in-master

    **After**

    find-comboboxes-match

- Fix size of tabs in History

    **Before**

    imagen

    **After**

    imagen

- Fix style of widget used to change the IPython console tab names

    **Before**

    imagen

    **After**

    imagen

- Add clear button to FinderWidget

    imagen

- Create our own close button for tabs, so that we can position it where it really needs to be and make it follow the style of other buttons. This also helped to fix the height of tabs on Windows and Mac.

    **Before**

    old-close-button-for-tabs

    **After**

    new-close-button-for-tabs

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by jitseniesen** [comment]
> * Make match the width of the "Exclude" and "Search in" comboboxes present in Find

Would it be an idea to also match up the left side of these comboboxes?

**Comment by ccordoba12** [comment]
> Would it be an idea to also match up the left side of these comboboxes?

Good point @jitseniesen! I fixed that in one of my last commits and updated the OP with the new UI.

**Comment by dalthviz** [comment]
On Windows you can see something like:

find_widget

On macOS you can see something like:

find_widget_macos

**Comment by dalthviz** [comment]
Just in case, another update running with the latest commit:

* On Windows:

find_replace

* On macOS:

find_replace_macos

**Comment by ccordoba12** [comment]
@dalthviz, this should be ready for another review. I tested these changes in all OSes and made the necessary adjustments so that things look good in all of them (I'll fix the issues you found with the Editor on Windows once it's migrated to the new API).

In addition, I created a new close button for our tabs (see the updated OP), so that we can position and style it correctly.

**Review by dalthviz — APPROVED** [review]
Thanks @ccordoba12 ! Checked locally on Windows and seems like things are working so this LGTM :+1:

Just in case,  do you have any other comment regarding the changes here @jitseniesen ?

**Comment by jitseniesen** [comment]
> Just in case, do you have any other comment regarding the changes here @jitseniesen ?

No

**Comment by ccordoba12** [comment]
Thanks @jitseniesen!

I'll merge after fixing #21322 to be sure tests are really passing.

**Pull request merged**
