### PR TITLE
PR : Add Cython files import and run support

### PR DESCRIPTION
**Pull request by JGoutin**
This PR improve Cython support by adding ".pyx" importing and running abilities to consoles.
- Automatically compile ".pyx" files when importing them with `import` (Enable `pyximport` with file reload option and NumPy support).
- Allow to run ".pyx" file with the "Run" button and the `runfile ` function (Using `cython_inline` function).
- Automatically enable IPython Cython magic.

### CODE REVIEW

**Comment by ccordoba12** [comment]
This is a really great addition, thanks a lot for it!! I think the only thing missing is a test for this.

For that, please take a look at `test_run_code` in `spyder/app/tests/test_mainwindow.py` to see how to create one for Cython. You also need to add `cython` as a conda dependency in `circle.yml`.

**Comment by ccordoba12** [comment]
And your test should go to `spyder/app/tests/test_mainwindow.py` too.

**Comment by JGoutin** [comment]
`ImportError: No module named 'pyx_lib'`
Is there a way to add this path to `sys.path` on active IPython console ?

**Comment by ccordoba12** [comment]
I'll help you to fix your test in a couple of days.

**Comment by JGoutin** [comment]
Thanks !

**Comment by ccordoba12** [comment]
@JGoutin, I changed your code to run Cython code using the Cython magic instead of `cython_inline` (in `sitecustomize.py`).

This allows to run any Cython file (with `cython_inline` you can't run a file that starts with `cdef` or `cpdef`) and also get its results injected in the console namespace (which is why your tests were failing before, because `cython_inline` doesn't do that).

However, this approach doesn't take into account the variables defined in the current namespace. But I think that's a minor price to pay for having things to work in a more intuitive way.

Please let me know what you think :-)

**Comment by JGoutin** [comment]
Yes, `cython_inline` seem to have some limitations. Using the magic is better, I agree.

A solution may be to run the compiled Cyhon file in the console (generated with `pyximport.pyxbuild.pyx_to_dll`). Actually, I don't find a way to run the file, but I am still searching.

**Comment by ccordoba12** [comment]
Tests are passing (ignore Travis, it's down now), so this is ready from my point of view.

@JGoutin?

**Comment by goanpeca** [comment]
@ccordoba12 maybe we can create a `spyder-extras`? or somethin metapackage to include all the optional things?

**Comment by ccordoba12** [comment]
> or something conda metapackage to include all the optional things?

Yeah, it could be nice to have it for `conda`, but I wouldn't want to change things for `pip` ;-)

**Comment by JGoutin** [comment]
It's OK for me. If I found an improvement, I'll create a new PR.

And thanks for fixing tests !

**Comment by ccordoba12** [comment]
> It's OK for me. If I found an improvement, I'll create a new PR.

Please make new PRs against the `3.x` branch. That's because we're going to release your work in Spyder 3.2 (`master` is for Spyder 4.0)

**Comment by goanpeca** [comment]
@JGoutin thanks for this contribution :-). Would you be interested in writing/cowriting a small blog post to showcase this feature?

**Comment by JGoutin** [comment]
@goanpeca Sorry, I am not interested by writing something. 😄

**Pull request merged**
