### PR TITLE
Update Matlab data parser

### PR DESCRIPTION
**Pull request by blink1073**
Uses the new streamlined parser from https://github.com/blink1073/oct2py/pull/108, and adds a simple test.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@blink1073, my man, glad to see you around these lands!! :-)

The failures in Travis and Appveyor are caused by a new conda version. I'll fix them tomorrow (by pinning conda to `4.2.x`) so you can do a rebase here ;-)

**Comment by ccordoba12** [comment]
I fixed out errors in Appveyor and Travis. Please rebase and make this PR against the 3.x branch so we can merge your work in Spyder 3 :-)

**Comment by blink1073** [comment]
Do you want both PRs open?  I opened https://github.com/spyder-ide/spyder/pull/3964 against 3.x.

**Comment by ccordoba12** [comment]
Nop, I'll close this one. Thanks for opening the other one.

**Pull request closed without merging**
