### PR TITLE
PR: Add delay to dot completion logic

### LINKED ISSUE #10634: 'Show completions on the fly' cannot be turned off
## Problem Description

Completions on the fly kicks in even when the option is unchecked.

bug_auto_completion

### What steps reproduce the problem?

1. Uncheck the option `Show completions on the fly`
2. Type some code that includes a '.'
3. Wait for completions to kicks in.

The problem seems to come from the code here :

https://github.com/spyder-ide/spyder/blob/90df471cff7d2713d20ebce900d27ede7b11e6f5/spyder/plugins/editor/widgets/codeeditor.py#L3602-L3610

It results in a call to `self.do_completion` directly even when the option `Show completions on the fly` is unchecked. Adding `and self.automatic_completions` to the condition `elif text in self.auto_completion_characters:` seems to fix the problem.

## Versions

* Spyder 4.0.0.dev0 (Commit: 3fd0553b4) 
* Python 3.7.3 64-bit | Qt 5.9.6 | PyQt5 5.9.2 | Windows 10

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)

### Issue(s) Resolved

Fixes #10634

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
@jnsebgosselin could you test this?

@ccordoba12 if '.' completion now is treated as a on the fly completion. Should `(` for calltip display be treated as that as well?

**Comment by ccordoba12** [comment]
> Should ( for calltip display be treated as that as well?

What do you mean?

**Comment by goanpeca** [comment]
```python

import numpy as np

np.array(*   # * is the cursor
```

After typing the `(` a calltip hint will appear. Is this considered on the fly completion as well?

**Comment by ccordoba12** [comment]
> Is this considered on the fly completion as well?

No, because it doesn't correspond to completing certain text in the editor. So I think you shouldn't consider that case in this PR.

**Comment by goanpeca** [comment]
>No, because it doesn't correspond to completing certain text in the editor. So I think you shouldn't consider that case in this PR.

In that case, is the `.` dot (the subject of this pr) considered as text for completion on the fly?

**Comment by ccordoba12** [comment]
> In that case, is the . dot (the subject of this pr) considered as text for completion on the fly?

Well, since the dot calls our completion widget, I'd say it breaks users expectations about the options they have set for that.

**Pull request merged**
