### PR TITLE
PR: Update Jedi requirement to 0.15.2

### LINKED ISSUE #11150: Unable to load docstring into "Help" pane for functions with certain decorators
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. Install this library, `typeguard` (https://github.com/agronholm/typeguard) by `pip install typeguard`
2. Use the following script:
```python
from typeguard import typechecked

@typechecked
def func(a: int):
    """
    Parameters
    ----------

    a : int
        Something.
    """
    print('someting')

b = func(3)
```
3. Move your cursor to `func` in the last line of the script, and press `Ctrl + I` ("inspect current object"). 

### What is the expected output? What do you see instead?

The docstring cannot be loaded into the "Help" pane.

However, if you comment out the line `@typechecked`, and then press `Ctrl + I` (with the cursor on `func`), you will be able to see the docstring correctly loaded.

## Versions

* Spyder version: 4.0.0
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.3
* Operating System name/version: Windows 10 and Ubuntu 18.04

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
nbconvert >=4.0              :  5.6.1 (OK)
sphinx >=0.6.6               :  2.2.1 (OK)
pylint >=0.25                :  2.4.4 (OK)
psutil >=0.3                 :  5.6.5 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  1.4 (OK)
cython >=0.21                :  0.29.14 (OK)
IPython >=4.0                :  7.9.0 (OK)
matplotlib >=2.0.0           :  3.0.3 (OK)
pandas >=0.13.1              :  0.25.3 (OK)
numpy >=1.7                  :  1.17.3 (OK)
scipy >=0.17.0               :  1.3.1 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.2 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

### PR DESCRIPTION
**Pull request by ccordoba12**
That version works correctly with Parso 0.5.2, so there should be no harm in updating to it.

Fixes #11150.

### CODE REVIEW

**Comment by EBenkler** [comment]
When I install spyder 4.1.1 using conda, I get a dependencies error related to jedi after spyder startup, because conda solved the dependencies such that jedi=0.14.1. When I try to force jedi=0.15.1 I get:

> conda install jedi=0.15.2
> 
> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: done
> 
>  Package Plan 
> 
>   environment location: C:\Miniconda3\envs\default
> 
>   added / updated specs:
>     - jedi=0.15.2
> 
> 
> The following packages will be downloaded:
> 
>     package                    |            build
>     ---------------------------|-----------------
>     jedi-0.15.2                |           py37_0         738 KB
>     spyder-3.3.6               |           py37_0         2.3 MB
>     spyder-kernels-0.5.2       |           py37_0          71 KB
>     ------------------------------------------------------------
>                                            Total:         3.1 MB
> 
> The following packages will be UPDATED:
> 
>   ca-certificates    conda-forge::ca-certificates-2019.11.~ --> pkgs/main::ca-certificates-2020.1.1-0
>   jedi                      conda-forge::jedi-0.14.1-py37_0 --> pkgs/main::jedi-0.15.2-py37_0
> 
> The following packages will be SUPERSEDED by a higher-priority channel:
> 
>   certifi            conda-forge::certifi-2019.11.28-py37h~ --> pkgs/main::certifi-2019.11.28-py37_0
>   openssl            conda-forge::openssl-1.1.1e-hfa6e2cd_0 --> pkgs/main::openssl-1.1.1e-he774522_0
>   spyder             conda-forge::spyder-4.1.1-py37hc8dfbb~ --> pkgs/main::spyder-3.3.6-py37_0
>   spyder-kernels     conda-forge::spyder-kernels-1.9.0-py3~ --> pkgs/main::spyder-kernels-0.5.2-py37_0
> 
> 
> Proceed ([y]/n)?

Maybe I am wrong (newbie), but this looks to me as if there is dependency conflict indirectly caused by spyder 4.1.1?

**Comment by ccordoba12** [comment]
> When I install spyder 4.1.1 using conda

This version is still not available in Anaconda, so I don't understand what you mean by this.

**Comment by EBenkler** [comment]
But spyder was updated to 4.1.1 today when I did conda update spyder:

> conda list spyder
>  packages in environment at C:\Miniconda3\envs\default:
> 
>  Name                    Version                   Build  Channel
> spyder                    4.1.1            py37hc8dfbb8_0    conda-forge
> spyder-kernels            1.9.0            py37hc8dfbb8_0    conda-forge

**Comment by ccordoba12** [comment]
I see, you're using conda-forge. Then your error is a duplicate of #11879. New packages with a fix are being generated right now.

**Comment by PrinceFPF** [comment]
@ccordoba12 Hello, I encountered the same problem, and I want to know how can I solve this problem?
spyder update ide  start error info

**Pull request merged**
