### PR TITLE
PR: Print std stream messages in the console while starting

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by impact27** [comment]
The tests don't pass because something is writing: 'Update LANGUAGE_CODES (inside config/base.py) if a new translation has been added to Spyder'

**Comment by ccordoba12** [comment]
> The tests don't pass because something is writing: 'Update LANGUAGE_CODES (inside config/base.py) if a new translation has been added to Spyder'

Please add the necessary code to ignore that message.

**Comment by ccordoba12** [comment]
@impact27, please remove your last two commits, do a `git commit --amend` to generate a new commit for your merge and force push.

Remember that our Mac app tests now fail if you don't set the right base for your branch. So you don't need to do anything to fix them, just change your base to `5.x` (which I already did).

**Review by ccordoba12 — APPROVED** [review]
Thanks @impact27 for your help with this!

**Pull request merged**
