### PR TITLE
PR: Fix updated Spyder logos

### PR DESCRIPTION
**Pull request by isabela-pf**
## Description of Changes

Removes the upper left web in the corner of the last round of logos per request.

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes the last comment in #15829.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
isabela-pf

### CODE REVIEW

**Comment by isabela-pf** [comment]
Here's how it looks in binder:

Screen Shot 2021-07-12 at 1 56 35 PM
Screen Shot 2021-07-12 at 1 56 57 PM
Screen Shot 2021-07-12 at 1 57 23 PM
Screen Shot 2021-07-12 at 1 57 35 PM
Screen Shot 2021-07-12 at 1 59 00 PM
Screen Shot 2021-07-12 at 1 59 13 PM

**Comment by isabela-pf** [comment]
- [ ] Add a background to `spyder-readme-banner.png`
- [ ] Move `spyder-readme-banner.png` to branding directory since it does not influence the application. This file will be deleted in this PR and added to the new path in #15980.

**Review by steff456 — APPROVED** [review]
The latest commit works as expected for Mac Qt 5.9 and Qt 5.12. Thanks for this work @isabela-pf!

**Pull request merged**
