### PR TITLE
PR: Fix KeyError issue with format in update worker

### LINKED ISSUE #21546: Error 403 (rate limit at github.com) is not handled when cheking for updates.
### What steps will reproduce the problem?

See Traceback. 
Error 403 (rate limit at github.com) is not handled well when cheking for updates.

### Traceback
```python-traceback
Traceback (most recent call last):
  File "C:\Users\thlu\AppData\Local\Programs\Spyder\pkgs\spyder\workers\updates.py", line 130, in start
    page.raise_for_status()
  File "C:\Users\thlu\AppData\Local\Programs\Spyder\pkgs\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: rate limit exceeded for url: https://api.github.com/repos/spyder-ide/spyder/releases

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\thlu\AppData\Local\Programs\Spyder\pkgs\spyder\workers\updates.py", line 157, in start
    error_msg = HTTP_ERROR_MSG.format(page.status_code)
KeyError: 'status_code'
```

## Versions

* Spyder version: 5.5.0  (standalone)
* Python version: 3.8.10 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.10
* Operating System: Windows-10-10.0.19045-SP0

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.2.0 (OK)
cloudpickle >=0.5.0           :  3.0.0 (OK)
cookiecutter >=1.6.0          :  2.4.0 (OK)
diff_match_patch >=20181111   :  20230430 (OK)
intervaltree                  :  None (OK)
IPython >=8.12.2,<8.13.0      :  8.12.3 (OK)
jedi >=0.17.2,<0.20.0         :  0.19.1 (OK)
jellyfish >=0.7               :  1.0.1 (OK)
jsonschema >=3.2.0            :  4.19.2 (OK)
keyring >=17.0.0              :  24.2.0 (OK)
nbconvert >=4.0               :  7.11.0 (OK)
numpydoc >=0.6.0              :  1.6.0 (OK)
paramiko >=2.4.0              :  3.3.1 (OK)
parso >=0.7.0,<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.6 (OK)
pygments >=2.0                :  2.16.1 (OK)
pylint >=2.5.0,<3.1           :  3.0.2 (OK)
pylint_venv >=3.0.2           :  3.0.3 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.9.0,<1.10.0         :  1.9.0 (OK)
pylsp_black >=1.2.0,<3.0.0    :  1.3.0 (OK)
qdarkstyle >=3.2.0,<3.3.0     :  3.2 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.3 (OK)
qtconsole >=5.5.0,<5.6.0      :  5.5.0 (OK)
qtpy >=2.1.0                  :  2.4.1 (OK)
rtree >=0.9.7                 :  1.1.0 (OK)
setuptools >=49.6.0           :  68.2.2 (OK)
sphinx >=0.6.6                :  7.1.2 (OK)
spyder_kernels >=2.5.0,<2.6.0 :  2.5.0 (OK)
textdistance >=4.2.0          :  4.6.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  3.0.0 (OK)
zmq >=22.1.0                  :  25.1.1 (OK)

# Optional:
cython >=0.21                 :  3.0.5 (OK)
matplotlib >=3.0.0            :  3.7.3 (OK)
numpy >=1.7                   :  1.24.4 (OK)
pandas >=1.1.1                :  2.0.3 (OK)
scipy >=0.17.0                :  1.10.1 (OK)
sympy >=0.7.3                 :  1.12 (OK)
```

### PR DESCRIPTION
**Pull request by mrclary**
Added keyword argument to string format method in order to resolve `KeyError`.

### Issue(s) Resolved

Fixes #21546

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for your prompt help @mrclary! Could you describe how this helps to solve issue #21546?

Also, to fix our tests please apply the changes in PR #21517, specifically those related to QDarkstyle.

**Comment by mrclary** [comment]
> Also, to fix our tests please apply the changes in PR #21517, specifically those related to QDarkstyle.

🤔 The test environment was already using QDarkstyle 3.2.1; nevertheless, I applied the changes in #21517. However, the tests are still failing.

**Comment by ccordoba12** [comment]
> However, the tests are still failing.

It seems a test for the `%edit` magic started to fail. I don't know why, but I'll take a look at it.

For the conda-based Linux installer, please check what's happening. From the logs, it seems `mamba` is no longer available in the build env.

**Comment by ccordoba12** [comment]
@mrclary, I fixed both the failing test and building our Linux installer (which was not so hard) on PR #21553.

So, please drop your last commit here and rebase on top of `5.x` to get those fixes.

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary!

**Pull request merged**
