### PR TITLE
Remove light mode

### LINKED ISSUE #2619: Spyder fails to start on light mode because of check_updates code
when launching spyder_light on Python3.4/PyQt5.5.0/Jupyter4/spyder-3.0.0dev, i get this strange error:

````
Traceback (most recent call last):
  File "python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 3103, in main
    mainwindow = run_spyder(app, options, args)
  File "python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 2999, in run_spyder
    main.post_visible_setup()
  File "python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 1308, in post_visible_setup
    self.check_updates()
  File "python-3.4.3.amd64\lib\site-packages\spyderlib\spyder.py", line 2900, in check_updates
    self.check_updates_action.setDisabled(True)
AttributeError: 'NoneType' object has no attribute 'setDisabled'
````

on a side-note, I would be happy if the check_update was disabled per default

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #2619

----

This is my decision as the current maintainer, so please don't complain about it.

Reasons for my decision (in decreasing order of importance):

* By removing Light Mode (LM) we have one less moving piece to worry about. Given Spyder's great complexity, I feel very good about it :-)
* LM is barely tested by our users
* LM makes `MainWindow` code much more complicated than it should be.
* Anaconda doesn't create a LM menu entry on Windows, so few users know about it.

### CODE REVIEW

**Comment by ccordoba12** [comment]
One more reason I forgot to mention: people is using `qtconsole` as the equivalent of light mode.

**Comment by stonebig** [comment]
ok

**Comment by Nodd** [comment]
I never used it anyway. Spyder's power is in all the tools it contains !

**Comment by ccordoba12** [comment]
Agreed, thanks for understanding! :-)

**Pull request merged**
