### PR TITLE
PR: Fix deprecated top-level `developer_name` in AppData XML (Linux)

### PR DESCRIPTION
**Pull request by musicinmybrain**
Use the name element in a developer block instead, as recommended by appstreamcli 1.0.0.

## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions) **N/A**
* [ ] Added unit test(s) covering the changes (if testable) **N/A**

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/)) **N/A**

Use the `name` element in a `developer` block instead, as recommended by `appstreamcli` 1.0.0.

This fixes all warnings when validating the AppData XML file, although there are still informational messages:

```
I: org.spyder_ide.spyder:32: developer-id-missing
   The `developer` element is missing an `id` property, containing a unique string ID for the
   developer. Consider adding a unique ID.

I: org.spyder_ide.spyder:~: content-rating-missing
   This component has no `content_rating` tag to provide age rating information. You can generate
   the tag data online by answering a few questions at https://hughsie.github.io/oars/

✔ Validation was successful: infos: 2, pedantic: 2
```

### Issue(s) Resolved

**N/A**

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: `musicinmybrain`

### CODE REVIEW

**Comment by musicinmybrain** [comment]
Let me clarify that `appstream` 1.0.0 has not yet been released, and my `appstream` is a pre-release as [currently packaged](https://src.fedoraproject.org/rpms/appstream/blob/51384dca2599ac6ff1895beb927ceb6e28018adc/f/appstream.spec) in Fedora Linux Rawhide (the development version of the OS), corresponding to https://github.com/ximion/appstream/commit/d88ed03cb5b3b1803bdee3528c9b99d528ceb065. See also https://github.com/ximion/appstream/issues/244.

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification @musicinmybrain. When do the `appstream` maintainers plan to release 1.0?

**Comment by musicinmybrain** [comment]
> Ok, thanks for the clarification @musicinmybrain. When do the `appstream` maintainers plan to release 1.0?

The day after my comment, apparently! https://github.com/ximion/appstream/releases/tag/v1.0.0

**Comment by ccordoba12** [comment]
> The day after my comment, apparently!

Haha, ok. Let's merge this one then.

We don't have time to address the remaining warnings you mentioned. Do you want to take a look at them? Or should I merge?

**Comment by musicinmybrain** [comment]
Hmm, apparently with the actual release of 1.0.0 the FreeDesktop documentation has been updated: https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-developer

It documents the `id` property of the `developer` element as follows:

> The element should have a id property, containing a unique ID to identify the respective developer. It is recommended to use a web URL, like gnome.org as ID to achieve a higher chance of uniqueness.

How about I write:

```xml
<developer id="spyder-ide.org">
```

That would seem to fit with the spirit of the design and eliminate one of the warnings.

I’m not particularly interested in trying to add a content rating.

**Comment by musicinmybrain** [comment]
If you’re happy with this, I’m happy for it to be merged.

**Review by ccordoba12 — APPROVED** [review]
Thanks @musicinmybrain!

**Pull request merged**
