### PR TITLE
PR: Change variableexplorer viewer collections name to iterables

### PR DESCRIPTION
**Pull request by rlaverde**
See: https://github.com/spyder-ide/spyder/pull/5206#issuecomment-329018836

In #4557 `collectionseditor.py` was changed to `collections.py` (and that interferes with `collections` built-in)

This have to be rebased after #5206

### CODE REVIEW

**Comment by ccordoba12** [comment]
Please rebase this one. Also, please rename `test_collectionseditor.py` to `test_iterablesviewer.py`

**Comment by rlaverde** [comment]
Also `array.py` interferes, I'm not sure if also `dataframe.py` `object.py`  or `text.py` intereferes too

**Comment by goanpeca** [comment]
Maybe we should add a prefix letter or something to each object?

sobject, sarray, sdataframe, scollection ? (for spyder?) or something similar

**Comment by rlaverde** [comment]
yes, or maybe `v` for viewer, or `e` for editor

**Comment by goanpeca** [comment]
Sure, lets use something like that and get rid of these problems for good. Maybe with underscore  to make it clearer?

ve_object
ve_array
ve_collections   

ve = variable explorer ?
etc...

@ccordoba12 ?

**Comment by ccordoba12** [comment]
Then we should remove the `viewers` module and leave things as they were before, i.e. `collectionseditor.py`, `dataframeeditor.py`, etc.

**Comment by rlaverde** [comment]
Closing in favor of #5263

**Pull request closed without merging**
