### PR TITLE
PR: Fix detection of conda and pyenv environments on Windows

### PR DESCRIPTION
**Pull request by ccordoba12**
@steff456, the detection of environments was failing on Windows due to some small issues. Please take a look at this PR to see if it looks ok for you.

@CAM-Gerlach, could you test if this works locally for you? Thanks!

### CODE REVIEW

**Review by steff456 — APPROVED** [review]
Thanks for this PR @ccordoba12, I totally forgot to add this support in the original PR. I'll test it tomorrow on my VM, but all the code looks really good!

**Review by CAM-Gerlach — CHANGES_REQUESTED** [review]
I'm still not 100% sure of the precise exact behaviors I'm supposed to be validating (nor how it really didn't occur to anyone to test highly platform-dependent functionality on Spyder's biggest and most problematic platform), but as far as I can tell, it still doesn't work. I don't see any difference from spyder-ide/spyder#199 on any of the [things](https://github.com/spyder-ide/spyder-docs/pull/199#pullrequestreview-524773922) I mentioned in my review there. I tested with and without safe mode, and it appeared to make no difference either.

Let me know what you would like me to test further.

**Comment by ccordoba12** [comment]
@CAM-Gerlach, if you don't have conda in your PATH and you installed Anaconda in a non-standard location, the it won't be possible for Spyder to list your envs.

Is that the case for you?

**Comment by CAM-Gerlach** [comment]
Some additional info now that I've tried to sleep a little...

I thought it was intentional, but I'm also still experiencing #14136 where the status bar widget shows the full path, instead of just the env name, though it may be a side effect of whatever is resulting in these changes not working on my system. Other than that, and the ability to click the env name to get a popup to go to preferences, nothing else appears to be different (good or bad) with this PR, as I can still browse for envs, switch between them, start consoles in them, etc. but they are not autodetected).

image

Taking a quick look at the code, I don't see anything immediately obvious as to why; there are no spaces in my Miniconda path, it uses the default directory name, and contains `conda` which it looks like the code checks for. I also have all the new deps installed and no warnings on that.

Some potentially useful output in my default Spyder env, from within Spyder:

image

And outside of it:

image

**Comment by ccordoba12** [comment]
Ok, I think we haven't added `C:\Miniconda3` to the list of locations we search for the conda executable.

I'll do that in a bit so you can test again.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Sorry, your message didn't how up when I posted mine.

On Windows, conda is not added to the `PATH` by default; there is a non-default option for that in the installer but it warns strongly against it, so we shouldn't rely on this on that platform. I did install to `C:/Miniconda3` via the conda installer instead of the default suggested path (as I did with `C:/Anaconda3` before it) due to the conda installer warning me about the space in my username (chosen many, many years ago, before I knew better), but I've seen a significant fraction of other users on our issue tracker do the same, either to avoid spaces/special characters on their path that conda warned about, or for other reasons.

Instead of hardcoding `C:/(Ana|Mini)conda` or the default Anaconda/Miniconda install paths (which would only work for users who happen to choose that), the officially supported and most reliable way to get the path to the system's default Python install on Windows (Anaconda or otherwise) is with the `py` launcher that comes with Windows by default, which Anaconda/Miniconda automatically registers itself with as the default Python. Therefore, all you need to do is run the following command (works regardless of what env is activated), which I verified works on my system, to get the path to the Python in the base conda env; its parent directory on Windows is the Anaconda/Minconda directory

```bash
py -c "import sys;print(sys.executable)"
```

image

If for some reason you need a fallback to that, you could also simply check the `sys.executable` returned by Spyder's own copy of Python to get the base path to its Python install, either Anaconda/Miniconda, or its standalone Python (not sure what you do already in that case).

Speaking of which, I probably should test this using the Windows installer too? Where can I find that?

**Comment by mrclary** [comment]
> Ok, I think we haven't added `C:\Miniconda3` to the list of locations we search for the conda executable.
> 
> I'll do that in a bit so you can test again.

That should already be in the search path...
`spyder.utils.programs.py:107`
```python
elif WINDOWS:
    pyenv = [osp.join(home, '.pyenv', 'pyenv-win', 'bin')]
    
    a = [home, 'C:', osp.join('C:', 'ProgramData')]
    b = ['Anaconda3', 'Miniconda3']
    conda = [osp.join(*p, 'condabin') for p in itertools.product(a, b)]

    req_paths.extend(pyenv + conda)
```

**Comment by ccordoba12** [comment]
Thanks @mrclary for your help! I ran that code locally and I think I found the error: `C:` needs to be `C:\\` so it's joined correctly by `osp.join`.

**Review by CAM-Gerlach — APPROVED** [review]

**Comment by mrclary** [comment]
> Thanks @mrclary for your help! I ran that code locally and I think I found the error: `C:` needs to be `C:\\` so it's joined correctly by `osp.join`.

Thanks @ccordoba12 for catching that! I'm sorry I missed it in the first place.

**Comment by ccordoba12** [comment]
No worries. @CAM-Gerlach also helped me to found other thorny issues that we hadn't considered before. So the credit to make this one finally work goes to him too.

**Pull request merged**
