### PR TITLE
PR: Some fixes to load project configuration files correctly

### LINKED ISSUE #13110: Linting is not respecting pycodestyle.cfg
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Linting no longer respects pycodestyle.cfg after #12812

### What steps reproduce the problem?

1. Bootstrap with a8565a1f1df017b38a34c4cf7ea4e603cb22b7ff (last good 4.x commit); observe that linting respects pycodestyle.cfg
2. Bootstrap with a4d9ae4a4aede506737b71b9426e4f5d7afb0d04; observe that linting does not respect pycodestyle.cfg

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.0dev
* Python version: 3.7.7
* Qt version: 5.12.5
* PyQt version: 5.12.3
* Operating System name/version: Darwin 18.7.0

### Dependencies
<details><summary>Dependencies</summary>

```
# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.15.0 (OK)
jedi =0.17.0                   :  0.17.1 (NOK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.0.0 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.5.3 (OK)
pyls >=0.33.0;<0.34.0          :  v4.1.3+298.ga4d9ae4a4 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.4 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.4 (OK)
spyder_kernels >=1.9.1;<1.10.0 :  1.10.0.dev0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.20 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.4 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.6 (OK)
```
</details>

### PR DESCRIPTION
**Pull request by ccordoba12**
With this PR (which contains a lot of fixes on the PyLS side) is now possible to load `~/.config/pycodestyle` or `/path/to/project/pycodestyle.cfg` and have those settings prevail over the ones defined by the user in Spyder.

I also updated the PyLS version to `>=0.34.0,<0.35.0` to have the fixes we need for this.

Fixes #13110.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Pinging @mrclary about this one.

**Comment by mrclary** [comment]
@ccordoba12 , Thanks for taking care of this.

**Comment by ccordoba12** [comment]
No problem. It was a lot of work, but the functionality was horribly broken.

So, thanks a lot to you too for letting us know that before releasing 4.1.4.

**Comment by ccordoba12** [comment]
This is finally ready!

**Pull request merged**
