### PR TITLE
PR: Automatically scroll down to newest plot in Plots pane

### LINKED ISSUE #10912: When plotting new plot, plot pane does automatically scroll down to newest plot.
I'm using 4.0.0rc3. 

The plot displays the last made plot, but the scroll bar on the right does not default to its lowest scroll point. Not a huge deal, just notifying the Spyder team that I'm seeing it!

Also, I LOVE the new update from 3.6 -> 4.0!! Great work!

### PR DESCRIPTION
**Pull request by jnsebgosselin**
## Description of Changes

scroll_to_new_row

### Issue(s) Resolved

Fixes #10912

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Jean-Sébastien Gosselin

### CODE REVIEW

**Comment by jnsebgosselin** [comment]
> Looks good to me, but a lot of test failures! Is that related?

Yes, it is related.

Is it working locally for you on mac?

**Comment by goanpeca** [comment]
>Is it working locally for you on mac?

You mean the tests?

**Comment by jnsebgosselin** [comment]
> 
> 
> > Is it working locally for you on mac?
> 
> You mean the tests? or the fix?

The fix.

To know that it's working or not for you will help me fix the test... I hope at least :P

**Comment by goanpeca** [comment]
@jnsebgosselin the test was indeed failing for me locally so I simplified it a bit.

**Comment by goanpeca** [comment]
I am not sure why the slow tests are failing, it seems some of the latest PR merged caused some issues 🤷‍♂ 

The test is failing on Linux py3.7. I will need to start a VM to see if I can reproduce.

**Comment by jnsebgosselin** [comment]
> 
> @jnsebgosselin the test was indeed failing for me locally so I simplified it a bit.

Thanks a lot @goanpeca for you help.

However, it is not sufficient to assert that `assert vsb.value() == vsb.maximum()`, because there an issue in Qt where the maximum value of the scrollbar doesn't get updated right after a new widget is added to the layout of the scrollarea widget. So this is why we need to calculate the expected range of the scrollbar from the content of the scrollarea.

See for instance https://stackoverflow.com/questions/19836404/qscrollarea-does-not-scroll-to-maximum-after-widgets-have-been-added

I've changed the approach to scroll to newest plot by connecting to the signal `rangeChanged` of the scroll bar instead using a call to `QApplication.proccessEvent`. The animation seems better for me and there is less flickering on Windows.

I reworked the test a little bit, we will see how it goes...

**Comment by jnsebgosselin** [comment]
@goanpeca just letting you know that this is ready, so you can review when you have the time, there is no rush.

**Pull request merged**
