### PR TITLE
PR: Patch py2app site.py template for IPython help()

### LINKED ISSUE #14713: python "help" command failed in iPython console
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

### What steps reproduce the problem?

1. type "?" in ipython console, it shows "help      -> Access Python's own help system"
2. type "help()", it failed with "NameError: name 'help' is not defined"

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.1
* Python version: 3.9.1
* Qt version: 
* PyQt version: 
* Operating System name/version: macOS 10.15.7 (Catalina)

### Dependencies

```
PASTE DEPENDENCIES HERE
```

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes
Patch `py2app` template `site.py` file so that IPython `help()` works with internal IPython consoles on macOS application.

### Issue(s) Resolved

Fixes #14713

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@mrclary

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @mrclary, we found out we must release 4.2.3 due to bug #14801. How confident do you feel about us including this PR in that version?

**Comment by mrclary** [comment]
@ccordoba12, very confident.

**Comment by ccordoba12** [comment]
Great! Thanks for the confirmation.

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary!

**Pull request merged**
