### PR TITLE
PR: Correct auto-indent behaving in unexpected ways

### LINKED ISSUE #887: Fix issues with incorrect auto-indentation
_From [julian.h...@gmail.com](https://code.google.com/u/105129497054033444742/) on 2011-12-15T17:08:06Z_

This is a enhancement/feature request.

Enhancement request:

```
1: def parseargs():
2:    ap = argparse.ArgumentParser()
3:    ap.description('Records results from standard HPC benchmarks and '+ \
4:        'corresponding information about the enviornment and input data to '+ \
5:        'interprete the results')
6:    ap.add_argument(...)
```

After hitting return on line 5, spyder autoindents with 8 spaces, thus requiring the user to hit backspace or shift-tab. This should be changed to: if the last line (where return was hit) completes a statement (in this case ap.description(...)), then autoindent to the indentation level of that statement, otherwise autoindent to previous line level.

Feature request:

```
1: if some.condition():
2:     do_one_thing()
3: else:
4:     do_another_thing()
```

After hitting return on line 2 spyder indents to 4 spaces, fine so fare. Here would it be nice to just type "else:" and have spyder do the unindentation by itself. The same behavior should be implemented for "except:" and "final:".
It makes sens to check if the user had already done the unindentation, to not confuse old users with this new behavior, for example by checking if a corresponding "if ...:" or "try:" exists (this would fail with nested blocks) or by checking if backspace/shift-tab was hit just before typing the keyword.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=887_

### LINKED ISSUE #5606: Editor sets incorrect indent when character immediately before the break is a paren
## Description

I've been having consistent issues with the  editor's automatic indents, that not only render it useless, but actively hinder in many situations. Specifically, when breaking a line, whenever the last non-whitespace character before the break is a parenthesis (which happens frequently when following the PEP8 recommendation to break before the operator), auto-indent sets an incorrect indent level for the following line, (the indent level of whatever statement on the previous line if after a close paren, or two tabs over if an open paren) and makes it very difficult to even manually fix every time—if I tab or space even one character past the desired position, backspace, shift-tab etc. will send me all the way back where I started. This is sufficiently problematic that the feature is a net loss in efficiency if left unfixed.

**What steps will reproduce the problem?**

1. Paste one of the example snippets below
2. Place cursor where indicated ("|")
3. Hit return/enter for a linebreak
4. Experience the joys and sorrows of trying to manually align it properly, with the auto-indent actively working against you if you slip up.

**What is the expected output? What do you see instead?**

Some contrived/minimal examples (cursor "|"):

**Works:**

_When the last char before a break isn't a paren, regardless of style_
Before Break:
```
if True:
    print(str(str("foo" |+ str("bar"))))
```
vs.
```
if True:
    print(str(str("foo" +| str("bar"))))
```
After Break (As Expected):
```
if True:
    print(str(str("foo" 
                  + str("bar"))))
if True:
    print(str(str("foo" + 
                  str("bar"))))
```

**Doesn't Work**

_When the last character before the break is a close paren, as is much more common when following PEP8 break before operator style, it doesn't work:_
Before Break:
```
if True:
    print(str(str(str("foo") +| "bar")))
```
vs.
```
if True:
    print(str(str(str("foo") |+ "bar")))
```
Expected After Break:
```

if True:
    print(str(str(str("foo") +
                  "bar")))

if True:
    print(str(str(str("foo") 
                  + "bar")))
```
Actual After Break for Second Case:
```
if True:
    print(str(str(str("foo") 
    + "bar")))
```

_Open Paren Case_
Before Break:
```
if True:
    some_long_variable_name = ("foo" + "bar")
```
Expected After Break (Yeah, not great style, but better than the actual):
```
if True:
    some_long_variable_name = (
        "foo" + "bar")
```
Actual After Break:
```
if True:
    some_long_variable_name = (
            "foo" + "bar")
```

_Another (slightly less minimal/contrived) example_
Before break:
```
if True:
    (print(str(("Long string " + "Yeah").|format(some_long_variable_name))
```
vs.
```
if True:
    (print(str(("Long string " + "Yeah")|.format(some_long_variable_name))
```
Expected After Break:
```
if True:
    (print(str(("Long string " + "Yeah").
               format(some_long_variable_name))))

if True:
    (print(str(("Long string " + "Yeah")
               .format(some_long_variable_name))))
```
Actual After Break for Second Case :
```
if True:
    (print(str(("Long string " + "Yeah")
    .format(some_long_variable_name))))
```

**Please provide any additional information below**

Experienced on multiple platforms since Spyder 3.2.2, when I started using it.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.3
* Qt Versions: 5.6.2, PyQt5 5.6 on Windows 8.1 x64

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.3 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.5 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26.1 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

### LINKED ISSUE #7377: Indentation errors for fuction calls with `#` in a string
Using Spyder 3.2.8 and reset to default settings.
Running on Xubuntu 18.04.

Situation: For an on-line Physics course, I am creating Python code that has no control statements at all. Just straight down executable statements beginning in column 1.  Call it a fancy calculator.

I find, in this situation, that Spyder automatically indents when I enter a newline after a Python print statement.  Sample code follows.
```
# Weight on Earth
m = 79 # kg
g = 9.8 # m/s^2
w = m * g # N
print("#1 w(Earth) =", w)
```
When I am positioned at the end of the print statement and press Enter, Spyder inserts a line immediately after the print line with exactly 6 spaces.  Since I had reset to default settings, the tab-indent uses 4 spaces so it doesn't seem to be a false tab.

### PR DESCRIPTION
**Pull request by definite-purple**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)
  * [x] Change Tests for unmatched opening brackets without keyword
  * [x] Add Tests for more keywords
  * [x] Add Tests for brackets, # and keywords in single quote strings
  * [x] Add Tests for brackets, # and keywords in triple quote strings
    * [x] Over multiple lines
  * [x] Add Tests for all behaviours described in #5606 
  * [ ] Add Tests for all behaviours described in #887 
  * [x] Add Tests for all behaviours described in #7377 

* [x] ~~Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))~~

Correct unexpected behaviour of the auto-indent feature of the editor widget.

Largely rewrite `plugins/editor/widgets/codeeditor.py CodeEditor.fix_indent_smart`
to be more readable, make it respect strings and comments better when matching brackets,
have it only indent by two levels when required by keywords, and possibly more.

### Issue(s) Resolved

Fixes #5606
Fixes #887
Fixes #7377

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: definite-purple

### CODE REVIEW

**Comment by definite-purple** [comment]
Heya, so first-time contributor here. I'll need another one or two days to get this done but had questions and didn't know where else to ask them:

The file test_autoindent.py contains the tests relevant to my PR.  
When I notice something amiss with already implemented tests (e.g. a test named curly brackets testing parens like the two above), can I just fix that in a commit for *this* PR, or should I not touch them?

I haven't really figured out how squashing commits works, and it's not that high of a priority for me personally. Since the relevant section in the Dev-wiki is still unwritten, should I just not bother for this?

That's all for now, looking forward to hearing back from you!

**Comment by ccordoba12** [comment]
> Heya, so first-time contributor here.

Hey, really glad to know that you want to contribute to Spyder!

> I'll need another one or two days to get this done but had questions and didn't know where else to ask them

Sure, this is the best place to ask questions.

> When I notice something amiss with already implemented tests (e.g. a test named curly brackets testing parens like the two above), can I just fix that in a commit for this PR, or should I not touch them?

If the changes you're making also alter the results of some of our tests, then you need to fix them. But if you think our tests could be improved to better catch what they are supposed to do, then I think it's better to leave that for another PR.

**Comment by definite-purple** [comment]
I hit a minor(?) roadblock when trying to infer the appropriate indent from lines inside a triple-quoted string literal or line-continued string literal.

There isn't by chance something like a context explorer already implemented in spyder?  
Something that tells me whether the literal was opened with `' " ''' """`?

(Or some form of lexical analysis tool, that works inside a limited scope?)

I can manage without, but it won't be as elegant as it could be.

**Comment by ccordoba12** [comment]
> Something that tells me whether the literal was opened with ' " ''' """?

You can take a look at the method called `in_comment_or_string` in `spyder/plugins/editor/widgets/codeeditor.py`

**Comment by definite-purple** [comment]
I found sourcecode.get_identifiers

> You can take a look at the method called `in_comment_or_string` in `spyder/plugins/editor/widgets/codeeditor.py`

Thanks. I can't really use this for what I was trying to do. I was looking for something more like #3493

**Comment by definite-purple** [comment]
Okay…
My latest commit affected pre-existing tests. Could somebody please look over them to check that the new behaviour is indeed the correct one?

Summary of changes in the tests:

Old | New
-|-
Ending a line with an opening bracket always indents the next line two levels | Only indents one level, except if prevline started with one of the block opening keywords that accept arguments
When in tabstop mode, always try to vertically align with the opening bracket, but no more than two tabs |  … I just added an item after the opening bracket and commented out the first two tests, because I don't think that was ever intended behaviour?

**Comment by ccordoba12** [comment]
Could you some examples of the before/after behaviors? I think that would make things easier to understand for us.

**Comment by definite-purple** [comment]
Through all the changed behaviour, only the tests ending with any opening bracket and not starting with a keyword have been affected.

Each of the examples shows the new cursor position after the function got called as `|`

```python
long_list_name = (
        |
```
Changed to:
```python
long_list_name = (
    |
```
---
In addition the tests about vertical align when using tabstops with `print(` were changed to `print(""`

---
```python
def function(
        |
```
Stayed the same as before.

---
```python
long_list_name = (a,
                  |
```
Stayed the same as before

**Comment by ccordoba12** [comment]
Ok, thanks! I agree with all your changes.

**Comment by ccordoba12** [comment]
@definite-purple, do you need help to finish this PR?

**Comment by ccordoba12** [comment]
@dalthviz, please help @definite-purple to finish this PR. I think it's very important that we include this work in our next beta.

**Comment by definite-purple** [comment]
> @definite-purple, do you need help to finish this PR?

Hey, yes. I need help with this PR. Somehow this project fell off my radar, and my free time is limited for the next handful of weeks.

> @dalthviz, please help @definite-purple to finish this PR. I think it's very important that we include this work in our next beta.

That would be much appreciated. I have some changes that are still local-only, which I'll commit and push later today.

As far as I remember, most of the implementation is done. What was left was writing tests and figuring out if the sloppy way I handled triple-quoted string literals causes issues.

**Comment by ccordoba12** [comment]
Thanks a lot @dalthviz for helping @definite-purple to finish this one!! Do you think it's ready? Or are there other things still to be addressed?

**Comment by dalthviz** [comment]
No problem @ccordoba12 :+1:, about the state of the PR, I think I'm missing the addition of a test with the cases at #887 although I'm unsure of what is the expected behavior and how the test should be

**Comment by ccordoba12** [comment]
> I'm unsure of what is the expected behavior and how the test should be

I think the only thing worth covering in test is what's mentioned here https://github.com/spyder-ide/spyder/issues/887#issuecomment-232154538

**Pull request merged**
