### PR TITLE
PR: Mention that we need to publish release candidates for stable versions in release instructions

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

Also, update instructions to update Spyder-kernels before a new release. That's necessary now that we're using a backporting workflow. 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @ccordoba12

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, please check that the new instructions make sense for you.

@mrclary, are the changes I did enough to include the new `spyder_rc` channel in the workflow and script that build our installers?

**Review by mrclary — APPROVED** [review]
Looks good to me, @ccordoba12. Yep, just needed to add the rc channel to the channel lists.

**Review by dalthviz — APPROVED** [review]
Thanks @ccordoba12 !

**Comment by dalthviz** [comment]
@meeseeksdev please backport to 6.x

**Pull request merged**
