### PR TITLE
Added .idea folder to .gitignore for PyCharm users

### PR DESCRIPTION
**Pull request by dhirschfeld**

### CODE REVIEW

**Comment by Nodd** [comment]
That's not very informative. Do you at least have a link explaining why it's useful ?

**Comment by cjrh** [comment]
The PyCharm IDE uses a hidden folder `.idea/` to keep "project information and settings" for the IDE.  If `.idea/` is not added to `.gitignore`, you keep getting asked whether you want to add things like `vcs.xml` to version control.  This is one of the files within the `.idea/` folder.   I'm personally neutral on this PR, even though I've started using PyCharm, but that's the basic background.

**Comment by dhirschfeld** [comment]
As @cjrh mentions it's the folder reserved for PyCharm specific settings so shouldn't be committed to the repo.

This PR simply adds that folder to the `.gitignore` file which improves the development experience for PyCharm users hence lowering the barrier to contribution (in an admittedly small way).

**Comment by Nodd** [comment]
Oh sorry, I thought that it was an issue instead of a pr. I'm fine with it then.

**Comment by ccordoba12** [comment]
I'm fine with this. No problem with our contributors using other IDEs to develop Spyder, though I'd prefer them to use Spyder itself to do it ;-)

**Comment by cjrh** [comment]
@ccordoba12 Think of it as "IDE bootstrapping" 😉

**Pull request merged**
