### PR TITLE
PR: Prevent error when multiple threads try to write messages from comm handlers (IPython console)

### LINKED ISSUE #19735: AttributeError: 'WriteWrapper' object has no attribute '_thread_id' in kernel
### What steps will reproduce the problem?

I am writing this code and occur this error. Not sure what's going on.

import networkx as nx
G = nx.DiGraph(nx.path_graph(4))
nx.pagerank(G)

### Traceback
```python-traceback
Exception in comms call get_namespace_view:
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/comms/commbase.py", line 343, in _handle_remote_call
    return_value = self._remote_callback(
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/comms/frontendcomm.py", line 270, in _remote_callback
    return super(FrontendComm, self)._remote_callback(
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/comms/commbase.py", line 356, in _remote_callback
    return self._remote_call_handlers[call_name](
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/console/kernel.py", line 194, in get_namespace_view
    view = make_remote_view(ns, settings, EXCLUDED_NAMES)
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/utils/nsview.py", line 686, in make_remote_view
    view = value_to_display(value, minmax=settings['minmax'])
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/utils/nsview.py", line 443, in value_to_display
    np.set_printoptions(**np_printoptions)
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/numpy/core/arrayprint.py", line 252, in set_printoptions
    array([-0., -0.,  0.,  0.])
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/numpy/core/arrayprint.py", line 94, in _make_options_dict
    warnings.warn(
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/warnings.py", line 112, in _showwarnmsg
    _showwarnmsg_impl(msg)
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/warnings.py", line 30, in _showwarnmsg_impl
    file.write(text)
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/comms/frontendcomm.py", line 310, in __call__
    self._write(
  File "/Users/chengxueqi/opt/anaconda3/lib/python3.9/site-packages/spyder_kernels/comms/frontendcomm.py", line 300, in __call__
    if self._thread_id != threading.get_ident():
AttributeError: 'WriteWrapper' object has no attribute '_thread_id'
```

## Versions

* Spyder version: 5.2.2 
* Python version: 3.9.12
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Darwin 21.6.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.1.7     :  0.3.0 (OK)
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.6.0;<8.0.0        :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.4.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.4.4 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.0 (OK)
pygments >=2.0                :  2.11.2 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.0 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.1.10 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  2.2.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  63.4.1 (OK)
sphinx >=0.6.6                :  5.0.2 (OK)
spyder_kernels >=2.2.1;<2.3.0 :  2.2.1 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.6 (OK)
zmq >=17                      :  23.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.30 (OK)
matplotlib >=2.0.0            :  3.5.2 (OK)
numpy >=1.7                   :  1.21.5 (OK)
pandas >=1.1.1                :  1.4.3 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.10.1 (OK)
```

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

- We're not sure if this will solve the problem (see https://github.com/spyder-ide/spyder/issues/19735#issuecomment-1277218194), but it's the best we can do at the moment.
- Depends on spyder-ide/spyder-kernels#420 and spyder-ide/spyder-kernels#422

### Issue(s) Resolved

Fixes #19735 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
@impact27, I don't understand what happens but your changes in spyder-ide/spyder-kernels#420 don't work here, i.e. we can't start consoles with them.

Could you take a look at it?

**Comment by impact27** [comment]
https://github.com/spyder-ide/spyder-kernels/pull/422

**Comment by ccordoba12** [comment]
Great! Thanks for the quick response!!

> Ha yes the lock needs to be re-entrant in 5.x

So, what do I need to do when merging your new PR to master of Spyder-kernels?

**Comment by impact27** [comment]
> So, what do I need to do when merging your new PR to master of Spyder-kernels?

You should be able to merge it as is

**Pull request merged**
