### PR TITLE
PR: Feature/docks

### PR DESCRIPTION
**Pull request by goanpeca**
OSX

screen shot 2017-01-28 at 7 14 25 pm

TODO:
- [x] Fix segfault on direct drag and drop for docks
- [x] Fix random missing custome titlebar tabs
- [ ] Enable floating behavior (windows individual floating windows?)

### CODE REVIEW

**Comment by ccordoba12** [comment]
It looks so nice on Linux! Thanks a lot for this!! ;-)

Do you want to improve our css on macOS to make the dockwidgets tabbar look similar to the one on Linux? Or do you prefer to do that in another PR?

**Comment by goanpeca** [comment]
>Do you want to improve our css on macOS to make the dockwidgets tabbar look similar to the one on Linux? Or do you prefer to do that in another PR?

Yes I will add this here, still checking on windows and linux to make sure everything works ok.

**Comment by goanpeca** [comment]
Hmmm @ccordoba12 any comment regarding this, I changed my mind, I think I want to merge and update the dark stye theme.

**Comment by ccordoba12** [comment]
It looks good to me, but people in master won't be able to close and undock plugins if we merge this as it is.

So I think we should add those actions to the Options menu of every plugin, as we talked about. How hard do you see to do that here?

**Comment by ccordoba12** [comment]
@goanpeca, please finish this one, I'm very interested on merge it because it's a terrific improvement!!

Also, would it be possible to organize some plugins vertically, i.e. to add a vertical tabbar with the Project and Outline explores?

**Comment by goanpeca** [comment]
@ccordoba12 I will but I don't have time this week. I will do my best on the weekend. The issue here is that there are many corner cases (os specific sometimes) to consider since I am replacing the tab bar with a new one, I have to reimplement almost all the behavior.

>Also, would it be possible to organize some plugins vertically, i.e. to add a vertical tabbar with the Project and Outline explores?

I dont follow

**Comment by ccordoba12** [comment]
> I dont follow

I mean, to have something like this *Documents* tab on the left in Kate:

seleccion_001

**Comment by goanpeca** [comment]
>I mean, to have something like this Documents tab on the left in Kate:

We need to consider this more in depth cause we have options.

Option 1 is to have vertical tabs for docks, but this only works for docks on the left or on the right, if there is a 3 column layout this will look bad.

Option 2 is to use two toolbars on the left and right of the main window and allow for docks to be dragged there, which would in turn make them toggleable. Much this would allow for Spyder to work like jlab or pycharm or kate.

I am in favor of option 2 as it would really provide the best customization and the best behavior, but this is clearly out if scope of this PR.

**Comment by ccordoba12** [comment]
> I am in favor of option 2 as it would really provide the best customization and the best behavior

Yep, me too.

> but this is clearly out if scope of this PR.

Ok, no prob :-)

**Comment by goanpeca** [comment]
@ccordoba12 I would like to have a meeting to go over how the behavior should be now that the title bar is at the same time the tabbar for docked widgets.

**Comment by ccordoba12** [comment]
> I would like to have a meeting to go over how the behavior

Next week, any time after 3 pm of Colombia.

----

Quick comments:

1. Is it possible to add tests for this?
2. Please remove some commented code you left behind.

**Comment by goanpeca** [comment]
Is it possible to add tests for this?

1. It is going to be difficult to emulate the interaction for this, so no.
2. Yes, I need to rebase the work and only update the real changes, will do as I have a more complete version.

**Comment by ccordoba12** [comment]
Closing this one for now. Please reopen it when you feel it's ready.

**Pull request closed without merging**
