### PR TITLE
Do not ask for confirmation when removing dicteditor items

### PR DESCRIPTION
**Pull request by jondo**
See #1981.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for the PR, but what if people accidentally press delete over a variable?

**Comment by jondo** [comment]
Ok, in this case confirmation makes sense.

**Comment by ccordoba12** [comment]
Yes, this has to be smarter. My suggestion is to add a third button to the current `QMessageBox` dialog, called *Don't ask again* or something like that.

If the user press that button, then we'd save that to a variable (say `show_del_warning`) in the class the dialog is part of. So, next time the user press delete, we should check the value of `show_del_warning`, and if it's false, don't show the dialog.

I think this should be enough. There is no need to save this across session restarts :-)

**Comment by jondo** [comment]
> There is no need to save this across session restarts :-)

I have thought about it and in fact **I never** want to have this confirmation. I do not accidentally press 'delete' (and if so, I can cope with the consequences). So please **do** save this across session restarts :-)

In fact, the best UI for this would be a limited (one step) 'undo' functionality, and no dialogs at all.

**Comment by ccordoba12** [comment]
Ok, this is your PR ;-) So if you don't want to show the confirmation dialog across sessions, you need to add an option to `config.py` (under the `variable_explorer` section) and associate it with the corresponding button of the `QMessageBox` you removed.

----

 > the best UI for this would be a limited (one step) 'undo' functionality, and no modal dialogs at all.

This is (technically) not easy to achieve. I think it'd demand a lot of time from us to do it for very little gain ;-)

**Comment by goanpeca** [comment]
@ccordoba12 would it be that difficult? everytime something gets erased it should be stored

**Comment by goanpeca** [comment]
Sorry... wrong click!

**Comment by ccordoba12** [comment]
@jondo, do you plan to finish this one?

**Comment by jondo** [comment]
@ccordoba12 I'm afraid currently not. For the moment, I will just patch my versions locally.

**Comment by ccordoba12** [comment]
@jondo, well, the easiest option would be to ask for confirmation only one time per session. Why don't you go for that? That would be much better than what we have right now ;-)

**Pull request closed without merging**
