### PR TITLE
Draft: [5.x branch] Allow ipython 8+ v2

### PR DESCRIPTION
**Pull request by eendebakpt**
## Description of Changes

Test Spyder with ipython 8+

* Tests in python 3.7 will fail since ipython 8+ is not available
* ? `Create Windows Installer / Windows installer (Lite)` will fail since the updated spyder-kernels is not available in conda

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
Closing and reopening to see if our tests run.

**Comment by ccordoba12** [comment]
@eendebakpt, some comments for you:

* I don't know why but we're not installing IPython 8 on Github actions:

    https://github.com/spyder-ide/spyder/actions/runs/3243542120/jobs/5318407187#step:12:128

    So, I'd suggest to change our dependency on IPython to be `>=8.5.0,<9` to force our tests to really run with IPython 8. Besides, trying to support IPython 7 and 8 is too much for us, so I think it's better go only with 8 from now on.

* You also need to update the requirement in our `setup.py`.

* Please also make the `>=8.5.0,<9` change in your Spyder-kernels PR and resync our subrepo here following the instructions in our Contributing guide.

**Comment by eendebakpt** [comment]
@ccordoba12 ipython 8+ does not support python 3.7 any longer (from the setup.py: `IPython 8+ supports Python 3.8 and above, following NEP 29.`). I will look into the tests for 3.8+

**Comment by eendebakpt** [comment]
@ccordoba12 I am not familiar with conda. Most tests fail because:
```
- nothing provides __win needed by ipython-8.5.0-pyh08f2357_1
```
This also happens on the Linux tests, even though  `__win` is a virtual package related to windows (https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html).

Do you have an idea what is going on?

**Comment by ccordoba12** [comment]
> ipython 8+ does not support python 3.7 any longer

Right, I forgot about it. So we need to change the requirement to `>=7.31.1,<9`. However, your previous run was not picking up IPython 8 even for Python 3.9:

https://github.com/spyder-ide/spyder/actions/runs/3243542112/jobs/5318406491#step:11:115
https://github.com/spyder-ide/spyder/actions/runs/3243542104/jobs/5318406138#step:11:114

> Do you have an idea what is going on?

Nop, sorry. But a way to solve this could be to force installing IPython 8 in our [`install.sh`](https://github.com/spyder-ide/spyder/blob/master/.github/scripts/install.sh) script for Python 3.9. Please try that for the `pip` part of the big `if` on it. That at least will run our tests on some Windows and Linux slots.

**Comment by eendebakpt** [comment]
@ccordoba12 For some reason I cannot get the dependencies right between the spyder-kernels and spyder reposities. But the `Linux tests / Linux - Py3.9, conda, slow (pull_request)` and `Win tests / Windows - Py3.9, pip, slow (pull_request` are running now with ipython 8+. 

Besides some tests related to the package versions (`test_dependencies_in_sync.py`), there was only a single failing test. I created a separate PR to the 5.x branch to address this: https://github.com/spyder-ide/spyder/pull/19885

**Comment by ccordoba12** [comment]
Ok, thanks a lot for your help with this! Unfortunately, I don't have time right now to fix our CIs so that they pass for all operating systems and Python versions.

So, I'm afraid this will have to wait until 5.4.1, to be released in December.

**Comment by ccordoba12** [comment]
Closing because this was superseded by PR #20271.

**Pull request closed without merging**
