### PR TITLE
PR: Don't add repeated entries to history while on pdb

### LINKED ISSUE #6295: pdb history doesn't collapse similar text
## Description of your problem

**What steps will reproduce the problem?**

1. debug
2. enter something interesting
3. press 'n' 100 times
4. press 'up' 101 times to get back to the interesting stuff

**What is the expected output? What do you see instead?**
I don't see the point of 'up' returning the same text 100 times.

### PR DESCRIPTION
**Pull request by impact27**
Fixes #6295

### CODE REVIEW

**Comment by csabella** [comment]
Sorry, this got merged before I could ask a question.  I noticed when using ipdb that pressing Enter repeats the last command (which I think is actually kind of cool).  I wonder if these blank `lines` should be skipped from being added to history.

**Comment by impact27** [comment]
Well my point of view is that even the pub commands should not go in the history. But this might be another issue. I actually added a ‘if len(line) > 1’ to my personal spyder to get rid of the single character commands. But it is a ugly hack so I haven’t pushed it.

**Comment by csabella** [comment]
Actually, you wouldn't need all that.
```
if (line and
   (not self._control.history or not self._control.history[-1] == line)):
```

I don't think they go into the real history, do they?

**Comment by impact27** [comment]
Sure but my point was that I also wanted to get rid of the ‘n, s, I, d’ that are specific to PDB, and only keep the actual python code.

**Comment by csabella** [comment]
@impact27   Ah, I see.  Thanks for clarifying.  Since the change narrows it down to just one copy of those commands, I don't find that they are in the way at all. But, I see your point.  I guess you would need to have a set of them or look to see how the program handles them now to know the difference between a single character variable name and a pdb command.

**Pull request merged**
