### PR TITLE
PR: Fix missing shortcuts on Preferences

### LINKED ISSUE #12415: Not all shortcuts are displayed in the preferences table
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The following shortcuts are not displayed in the preferences table (shown in name - context)

close pane - _
lock unlock panes - _
use next layout - _
use previous layout - _
preferences - _
maximize pane - _
fullscreen mode - _
save current layout - _
layout preferences - _
show toolbars - _
restart - _
quit - _
file switcher - _
debug - _
debug step over - _
debug continue - _
debug step into - _
debug step return - _
debug exit - _
run - _
configure - _
re-run last script - _
switch to help - _
switch to outline_explorer - _
switch to editor - _
switch to historylog - _
switch to onlinehelp - _
switch to project_explorer - _
switch to ipython_console - _
switch to variable_explorer - _
switch to find_in_files - _
switch to explorer - _
switch to plots - _
find text - find_replace
find next - find_replace
find previous - find_replace
replace text - find_replace
inspect current object - editor
breakpoint - editor
conditional breakpoint - editor
run selection - editor
go to line - editor
go to previous file - editor
go to next file - editor
cycle to previous file - editor
cycle to next file - editor
new file - editor
open last closed - editor
open file - editor
save file - editor
save all - editor
save as - editor
close all - editor
last edit location - editor
previous cursor position - editor
next cursor position - editor
previous warning - editor
next warning - editor
zoom in 1 - editor
zoom in 2 - editor
zoom out - editor
zoom reset - editor
close file 1 - editor
close file 2 - editor
run cell - editor
run cell and advance - editor
debug cell - editor
go to next cell - editor
go to previous cell - editor
re-run last cell - editor
split vertically - editor
split horizontally - editor
close split panel - editor
switch to breakpoints - _
inspect current object - console
clear shell - console
clear line - console
run analysis - pylint
run profiler - profiler
new tab - ipython_console
reset namespace - ipython_console
restart kernel - ipython_console
copy - variable_explorer
copy - terminal
paste - terminal
new_term - terminal
clear - terminal

### What steps reproduce the problem?

1. Open the preferences > Keyboard Shortcuts

### What is the expected output? What do you see instead?
Have all the shortcuts in the table

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)

### Issue(s) Resolved

Fixes #12415

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
The plugin needs to call register shortcut for any shortcut to work properly. Is this the case @steff456 ?

**Comment by steff456** [comment]
I think so, the best way to prevent this type of issues is creating a migration guide for updating the third party plugins.

**Comment by goanpeca** [comment]
Ok indeed, they are not visible on the plugins. Let me make a fix @steff456 !

**Comment by goanpeca** [comment]
@steff456 please see -> https://github.com/spyder-ide/spyder/wiki/External-Plugins-Shortcut-definition-4.x

Those are the changes you need to make on the terminal plugin

**Pull request merged**
