### PR TITLE
PR: Fix close comm (IPython console)

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes
Close comm properly when the shutdown message is sent to the comm channel

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes https://github.com/spyder-ide/spyder/issues/15356
Removes "no such comm" messages
Depend on https://github.com/spyder-ide/spyder-kernels/pull/287

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for your help with this @impact27!

> Depend on spyder-ide/spyder-kernels#287

Please sync our subrepo with that PR then. That's necessary to check that our tests here don't fail due to that PR in spyder-kernels.

> Actually there is still the possibility of sending a message before getting the shutwdown message

Is it possible to handle that case in the future?

**Comment by impact27** [comment]
> Is it possible to handle that case in the future?

The problem is basically https://en.wikipedia.org/wiki/Two_Generals%27_Problem

But we could send a shutdown to the kernel, and expect an acknowledgment before removing the comm. I will think about that.

**Comment by impact27** [comment]
the failure doesn't appear to be related to this PR?

**Comment by ccordoba12** [comment]
> the failure doesn't appear to be related to this PR?

Right, I fixed it in PR #15483. I merged with `5.x` to see if our tests pass. After that, I'll test this on Windows.

**Review by ccordoba12 — APPROVED** [review]
Thanks a lot for your help with this bug @impact27!

I tested it on Windows and verified it fixes issue #15356.

**Pull request merged**
