### PR TITLE
WIP: Add fadeout to scroolbar

### LINKED ISSUE #12637: The right scroll bar is missing in Spyder 4 on MacOS 10.15
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
The scroll bar on the right hand side that shows overview of issues, highlighted items, etc... is missing in Spyder 4.1.2 and 4.x.x releases on MacOS 10.15.4

### What steps reproduce the problem?

1. I have tried to use "spyder --reset" no luck 
2. I have downgraded to 3.3.6 and it works

image

3. I have upgraded to 4.0.0, missing.

image

### What is the expected output? What do you see instead?
I am not seeing the scroll bar that I am used to on 3.x versions. Talked to @bcolsen and he suggested that I should open a bug at github.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
spyder                    4.1.2                    py37_0  
spyder-kernels            1.9.0                    py37_0  
* Python version: 
python                    3.7.3                h359304d_0  
python-chromedriver-binary 83.0.4103.14.0   py37hc8dfbb8_0    conda-forge
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.3.4                      py_0  
python-language-server    0.31.10                  py37_0  
python-libarchive-c       2.9                        py_0  
python.app                2                        py37_9  
python_abi                3.7                     1_cp37m    conda-forge
* Qt version: 
qt                        5.9.7                h468cd18_1  
qtawesome                 0.7.0                      py_0  
qtconsole                 4.7.3                      py_0  
qtpy                      1.9.0                      py_0  
qt                        5.9.7                h468cd18_1  
qtawesome                 0.7.0                      py_0  
qtconsole                 4.7.3                      py_0  
qtpy                      1.9.0                      py_0  
* PyQt version: 
pyqt                      5.9.2            py37h655552a_2  
* Operating System name/version: 
MacOS 10.15.4

### Dependencies

```

# Mandatory:
applaunchservices >=0.1.7      :  0.2.1 (OK)
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.4.1 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.5.0 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.0.3 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  None (OK)
matplotlib >=2.0.0             :  None (OK)
numpy >=1.7                    :  None (OK)
pandas >=0.13.1                :  None (OK)
scipy >=0.17.0                 :  None (OK)
sympy >=0.7.3                  :  None (OK)
```

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #12637

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca 

maximize

### CODE REVIEW

**Comment by goanpeca** [comment]
@aosavas this is not ready but a preview of how this will work following the Mac HIC guidelines.

@impact27 I commented some code you wrote to optimize things for now while I get things fixed. 

On the Light Theme on Mac is that the ScrollFlagBar was not displaying the full contents of the file, but only the visible part. The code I commented for now makes sure the scrollFlagBar displays all the contents all the time

**Comment by aosavas** [comment]
Thank you!!!

**Comment by ccordoba12** [comment]
Hey @goanpeca, do you think this one could be ready for 4.1.4?

**Comment by goanpeca** [comment]
>do you think this one could be ready for 4.1.4?

I am working on this now, let's see how far I get.

**Comment by goanpeca** [comment]
I cannot longer reproduce this in the latest 4.x

**Comment by ccordoba12** [comment]
That's really weird because we've done nothing to fix it. @steff456, could you test if the bug reported on issue #12637 is no longer present in the latest 4.x?

**Comment by aosavas** [comment]
I can test it as well if it is ok with you and if you can provide me an
installation guide that would be great.

**Comment by steff456** [comment]
Hi, I just tested in the current 4.x branch and I can reproduce it. The errors are not shown in the right side of the editor.

image

**Comment by steff456** [comment]
@goanpeca I think that instead of adding a fadeout to the scrollbar we can add a transparency to the color in a way that the scrollbar is always shown in a lighter color and the error messages can be seen as well. For example,

image

In that way the scrollbar is always present and everything can be seen by the user (:

**Comment by ccordoba12** [comment]
That's a very good idea @steff456! What do you think @goanpeca?

**Comment by goanpeca** [comment]
Sure, go ahead @steff456. Closing this one, since I cannot reproduce it, I can't really work on this.

**Pull request closed without merging**
