### PR TITLE
PR: Improve compatibility with PySide2

### PR DESCRIPTION
**Pull request by rear1019**
## Description of Changes

Some patches to improve compatibility with PySide2 (not tested against PySide6).

A note regarding the commit “pyside2: Fix usage of “mode” keyword argument in QTextCursor.movePosition()”
* The fixed error is “silent” in PySide2 5.15.0 and 5.15.2.1. We never noticed it until so far.
* This could be patched globally by monkeypatching in the qtpy Module (so that all users of qtpy benefit)

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

rear1019

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @rear1019, thanks a lot for your continued contributions to improve our PySide2 support. In order to include your work in our next release (5.3.1), please make your branch to derive from our `5.x` one (instead of master), with the following commands:

    git checkout 5.x
    git checkout pyside_fixes4
    git rebase --onto 5.x master pyside_fixes4
    git push -f origin pyside_fixes4

Also, about this:

> This could be patched globally by monkeypatching in the qtpy Module (so that all users of qtpy benefit)

Could you submit a PR to Qtpy, so we can include it on its next version (2.1.0), to be released soon?

**Comment by rear1019** [comment]
> Hey @rear1019, thanks a lot for your continued contributions to improve our PySide2 support. In order to include your work in our next version (5.3.1), please make your branch to derive from our `5.x` one (instead of master), with the following commands:
> […]

Done. Note that the target branch for the merge is still `master`. Please let me know if this should be changed to `5.x` as well.

> Also, about this:
> 
> > This could be patched globally by monkeypatching in the qtpy Module (so that all users of qtpy benefit)
> 
> Could you submit a PR to Qtpy, so we can include it in its next version (2.1.0), to be released soon?

See https://github.com/spyder-ide/qtpy/pull/341

**Comment by ccordoba12** [comment]
> Done. Note that the target branch for the merge is still master. Please let me know if this should be changed to 5.x as well.

Thanks! And yes, please change the target here on Github to be `5.x`.

> See https://github.com/spyder-ide/qtpy/pull/341

Thanks for that too! Then I think we should wait until that PR is merged and part of Qtpy 2.1.0, so we can drop here commit 
82c3a6f and depend on that Qtpy version.

What do you think?

**Comment by rear1019** [comment]
> > See [spyder-ide/qtpy#341](https://github.com/spyder-ide/qtpy/pull/341)
> 
> Thanks for that too! Then I think we should wait until that PR is merged and part of Qtpy 2.1.0, so we can drop here commit [82c3a6f](https://github.com/spyder-ide/spyder/commit/82c3a6fac236525ba97a11356b415e05dcc411bb) and depend on that version.
> 
> What do you think?

This should work :+1:. I will update this PR once https://github.com/spyder-ide/qtpy/pull/341 is merged.

**Comment by ccordoba12** [comment]
Thanks @dalthviz! But we need it in Qtpy 2.1.0, so that @rear1019 can replace commit 82c3a6f for a dependency on that version.

**Comment by rear1019** [comment]
Latest force push:
* Rebased against current `5.x`
* Updated QtPy dependency so that https://github.com/spyder-ide/qtpy/pull/341 is included

**Comment by ccordoba12** [comment]
@rear1019, you also need to update our required Qtpy version here:

https://github.com/spyder-ide/spyder/blob/34826d6fe89b2800da7cf7b659871b6e0072c3c3/spyder/dependencies.py#L65

**Pull request merged**
