### PR TITLE
PR: Implement replace in selection in the Editor

### PR DESCRIPTION
**Pull request by spillz**
Supports replacing all instances of the search text with the replace text in a selection of text. Changes find/replace dialog to add buttons for "replace in selection" and "replace all" and removes the "replace all" checkbox. Tweaks behavior of automatically filling the searchbox depending on whether multiple lines were selected.

A refinement would be to either add shortcuts for the three buttons or combine the three buttons into one and use radio/combo to control scope.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Please follow our [contributing guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md#changing-base-branch) to see how to change this PR from `master` to `3.x`, so we can merge it for 3.2.

@rlaverde, please review this one, given that you've been working on this.

**Comment by spillz** [comment]
Did I do this correctly? I had to do:

git rebase --onto origin/3.x origin/master spillz-replace-selection-patch

The instructions didn't mention the "origin" part. (Or the git push)

**Comment by ccordoba12** [comment]
Nop, sorry, your rebase didn't work as expected. @rlaverde, please help @spillz to do this rebase.

**Comment by spillz** [comment]
Why don't I just delete and resubmit?

**Comment by ccordoba12** [comment]
Sure, if you prefer that. Just make sure to create your branch after you checkout our 3.x branch.

Thanks for your patience!

**Comment by ccordoba12** [comment]
Closing in favor of #4638.

**Pull request closed without merging**
