### PR TITLE
PR: Resize plot when Plots pane is resized and "Fits plots to window" is checked.

### LINKED ISSUE #9368: Resizing plot panes does not resize the content
I suggest that when panes are resized the content adapts to the new size. This is not currently the case for the Plots pane

problem3

### PR DESCRIPTION
**Pull request by jnsebgosselin**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)
* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

scale_plot_when_resize

### Issue(s) Resolved

Fixes #9368

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Jean-Sébastien Gosselin

### CODE REVIEW

**Comment by goanpeca** [comment]
Thanks for working on this @jnsebgosselin. Let me know when this is ready for a review :-)

**Comment by ok97465** [comment]
This is a feature I need so much. Thank you. @jnsebgosselin @ccordoba12

**Comment by goanpeca** [comment]
Yeii, great work @jnsebgosselin thanks!

**Comment by jnsebgosselin** [comment]
Excellent!

**Pull request merged**
