### PR TITLE
PR: Change margins and sizes of buttons in toolbars

### PR DESCRIPTION
**Pull request by juanis2112**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

This is WIP on the work for changing margins and sizes of buttons in toolbars.
The first commit sets the size of buttons to 54px as specified:
Screenshot 2021-03-15 at 12 03 52 AM

### Issue(s) Resolved

Fixes #
https://github.com/spyder-ide/ux-improvements/issues/28

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
juanis2112

### CODE REVIEW

**Comment by juanis2112** [comment]
Here is a preview of what I have achieved till now on the margins/sizes of toolbars work. I would like your feedback to continue iterating on this @ccordoba12, @isabela-pf  and @steff456.

Screenshot 2021-03-16 at 11 29 55 PM

The specified icon sizes for main toolbar and pane toolbars are 24 and 16 respectively and those are already the values we are using in spyder so I didn't make any change regarding this.

Let me know if you feel comfortable with this sizes/spacing. As we discussed in the meeting, due to the "translation" between ems and pixels, they might not be 100% accurate but we can continue trying some more values till we fill more comfortable with them.

**Comment by isabela-pf** [comment]
To summarize what we discussed not on Github:
### Initial reaction
- The panes toolbars feel bigger than expected
- The margins around each button shouldn't be there
- Taking up more vertical space on the screen will make users unhappy

### What we tried
Making changes to 
- QToolbar padding
- QToolbutton size, borders, and margins
- The secret region/element between main and pane toolbars
- main_widget.py Layout section
 
### Changes we agreed on
- Make the QToolbutton size a little smaller. Try a minimum of 1.7em height and width
- Keep icons the same size within those buttons
- If we can't remove the top border/whatever that is fully, then make it as small as possible
- We are choosing to have buttons take up the the full toolbar regions without borders

### Questions we may not have answered
- Rounded or sharp hover state regions?

**Comment by juanis2112** [comment]
The last commit fixes the weird spacing in the find/replace combobox
Screenshot 2021-03-26 at 7 02 02 PM

**Review by ccordoba12 — APPROVED** [review]
This is finally ready! Thanks a lot for your help with it @juanis2112!

**Pull request merged**
