### PR TITLE
PR: Add PyQt5 to be a requirement in setup.py

### LINKED ISSUE #3242: Spyder is not installing the PyQt5 wheel when using pip
## Description of your problem

There are two problems. 
1. spyder.exe "doesn't work"
2. spyder.exe doesn't show anything and doesn't respond to options

**What steps will reproduce the problem?**
1. virtualenv v
2. v\Scripts\pip install --pre -U spyder
3. v\Scripts\spyder -h

**What is the expected output? What do you see instead?**

Expected to see help, but nothing happens at all.

**Please provide any additional information below**
## Versions and main components
- Spyder Version: 3.0.0b3
- Python Version: 2.7.11
- Operating system: Vista 32-bit
## Dependencies

Doesn't start to get those. `pip freeze`

```
alabaster==0.7.8
astroid==1.4.6
Babel==2.3.4
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.5.0.1
certifi==2016.2.28
colorama==0.3.7
configparser==3.5.0
decorator==4.0.10
docutils==0.12
entrypoints==0.2.2
functools32==3.2.3.post2
imagesize==0.7.1
ipykernel==4.3.1
ipython==5.0.0b4
ipython-genutils==0.1.0
jedi==0.9.0
Jinja2==2.8
jsonschema==2.5.1
jupyter-client==4.3.0
jupyter-core==4.1.0
lazy-object-proxy==1.2.2
MarkupSafe==0.23
mistune==0.7.2
nbconvert==4.2.0
nbformat==4.0.1
pathlib2==2.1.0
pep8==1.7.0
pickleshare==0.7.2
prompt-toolkit==1.0.3
psutil==4.3.0
pyflakes==1.2.3
Pygments==2.1.3
pylint==1.5.6
pytz==2016.4
pyzmq==15.2.0
QtAwesome==0.3.3
qtconsole==4.2.1
QtPy==1.0.2
rope==0.10.3
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.4.4
spyder==3.0.0b3
tornado==4.3
traitlets==4.2.1
wcwidth==0.1.6
win-unicode-console==0.4
wrapt==1.10.8
zmq==0.0.0
```

### PR DESCRIPTION
**Pull request by JakobJakobson**
Fixes #3242

The pull request #5822 is moved to the 3.x branch. 
Changes within the pull request are:
- addition of PyQt5 as a hard dependency
- some minor alphabetical code sorting

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for your contributiobn @JakobJakobson! I'll take a look at Travis to see why it's failing, then I'll merge.

**Comment by ccordoba12** [comment]
@JakobJakobson, thanks for your contribution! I'm going to ask you to revert all alphabetical reorderings you did because they can easily generate conflicts with other pull requests and they are not really necessary.

Thanks!

**Comment by JakobJakobson** [comment]
Superseded by #5862. (Sorry for all the inconvenience but I'm new to git and still figuring out.)

**Comment by ccordoba12** [comment]
Don't worry about, thanks for wanting to help us!

**Pull request closed without merging**
