### PR TITLE
PR: Make Spyder documentation keyboard shortcut configurable

### LINKED ISSUE #3818: F1 shortcut is hard-coded
## Description of your problem
Instead binding to Spyder documentation, I want to bind F1 to run.

**What steps will reproduce the problem?**

1. open keyboard shortcuts
2. rind run, bind to F1, apply, Ok.
3. restart

**What is the expected output? What do you see instead?**
Expected F1= run.
see F1= Spyder documentation. 

**Please provide any additional information below**

## Versions and main components

* Spyder Version:Spyder 3.0.2 
* Python Version:
* Operating system:
Python 3.5.2 64bits, Qt 5.7.0, PyQt5 5.7 on Darwin 

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

### PR DESCRIPTION
**Pull request by pwoosam**
Fixes #3818

Removed shortcut for opening spyder documentation from /app/mainwindow.py
Registered shortcut for opening spyder documentation in /app/mainwindow.py
Created default configuration for opening spyder documentaion in /config/main.py

### CODE REVIEW

**Comment by pwoosam** [comment]
I really hope I did this properly this time @ccordoba12 
Thanks for your patience; I've still got to learn more git!

**Comment by ccordoba12** [comment]
> Thanks for your patience; I've still got to learn more git!

No worries, you did just fine :-)

**Comment by ccordoba12** [comment]
There's a minor style error. Please check the CircleCI link below to see how to fix it.

**Comment by ccordoba12** [comment]
@goanpeca, ciocheck is hanging in this PR. Any ideas?

**Comment by goanpeca** [comment]
hanging?

**Comment by goanpeca** [comment]
@ccordoba12 nope

**Comment by goanpeca** [comment]
I think we could just run it on 2.7 or 3.5, cause it does not really make a difference. That could help?

**Comment by goanpeca** [comment]
It says
```
=======================
Ciocheck successful run
=======================
```

On 3.5 so if the PR is ok, I would just merge

**Comment by goanpeca** [comment]
Although, @pwoosam it would be definitely much better to rebase style commits into a single one.

**Comment by ccordoba12** [comment]
I don't understand why CircleCI doesn't finish correctly. I'll ping you when it fails again so you could see the results yourself.

**Comment by pwoosam** [comment]
Thanks @goanpeca, I did that 👍

**Comment by ccordoba12** [comment]
@goanpeca, please check CircleCI now. It always time out while running ciocheck (and not just for this PR :-)

**Comment by goanpeca** [comment]
I dont have time @ccordoba12. You can disbale it if its a problem.

**Comment by ccordoba12** [comment]
Please update with the latest changes in the 3.x branch to fix the errors in CircleCI

**Comment by ccordoba12** [comment]
Good job @pwoosam! And glad to have you on board both here and in spyder-vim :-)

**Pull request merged**
