### PR TITLE
PR: Install PyLS locally without modifying site-packages

### PR DESCRIPTION
**Pull request by andfoy**
## Description of Changes
This PR installs pyls on a external directory different to site-packages, by doing so, Spyder won't remove any user-installed pyls

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @andfoy

### CODE REVIEW

**Comment by jitseniesen** [comment]
@andfoy Can you please explain what this means for us, developers (or point to an existing description)? I never really understood all the magic that bootstrap.py is doing with pyls and spyder-kernels; I just know that it usually works, but sometimes it does not ...

**Comment by andfoy** [comment]
@jitseniesen, basically Spyder starts with its own development version of pyls, due to the difficulty and complexity of producing releases each time a critical feature/bug is introduced there (pyls is controlled by Palantir and we have limited permissions). So basically we have a local version of pyls independent of any other version that would exist on site-packages, which point to the latest develop/branch commit that we require on Spyder

**Comment by jitseniesen** [comment]
@andfoy Sounds good, thanks for the explanation!

**Comment by ccordoba12** [comment]
That's the big picture @jitseniesen. Regarding this PR, it changes the way we use the subrepo present in `external-deps/python-language-server` from `bootstrap.py` to **not** remove the current version present in site-packages and reinstall it again in development mode (which is the solution I came up with in PR #12389).

Instead, @andfoy found a brilliant solution: install that subrepo in development mode in a temporary directory and patch `sys.path` to use it (this and removing that temp dir after closing Spyder is handled by `bootstrap.py` now). That way we don't need to touch the PyLS version present in `site-packages` anymore, which won't break people's environments from now on.

**Pull request merged**
