### PR TITLE
Add keyboard shortcuts to context menu in editor

### PR DESCRIPTION
**Pull request by jitseniesen**
Before:
contextmenu-before

After:
contextmenu-after

### CODE REVIEW

**Comment by jitseniesen** [comment]
The second commit (b131781) is something that looked wrong, but as far as I know it does not make a difference, and I don't really understand what's going on.

**Comment by goanpeca** [comment]
Sweet :+1:, let me test on Mac and Win ;-)

**Comment by Nodd** [comment]
The indentation for all `create_action` calls doesn't follow pep8 at all, it may be a good time to correct it.

**Comment by goanpeca** [comment]
@nodd, you mean like:

```python
    def setup_context_menu(self):
        """Setup context menu"""
        self.undo_action = create_action(
            self,
            _("Undo"),
            icon=ima.icon('undo'),
            shortcut=get_shortcut('editor', 'undo'), 
            triggered=self.undo,
            )

**Comment by jitseniesen** [comment]
As I read pep8, you can also write
```
    def setup_context_menu(self):
        """Setup context menu"""
        self.undo_action = create_action(
            self, _("Undo"), icon=ima.icon('undo'),
            shortcut=get_shortcut('editor', 'undo'), triggered=self.undo)
```
But I guess most important is to be consistent as it looks annoyingly messy otherwise.

Anyway, I will make the change.

**Comment by Nodd** [comment]
Yes, either this or align after the opened parenthesis:
```python
    def setup_context_menu(self):
        """Setup context menu"""
        self.undo_action = create_action(self, _("Undo"),
                                         icon=ima.icon('undo'),
                                         shortcut=get_shortcut('editor', 'undo'), 
                                         triggered=self.undo,
                                         )
```
But I think the lines will be too long.

**Comment by goanpeca** [comment]
Yes @Nodd, that's why I think about that option (it is too long)

**Comment by ccordoba12** [comment]
Thanks @jitseniesen, this looks good to me ;-)

*Note*: The failure in our tests is related to CircleCI, whose support is unfinished. I stopped it for now to avoid further errors. I'll restart again after 3.0 is released.

**Pull request merged**
