### PR TITLE
Finish reorganization of the Spyder repo

### LINKED ISSUE #1320: Reorganize Spyder repository
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2013-03-17T03:48:24Z_

If I had to rewrite Spyder from scratch, I would probably start with the following outline:

    spyder/__init__.py
    spyder/conf.py
    spyder/app/spyder.py (and other modules)
    spyder/lib/baseconfig.py
    spyder/lib/utils/...
    spyder/lib/widgets/...

And of course it's not too late to do well...

See also those comments (motivation): https://code.google.com/p/spyderlib/source/detail?r=82bbf24ae1546470a09170c04743c28e585945ee

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1320_

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #1320

----

- This PR renames `spyderlib` to `spyder` (one of the main reasons of bumping our version to 3.0). Sorry for doing it so late, but there were many other things to do before this ;-)
- I'll merge it after all other important PRs are done.

Pinging @Nodd about it :-)

### CODE REVIEW

**Comment by goanpeca** [comment]
Better to get this merge soon, no?
anyway a rebase would be quite straightforward if only names changed, no?

**Comment by ccordoba12** [comment]
I prefer to leave this PR to be the last one because it's easier for me to handle updating it.

**Comment by ccordoba12** [comment]
Also pinging @picca and @ghisvail about this one.

**Comment by ccordoba12** [comment]
And @stonebig ;-)

**Comment by Nodd** [comment]
It's fine for me. I'll have to update every plugin once again.

**Comment by ccordoba12** [comment]
Yeah, sorry about it :-) Last major refactor before 3.0 final, promised!!

**Comment by stonebig** [comment]
I don't rely anymore on "\spyderlib" (at least I believe it), so you can proceed.

**Comment by ccordoba12** [comment]
Ok, this one is going in. Hopefully it won't cause too much disruption for the rest of our PRs :-)

Letting all @spyder-ide/core-developers know about it.

**Pull request merged**
