### PR TITLE
PR: Fix error in tutorial (Help)

### LINKED ISSUE #13417: Error in Spyder tutorial
### What steps will reproduce the problem?

Tools > Preferences > Editor > Code Introspection/Analysis

This was the old way of enabling pep 8 auto-correction. It is still currently written in the tutorial as such.

Tools > Preferences > Completion and linting > Code style

This is what should be written.

## Versions

* Spyder version: 4.1.4 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.4.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.5.0 (OK)
diff_match_patch >=20181111    :  20200713 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.16.1 (OK)
jedi =0.17.1                   :  0.17.1 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  1.1.0 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.7.0                   :  0.7.0 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=1.0                   :  2.4.4 (OK)
pyls >=0.34.0;<1.0.0           :  0.34.1 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.2 (OK)
qtconsole >=4.6.0              :  4.7.5 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.4 (OK)
sphinx >=0.6.6                 :  3.1.2 (OK)
spyder_kernels >=1.9.2;<1.10.0 :  1.9.2 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  19.0.1 (OK)

# Optional:
cython >=0.21                  :  0.29.21 (OK)
matplotlib >=2.0.0             :  3.2.2 (OK)
numpy >=1.7                    :  1.18.5 (OK)
pandas >=0.13.1                :  1.0.5 (OK)
scipy >=0.17.0                 :  1.5.0 (OK)
sympy >=0.7.3                  :  1.6.1 (OK)
```

### PR DESCRIPTION
**Pull request by aznpooface**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #13417.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by dalthviz** [comment]
Hi @aznpooface thanks for the contribution! Could be possible for you to rebase your work over our 4.x branch (to add it to the next release - Spyder 4.2.0)? you can do this by running from the local clone of your fork the following:
```
git checkout 4.x
git checkout patch-1
git rebase --onto 4.x master patch-1
git push -f origin patch-1
```
Let us know if that's possible of if you prefer to let this change to only be available for Spyder 5

Thanks again :)

**Comment by aznpooface** [comment]
I’m very new to programming, I don’t think I’ll be good to rely on for these things

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ccordoba12** [comment]
@dalthviz, please help @aznpooface to move this PR's branch to our 4.x one so we can merge it.

**Comment by dalthviz** [comment]
Done @ccordoba12

**Pull request merged**
