### PR TITLE
PR: Add Github action to close duplicate issues

### PR DESCRIPTION
**Pull request by goanpeca**
This adds the action to handle duplicates and add a label.

Any thoughts @ccordoba12 ?

### CODE REVIEW

**Comment by ccordoba12** [comment]
Do we need a different repo per action? I mean, can't we have multiple actions in a single repo?

**Comment by ccordoba12** [comment]
Also, can we add more patterns to close duplicates?

**Comment by goanpeca** [comment]
>Do we need a different repo per action? I mean, can't we have multiple actions in a single repo?

If we want to share them with "the world" or other repos we need to have it like that.

>Also, can we add more patterns to close duplicates?

Sure

**Comment by ccordoba12** [comment]
The error reported on issue https://github.com/spyder-ide/spyder/issues/11086 is still reported a lot. Please add it to the list.

**Comment by goanpeca** [comment]
Will do!

**Pull request merged**
