### PR TITLE
[WIP] PR: Update icons using a threadpool in File Explorer

### LINKED ISSUE #10081: Opening a folder with many files causes spyder to freeze
### What steps will reproduce the problem?

When opening a folder with many (think 1000 and upwards) files in the 'files' pane causes Spyder to completely freeze until loading is completed. While it appears that it does eventually come back to life after loading is completed, many times Windows will tell you the program is frozen and ask whether you want to wait or force quit during the process. For folders with larger amounts of files the waiting time is longer.

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.1
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  None (NOK)
qtconsole >=4.5.2 :  4.5.3 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Change the way we set file icons to prevent GUI freezing

### Issue(s) Resolved

Fixes #10081 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @dalthviz remember to test this issue by commenting all the `IconProvider` code to check if we are specifically introducing a problem with it.

**Comment by dalthviz** [comment]
@goanpeca it can freeze even without the IconProvider (although just for some seconds and I have to do the scrolling quite quickly):

ee

**Comment by ccordoba12** [comment]
@dalthviz, do these freezes happen in Spyder 3?

**Comment by dalthviz** [comment]
@ccordoba12 Spyder 3 can freeze, although just when adding a lot of files to the directory you are viewing:

s3

**Comment by ccordoba12** [comment]
Closing because this solution doesn't really solve the problem.

**Pull request closed without merging**
