### PR TITLE
PR: Fix a few typos in the FR locale file

### PR DESCRIPTION
**Pull request by afvincent**
*Superseeds #4446, targetting the right branch this time :sheep:.*

Some fixes for the French locale of Spyder. Mainly:

* échèle <- échelle (“scale”)
* barre d'outil <- barre d'outils (plural form on “tools”)
* miscellaneous typos like missing ending "s" for some plural forms, weird phrasing, fixes to follow French typography rules, etc.
* translation of a couple of missing messages

*Disclaimer*
I am a French native speaker from France: if some of the modified phrasings were correct Canadian (or elsewhere) French idioms, please let me know and I will be glad to revert the modifications.

Unfortunately, I do not currently have time to check the thousands of lines in the locale file. Hopefully I will be able to have a further look in the future if nobody else does it before.

**Edit:**
Ugh, definitively I am not an expert of the GitHub editor yet… I apologize for the super long commit message, I thought it was the PR message instead.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@afvincent, thanks a lot for moving your PR to 3.x!!

Could we ping you to help us with our French translation once new versions are about to be released?

----

Merging because the failures in Circle and Travis are unrelated to this work and they were fixed yesterday.

**Comment by afvincent** [comment]
@ccordoba12 You're welcome.  About keeping up-to-date or improving the French translation, sure you can ping me when needed, and I'll see what I can do about it.

**Comment by ccordoba12** [comment]
Ok, thanks a lot for your help!!

**Comment by goanpeca** [comment]
Thanks @afvincent for the help :-), we added you to https://github.com/spyder-ide/spyder/wiki/Dev:-Translations

**Pull request merged**
