### PR TITLE
PR: Change the way %(date)s and %(username)s are dealt with in the template.py

### LINKED ISSUE #6379: change the way dealing with %(date)s and %(username)s in the template.py
# maybe we should only replace placeholder between the tripe-double-quotes（“”“...”“”）
# if u use this template.py
```python
# -*- coding: utf-8 -*-
"""
Created on %(date)s

Creator: yourname
"""
from logging import debug as LD
from logging import info as LI
import logging as log
log.basicConfig(level=log.DEBUG,
               format='%(levelname)s|%(funcName)s|line:%(lineno)d - %(message)s')
log.disable(log.DEBUG)
#log.disable(log.CRITICAL)
```
# u will get this
```python
# -*- coding: utf-8 -*-
"""
Created on %(date)s

Creator: yourname
"""
from logging import debug as LD
from logging import info as LI
import logging as log
log.basicConfig(level=log.DEBUG,
               format='%(levelname)s|%(funcName)s|line:%(lineno)d - %(message)s')
log.disable(log.DEBUG)
#log.disable(log.CRITICAL)
```
# but of course we r expecting this
```python
# -*- coding: utf-8 -*-
"""
Created on 2018-2-4

Creator: yourname
"""
from logging import debug as LD
from logging import info as LI
import logging as log
log.basicConfig(level=log.DEBUG,
               format='%(levelname)s|%(funcName)s|line:%(lineno)d - %(message)s')
log.disable(log.DEBUG)
#log.disable(log.CRITICAL)
```
# the %(date)s has not been replaced properly because there is more placeholder

> format='%(levelname)s|%(funcName)s|line:%(lineno)d - %(message)s')

# in this template.py
# in the code dealing with template.py
spyder
# if we take the part between tripe-double-quotes seperately and deal with it seperately we can replace %(date)s properly no matter what a man add in template.py
# i edit the edior.py as following,and it worked.
```python
        if text is None:
            default_content = True
            text, enc = encoding.read(self.TEMPLATE_PATH)
            enc_match = re.search('-*- coding: ?([a-z0-9A-Z\-]*) -*-', text)
            annotation_match = re.search('"""(?:(?!""").|[\n\r])*"""', text)
            if enc_match:
                enc = enc_match.group(1)
            # Initialize template variables
            # Windows
            username = encoding.to_unicode_from_fs(os.environ.get('USERNAME',
                                                                  ''))
            # Linux, Mac OS X
            if not username:
                username = encoding.to_unicode_from_fs(os.environ.get('USER',
                                                                      '-'))
            VARS = {
                'date': time.strftime("%Y-%m-%d %H:%M"),
                'username': username,
            }
            try:
                #text = text % VARS
                text = re.sub('"""(?:(?!""").|[\n\r])*"""',
                              annotation_match[0] % VARS,
                              text,
                              count=1)
            except:
                pass
```

### PR DESCRIPTION
**Pull request by chengtian5huang**
Fixes #6379

Take the part between tripe-double-quotes separately and deal with it separately we can replace %(date)s properly no matter what a man add in `template.py`

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for your contribution. There can be several triple quote sections in a template. How does your code deal with that?

**Comment by chengtian5huang** [comment]
improved my code now, it can handle all cases i hope.

to anwser ccordoba12's question:
> if there are several triple quote sections in a template, it will check and check only(leave along other part of template) every section to replace vaild placeholder in the pre-set VARS.

and i have to change the name of these placeholders(eg change "date" to "date-spyder") in order to avoide over-replacing.

# i describe in detail how it work under all cases as following:(skip this if u r not interested)
following "invaild"s means spyder DONT know how to replace it.to be specific:it is NOT in the VARS dict.
following "vaild"s means spyder know how to replace it.to be specific:it is in the VARS dict.
default
## this problem can be divided into following cases

* there is no invaild placeholder in the template.

> replace them all, of course.

* there are invaild placeholder in the template but all of them are in the outside of triple quote sections(no matter how many)

> ignore these placeholders, they will remain the same

* there are invaild placeholder in the template but all of them are in triple quote sections(no matter how many)

> the triple quote sections which contain and contain only vaild placeholder will be dealt properly. **all placeholders in them will be replaced**.
> the triple quote sections which contain invaild placeholder will be ignore. **any of these placeholders wont be replaced.**

* there are invaild placeholder in the template but some of them are in triple quote sections(no matter how many), some of them are in the outside of triple quote sections(no matter how many).

> only triple quote sections which contain and contain only vaild placeholders **will be replaced**. 
> the placeholder in the outside of triple quote sections **wont be replaced**.
> all triple quote sections contain any invaild placeholders will be **remain the same**.

**Comment by chengtian5huang** [comment]
@CAM-Gerlach 
i put whole thing into new().
i dont know what do u mean by "**simple tests**".  i cant use simple tests to deal with these.
only when
 ```python 
text = text % VARS
```
raise an exception i am able to know there is user-specified(which is invaild to spyder) placeholder.
the simpler way i can see is go down templete.py line by line.
```python
    try:
        text = text % VARS
    except (KeyError,TypeError) as err:
        text = text.split('\n') # if Macintosh, use \r
        for i,line in enumerate(text):
            try:
                text[i] = line % VARS
            except:
                pass
```

**Comment by CAM-Gerlach** [comment]
Sorry, but I think we've had a major misunderstanding here. Please see my review comment for more on that specifically.

> i put whole thing into new().

Umm, what? Where exactly did I ever suggest you do this? It is better design to keep it separate as a helper function as you had it originally, so I have no idea what you thought it should be changed.

> i dont know what do u mean by "simple tests". i cant use simple tests to deal with these.

I mean unit tests for your code, not anything to do with the program logic you've already written. As you seemed to have an understanding of various cases and how it should handle them, I figured it wouldn't be too difficult to write a few of them into proper tests. At the very least, testing your helper function should be easy to do. If you don't know what unit tests are, I suggest you at least make yourself familiar with them as they are a huge part of programming nowadays; ``pytest`` makes them very easy to write without a lot of extra baggage that other frameworks have.

> only when  ``text = text % VARS`` raise an exception i am able to know there is user-specified(which is invaild to spyder) placeholder. **the simpler way i can see is go down templete.py line by line.**

Not 100% sure what you're proposing nor why, but it seems clear it has nothing to do with what I requested, which were only minor changes and adding tests that had nothing to do with the core logic.

**Comment by chengtian5huang** [comment]
truly sorry for inconvenience.
i will commit one with unit tests added later.

**Comment by CAM-Gerlach** [comment]
> i will commit one with unit tests added later.

Thanks

**Comment by CAM-Gerlach** [comment]
@chengtian5huang Hey, any updates?

**Comment by ccordoba12** [comment]
I'm closing this one. I don't understand very well what it tries to fix or improve, sorry.

**Pull request closed without merging**
