### PR TITLE
PR: Update translation files

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

Update pot files

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by bnavigator** [comment]
I don't know what you did, but my changes submitted to Crowdin as discussed in #11977 and appearing in #11825 did not make it into this update. In contrast, #11982 is in there.

**Comment by ccordoba12** [comment]
We haven't merged the Crowdin changes yet. This just updated the po files with new strings.

Look, we know what we're doing. Please just keep using Crowdin.

**Comment by ccordoba12** [comment]
The problem is Crowdin takes some time to update the files registered there after we update them here.

So the new strings will show up there in a few hours.

**Comment by bnavigator** [comment]
See #12091

**Pull request merged**
