### PR TITLE
PR: Allow underscore to be valid for Enter in File Switcher

### LINKED ISSUE #3575: Cannot press Enter after underscore in File Switcher
## Description of your problem

**What steps will reproduce the problem?**

1. Open a file with a `_` (underscore) character in the file name, e.g. `test_dataframeeditor.py`
2. Open the File Switcher (Ctrl-P)
3. Type `_`. The file name with the underscore character is selected.
4. Press Enter to switch to that file.
5. Nothing happens. The File Switcher does not close.

**What is the expected output? What do you see instead?**

Normally, when you press Enter, the File Switcher closes and the editor switches to the tab with the selected file. For some reason, this does not happen if the text typed into the File Switcher ends with an underscore.

## Versions and main components

* Spyder Version: 3.0.1
* Python Version: 3.5.2
* Operating system: Linux

## Dependencies

```
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)
```

### PR DESCRIPTION
**Pull request by dalthviz**
Fixes #3575

### CODE REVIEW

**Comment by dalthviz** [comment]
The problem was that the regex to validate the line number filter wasn´t taking into account the underscore symbol, so the signal wouldn´t be emitted.

**Comment by goanpeca** [comment]
LGTM :-0

**Comment by ccordoba12** [comment]
Nice!! Thanks @dalthviz :-)

**Comment by dalthviz** [comment]
You're welcome 👍

**Pull request merged**
