### PR TITLE
ENH: Allow develop install mode

### PR DESCRIPTION
**Pull request by Eric89GXL**
Small enhancement that allows doing:
```
python setup.py develop
```
In this mode, any local changes are immediately reflected on next launch without having to modify paths, which is nice.

### CODE REVIEW

**Comment by goanpeca** [comment]
@Eric89GXL thanks, we are moving over to setup tools soon :-)

**Comment by Eric89GXL** [comment]
This might make a decent stop-gap measure for other devs before full migration. I don't *think* it should cause any problems to have it. And it the meantime, it's still an optional component. But if you prefer to wait for a more complete solution, feel free to close.

**Comment by goanpeca** [comment]
Sure, @ccordoba12 is working on that so it will be his call :-)

**Comment by ccordoba12** [comment]
@Eric89GXL, but we always have used `bootstrap.py` for this kind of purpose. Isn't that enough?

**Comment by Eric89GXL** [comment]
What is the procedure for using `bootstrap`? I'm not familiar with it. It's not a standard thing AFAIK, which is one knock against it.

By contrast, doing `python setup.py develop` is standard across many repos. And once you do it, you can launch Spyder normally as `spyder` from any terminal, and it will use the currently checked out version. But maybe it is missing some magic that `bootstrap` otherwise takes care of...?

**Comment by Nodd** [comment]
I think that the feature itself is nice, develop install is quite handy. I wouldn't personally use it for spyder though because I'd like to keep a working version just in case...
Still I'm afraid that using both distutils and setuptools can lead to conflicts in some corner case, so I'd prefer to wait for the real switch to setuptools.

**Comment by Eric89GXL** [comment]
@Nodd in my experience many packages use `import setuptools`, at least in certain cases / for certain commands (numpy, scikit-learn, etc.) so I think it's pretty safe. I'll go ahead and close, though, since it sounds like people are more comfortable with the full-switch solution.

**Comment by Eric89GXL** [comment]
It has been about 9 months without a `setuptools` transition. Any interest in putting this in in the meantime, given that the full `setuptools` transition might not be a high priority?

**Comment by ccordoba12** [comment]
We did the transition, but only for wheels (please take a look at our setup.py).

I think you could also use setuptools for `develop`, but given our preference for using our `bootstrap.py` script, I think there will be little interest about it.

**Pull request closed without merging**
