### PR TITLE
PR: URL awareness improvements

### LINKED ISSUE #9513: Improvements to URL awareness
* Make URLs work with `%20`.
* Remove the requirement of `mailto:`
* Make `{gh/bb/gl}-123` work.

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

- [x] Make URLs work with %20.
- [x] Remove the requirement of mailto:
- [x] Make `{gh/bb/gl}-123` work.

### Issue(s) Resolved

Fixes #9513

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
@rgommers for the shorthand notation

`gh-123` this will only work if we are cloning from the actual repo and not from the fork (like many projects follow) 

So I can ask git for this
`$ git config --get remote.origin.url`

And use the output to get the repo, but if the repo is a fork we may or may not have the `upstream` remote set. Thoughts no this?

**Comment by rgommers** [comment]
Oh yeah, having to check for the parent repo via the GitHub API would work but that's a weird design. The standard convention is that the parent is named `upstream`, but it's not always the case. I think the choice is between using `upstream` if it exists, or just forgetting about this.

**Comment by ccordoba12** [comment]
> The standard convention is that the parent is named upstream, but it's not always the case. I think the choice is between using upstream if it exists, or just forgetting about this.

I agree with this. Let's try to detect `upstream` using git locally and then use it for as the main URL for all `{gh/bb/gl}-123` kind of references.

**Comment by goanpeca** [comment]
The following dialog is displayed if `gh-123` is clicked on a file that is not being tracked by git or if there is no upstream, or no origin

**Comment by ccordoba12** [comment]
> The following dialog is displayed if gh-123 is clicked on a file that is not being tracked by git or if there is no upstream, or no origin

I agree with ti, thanks for adding it.

**Pull request merged**
