### PR TITLE
Fix runfile argument parsing error by using shlex

### LINKED ISSUE #2010: runfile arguments with spaces
_From [oth...@gmail.com](https://code.google.com/u/104424612751893720965/) on 2014-10-16T17:12:04Z_

What steps will reproduce the problem?

 1. I have a program that I run that takes a path as a command line option, but the path contains spaces, the Spyder runfile (atleast I think runfile is from spyder as I cannot find it in other python packages) see to not allow for this and my argparser sees the path as multiple args no matter how I escape it

eg:
runfile('temp.py', args='\"./path to files/\"', ...
...error: unrecognized arguments: to files/...
(the same happens if I escape the args or not)

After looking here and on google I cannot find a similar bug report

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=2010_

### PR DESCRIPTION
**Pull request by kapinga**
Changed `sitecustomize.runfile()` to parse arguments using `shlex` instead of `string.split()`. This allows users to run scripts with arguments containing escaped spaces in ipython.

Fixes #2010

### CODE REVIEW

**Comment by ccordoba12** [comment]
I'm fixing the tests in Appveyor. The failure is unrelated to your work.

Please don't do more merges with master :-)

**Comment by ccordoba12** [comment]
I think I fixed the errors in AppVeyor, so please merge again with `master` now :-)

**Comment by kapinga** [comment]
Sorry about that. I did another merge with `master`, but won't do that to you in future commits.

**Comment by ccordoba12** [comment]
@kapinga, don't worry about it, It's fine what you did. I just wanted to warn you so you wait me until I fixed our (irritating) AppVeyor issues :-)

We're very new in this business of continuous integration, so we are still fixing things here and there :-)

**Comment by ccordoba12** [comment]
@kapinga, could you merge with master again so that your PR gets some fixes to Travis and Appveyor I pushed yersterday?

Thanks :-)

**Comment by kapinga** [comment]
@ccordoba12 I merged with `master` again and everything seems to have checked out.

**Comment by ccordoba12** [comment]
@kapinga, thanks a lot for your patience and for your contribution!

Merging because this seems very useful ;-)

**Pull request merged**
