### PR TITLE
PR: Prevent some plugins from being disabled

### PR DESCRIPTION
**Pull request by steff456**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

This PR prevents the following plugins from being disabled: 

- Layout
- Main interpreter
- Main menu
- Preferences
- Shortcuts
- Status bar
- Working directory
- Toolbar

The decision was mainly because these set of plugins shouldn't be disabled since they form part of the core of the application.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Steff456

### CODE REVIEW

**Review by ccordoba12 — COMMENTED** [review]
Thanks @steff456 for this! My comments:

* Why Shortcuts, the Working directory, Status bar and Toolbar plugins can't be disabled? I disable them successfully on my tests on #16409.
* Please don't allow the Internal console to be disabled. That's required because it's the default plugin against which any dockable plugin is docked in case it doesn't declare where it wants to be placed.
* As part of this PR, please remove the option to disable `Completion and linting` from its preferences page:

    imagen

* If we agree that the Status bar can be disabled, this option needs to be removed too

    imagen

**Comment by steff456** [comment]
Given our meeting, we decided to avoid disabling Shortcuts, Working directory and Toolbar plugins because it may not have sense to the Spyder interface. 

The last two commits:
- Added the internal console and plugin that cannot be disabled
- Preferences options were removed from the completion and linting page. 
- Statusbar plugin can be disabled in order to remove the `show status bar` option from the Statusbar's preferences page.

**Review by ccordoba12 — COMMENTED** [review]
Thanks @steff456! Looks good to me now.

Please merge with `5.x` to get the latest fixes to our tests, then this should be ready.

**Review by ccordoba12 — APPROVED** [review]
Thanks @steff456!

**Pull request merged**
