### PR TITLE
PR: Rename copy line and duplicate line shortcuts

### LINKED ISSUE #11092: Copy line and duplicate line shortcuts are confusing
In my opinion, the `copy line` and `duplicate line` shortcuts are confusing. From the dosctrings in the source code, these shortcuts are defined as :

copy line :  Paste the duplicated text *before* the current line/selected text
duplicate line: Paste the duplicated text *after* the current line/selected text

I think that "copy" and "duplicate" do not imply that the text is copied either up or down or below or after. I think it would be clearer if, as in vscode for example, we refer to these shortcuts as:

- `Copy line down` and `Copy line up` or
- `Copy line above` and `Copy line below` or
- `Duplicate line down` and `Duplicate line up` or
- `Duplicate line above` and `Duplicate line below`

https://vscode-docs.readthedocs.io/en/stable/customization/keybindings/

image

### PR DESCRIPTION
**Pull request by jnsebgosselin**
## Description of Changes

image

### Issue(s) Resolved

Fixes #11092

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Jean-Sébastien Gosselin

### CODE REVIEW

**Comment by jnsebgosselin** [comment]
Could Issue https://github.com/spyder-ide/spyder/issues/2905 be taken care here also?

**Comment by bcolsen** [comment]
This is a great change! I would suggest "duplicate above and below" as duplicate means copy and then paste which is what is happening here.

**Comment by jnsebgosselin** [comment]
> 
> 
> This is a great change! I would suggest "duplicate above and below" as duplicate means copy and then paste which is what is happening here.

I agree with you. 

@ccordoba12 @goanpeca Since the changes I'm proposing here are based on what is done in vscode, are you ok if I replace 'copy' by 'duplicate'?

**Comment by goanpeca** [comment]
I agree!

**Comment by ccordoba12** [comment]
+1 from me too.

**Comment by ccordoba12** [comment]
@jnsebgosselin, could you finish this one so we can merge it? Thanks!

**Comment by jnsebgosselin** [comment]
@ccordoba12 I think this PR was complete. It was only missing a review or am I missing something?

**Comment by ccordoba12** [comment]
Sorry @jnsebgosselin, I meant that this PR had a merge conflict and I couldn't merge it due to that. However, it was really easy to solve, so I did it through the web interface.

**Comment by jnsebgosselin** [comment]
> 
> 
> Sorry @jnsebgosselin, I meant that this PR had a merge conflict and I couldn't merge it due to that. However, it was really easy to solve, so I did it through the web interface.

Ah, I understand. Thank you very much!

**Pull request merged**
