### PR TITLE
PR: Migrate Explorer plugin to new API

### LINKED ISSUE #12195: Move Explorer/Projects plugin to use new API
- [ ] Move to new API
- [ ] Ensure tests pass

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #12195

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
This one is also ready for QA, when you have some time @dalthviz. Thanks :-)

**Comment by goanpeca** [comment]
>Seems like some tabs are being added in a corner of the preferences dialog (I think is probably the same tabs that are being added in the Files section):

Ahh yes, I know how to fix it :-) 

>If you have the single click enable, a right click opens the file instead of just showing the context menu (I don't know if that's intended but if you right click some thing like an image, the image will open externally and don't let you use the context menu):

Hmmm Sounds like a bug.

>You don't have access to the context menu from empty folders.

You mean right-clicking an empty folder @dalthviz ?

Thanks again for the review!

**Comment by dalthviz** [comment]
>You mean right-clicking an empty folder @dalthviz ?

More like entering inside a folder without any element and then right clicking inside it:
explorer1

**Comment by goanpeca** [comment]
>More like entering inside a folder without any element and then right clicking inside it:

I see @dalthviz, if this is present in Spyder 4 as well, then I think it should be fixed in there too. Could you please open an issue for it?

**Comment by goanpeca** [comment]
>If you have the single click enable, a right click opens the file instead of just showing the context menu (I don't know if that's intended but if you right click some thing like an image, the image will open externally and don't let you use the context menu):

@dalthviz I cannot reproduce this on Mac, @ccordoba12 can you reproduce this on Linux? Could it be a windows only issue?

**Comment by goanpeca** [comment]
>More like entering inside a folder without any element and then right clicking inside it:

@dalthviz I cannot reproduce it. Maybe a Windows only issue? @ccordoba12 could you check this on Linux?

Screen Shot 2020-06-11 at 22 50 00

**Comment by dalthviz** [comment]
>@dalthviz I cannot reproduce it. Maybe a Windows only issue? @ccordoba12 could you check this on Linux?

Maybe that's the case, will update the created issue with the Windows tag for now :+1:

**Comment by goanpeca** [comment]
This one is ready for review @ccordoba12

**Comment by goanpeca** [comment]
This is ready for review @ccordoba12

**Comment by dalthviz** [comment]
Just in case, seems like a merge/rebase needs to be done here @goanpeca

**Comment by goanpeca** [comment]
>Just in case, seems like a merge/rebase needs to be done here @goanpeca

Yes, will fix 👍

**Comment by goanpeca** [comment]
Ok this is werid :-|

**Comment by dalthviz** [comment]
The rebase failed? or there is some other reason to close this one?

**Comment by dalthviz** [comment]
Um now I see, I think I have a local copy of the branch (although I'm not sure how updated it is, should I try to force push to the remote to check if that helps?)

**Comment by goanpeca** [comment]
Yes please. Somethig went wrong with my rebase 🤷

**Comment by goanpeca** [comment]
The failing test seem to be some connectivity problem from the build machine.

```
Need to get 982 kB of archives.
After this operation, 3975 kB of additional disk space will be used.
Get:1 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-xfixes0 amd64 1.13-2~ubuntu18.04 [9352 B]
Err:2 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libegl-mesa0 amd64 19.2.8-0ubuntu0~18.04.3
  404  Not Found [IP: 52.177.174.250 80]
Get:3 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libegl1 amd64 1.0.0-2ubuntu2.3 [32.0 kB]
Get:4 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libegl1-mesa amd64 19.2.8-0ubuntu0~18.04.3 [6864 B]
Get:5 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-randr0 amd64 1.13-2~ubuntu18.04 [16.4 kB]
Get:6 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-randr0-dev amd64 1.13-2~ubuntu18.04 [20.4 kB]
Get:7 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-shape0-dev amd64 1.13-2~ubuntu18.04 [7144 B]
Get:8 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-xinerama0 amd64 1.13-2~ubuntu18.04 [5264 B]
Get:9 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-xinerama0-dev amd64 1.13-2~ubuntu18.04 [5944 B]
Get:10 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-xkb1 amd64 1.13-2~ubuntu18.04 [30.1 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-xkb-dev amd64 1.13-2~ubuntu18.04 [40.8 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-xtest0 amd64 1.13-2~ubuntu18.04 [4820 B]
Get:13 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxcb-xtest0-dev amd64 1.13-2~ubuntu18.04 [5224 B]
Get:14 http://azure.archive.ubuntu.com/ubuntu bionic-updates/main amd64 libxkbcommon-x11-0 amd64 0.8.2-1~ubuntu18.04.1 [13.4 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu bionic/main amd64 xbitmaps all 1.1.1-2 [28.1 kB]
Get:16 http://azure.archive.ubuntu.com/ubuntu bionic/universe amd64 xterm amd64 330-1ubuntu2 [661 kB]
Fetched 887 kB in 0s (11.0 MB/s)
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/m/mesa/libegl-mesa0_19.2.8-0ubuntu0~18.04.3_amd64.deb  404  Not Found [IP: 52.177.174.250 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
##[error]Process completed with exit code 100.
```

This is ready for review @ccordoba12 and is probably more important since the Projects API migration depends on this.

**Comment by ccordoba12** [comment]
I'm about to finish the Plots PR. Afterwards I'll continue with this one.

**Comment by goanpeca** [comment]
@dalthviz and @ccordoba12 this is ready for review. Failure is unrelated to the changes in this PR.

**Comment by ccordoba12** [comment]
Closing in favor of #14596.

**Pull request closed without merging**
