### PR TITLE
PR: Remove unused imports

### PR DESCRIPTION
**Pull request by oscargus**
## Description of Changes

Removed all unused imports I could find. (Except for utils.external.github which I didn't dare to touch.)

Any removed spaces are caused automatically.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Oscar Gustafsson/oscargus

### CODE REVIEW

**Comment by ccordoba12** [comment]
I'm sorry but I'm sure this will interfere with other PRs for no important gain. So I'll leave this to merge it in two or three weeks.

**Comment by oscargus** [comment]
No problems! Not really urgent, more that I find it a bit annoying with unused imports...

**Comment by ccordoba12** [comment]
Ok, thanks for understanding @oscargus!

**Comment by ccordoba12** [comment]
@oscargus, please update this PR so I can merge it. Thanks!

**Comment by ccordoba12** [comment]
@oscargus, I plan to release beta4 on July 31. Do you have time to finish this PR by then?

**Comment by oscargus** [comment]
New attempt in #9904 as I wasn't able to resolve all merge conflicts here and do not know how to start all over in the same branch...

**Pull request closed without merging**
