### PR TITLE
PR: Update Spyder's logo

### LINKED ISSUE #13181: Improve Spyder logo for Spyder 5
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Now that we have a UX/UI designer helping us in Spyder, one of our goals is to change the logo for Spyder 5.

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

### PR DESCRIPTION
**Pull request by isabela-pf**
## Description of Changes
This PR updates the logos in `img_src` to reflect the voting in [ux-improvements #50](https://github.com/spyder-ide/ux-improvements/issues/50) and discussion in #13181. This changes how the logo appears in Spyder itself, Spyder's application icons, and in the readme.

I've marked it as draft because there are still some images I haven't replaced as I try to figure out why they are separate files when some of them look the same visually.

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))
Screen Shot 2021-06-15 at 4 47 11 PM
Screen Shot 2021-06-15 at 4 42 01 PM
Screen Shot 2021-06-15 at 4 42 18 PM

### Issue(s) Resolved

Fixes #13181 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
isabela-pf

### CODE REVIEW

**Comment by isabela-pf** [comment]
Screenshots from binder after 69a0d1d
Screen Shot 2021-06-11 at 4 09 32 PM
Screen Shot 2021-06-11 at 4 10 04 PM
Screen Shot 2021-06-11 at 4 10 14 PM
Screen Shot 2021-06-11 at 4 10 49 PM

I'm definitely seeing less changes than I expected for changing eight files. On to the next experiment we go…  🧪

**Comment by isabela-pf** [comment]
eb13b89 and 79d3775 shows no changes! 😦 Fresh screenshots for proof: 
Screen Shot 2021-06-11 at 5 43 40 PM
Screen Shot 2021-06-11 at 5 44 10 PM
Screen Shot 2021-06-11 at 5 44 32 PM
Screen Shot 2021-06-11 at 5 44 47 PM

**Comment by isabela-pf** [comment]
Changes in the main `spyder/images` directory! Here's how that's looking.
Screen Shot 2021-06-15 at 4 41 30 PM
Screen Shot 2021-06-15 at 4 42 01 PM
Screen Shot 2021-06-15 at 4 42 18 PM

**Comment by isabela-pf** [comment]
Last commit just updated the SVG being used for the application icon. ✨ Huzzah!
Screen Shot 2021-06-15 at 4 47 11 PM

**Comment by isabela-pf** [comment]
I think I've made all the changes based on team feedback, so let me know if it looks like anything is still incorrect or missing.

**Review by steff456 — APPROVED** [review]

**Review by ccordoba12 — APPROVED** [review]
Thanks @isabela-pf!

**Comment by flying-sheep** [comment]
HI @isabela-pf, the logo version in this PR still contain the line I pointed out in https://github.com/spyder-ide/spyder/issues/13181#issuecomment-851931429. I interpreted your “:+1:” as agreement to change that detail, so I’m reminding you of it.

**Pull request merged**
