### PR TITLE
PR: Move dock attributes from plugin to dockwidget

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

This simplifies a bit the logic moving fowrard with the new API

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
Do we need this for Spyder 4?

**Comment by ccordoba12** [comment]
If so, why?

**Comment by goanpeca** [comment]
>If so, why?

We don't but it will make merging to 5 easier. I can move to master 🤷‍♂

**Comment by ccordoba12** [comment]
Ok, it's not a big deal. So we can leave it for Spyder 4 :+1:

**Pull request merged**
