### PR TITLE
PR: Improve how Matplotlib backend is set in the IPython console

### LINKED ISSUE #5541: Automatic graphics backend throws an error
## Description of your problem

If graphics backend for Ipython is set to "Automatic", ipython throws a ModuleNotFoundError for qt5 even if tkinter and/or GTK3 backend is installed.

**What steps will reproduce the problem?**

1. Tools -> Preferences ->IPython Console
2. Graphics tab
3. Set graphics backend to automatic

**What is the expected output? What do you see instead?**
Any code that generates graphics output should show output. Instead, there is not graphics output, only error message.

```
Traceback (most recent call last):

  File "<ipython-input-1-9701cca0214f>", line 1, in <module>
    runfile('/home/mukundan/nextcloud/documents/programming/python/misc/plot_test.py', wdir='/home/mukundan/nextcloud/documents/programming/python/misc')

  File "/usr/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/mukundan/nextcloud/documents/programming/python/misc/plot_test.py", line 9, in <module>
    import matplotlib.pyplot as plt

  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)

ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt5agg'
```

If I install matplotlib-qt5 and select automatic, I get this - 

```
 Traceback (most recent call last):

  File "<ipython-input-1-64557277dbff>", line 1, in <module>
    get_ipython().run_line_magic('matplotlib', 'qt5')

  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)

  File "<decorator-gen-107>", line 2, in matplotlib

  File "/usr/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)

  File "/usr/lib/python3.6/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)

  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2983, in enable_matplotlib
    self.enable_gui(gui)

  File "/usr/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 482, in enable_gui
    real_enable_gui(gui)

  File "/usr/lib/python3.6/site-packages/ipykernel/eventloops.py", line 284, in enable_gui
    raise RuntimeError("Cannot activate multiple GUI eventloops")

RuntimeError: Cannot activate multiple GUI eventloops
```
It seems like the tk (or other non qt) backend should be detected automatically but is not happening.

**Please provide any additional information below**
If I manually select the graphics backend (inline, qt5, gtk3, tkinter), everything works as expected. Only 'automatic' seems to fail.

## Versions and main components

* Spyder Version: 3.2.4 (same problem exists in 3.2.3 as well)
* Python Version: 3.6.3 (64-bit)
* Qt Version: 5.9.2
* PyQt Version: 5.9
* Operating system: Linux (Fedora 27 beta; problem also exists in Fedora 26).

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

```
IPython >=4.0    :  6.2.1 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
psutil >=0.3     :  5.2.2 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
rope >=0.9.4     :  None (NOK)
sphinx >=0.6.6   :  1.6.4 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
```

matplotlib-tk (python 3) is installed and works fine upon manual selection.
```
$ rpm -qa *matplotlib* | sort
python3-matplotlib-2.0.0-3.fc27.x86_64
python3-matplotlib-tk-2.0.0-3.fc27.x86_64
python-matplotlib-data-2.0.0-3.fc27.noarch
python-matplotlib-data-fonts-2.0.0-3.fc27.noarch
```

### LINKED ISSUE #5718: Problems with backend "TkAgg" on Linux
## Description of your problem
The TkAgg/Tkinter graphic backends behaves differently (one time it shows a plot, one time it shows a blank canvas) depending on the choice of the dialog
``` Preferences -> Run -> Console```

I ran into this issue by investigating the bug #5541 and I would be glad if you could give me hints for debugging.

**What steps will reproduce the problem?**

1.  Take the following script
```python
import matplotlib
print("matplotlib.get_backend(): " + matplotlib.get_backend())
import matplotlib.pyplot as plt
plt.plot([1, 2, 3])
plt.show()
```
2. Select the graphic backend as ```Tkinter``` via ```Preferences-> IPython Console -> Graphics -> Graphics -> Graphics backend```

3. Then test the two cases:
- a) run the script with the option ```Execute in external system terminal``` via ``` Preferences -> Run -> Console``` in the external system terminal. 
- b) run the script with the option ```Execute in current console``` via ``` Preferences -> Run -> Console``` in the current IPython console.

**What is the expected output? What do you see instead?**
In case A everything works fine (Screenshots "CaseA") 
casea_terminal
casea_plot

whereas case B gives me the following output on the console
```python
In [1]: runfile('~/untitled1.py', wdir='~')
matplotlib.get_backend(): TkAgg
```
and a blank canvas in the plot window.
caseb_plot
Also you can't close the plot window as it doesn't react on clicking.

**Please provide any additional information below**
It's an Fedora installation.

## Version and main components

* Spyder Version: 3.2.4 
* Python Version: 3.6.2
* Qt Versions: 4.8.7, PyQt4 (API v2) 4.12 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.1 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.2 (OK)
rope >=0.9.4     :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  5.3.0 (OK)
pylint >=0.25    :  1.7.4 (OK)

```

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #5718 
Fixes #5541

### CODE REVIEW

**Comment by JakobJakobson** [comment]
I tested your pull request (* Spyder Version: 3.2.5.dev0 afeb58173) and at startup of spyder I get the following message:

```python
Python 3.6.2 (default, Sep  1 2017, 12:03:48)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

NOTE: The following error appeared when setting your Matplotlib backend

Traceback (most recent call last):
  File "/home/ich/Kram/spyder/spyder/utils/ipython/spyder_kernel.py", line 439, in _set_mpl_backend
    get_ipython().run_line_magic('matplotlib', backend)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-107>", line 2, in matplotlib
  File "/usr/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/lib/python3.6/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2983, in enable_matplotlib
    self.enable_gui(gui)
  File "/usr/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 482, in enable_gui
    real_enable_gui(gui)
  File "/usr/lib/python3.6/site-packages/ipykernel/eventloops.py", line 284, in enable_gui
    raise RuntimeError("Cannot activate multiple GUI eventloops")
RuntimeError: Cannot activate multiple GUI eventloops
```

After that error I can use the IPython console but the attempt to plot still results in an empty canvas that does not react on mouse clicks.

**Comment by ccordoba12** [comment]
Right, this means things are working as expected. I mean, at least we are able to catch that error and show it to users.

This means you need to deactivate the `Activate support` option in

    Preferences > IPython console > Graphics

so that Matplotlib sets its backend by itself (i.e. without Spyder interference). That should fix your problem.

Could you verify it? Thanks!

**Comment by JakobJakobson** [comment]
If the ```Activate support``` is deactivated and matplotlib sets its backend by itself the plotting works. But under these conditions the plotting worked also before your pull request I have to admit.

Strangely however the installed backends have an influence on the behaviour of Spyder but I guess that I will discuss this with the Fedora mantainers.

**Comment by ccordoba12** [comment]
> If the Activate support is deactivated and matplotlib sets its backend by itself the plotting works. But under these conditions the plotting worked also before your pull request I have to admit.

Yeah, that's right. But after this PR we will be able to tell users that they need to deactivate our Graphics support, so that Matplotlib can do its job without us interfering on it.

For that, I'll catch the `RuntimeError` you posted and print a new message saying that instead.

> If I choose any other backend than TkAgg Spyder shows me the following message

That's part of this PR and just informs users that Spyder **can't** set a new backend if there's one in `matplotlibrc`. It's simply impossible because of the way Matplotlib is designed, and that was what I rant about on issue #5541.

> The installed backends have an influence on the plotting/importing of matplotlib in Spyder. But I will discuss that with the Fedora mantainers.

I think it's not exactly that, it's the fact that there's a default backend in `/etc/matplotlibrc`.

Could you comment the `backend` line in your `/etc/matplotlibrc` and see if Spyder can set your backend without problems?

**Comment by JakobJakobson** [comment]
Well there is a short and a long answer. 

## Short answer

> Could you comment the backend line in your /etc/matplotlibrc and see if Spyder can set your backend without problems?

The short answer is: yes, Spyder can set the backend but you obviously have set the interactive backend manually if you call matplotlib outside of spyder. The long answer follows at the bottom.

Given the scenario you write your plotting script in spyder and you commented your backend in ```/etc/matplotlibrc``` , you either don't set the graphics backend (as spyder does it for you) in your plotting script or you choose the one spyder uses (as otherwise you will run into problems). If you now switch to python3 console without the spyder context you have to insert the line ```matplotlib.use("XY")``` into your script. What would possibly break you compatibility if you switch to the spyder IDE again.
So I wouldn't take it as the most elegant solution to adapt your python scripts to each interpreter/IDE.

## Long answer
> > The installed backends have an influence on the plotting/importing of matplotlib in Spyder. But I will discuss that with the Fedora mantainers.

> I think it's not exactly that, it's the fact that there's a default backend in /etc/matplotlibrc.

Well, I think we have a bit of a misunderstanding here as I meant some different behaviour of Spyder. I have two test cases:

### Test case A
I commented the ```TkAgg``` backend in ```/etc/matplotlibrc``` and have the following backends installed:
```bash
$ dnf list *matplotlib*
python-matplotlib-data.noarch                   2.0.0-3.fc27             @fedora
python-matplotlib-data-fonts.noarch             2.0.0-3.fc27             @fedora
python2-matplotlib.x86_64                       2.0.0-3.fc27             @fedora
python2-matplotlib-doc.x86_64                   2.0.0-3.fc27             @fedora
python2-matplotlib-tk.x86_64                    2.0.0-3.fc27             @fedora
python3-matplotlib.x86_64                       2.0.0-3.fc27             @fedora
python3-matplotlib-gtk3.x86_64                  2.0.0-3.fc27             @fedora
python3-matplotlib-tk.x86_64                    2.0.0-3.fc27             @fedora
```
Testing only the different installed backends gives the following results:
- Inline: works without problems
- GTK3: works
- TkInter: works


### Test case B
I commented the ```TkAgg``` backend in ```/etc/matplotlibrc``` and have the following backends installed:
```bash
$dnf list *matplotlib*
python-matplotlib-data.noarch                   2.0.0-3.fc27             @fedora
python-matplotlib-data-fonts.noarch             2.0.0-3.fc27             @fedora
python3-matplotlib.x86_64                       2.0.0-3.fc27             @fedora
python3-matplotlib-gtk3.x86_64                  2.0.0-3.fc27             @fedora
python3-matplotlib-qt4.x86_64                   2.0.0-3.fc27             @fedora
python3-matplotlib-qt5.x86_64                   2.0.0-3.fc27             @fedora
python3-matplotlib-tk.x86_64                    2.0.0-3.fc27             @fedora
```
Testing only the different installed backends gives the following results:
- Inline: works
- Automatic:
```python
Python 3.6.2 (default, Sep  1 2017, 12:03:48)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

NOTE: The following error appeared when setting your Matplotlib backend

Traceback (most recent call last):
  File "/home/ich/Kram/spyder/spyder/utils/ipython/spyder_kernel.py", line 439, in _set_mpl_backend
    get_ipython().run_line_magic('matplotlib', backend)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-107>", line 2, in matplotlib
  File "/usr/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/lib/python3.6/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2978, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "/usr/lib/python3.6/site-packages/IPython/core/pylabtools.py", line 307, in activate_matplotlib
    import matplotlib.pyplot
  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 127, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class


In [1]: 
```

- Qt5:
```python
Python 3.6.2 (default, Sep  1 2017, 12:03:48)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

NOTE: The following error appeared when setting your Matplotlib backend

Traceback (most recent call last):
  File "/home/ich/Kram/spyder/spyder/utils/ipython/spyder_kernel.py", line 439, in _set_mpl_backend
    get_ipython().run_line_magic('matplotlib', backend)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-107>", line 2, in matplotlib
  File "/usr/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/lib/python3.6/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2983, in enable_matplotlib
    self.enable_gui(gui)
  File "/usr/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 482, in enable_gui
    real_enable_gui(gui)
  File "/usr/lib/python3.6/site-packages/ipykernel/eventloops.py", line 284, in enable_gui
    raise RuntimeError("Cannot activate multiple GUI eventloops")
RuntimeError: Cannot activate multiple GUI eventloops


In [1]: 
```

- QT4: Shows no graphic windows. (As running the plot files does nothing?)
```python
In [1]: runfile('/home/ich/.config/spyder-py3/temp.py', wdir='/home/ich/.config/spyder-py3')

In [2]: 
```

- Gtk3: It takes forever to connect to the IPython console, actually I never made it that far.
- TkInter:
```python
Python 3.6.2 (default, Sep  1 2017, 12:03:48)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

NOTE: The following error appeared when setting your Matplotlib backend

Traceback (most recent call last):
  File "/home/ich/Kram/spyder/spyder/utils/ipython/spyder_kernel.py", line 439, in _set_mpl_backend
    get_ipython().run_line_magic('matplotlib', backend)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-107>", line 2, in matplotlib
  File "/usr/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/lib/python3.6/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2983, in enable_matplotlib
    self.enable_gui(gui)
  File "/usr/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 482, in enable_gui
    real_enable_gui(gui)
  File "/usr/lib/python3.6/site-packages/ipykernel/eventloops.py", line 284, in enable_gui
    raise RuntimeError("Cannot activate multiple GUI eventloops")
RuntimeError: Cannot activate multiple GUI eventloops


In [1]
```

So what I meant was that the behaviour of Tkinter differs from test case A to test case B even though only the number of installed backends (and the included dependencies) is different in the two cases.
But from my point of view backend X shouldn't interfere with backend Y and that is what I meant when I said:
> The installed backends have an influence on the plotting/importing of matplotlib in Spyder. But I will discuss that with the Fedora mantainers.

Regards

**Comment by bcolsen** [comment]
I didn't fully look into this but it seem it might be useful here:

https://github.com/matplotlib/matplotlib/pull/9795

**Comment by ccordoba12** [comment]
@JakobJakobson, I think the problem is that you have both the PyQt4 and PyQt5 backends installed *and* you're using Spyder with PyQt4 (at least that's what you reported on issue #5718).

What happens if you remove the PyQt4 backend and use Spyder with PyQt5 instead?

**Comment by JakobJakobson** [comment]
Removing the PyQt4 backend and keeping the PyQt5 backend leaves me at the following situation:
```
[ich@localhost spyder]$ python3 bootstrap.py 
Executing Spyder from source checkout
WARNING: 3rd party Python exception hook is active: '<lambda>'
Revision afeb58173, Branch: test-pl5758
01. Patched sys.path with /home/ich/Kram/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 3.2.5.dev0
    [Python 3.6.2 64bits, Qt 5.9.1, PyQt5 5.9 on Linux]
04. Running Spyder
```

Choosing either the ```Automatic``` or the ```Qt5``` backend gives me the following message at startup
```
Python 3.6.2 (default, Sep  1 2017, 12:03:48)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

NOTE: The following error appeared when setting your Matplotlib backend

Traceback (most recent call last):
  File "/home/ich/Kram/spyder/spyder/utils/ipython/spyder_kernel.py", line 439, in _set_mpl_backend
    get_ipython().run_line_magic('matplotlib', backend)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-107>", line 2, in matplotlib
  File "/usr/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/lib/python3.6/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2983, in enable_matplotlib
    self.enable_gui(gui)
  File "/usr/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 482, in enable_gui
    real_enable_gui(gui)
  File "/usr/lib/python3.6/site-packages/ipykernel/eventloops.py", line 284, in enable_gui
    raise RuntimeError("Cannot activate multiple GUI eventloops")
RuntimeError: Cannot activate multiple GUI eventloops
```

**Comment by ccordoba12** [comment]
@JakobJakobson, please try your **Test Case B** again. I changed this PR's approach in my last commit to better inform users about this problem and what Matplotlib backend is going to be used in Spyder's consoles if one is already set.

**Comment by JakobJakobson** [comment]
Recapping the **Test Case B**:
The backend in ```/etc/matplotlibrc``` is commented, the ~/.config/matplotlib/ folder is empty, the following backends are installed
```
python-matplotlib-data.noarch                   2.0.0-3.fc27             @fedora
python-matplotlib-data-fonts.noarch             2.0.0-3.fc27             @fedora
python3-matplotlib.x86_64                       2.0.0-3.fc27             @fedora
python3-matplotlib-gtk3.x86_64                  2.0.0-3.fc27             @fedora
python3-matplotlib-qt4.x86_64                   2.0.0-3.fc27             @fedora
python3-matplotlib-qt5.x86_64                   2.0.0-3.fc27         
```
and I'm using the following Spyder configuration:
```
[ich@localhost spyder]$ python3 bootstrap.py 
Executing Spyder from source checkout
WARNING: 3rd party Python exception hook is active: '<lambda>'
Revision 8c6c7bf8c, Branch: test-pl5758
01. Patched sys.path with /home/ich/Kram/spyder
02. PyQt5 is detected, selecting
03. Imported Spyder 3.2.5.dev0
    [Python 3.6.2 64bits, Qt 5.9.1, PyQt5 5.9 on Linux]
04. Running Spyder
Bootstrap completed in 00:00:00.9894
```
and the following plotting file ```temp.py```
<details>

```
# -*- coding: utf-8 -*-
"""
Spyder Editor

This is a temporary script file.
"""

import matplotlib.pyplot 
matplotlib.pyplot.plot([1, 2, 3])
```

</details>

Using this configuration leads to the startup/plotting behaviour with the following backends:
- Automatic
```
Python 3.6.2 (default, Sep  1 2017, 12:03:48)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

NOTE: The following error appeared when setting your Matplotlib backend

Traceback (most recent call last):
  File "/home/ich/Kram/spyder/spyder/utils/ipython/spyder_kernel.py", line 436, in _set_mpl_backend
    get_ipython().run_line_magic('matplotlib', backend)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2095, in run_line_magic
    result = fn(*args,**kwargs)
  File "<decorator-gen-107>", line 2, in matplotlib
  File "/usr/lib/python3.6/site-packages/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/lib/python3.6/site-packages/IPython/core/magics/pylab.py", line 99, in matplotlib
    gui, backend = self.shell.enable_matplotlib(args.gui)
  File "/usr/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2978, in enable_matplotlib
    pt.activate_matplotlib(backend)
  File "/usr/lib/python3.6/site-packages/IPython/core/pylabtools.py", line 307, in activate_matplotlib
    import matplotlib.pyplot
  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 127, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class


In [1]: runfile('/home/ich/.config/spyder-py3/temp.py', wdir='/home/ich/.config/spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-1-70108edc084d>", line 1, in <module>
    runfile('/home/ich/.config/spyder-py3/temp.py', wdir='/home/ich/.config/spyder-py3')

  File "/home/ich/Kram/spyder/spyder/utils/site/sitecustomize.py", line 716, in runfile
    execfile(filename, namespace)

  File "/home/ich/Kram/spyder/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/ich/.config/spyder-py3/temp.py", line 8, in <module>
    import matplotlib.pyplot

  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/qt_compat.py", line 127, in <module>
    from PyQt5 import QtCore, QtGui, QtWidgets

RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class


In [2]: 

In [2]: 
```


- Qt5:
```
Python 3.6.2 (default, Sep  1 2017, 12:03:48)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

NOTE: Spyder *can't* set your selected Matplotlib backend because there is a previous backend already in use.

Your backend will be Qt5Agg

In [1]: runfile('/home/ich/.config/spyder-py3/temp.py', wdir='/home/ich/.config/spyder-py3')
Traceback (most recent call last):

  File "<ipython-input-1-70108edc084d>", line 1, in <module>
    runfile('/home/ich/.config/spyder-py3/temp.py', wdir='/home/ich/.config/spyder-py3')

  File "/home/ich/Kram/spyder/spyder/utils/site/sitecustomize.py", line 716, in runfile
    execfile(filename, namespace)

  File "/home/ich/Kram/spyder/spyder/utils/site/sitecustomize.py", line 101, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/ich/.config/spyder-py3/temp.py", line 9, in <module>
    matplotlib.pyplot.plot([1, 2, 3])

  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 3307, in plot
    ax = gca()

  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 950, in gca
    return gcf().gca(**kwargs)

  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 586, in gcf
    return figure()

  File "/usr/lib64/python3.6/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 44, in new_figure_manager
    return new_figure_manager_given_figure(num, thisFig)

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 51, in new_figure_manager_given_figure
    canvas = FigureCanvasQTAgg(figure)

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 242, in __init__
    super(FigureCanvasQTAgg, self).__init__(figure=figure)

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 66, in __init__
    super(FigureCanvasQTAggBase, self).__init__(figure=figure)

  File "/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_qt5.py", line 240, in __init__
    super(FigureCanvasQT, self).__init__(figure=figure)

TypeError: 'figure' is an unknown keyword argument


In [2]: 

In [2]: 
```

- Qt4: shows no plotting window
```
Python 3.6.2 (default, Sep  1 2017, 12:03:48)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

In [1]: runfile('/home/ich/.config/spyder-py3/temp.py', wdir='/home/ich/.config/spyder-py3')

In [2]: 
```

- Gtk3: Takes forever to connect
- Gtk: some further dependencies are not installed
- Tkinter: shows an unresponsive blank canvas 
```
Python 3.6.2 (default, Sep  1 2017, 12:03:48)
Type "copyright", "credits" or "license" for more information.

IPython 6.2.1 -- An enhanced Interactive Python.

NOTE: Spyder *can't* set your selected Matplotlib backend because there is a previous backend already in use.

Your backend will be TkAgg

In [1]: runfile('/home/ich/.config/spyder-py3/temp.py', wdir='/home/ich/.config/spyder-py3')

In [2]: 
```

**Comment by ccordoba12** [comment]
@JakobJakobson, I'm going to merge this one because it's an improvement and I'm not seeing the errors you reported in Ubuntu 17.04, so I think it's an issue exclusive to Fedora (as you already pointed out).

**Pull request merged**
