### PR TITLE
PR: Remove IPython kernels from the Python console and connect directly to them

### LINKED ISSUE #1053: New IPython Console handling both clients and kernels
_From [pierre.raybaut](https://code.google.com/u/pierre.raybaut/) on 2012-05-26T08:45:05Z_

Before being able to implement this plugin (which is an evolution of the "IPython Console" plugin introduced with issue #1050 in Spyder v2.2+), we have to implement the features described in blocked issues.

To avoid polluting too much this issue thread, let's add "child" issues to the "Blocked on" list only.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1053_

### LINKED ISSUE #1860: Don't show IPython kernels in the Python console by default
_From [contrebasse](https://code.google.com/u/contrebasse/) on 2014-06-20T02:59:24Z_

Spyder Version:  2.3.0rc (3802: rc376e27fb117 )
Python Version:  3.4.1
Qt Version    :  4.8.6, PySide 1.2.2 on Linux
pyflakes >=0.6.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  2.1.0 (OK)
pygments >=1.6  :  1.6 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
psutil >=0.3    :  2.1.1 (OK)
jedi >=0.8.0    :  None (NOK)
rope >=0.9.2    :  0.9.4-1 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.5 (OK)
pylint >=0.25   :  1.2.1 (OK) 

What steps will reproduce the problem?

 1. open spyder (I tried resetting the defaults)
2. Show the Console Tab 3. 

What is the expected output? What do you see instead?

 I expect to see one python console, but I also have an ipython kernel with the following text:

    NOTE: When using the `ipython kernel` entry point, Ctrl-C will not work.

    To exit, you will have to explicitly quit this process, by either sending
    "quit" from a client, or using Ctrl-\ in UNIX-like environments.

    To read more about this, see https://github.com/ipython/ipython/issues/2049 To connect another client to this kernel, use:
        --existing kernel-12934.json

Also, while the kernel is cloed if I type "quit" in the corresponding ipython console, if I stop the kernel manually with the topright button I still have to close the ipythonconsole and I can't quit the kernel directly.

So I have 2 problems:
- Why is the ipython kernel showing up in the python console tab ?
- Why can't I close the kernel once I killed it ?

Please provide any additional information below

.
I rarely use python interactively so I'm not used to the ipython console, these problems are very misleading for beginners.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1860_

### LINKED ISSUE #2696: Enter in the IPython console inserts new line instead of executing current line after kernel restart
Recently I updated my anaconda package, which installed

    ipython 4.0.0
    ipython-qtconsole 4.0.1
    spyder 2.3.6

After that, whenever I restart the ipython kernel in the qt-console (using `ctrl + .`), the console will not execute any command, e.g.:

    Python 2.7.10 |Anaconda 2.3.0 (64-bit)| (default, May 28 2015, 16:44:52) [MSC v.1500 64 bit (AMD64)]
    Type "copyright", "credits" or "license" for more information.

    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.
    %guiref   -> A brief reference about the graphical user interface.

    In [1]: 1
       ...: 

I cannot reproduce this behavior when running ipython-qtconsole outside spyder, i.e. it works as expected. My current workaround ist closing the console, thus killing the kernel, and load a fresh one.

### LINKED ISSUE #2790: Make "Ask for confirmation before closing tabs" in IPython console work for all consoles
Feature request: Closing a tab in IPython console should ask for confirmation, or at least there should be an option in preferences to enable such a confirmation.

### LINKED ISSUE #2844: Spyder won't connect to kernel / IPython console after switching to an external interpreter
So I just freshly installed th spyder dmg from this repository. When i switch to my standard python interpreter (/Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7) however, the console keeps giving the message: Connecting to kernel. 

Things I have checked & run:

- I can run ipython from terminal
- I can use the iPython console in PyCharm using the SAME interpreter
- pip install jupyter -U
- I can import IPython from the regular 'console' in spyder.

I am currently on OS X el capitan.

### LINKED ISSUE #2846: Import runfile() produces errors when using a virtualenv
Hi,

So I guess I've traced this error from symptom to potential solution :

### Steps to see the problem :
1. Install PyQt4 without pip (for example, with Ubuntu ``sudo apt-get install python-qt4``)
(note : qt is hellish to install properly via pip)
2. ``pip install spyder`` (note : I need the latest version that solves a blocking bug, so apt-get won't do)(version 2.3.8 at the time of writing)
3. Open Spyder and configure it to use a different Python interpreter, for example a virtualenv's python without --use-global-site because this may introduce a **lot** of bugs.
4. Open file, try to run code via ``F5``

### What I expect :
Code runs.

### What actually happens :
Fails due to ``ImportError`` on ``runfile``

### Reasons why this happens :
In sitecustomize, among other things, 3 things happen :

#### Python path
Thanks to the PYTHONPATH env variable set by [``pythonshell.py``](https://github.com/spyder-ide/spyder/blob/master/spyderlib/widgets/externalshell/pythonshell.py#L501), we have the ``/spyderlib/widgets/externalshell/`` in the pythonpath. However, we need to have the whole ``spyderlib`` in order to load the monitor. So we [add the folder](https://github.com/spyder-ide/spyder/blob/master/spyderlib/widgets/externalshell/sitecustomize.py#L132) containing ``spyderlib`` to the python path. Under Ubuntu 14.4 with latest pip, and python2.7 this is ``/usr/local/lib/python2.7/dist-packages/``.

#### Monitor
In the part that [loads the monitor](https://github.com/spyder-ide/spyder/blob/master/spyderlib/widgets/externalshell/sitecustomize.py#L229), there's an ImportError that is silenced because that's how [Python works](https://docs.python.org/2/library/site.html) ("If this import fails with an ImportError exception, it is silently ignored")

#### Cleaning
(we [remove](https://github.com/spyder-ide/spyder/blob/master/spyderlib/widgets/externalshell/sitecustomize.py#L606) ``/usr/local/lib/python2.7/dist-packages/`` from ``sys.path`` of course, otherwise, that would completely break the user's virtualenv)

When explored, the import error of the Monitor part above traces to [the import of ``sip``](https://github.com/spyder-ide/spyder/blob/master/spyderlib/qt/__init__.py#L23) and it fails because SIP and PyQt4 were installed using apt-get, and they were placed into ``/usr/lib/python2.7/dist-packages/`` (note : ``usr/lib`` and **not** ``/usr/local/lib``) which is not present in our current ``sys.path``

### Workaround

Once I had understood all of this, I got it to work simply by creating a symlink of PyQt4 and sip in the right folder :
```bash
cd /usr/local/lib/python2.7/dist_package
ln -s  /usr/lib/python2.7/dist_package/sip.so sip.so
ln -s  /usr/lib/python2.7/dist_package/PyQt4 PyQt4
```

### Leads for a real fix

I think what's really wrong here is either:

1. that we need the whole ``spyderlib`` to be loaded in the external python
2. or that we assume that ``spyderlib`` and ``PyQt4`` are installed in the same physical directory (all we know is that they're both in a directory present in the internal python's sys.path)

To fix 1. requires a knowledge of spyder that I don't have.
Fixing 2 can actually seem easier, but there might be tricky situations (because until we load it, we don't know in advance if we're going to use ``PyQt4`` or ``PySide`` for example). Maybe we need to store the location of ``sip`` / ``PyQt4`` / ``PySide`` from the internal python and give it to the external python for it to use **only** during launch time.

### LINKED ISSUE #2918: Spyder always switches back to IPython kernel from IPyhton console
For me a bit uncomfortable, that if I work with a task in the Console and switch to IP console and then back, then Spyder always switch to the IPython kernel tab in the Console instead of the previously used Console task/tab.

### LINKED ISSUE #2945: Cannot locate kernel json file when connecting to remote ipython kernel
When attempting to connect to a remote ipython kernel, a dialog box comes up which allows browsing for the applicable `kernel-????.json` file.  After browsing for and selecting the json file (or manually typing in the path and name file), entering the ssh information, and clicking ok, the error "Unable to connect to Ipython `kernel-????`" appears.

After removing the try/except from `_create_client_for_kernel()` function in `ipythonconsole.py`, I discovered that `find_connection_file()` is searching for the json file in the path `/run/user/1000/jupyter`, regardless of the path entered into the dialog box. Commenting the line `cf = osp.basename(cf)`, which gets rid of the path, appears to fix the problem, since the `jupyter_console` function `find_connection_file()` appears to default to looking for the json file in the aforementioned directory. Of course copying the json file to the `/run/user/1000/jupyter` directory also fixes the problem, but that seems unnecessary.

Is this a bug, or am I missing something?

### LINKED ISSUE #3011: Cannot connect to existing kernel with full path specified
## Description of your problem
I was using Atom Hydrogen which starts its own ipython kernel inside the editor. In the console, it gives information on how to connect other clients to that kernel 
`"To connect another client to this kernel, use: --existing /Users/h/.atom/packages/Hydrogen/kernel-configs/kernel-f489dd13-5e0d-4eeb-857d-bad421d7863f.json"`

So I copy and paste the full path to spyder's connecting existing kernel dialogue but got 

> "Unable to connect to IPython kernel-f489dd13-5e0d-4eeb-857d-bad421d7863f.json"

It was running just fine before I deleted the old version of anaconda and reinstall the new one (which now has the folder "anaconda2"). I have tried to launch spyder from anaconda launcher and through terminal, neither worked.

I am not sure if it is Atom/Hydrogen or Spyder that is causing this error. I can connect to the same Hydrogen generated kernel through `ipython qtconsole --existing /Users/h/.atom/packages/Hydrogen/kernel-configs/kernel-f489dd13-5e0d-4eeb-857d-bad421d7863f.json` which made me believe it was spyder but I was, on the other hand, able to connect spyder to an existing Jupyter notebook kernel by giving the full path of that kernel in the spyder dialogue:
`/Users/h/Library/Jupyter/runtime/kernel-7e7152ea-e5cd-4f7c-8a05-265da567afe6.json`

Thanks for the help!

## Versions and main components

Anaconda2
Python 2.7
Spyder 2.3.8
Mac OS X

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=1.0   :  4.0.3 (OK)
matplotlib >=1.0:  1.5.1 (OK)
pandas >=0.13.1 :  0.17.1 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  3.4.2 (OK)
pyflakes >=0.5.0:  1.0.0 (OK)
pygments >=1.6  :  2.1 (OK)
pylint >=0.25   :  None (NOK)
qtconsole >=4.0 :  4.1.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
sympy >=0.7.3   :  0.7.6.1 (OK)
zmq >=2.1.11    :  15.2.0 (OK)

### LINKED ISSUE #3109: Auto select the only IPython or Python console after startup
When I first start Spyder and try to run a file, a dialog pops up with the complaint:

> No Python console is currently selected to run XXX.py.
> 
> Please select or open a new Python console and try again.

Since I have only one IPython console open and no Python console, I think it will be great if Spyder can automatically select that only IPython console for me and run the file...

I guess many users would have only one IPython or Python console open after starting Spyder, 
so it can be a very convenient feature for Spyder to auto select the only IPython or Python console after startup.

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #1860 
Fixes #2696
Fixes #2790 
Fixes #2844
Fixes #2846
Fixes #2918
Fixes #2945
Fixes #3011
Fixes #3109 

----

This is our fourth iteration(!) to integrate qtconsole within Spyder. The first one was created by Pierre in 2.1, and I Improved what he did in 2.2 and again in 2.3.

The idea this time is to avoid creating IPython kernels as widgets in the Python console, and instead talk to them directly. Of course, this is a major undertaking and so I've been procrastinating to do it for a long time! :-)

The advantages of this approach are:

* Remove perhaps the ugliest UX present in Spyder at the moment
* Avoid a ton of intricate code to maintain kernels and IPython consoles in sync
* A promising approach to improve our debugging experience in a future release (4.0?)

Tasks:

- [x] Reestablish connection with the Editor
- [x] Reestablish connection with the Help plugin
- [x] Reestablish connection with the Variable Explorer (this is the hardest task!)
- [x] Remove unneeded code from the Python console

### CODE REVIEW

**Comment by dhirschfeld** [comment]
FYI: On this branch I can't open an IPython console - I get the below error in the internal console:
```python
>>> Traceback (most recent call last):
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\__init__.py", line 503, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\ipythonconsole.py", line 689, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\ipythonconsole.py", line 876, in create_new_client
    self.connect_client_to_kernel(client)
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\ipythonconsole.py", line 1126, in connect_client_to_kernel
    client.password)
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\ipythonconsole.py", line 1098, in create_kernel_manager_and_client
    kernel_manager.kernel_spec = self.create_kernel_spec()
AttributeError: can't set attribute
```

**Comment by ccordoba12** [comment]
@dhirschfeld, thanks for testing. I'll see what's happening :-)

**Comment by ccordoba12** [comment]
@dhirschfeld, my last commit should fix the error you reported.

**Comment by dhirschfeld** [comment]
Thanks - the latest version  seems to be running fine on my Py3.5.1 /Win10 setup. I'll have to find some time to look at the code behind it...

**Comment by dhirschfeld** [comment]
With the latest on this branch I'm seeing the below error in the internal console:
```python
>>> Traceback (most recent call last):
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\__init__.py", line 503, in <lambda>
    toggled=lambda checked: self.toggle_view(checked),
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\ipythonconsole.py", line 698, in toggle_view
    self.create_new_client(give_focus=False)
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\ipythonconsole.py", line 884, in create_new_client
    self.register_client(client)
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\ipythonconsole.py", line 938, in register_client
    control.set_help(self.help)
  File "C:\Users\Dave\Code\spyder\spyderlib\widgets\mixins.py", line 592, in set_help
    self.help.set_shell(self)
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\help.py", line 949, in set_shell
    self.shell = self.external_console.get_current_shell()
  File "C:\Users\Dave\Code\spyder\spyderlib\plugins\externalconsole.py", line 578, in get_current_shell
    return shellwidget.shell
AttributeError: 'NoneType' object has no attribute 'shell'
```
I checked and don't seem 'to be getting it on master.

In case it matters I don't have a console pane open - just the IPython console, History log and Internal Console.

**Comment by ccordoba12** [comment]
@dhirschfeld, my last commit fixes that problem.

**Comment by dhirschfeld** [comment]
LGTM!

**Comment by Nodd** [comment]
I just tested it briefly, the ipython console works fine.

The variable explorer doesn't work with the ipython console, I don't remember if it's supposed to work or not.

**Comment by ccordoba12** [comment]
> The variable explorer doesn't work with the ipython console

Yep, I know. It's one of the tasks to be finished before merging this PR ;-)

**Comment by Nodd** [comment]
Sorry, I didn't check the first post where you have a TODO list.

**Comment by dhirschfeld** [comment]
Just xref'ing nteract/hydrogen#330 as there may be something to learn from it. I would *love* if spyder could connect to remote kernels too!

**Comment by ccordoba12** [comment]
I think this one is finally ready!! There are some missing things (like inspecting values in the Variable Explorer while debugging) but I'll fix them in 3.1.

For now the most important things are working, i.e. the connections with the Editor, Help and Variable Explorer in normal mode.

**Comment by goanpeca** [comment]
:+1:

**Comment by ccordoba12** [comment]
Perhaps what I did is not the best approach (we could have used comm messages for some parts), but it's working for now ;-)

**Comment by goanpeca** [comment]
Lets create an issue so we can track these things you suggest we use

**Pull request merged**
