### PR TITLE
Fix resetting IPython custom exception hook

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-2395

Ping @DSLituiev - this should fix the problem you showed me yesterday.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Looking at the docstring for `set_custom_exc`, I wonder why `None` was there in the first place. Was it required in older versions of IPython?

**Comment by takluyver** [comment]
It's possible, but I don't think that code has changed for some time.

**Comment by ccordoba12** [comment]
@takluyver, thanks a lot for taking a look at this one :-)

@blink1073, please take a look at this one, given that it was you who added this code.

**Comment by blink1073** [comment]
Looks good to me.

**Pull request merged**
