### PR TITLE
PR: Escape regex characters from parameters while processing a signature

### LINKED ISSUE #10011: re.error when getting signature in the editor
### What steps will reproduce the problem?

I was just typing the statement new_shape = np.concatenate(()) and the issue reporter popped up.

### Traceback
```python-traceback
    documentation=documentation,
    max_width=max_width)
    max_width=max_width
    row = re.sub(pattern, handle_sub, row)
    return _compile(pattern, flags).sub(repl, string, count)
    p = sre_compile.compile(pattern, flags)
    p = sre_parse.parse(p, flags)
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
    not nested and not items))
    source.tell() - start)
re.error: missing ), unterminated subpattern at position 9

Traceback (most recent call last):
    msg = self.format(record)
    return fmt.format(record)
    record.message = record.getMessage()
    msg = msg % self.args
ValueError: incomplete format
Call stack:
    sys.exit(main())
    mainwindow.main()
    mainwindow = run_spyder(app, options, args)
    app.exec_()
    handler(resp['result'], req_id)
    {'params': response})
    self.COMPLETION_CLIENT_NAME, req_id, response)
    completion_source, response_instance, req_type, req_id)
    response_instance.handle_response(req_type, responses)
    handler(params)
    self.log_lsp_handle_errors("Error when processing signature")
    logger.error('%', 1, stack_info=True)
Arguments: (1,)
```

## Versions

* Spyder version: 4.0.0b4 
* Python version: 3.7.4
* Qt version: 5.12.4
* PyQt5 version: 5.12.3
* Operating System: Linux 4.15.0-54-generic

### Dependencies

```
pygments >=2.0    :  2.4.2 (OK)
qdarkstyle >=2.6.4:  2.7 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pyls >=0.27.0     :  0.28.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
pandas >=0.13.1   :  None (NOK)
numpy >=1.7       :  1.16.4 (OK)
sympy >=0.7.3     :  None (NOK)
cython >=0.21     :  0.29.12 (OK)
qtconsole >=4.5.2 :  4.5.2 (OK)
IPython >=4.0     :  7.7.0 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #10011 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, could you explain why this change is necessary?

@goanpeca, please take a look at this one.

**Comment by ccordoba12** [comment]
> please add a test for this one

@dalthviz, instead of testing this directly with the PyLS (which is not  easy), I think it's simpler to create a fixture that contains an instance of CodeEditor with no LSP services (by using `codeeditor_factory` in `spyder/plugins/editor/widgets/tests/conftest.py`), and then pass different parameters to `_format_signature` to test what it returns.

**Comment by dalthviz** [comment]
@ccordoba12 when processing the signature and more precisely the parameters if any, we create a regex pattern with the parameter's text at [this line](https://github.com/spyder-ide/spyder/blob/37952393120d49231ef1b63c90cab97b632f1c3a/spyder/widgets/mixins.py#L361) which is used with `re.sub` at [this line](https://github.com/spyder-ide/spyder/blob/37952393120d49231ef1b63c90cab97b632f1c3a/spyder/widgets/mixins.py#L371). The error was caused because the signature of `numpy.concatenate` includes a tuple (array like parameter) as a parameter:

```python
numpy.concatenate((a1, a2, ...), axis=0, out=None)
```

So when processing such signature and parameters, the regex pattern had an extra `(` (from the initial parameter taken `(a1`), making an invalid pattern.

**Comment by ccordoba12** [comment]
Ok, thanks for the explanation @dalthviz! Then let's try to exercise `_format_signature` as much as possible in the new test, to try to avoid similar failures in the future.

**Comment by dalthviz** [comment]
@ccordoba12 while testing this I realized that part of the problem is that the `activeParameter` retrieved doesn't respect that the first parameter is a tuple or array like element (in the case of `numpy.concatenate`, for example). So the signature's info has, as list of parameters, something like:

```python
['(a1', 'a2', '...)',  'axis', 'out']
```
instead of

```python
 ['(a1, a2, ...)', 'axis', 'out']
```
From what I saw this, is the way Jedi parses the parameters ([since the `pyls` at the end just calls `jedi.Script(...).call_signatures()`](https://github.com/palantir/python-language-server/blob/1b5b69b0a23c26b6767511cb7c6f3e0a5df2b2ac/pyls/plugins/signature.py#L16))

**Comment by ccordoba12** [comment]
> So the signature's info has, as list of parameters, something like:
['(a1', 'a2', '...)',  'axis', 'out']

That's really awful indeed!!

However, after talking with @dalthviz about the way Jedi returns parameters for collections, we decided that the best thing we can do for now is to merge this PR to avoid the error reported on issue #10011 and similar errors in the future.

Then we need to report this in the Jedi repo and try to fix it there.

**Pull request merged**
