### PR TITLE
PR: Retrieve Kite copilot documentation on click

### LINKED ISSUE #10349: Kite autosearch docs not working on mouse events
## Problem Description

With Kite enabled, docs are not automatically displayed in the Kite Copilot on mouse events. However, docs are automatically displayed on keyboard (e.g. arrow key) events.

### What steps reproduce the problem?

1. Open the following file:
```python
import pandas as pd
df = pd.read_csv('csv')
```
2. Open the Kite Copilot and enable "Docs Follow Cursor".
3. In the file above, try clicking on different identifiers e.g. `panads` or `read_csv`.

### What is the expected output? What do you see instead?

__Expected:__ Docs should show up automatically in the Copilot.
__Actual:__ Nothing happens. However, if you use the arrow keys to move the cursor, docs are updated.

spyder-autosearch-bug

## Versions

* Spyder version: Spyder 4.0.0.dev0 (Commit: e362c9525) 
* Python version: Python 3.7.3 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Darwin 18.7.0 

### Dependencies

```
cloudpickle >=0.5.0          :  1.2.2 (OK)
pygments >=2.0               :  2.4.2 (OK)
qtconsole >=4.5.5            :  4.5.5 (OK)
nbconvert >=4.0              :  5.5.0 (OK)
sphinx >=0.6.6               :  2.1.2 (OK)
pylint >=0.25                :  2.3.1 (OK)
psutil >=0.3                 :  5.6.3 (OK)
qtawesome >=0.5.7            :  0.5.7 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
zmq >=17                     :  18.1.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
spyder_kernels >=1.5.0;<2.0.0:  1.5.0 (OK)
qdarkstyle >=2.7             :  2.7 (OK)
atomicwrites >=1.2.0         :  1.3.0 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
watchdog                     :  None (OK)
keyring                      :  None (OK)
pexpect >=4.4.0              :  4.7.0 (OK)
pympler                      :  None (OK)
sympy >=0.7.3                :  None (NOK)
cython >=0.21                :  None (NOK)
IPython >=4.0                :  7.8.0 (OK)
matplotlib >=2.0.0           :  None (NOK)
pandas >=0.13.1              :  None (NOK)
numpy >=1.7                  :  None (NOK)
scipy >=0.17.0               :  None (NOK)
pyls >=0.28.2;<0.29.0        :  0.28.3 (OK)
rtree >=0.8.3                :  0.8.3 (OK)
```

### PR DESCRIPTION
**Pull request by andfoy**
## Description of Changes
This PR enables Kite copilot to display documentation whenever the cursor is moved on click.

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

ezgif com-video-to-gif(15)

### Issue(s) Resolved

Fixes #10349

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@andfoy

### CODE REVIEW

**Comment by dalthviz** [comment]
@ccordoba12 @andfoy testing on Windows it works fine for standard library imports, although not for local definitions:

cc


Also more than on click, this is more like on hover, right?

**Comment by goanpeca** [comment]
@metalogical just to check something:

Currently we have the following cursor interactions working:

1) Move the cursor with arrow keys -> copilot follows
2) Move the cursor with mouse and press on some code -> copilot follows
3) Move the cursor with mouse and DO NOT press but wait for spyder hover help on some code -> copilot follows

You agree with all these options or is the third one something copilot should not follow?

**Comment by metalogical** [comment]
In other editors, the copilot does not follow on hover (3). I'm not inherently opposed to the behavior from a UI-perspective, but I'm concerned this may end up causing weird side-effects because Kite may start pre-caching completions based on the cursor position sent with the edit event (text document changed).

I would prefer to subscribe to this signal: https://doc.qt.io/qt-5/qplaintextedit.html#cursorPositionChanged and call `document_did_change` there.

**Comment by goanpeca** [comment]
This should now take care of 1 and 2, but not 3.

**Pull request merged**
