### PR TITLE
PR: More improvements to Online Help

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### TODO
- [x] Remove validation icon
- [x] Change error message
- [x] Change error style
- [x] Change label (`Module or package` -> `Package`)
- [x] Change author class style
- [x] Increase `normal` style font size
- [x] Code tag (strings) to mono space font style 
- [x] Align search input to the right, change input and button size 
- [x] Add placeholder text in the search field
- [x] Remove link style from signatures
- [x] Don't put search text in url combobox

A preview:

image

Update error page:

image

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by goanpeca** [comment]
This PR is looking sweet!

Is this ready for a final review @dalthviz ?

**Comment by ccordoba12** [comment]
There are still some minor details that I need to talk with @dalthviz before this one is ready.

**Comment by dalthviz** [comment]
@goanpeca just in case, there are no issues related with this

**Comment by goanpeca** [comment]
Thanks :-)

**Comment by goanpeca** [comment]
@dalthviz is the red used in the second screenshot part of the theme. Feels a bit off. Just wondering if there was another "red" available on that theme. Not super important though :-p

**Pull request merged**
