### PR TITLE
PR: Fix Ctrl+Tab to cycle files on the editor

### LINKED ISSUE #6055: Ctrl-Tab doesn't switch between Editor files in macOS
## Description of your problem

I cannot switch between editor files/tabs using Ctrl-Tab or Ctrl-Shift-Tab. Nothing happens at all. I don't think there's anything weird with my OS/keyboard settings, because I use the same shortcut in many other applications just fine. 

**Please provide any additional information below**

Here are my shortcut settings: 

image

## Versions and main components

* Spyder Version: 3.2.4
* Python Version: Python 3.6.3 64bits, Qt 5.6.2,
* Qt Version: Qt 5.6.2, 
* PyQt Version: PyQt5 5.6 on Darwin
* Operating system: macOS Sierra 10.12.6

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  0.26.1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.13.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
psutil >=0.3     :  5.4.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.4 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.5 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.1.1 (OK)

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

shortcuts

As per https://bugreports.qt.io/browse/QTBUG-8596, the action needs to be added to a menu for this to work on OSX. Created a "hidden" menu to try this out and it is working :-). now... where should we add these actions? We cannot disable or hide them or this will cease to work

Screen Shot 2019-05-23 at 00 44 53

This PR now updates the default shortcut on MAC to use the `control` key as chrome firefox and similar applications do on OSX.

There is a separate issue on the `Spyder Preferences` related to setting shortcuts on OSX that use `tab` and `control`, which currently do not seem to work.

### Issue(s) Resolved

Fixes #6055

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by ccordoba12** [comment]
> where should we add these actions?

I think they can go in the File menu.

**Comment by goanpeca** [comment]
Like this @ccordoba12 

Screen Shot 2019-05-23 at 05 41 50
?

**Comment by ccordoba12** [comment]
Let's put them at the end, i.e. after `Symbol switcher` and before `Restart`. That's because I think most people will use the shortcuts instead of the actions.

**Comment by goanpeca** [comment]
>Let's put them at the end, i.e. after Symbol switcher and before Restart. That's because I think most people will use the shortcuts instead of the actions.

👍

**Comment by goanpeca** [comment]
Ready @ccordoba12 

Screen Shot 2019-05-23 at 08 08 23

**Comment by DanilZherebtsov** [comment]
Hi everyone. Did this eventually got fixed? I've downloaded and installed the latest version of Spyder 5.1.1. for Mac and can't see these newly added options to the file menu

**Pull request merged**
