### PR TITLE
PR: Remove adding second interpreter prompt after error

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes
Revert changes made in https://github.com/spyder-ide/spyder/pull/4914 as underlying error is now corrected.

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for taking a look at this @impact27! I was really tired of this double prompt.

> Revert changes made in #4914 as underlying error is now corrected.

Could you be more specific here? What was the underlining error? And when was it corrected?

**Comment by impact27** [comment]
Unfortunately I don't know. It was solved either in qtconsole or in spyder at some point in the last 2 years.

**Comment by impact27** [comment]
The error is not 100% reproducible so it will be a pain to bisect, but I can't see it with the latest qtconsole and master.

**Comment by ccordoba12** [comment]
Ok, no problem. I trust you on this one.

**Pull request merged**
