### PR TITLE
PR: Prevent Python variable validation to get current word and position when doing completions

### LINKED ISSUE #20156: Autocomplete does not work properly if the file starts with a number
### What steps will reproduce the problem?

Hello.

I typed "00".
And I tried to automatically complete a filename that starts with "00_" as in the example below.
But The auto-completion result was "0000_".

Exp

This problem has been around for a long time.

Thank you.

## Versions

* Spyder version: 5.4.0  (conda)
* Python version: 3.9.12 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.15.0-56-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0                  :  1.4.0 (OK)
chardet >=2.0.0                       :  4.0.0 (OK)
cloudpickle >=0.5.0                   :  2.0.0 (OK)
cookiecutter >=1.6.0                  :  1.7.3 (OK)
diff_match_patch >=20181111           :  20200713 (OK)
intervaltree >=3.0.2                  :  3.1.0 (OK)
IPython >=7.31.1;<8.0.0               :  7.31.1 (OK)
jedi >=0.17.2;<0.19.0                 :  0.18.1 (OK)
jellyfish >=0.7                       :  0.9.0 (OK)
jsonschema >=3.2.0                    :  4.16.0 (OK)
keyring >=17.0.0                      :  23.9.3 (OK)
nbconvert >=4.0                       :  6.5.4 (OK)
numpydoc >=0.6.0                      :  1.5.0 (OK)
parso >=0.7.0;<0.9.0                  :  0.8.3 (OK)
pexpect >=4.4.0                       :  4.8.0 (OK)
pickleshare >=0.4                     :  0.7.5 (OK)
psutil >=5.3                          :  5.9.0 (OK)
pygments >=2.0                        :  2.11.2 (OK)
pylint >=2.5.0;<3.0                   :  2.14.5 (OK)
pylint_venv >=2.1.1                   :  2.3.0 (OK)
pyls_spyder >=0.4.0                   :  0.4.0 (OK)
pylsp >=1.6.0;<1.7.0                  :  1.6.0 (OK)
pylsp_black >=1.2.0                   :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0             :  3.0.2 (OK)
qstylizer >=0.2.2                     :  0.2.2 (OK)
qtawesome >=1.2.1                     :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0              :  5.4.0 (OK)
qtpy >=2.1.0                          :  2.2.0 (OK)
rtree >=0.9.7                         :  0.9.7 (OK)
setuptools >=49.6.0                   :  65.5.0 (OK)
sphinx >=0.6.6                        :  5.0.2 (OK)
spyder_kernels >=2.4.0;<2.5.0         :  2.4.0 (OK)
textdistance >=4.2.0                  :  4.2.1 (OK)
three_merge >=0.1.1                   :  0.1.1 (OK)
watchdog >=0.10.3                     :  2.1.6 (OK)
xdg >=0.26                            :  0.27 (OK)
zmq >=22.1.0                          :  23.2.0 (OK)

# Optional:
cython >=0.21                         :  0.29.32 (OK)
matplotlib >=3.0.0                    :  3.5.3 (OK)
numpy >=1.7                           :  1.21.5 (OK)
pandas >=1.1.1                        :  1.5.1 (OK)
scipy >=0.17.0                        :  1.7.3 (OK)
sympy >=0.7.3                         :  1.11.1 (OK)

```

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

When doing completions, the LSP provides also completions for file names. Files that start with number were not completed correctly since a validation for valid Python variables was being always made when getting the current word and position.

Preview

file_completion

### Issue(s) Resolved

Fixes #20156 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by ccordoba12** [comment]
Looks good to me @dalthviz, thanks!

Please rebase to get the fixes to our tests in PR #20224, then I'll merge.

**Comment by dalthviz** [comment]
@ccordoba12 just for testing, I enabled an option that allows doing merge/rebases to PRs from the GitHub interface if the PR branch is not up to date with the PR base branch (`Settings` -> `Always suggest updating pull request branches` ). Maybe it could be worthy to keep it so contributors have a more easy time if they need to do a rebase or merge to update their PRs?

**Comment by ccordoba12** [comment]
> Maybe it could be worthy to keep it so contributors have a more easy time if they need to do a rebase or merge to update their PRs?

Good idea! I agree with that.

I also see that this change breaks `test_kite_textEdit_completions`. Since we don't support Kite anymore, please remove it.

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz!

**Pull request merged**
