### PR TITLE
PR: Change the TODO checkmark

### LINKED ISSUE #2264: "TODO" should not be labeled with checkmark
Currently in the editor, lines starting with "TODO" get marked with a checkmark at the left border.

I am associating a checkmark with "done", i.e. the opposite of "todo" ;-)
So I suggest to replace this checkmark, e.g. by a red square.

### PR DESCRIPTION
**Pull request by jondo**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based this PR on the latest version of the correct branch (master or 3.x)
* [x] Followed [PEP 8](https://www.python.org/dev/peps/pep-0008/) code style
* [x] Ensured this pull request hasn't eliminated unrelated blank lines/spaces,
      modified the ``spyder/defaults`` directory, or added new icons/assets
* [x] Wrote at least one-line docstrings following PEP 257for any new functions
* [ ] Added at least one unit test covering the changes, if at all possible
* [x] Described the changes and the motivation for them below
* [x] Noted what issue(s) this pull request resolves, creating one if needed
* [x] Included a screenshot, if this PR makes any visible changes to the UI

### Developer Certificate of Origin Affirmation

By submitting this Pull Request or typing my name below, I affirm the
[Developer Certificate of Origin](https://developercertificate.org/)
with respect to both the content of the contribution itself and this post,
and understand I am releasing it under Spyder's MIT (Expat) license.

## Description of Changes

Currently in the editor, lines starting with "TODO" get marked with a checkmark at the left border.
I am associating a checkmark with "done", i.e. the opposite of "todo" ;-)
So I suggest to replace this checkmark with an unchecked checkbox symbol, as discussed in #2264.

Screenshot of the new label:
todo-checkboxes

### Issue(s) Resolved

Fixes #2264

### CODE REVIEW

**Comment by ccordoba12** [comment]
@spyder-ide/core-developers, what do you think about this change?

**Comment by jnsebgosselin** [comment]
> While the "checkbox" proposed above is better, I think, I'm not 100% sure it would always be clear to most users that it is a checkbox, and I'm not sure it always sends a clear message either especially to an international audience. My first thought is something like the warning/attention symbol (⚠️), since most if not all those comments are meant to bring attention to something in the code, but of course that's already used for code style warnings so that's out of the question.

The empty checkbox is fine, but I agree with @CAM-Gerlach. I think I like the red flag idea that was proposed in https://github.com/spyder-ide/spyder/issues/2264#issuecomment-422965174 better.

This is the symbol used in Outlook for to-do-list for what it's worth hehe.

**Comment by CAM-Gerlach** [comment]
> The empty checkbox is fine, but I agree with @CAM-Gerlach. I think I like the red flag idea that was proposed in #2264 (comment) better.

Yeah, a flag sounds like a great idea!

**Comment by jondo** [comment]
OK. This is what it looks like now:
todo-red-flag
Well ... at least it's not the irritating checkmark any more :-P

**Comment by jondo** [comment]
Here are three more ideas:

* `fa.flag-o`:
todo-outlined-flag

* `fa.exclamation-circle`:
todo-exclam-circle

* `fa.exclamation`:
todo-exclam

I like the last one most. Both the outlined flag and the simple exclamation mark are not as aggressive, and the exclamation mark looks more stylish to me.

**Comment by ccordoba12** [comment]
Yes, I also like the last one too. What if we use blue (as before) or green instead of red for that symbol? I mean, red usually means *be careful*, but that's not always the case here.

**Comment by CAM-Gerlach** [comment]
The advantage of the exclamation mark is it can be overlaid over the warning/error icons without completely covering them. I'd argue for blue, as at least in Western cultures "green" implies "go"/"good" while blue doesn't have those connotations.

**Comment by jondo** [comment]
Fine, I've now pushed this:
todo-blue-exclamation

**Comment by jondo** [comment]
Locally, I see `pytest spyder/utils/tests/test_codeanalysis.py::test_codeanalysis` fail differently (see the details below), but this happens both on this PR and on master. Am I right to conclude that my PR is OK?

<details/>

```
==================================================================== test session starts =====================================================================
platform linux -- Python 3.6.6, pytest-3.8.2, py-1.7.0, pluggy-0.7.1
PyQt5 5.11.2 -- Qt runtime 5.11.1 -- Qt compiled 5.11.1
rootdir: /home/robert/bin/spyder, inifile:
plugins: timeout-1.3.2, qt-3.2.1, mock-1.10.0, cov-2.6.0, flaky-3.4.0
collected 1 item                                                                                                                                             

spyder/utils/tests/test_codeanalysis.py F                                                                                                              [100%]

========================================================================== FAILURES ==========================================================================
_____________________________________________________________________ test_codeanalysis ______________________________________________________________________

    def test_codeanalysis():
        """Test codeanalysis with pyflakes and pep8."""
        code = open(TEST_FILE).read()
        check_results = check_with_pyflakes(code, TEST_FILE) + \
                        check_with_pep8(code, TEST_FILE) + find_tasks(code)
        if PY2:
            num_results = 89
        else:
            num_results = 90
>       assert len(check_results) == num_results
E       AssertionError: assert 2 == 90
E        +  where 2 = len([('Test', 13), ('XXX', 14)])

spyder/utils/tests/test_codeanalysis.py:50: AssertionError
===Flaky Test Report===


===End Flaky Test Report===
================================================================== 1 failed in 0.69 seconds ==================================================================
```

</details>

**Comment by CAM-Gerlach** [comment]
The local failure could be due to something with your ``pylint`` version, your ignore rules, etc. The remote failure is almost certainly due to a changing in the wording of analysis rules with Pylint 2.2.x vs 2.1.x and can be easily fixed by checking if the Pylint version is >=2.2.0 and setting ``num_results`` to 90 if so, although its ultimately due to the test being somewhat fragile and will happen again if Pylint adds more rules—we could consider checking for a slightly "fuzzier" range of results, since ultimately we're testing Spyder and not ``pylint`` after all. @ccordoba12 ?

**Comment by ccordoba12** [comment]
@jondo, how does your change look with the new dark theme?

**Comment by jondo** [comment]
I rebased s.t. `test_codeanalysis` is [fixed](https://github.com/spyder-ide/spyder/commit/b16e0679026072ff0883ae6696cbbdbfe70a5396) in the CI checks. Now all tests pass.

This is the look after switching to "Interface theme: Dark" and "Syntax scheme: Spyder Dark":
blue-exclamation-dark

**Comment by ccordoba12** [comment]
Looks good to me. @CAM-Gerlach?

**Pull request merged**
