### PR TITLE
Return default language in case no locale is found

### PR DESCRIPTION
**Pull request by goanpeca**

### CODE REVIEW

**Comment by goanpeca** [comment]
@CTPaHHuK-HEbA can you check if this works for you now?

Cheers

**Comment by ccordoba12** [comment]
Sorry, I didn't notice this PR ;-)

@goanpeca, could you rebase this PR and make the necessary changes after my revision 792372f4672db00145f1022770b11f5fb39abd2e?

**Comment by goanpeca** [comment]
Done @ccordoba12

**Comment by goanpeca** [comment]
@ccordoba12, I think you can merge this, the solution I did is slightly different to what the user suggested, and should work better

**Comment by ccordoba12** [comment]
Ok, merging then :-)

**Comment by CTPaHHuK-HEbA** [comment]
Thx. All works well.

**Pull request merged**
