### PR TITLE
PR: Add palette files with color roles

### PR DESCRIPTION
**Pull request by juanis2112**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

This PR adds the color roles from the Spyder's palette for both the light and dark theme.
It also replaces all the colors from the elements in spyder with the colors from either the qdarkstyle palette or the spyder palette. 
I will be posting screenshots of the elements changed as I change them to make sure we like the colors.

The following files still have hardcoded colors and will be changed once the colors on the variable explorer are migrated:

- spyder/external-deps/spyder-kernels/spyder_kernels/console/kernel.py 
- spyder/spyder/widgets/arraybuilder.py 
- spyder/external-deps/spyder-kernels/spyder_kernels/utils/nsview.py 
- spyder/spyder/plugins/variableexplorer/widgets/tests/test_namespacebrowser.py
- spyder/spyder/widgets/tests/test_collectioneditor.py

The following files still have hardcoded colors which we will leave that way because they are black:

- spyder/spyder/plugins/editor/utils/editor.py -> Lines 48,49 
- spyder/spyder/app/tests/test_mainwindow.py 

The following files still have hardcoded colors which we will figure out in the future:

- spyder/spyder/plugins/console/utils/ansihandler.py
- spyder/spyder/utils/syntaxhighlighters.py

### Issue(s) Resolved

Fixes https://github.com/spyder-ide/ux-improvements/issues/26
Fixes https://github.com/spyder-ide/ux-improvements/issues/13

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by juanis2112** [comment]
Tour:
Screenshot 2021-03-02 at 10 14 27 AM

**Comment by juanis2112** [comment]
IPython Console pager
Screenshot 2021-03-02 at 10 15 20 AM

**Comment by juanis2112** [comment]
Find in files invalid regex color
Screenshot 2021-03-02 at 10 27 47 AM

**Comment by juanis2112** [comment]
Profiler results
Screenshot 2021-03-02 at 1 32 33 PM

**Comment by juanis2112** [comment]
Kite dialog:
Screenshot 2021-03-04 at 1 24 32 AM

Screenshot 2021-03-04 at 1 27 11 AM

**Comment by juanis2112** [comment]
Code Analysis:

Screenshot 2021-03-04 at 10 26 23 AM
Screenshot 2021-03-04 at 10 26 13 AM
Screenshot 2021-03-04 at 10 26 00 AM
Screenshot 2021-03-04 at 10 24 55 AM
Screenshot 2021-03-04 at 10 24 39 AM
Screenshot 2021-03-04 at 10 24 25 AM

**Comment by isabela-pf** [comment]
> We might need to modify group color 4 for light mode a little bit. I think the contrast with the white is not enough (see the green text over the white background). What do you think @isabela-pf?

I agree. I think it's because I thought they were being used only in the variable explorer, so I'm happy to update those.

**Comment by juanis2112** [comment]
Editor:

Screenshot 2021-03-05 at 11 26 31 PM
Screenshot 2021-03-05 at 11 23 10 PM

**Comment by juanis2112** [comment]
Console client (Elapsed time):
Screenshot 2021-03-06 at 12 11 19 AM
Screenshot 2021-03-06 at 12 10 44 AM

**Comment by juanis2112** [comment]
Screenshot 2021-03-06 at 12 52 30 AM
Screenshot 2021-03-06 at 12 49 59 AM

**Comment by juanis2112** [comment]
Calltips link
Screenshot 2021-03-06 at 1 08 37 AM

Screenshot 2021-03-06 at 1 09 03 AM

**Comment by juanis2112** [comment]
> > We might need to modify group color 4 for light mode a little bit. I think the contrast with the white is not enough (see the green text over the white background). What do you think @isabela-pf?
> 
> I agree. I think it's because I thought they were being used only in the variable explorer, so I'm happy to update those.

We could see if another color fits better (Maybe from the success or icon group). We can discuss it tomorrow in the meeting.

**Comment by juanis2112** [comment]
The last commit replaces colors in the icon manager which should address all icons in Spyder. I didn't replace the following colors:

- Yellow from Python icon-> `#ffd444`
- Blue from Python icon -> `#3775a9`
(I think this two should probably hard coded using the colors <a href="https://www.schemecolor.com/python-logo-colors.php#:~:text=The%20Python%20Logo%20Colors%20with,are%20in%20the%20table%20below."> here </a>)
- Light yellow for some deactivated icons -> `#face7e` (Not sure what to do about that color) See example:
<details>
WhatsApp Image 2021-03-08 at 2 54 24 PM
</details>

- All the logos from the Spyder's logo (They should probably also be hard coded)  Gray -> `#414141`  Lighter grey  -> `#fafafa` (almost white) Red -> `#ee0000`

I also wanted to ask if it's okay to have all yellow and orange icons the same color since there is only one orange/yellow color in the icon group. I did all the replacements of orange and yellow colors for color icon 5 `#F37E12`
And I used SpyderPalette.GROUP_10 to replace all the icons in "magenta" since we don't have an icon color to match that one. Not sure if that's okay.

**Comment by isabela-pf** [comment]
Thanks for listing out all these color statuses @juanis2112! I think I caught everything, but let me know if I missed any of your questions.

> Yellow from Python icon-> `#ffd444`
Blue from Python icon -> `#3775a9`
(I think this two should probably hard coded using the colors here )

I agree! They are colors defined by an external party so that makes sense. I don't know how many places they are used, but we could also create some constants like `PYTHON_YELLOW` and `PYTHON_BLUE` that aren't attached to the color system just for more easy tracking in the UI long term.

> Light yellow for some deactivated icons -> `#face7e` (Not sure what to do about that color)

If deactivated icons are all getting the same transparency treatment, I think it makes sense to apply that here unless there's a reason that won't work. Are you saying it's a different yellow than the main yellow used in that icon?

> All the logos from the Spyder's logo (They should probably also be hard coded) Gray -> `#414141` Lighter grey -> `#fafafa` (almost white) Red ->`#ee0000`

I have the same comments for this as the Python colors. We could hard code or make a set of constants specific to the brand if we want to keep better track.

> Is it okay to have all yellow and orange icons the same color since there is only one orange/yellow color in the icon group? I did all the replacements of orange and yellow colors for color icon 5 `#F37E12`

That was my idea since yellow is basically impossible to get contrast on when near light colors (like text or light mode) If we don't like the way this is working I can reconsider, but you are correct!

> I used SpyderPalette.GROUP_10 to replace all the icons in "magenta" since we don't have an icon color to match that one.

> There is a "darkred" used in the icons for the stop button and I think the icon red doesn't look good for it. Should I use the color Error 1?

I think that could work. Is the icon red just not working there or elsewhere? Because if it's not working overall I can work on that place in the color system.

I trust your judgement. Out of curiosity, are these icons with default `magenta` or something else?

>

**Comment by juanis2112** [comment]
**Screenshots after changes  from meeting review**

Dark theme:
<details>
Screenshot 2021-03-09 at 10 41 10 PM
Screenshot 2021-03-09 at 10 38 59 PM
Screenshot 2021-03-09 at 10 36 27 PM
Screenshot 2021-03-09 at 10 34 13 PM

</details>

Light theme:
<details>
Screenshot 2021-03-09 at 10 45 15 PM
Screenshot 2021-03-09 at 10 44 23 PM
Screenshot 2021-03-09 at 10 43 17 PM
Screenshot 2021-03-09 at 10 42 21 PM
</details>

**Comment by juanis2112** [comment]
Tha last commit changes the color for occurrences from the find widget which is now grey and the color of the highlight occurrences color from the editor highlighting theme which is now blue (we chose one blue for light theme and one for dark theme.)

This commit also changes the color of the text for the solarized dark theme because it was hard to find a color with enough contrast.

Default Spyder theme:

Screenshot 2021-03-11 at 5 35 07 PM

Dark syntax highlighting themes:
<details>
Screenshot 2021-03-11 at 4 02 54 PM
Screenshot 2021-03-11 at 4 07 05 PM
Screenshot 2021-03-11 at 4 06 20 PM
Screenshot 2021-03-11 at 4 05 57 PM
Screenshot 2021-03-11 at 4 15 36 PM
Screenshot 2021-03-11 at 4 15 10 PM
Screenshot 2021-03-11 at 4 14 26 PM
Screenshot 2021-03-11 at 4 08 17 PM
Screenshot 2021-03-11 at 4 05 30 PM
Screenshot 2021-03-11 at 4 07 54 PM
Screenshot 2021-03-11 at 4 05 03 PM

</details>


Light syntax highlighting themes:
<details>

Screenshot 2021-03-11 at 4 41 47 PM
Screenshot 2021-03-11 at 5 36 31 PM
Screenshot 2021-03-11 at 4 41 02 PM
Screenshot 2021-03-11 at 4 45 20 PM
Screenshot 2021-03-11 at 4 44 28 PM
Screenshot 2021-03-11 at 4 39 59 PM
Screenshot 2021-03-11 at 4 43 30 PM
Screenshot 2021-03-11 at 4 39 37 PM
Screenshot 2021-03-11 at 4 42 36 PM

</details>

**Comment by juanis2112** [comment]
Relevant screenshots from last commit:

Screenshot 2021-03-12 at 4 11 23 PM
Screenshot 2021-03-12 at 4 11 05 PM
Screenshot 2021-03-12 at 3 54 38 PM
Screenshot 2021-03-12 at 3 42 52 PM
Screenshot 2021-03-12 at 2 36 03 PM

**Comment by juanis2112** [comment]
As discussed in the meeting I chose better colors for the autocompletion symbols. The best I could find were GROUP_3, GROUP_5, GROUP_9, GROUP_11, GROUP_12, WARN_1 and WARN_2.

They can be seen in the following screenshots:

Screenshot 2021-03-12 at 6 31 20 PM
Screenshot 2021-03-12 at 6 25 59 PM
Screenshot 2021-03-12 at 6 16 13 PM

**Comment by juanis2112** [comment]
Screenshot of most of the other icons:
Screenshot 2021-03-12 at 6 40 09 PM
Screenshot 2021-03-12 at 6 39 43 PM

Screenshot 2021-03-12 at 6 38 46 PM

**Comment by ccordoba12** [comment]
Thanks @juanis2112 and @isabela-pf for your continued work on this! My comments on your latest screenshots @juanis2112:

> Screenshots after changes from meeting review

These look good to me.

> Tha last commit changes the color for occurrences from the find widget which is now grey and the color of the highlight occurrences color from the editor highlighting theme which is now blue

They are pretty nice! Thanks for taking the time to find colors for those elements that work well for all syntax highlighting themes (I guess it was not easy at all).

> Relevant screenshots from last commit

I think the orange for warnings in the editor

imagen

and the orange for missing packages

imagen

are different?

I'd like to see the same orange for missing packages as the one used in the editor.

> As discussed in the meeting I chose better colors for the autocompletion symbols

They look quite nice, thanks @juanis2112! Could you add to that a screenshot for the light theme?

**Comment by juanis2112** [comment]
Light theme:
Screenshot 2021-03-12 at 6 42 39 PM
Screenshot 2021-03-12 at 6 41 56 PM
Screenshot 2021-03-12 at 6 43 36 PM
Screenshot 2021-03-12 at 6 43 22 PM

**Comment by juanis2112** [comment]
> I'd like to see the same orange for missing packages as the one used in the editor.
I changed all the warning icons to be as the last screenshot one but If you like the editor ones better I'll change all of them to that one.

**Comment by juanis2112** [comment]
Warning:
Screenshot 2021-03-12 at 6 51 22 PM

**Comment by ccordoba12** [comment]
Thanks @juanis2112, they look better to me now, but we can discuss about that in our next meeting.

**Comment by juanis2112** [comment]
The last commit remove the occurrences button and sets highlighting the occurrences in the find/replace widget by default.
It fixes https://github.com/spyder-ide/ux-improvements/issues/26 and closes https://github.com/spyder-ide/spyder/pull/14632

**Comment by ccordoba12** [comment]
> It fixes spyder-ide/ux-improvements#26 and closes #14632

Please add this to the the `Issue(s) Resolved` section of the first comment in this PR.

Also, could you upload again the screenshot you tried to post in your last comment? Unfortunately, it wasn't uploaded correctly to Github.

**Comment by juanis2112** [comment]
Help pane:
Screenshot 2021-03-24 at 7 50 16 PM
Screenshot 2021-03-24 at 7 50 07 PM
Screenshot 2021-03-24 at 7 48 32 PM
Screenshot 2021-03-24 at 7 48 22 PM

Online Help:
Screenshot 2021-03-24 at 8 03 33 PM
Screenshot 2021-03-24 at 8 02 51 PM

IPython Console:
Screenshot 2021-03-24 at 7 54 22 PM
Screenshot 2021-03-24 at 7 53 41 PM

**Review by ccordoba12 — APPROVED** [review]
Thanks @juanis2112 for your hard work on the new color palette for Spyder 5! This is finally ready!

**Pull request merged**
