### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by techtonik**
Remove comments from Captain Obvious

### CODE REVIEW

**Comment by ccordoba12** [comment]
I don't agree with these changes. Perhaps they are too obvious, but I think it's better to be explicit rather than implicit in this case.

Thoughts anyone else? @goanpeca, @Nodd, @SylvainCorlay?

**Comment by goanpeca** [comment]
I think that @techtonik could probably invest his time on Spyder development in "better" fixes and PRs than this one, but hey who am I to judge that anyway?

Besides finding comments like *"Remove comments from Captain Obvious"* unnecessary(ly sarcastic...), I do agree that if the file contains 

```
 ## Version 2.3.3
```

Then what is the point of having immediately below 

```
New features since v2.3.2
```

**Comment by ccordoba12** [comment]
That's just to be clear that those features and fixes are added between those two versions. That's all :-) Nobody has complained about it before.

**Comment by goanpeca** [comment]
Not complaining about it ;-), but now that is open... it kinda make sense...

**Comment by techtonik** [comment]
I think you guys need to be less controlling. The metrics I see on this project doesn't match my expectation on how this beautiful project should have been raising up. When I picked it up on Google Code I surely had some expectations about its growth and a vision of a highly decoupled framework for building scientific interfaces.

For this specific issue, I think that you need to treat Spyder users/developers better. Leave them a space to use the brain and make your decisions based on data if you don't trust the former contributors. **The changelog contains noize that steals my time and attention. It offends my mental capabilities to induce the defaults.** Hence the sarcasm. **If you want more details, add release dates - that will be more useful.**

"Nobody complained about it before." sounds like my opinion doesn't count at all. If that's the fitness function for genetic algorithm of Spyder evolution then Houston, you have a problem. I am not saying that I am better - I also too picky, but at least I know the problem. Now you know it too.

More about potential Houston problems. First - only really hardcore users will complain about minor "product image" issues. Second problem - you don't know the bounce rate of users, what is affecting them, so Third - you make the judgements according to your own biased stereotypes about how users perceive the product (changelog in this case), and the issue is really doesn't affect you personally. The third one is the most important. If it is the issue for someone and it doesn't affect you, just let them do it and think twice before jumping in. You're maybe interrupting and delaying the flow that has more valuable things on the plate than a probe fixes.

Make it easier for people to make contribution and know that your Ask For Permission is hard. To feel what am I speaking about, switch to the review based workflow when all development is done in pull requests with obligatory approval and merge by somebody else. Gratipay and several other use that, and Spyder should use it too, because it a development tool.

Remember, Spyder users are also its developers, who like to learn, research and solve challenges including the areas of design, usability and user experience. Stick to that, help people unleash their creativity, and the future will be bright and prosperous.

**Comment by goanpeca** [comment]
@techtonik, a piece of advice, stop the sarcasm and the "aggressive attitude". That attitude will never be helpful in this project (I have been like this sometimes and is a nasty habit)

I understand that sometimes you need to take a stand on something you truly believe should be done to improve a project (I have found myself in this situation many times...), sometimes you will be right, sometimes you wont, and sometimes the other devs will pick on this (being right or wrong) or sometimes the wont (say you are wrong even if it might be a good idea, or the opposite). An even sometimes the devs will say things uncalled for, cause hey we are humans.... but lets try to keep respect above all.

Spyder has been developed in a somehow disorganized way and sometimes "the rules of the game" might not be clear, and this is something we need to keep working on (workflow in the wiki etc..) in the  meantime just be patient and polite.

This by no means that there is a veto on complaining how some thing are, I do it myself, and I encourage you to keep doing it, cause the way to improve is to highlight the shortcomings.... but I must insist... politeness will get you (and us) further!

Have a nice day :smile: :+1:

**Comment by ccordoba12** [comment]
I'm not going to argue about this. There are two votes (@techtonik and @goanpeca) against mine, so I'm going to merge it.

I just have a couple of comments:

1. 

    > Nobody has complained about it before.

    The headlines in our Changelog have been on it for 4 and a half years now, and Pierre started the tradition, not me. I just thought people was ok with them.

2. 

    >  I surely had some expectations about its growth and a vision of a highly decoupled framework for building scientific interfaces.

    Unfortunately that was (up to a certain point) Pierre's vision, but it's not mine. Creating a decoupled framework demands much more time and effort than I have available. That's ok for projects like IPython, that have thousands of dollars on investment and several developers working full time on it. But for a project that until one year ago was essentially Pierre and then me, I think it's not possible to demand something like that. My idea is just to create a good scientific IDE, not a framework that could be used to create your own IDE ;-) Fortunately, projects like PyQode (which was designed precisely with that purpose in mind) have filled that niche :-)

3. 

    > If you want more details, add release dates - that will be more useful

    Please add them yourself :-) (instead of writing long diatribes about it because that's expecting that I should do it, when I'm ok with our current Changelog)

**Comment by techtonik** [comment]
Thanks for understanding. =)

I still hope that Spyder won't lose its flexibility. The niche for monolithic apps was already filled by Eric and a dozen of other Python editors long ago. The promise of flexibility inscribed in Spyder's name and architecture was a big part of its success as a scientific IDE.

**Comment by Nodd** [comment]
Next version should have a better plugin management. This will add lots of flexibility !

**Comment by techtonik** [comment]
@Nodd, plugins need a stable and forward compatible API. Is there such a thing already?

**Comment by goanpeca** [comment]
@techtonik @Nodd this is an issue I have always been concerned about.... I have the feeling it grew organically but was never something that had planning. That is why I wanted to have some sort of `api` module that would keep more or less standard, even if internally we worked differently or refactor....

something like

`from spyder.api.ObjectInstpector`

or 

`from spyder.widgets.ObjectInstpector.api.`

**Comment by techtonik** [comment]
This may become bloated and overengineered Java-like stuff. Maybe that's the way all IDEs are evolving, but I would start with recipe book first, growing the API as necessary. The API should be easy to use from console. Like in Blender. It must be a replacement for mouse operations, because mouseops are slow by default. If the blind users will be able to command the IDE and setup it to their liking - that will be a huge win. API should allow that kind of flexibility. It also should track usage of different API things, so I'd include some counters by default. It may happen that these API connection endpoints will turn up to be slow, but if we cut some API features, it is better to document why we cut them.

**Comment by goanpeca** [comment]
@techtonik just some random thought.... not sure what is the best approach but I do agree in what you say. Ideally the public api would be any method that is... public, and anything else should be prepended by `_private_method` -> use with care, and `__private_method` -> never use!

**Comment by Nodd** [comment]
It depends on what the plugin is doing. It's different to add a widget to run an external tool like pylint, profiler, line_profiler, autopep8, or a plugin that would add full support for cython in the outline.explorer.
At the end, the whole spyder API should be stable. Currently this point is not enforced and this will be a problem in the future (I remember that it was already raised by debian devs or something like this)

**Comment by goanpeca** [comment]
I guess what I would like to have is something like

```python

class SpyderWidgetAPI:
    def __init__(self, parent):
        self.parent = parent

    def public_api_method_1(self):
        # Calls to private api

    def public_api_method_2(self):
        # Calls to private api

class SpyderWidget:
    def __init__(self):
        self.api = SpyderWidgetAPI(self)
        ....

    def private_api_method_1(self):
        # Calls to private api or more private methods of super private methods

    def _more_private_method_1(self):
        # Calls to private api or more private methods of super private methods

    def __super_private_method_1(self):
        # Calls to private api or more private methods of super private methods
```

**Comment by Nodd** [comment]
Oh, this is only the API for starting and registering plugins. I was talking about the whole spyder program.
In that case I think just having a parent class to inherit with public/private methods is enough. I don't see the need in abstracting the API since it's just a few methods anyway.

**Comment by goanpeca** [comment]
Yes,... it was an example.. but the whole spyder program could have a similar idea where an `SpyderAPI` would wrap other methods and functionality in a consistent and future proof way.

**Comment by Nodd** [comment]
I feel like it will be really complicated for not much gain. If we have to change spyder's internals it will be hard to not change the API too anyway.

**Comment by goanpeca** [comment]
That is precisely the point of a public api... to not change it... if spyder internals change the public api will be modified to continue to provide the same service without breaking any developer/user code.

One thing is expanding the api with new things and another one is changing behavior or names of it...

**Comment by goanpeca** [comment]
@Nodd then I have no idea what you meant by "Edit: I agree, there should be a distinction between public and private API." can you elaborate please otherwise I have no idea what the topic is you are discussing...

**Comment by Nodd** [comment]
OK, let's start from the beginning. There are  things here:
* The API to create a plugin, by subclassing classes like `PluginConfigPage`, `SpyderPluginMixin`, `SpyderPluginWidget`. Most methods in `SpyderPluginMixin` should be private since they are not meant to be used by plugin devs, but the class is sill used by subclassing. This API should (almost) never change after 3.0. This part is quite simple so I don't think it needs an intermediate API.
* The internals of spyder, that plugins will use to do anything useful (get the name or content of the active file for example). This is the part where it will be very hard to separate between a public API and a private API, and it will be harder to keep it stable.

What is really important for 3.0 is to improve and define the first API. The second part will come in time.

is it clearer now ?

**Comment by goanpeca** [comment]
Yes my dear ;-) thanks

* Agreed. I never talked about this...

* Here I would split it into two categories, one thing is a plugin that is completely Isolated from Spyder itself and only runs some specific things, take the pylint example... it barely uses spyder internals (I was not talking about this either). Another is a plugin that would enhance or adapt the core plugins, for instance, having a base editor with a well defined (and hopefully not changing API) that would allow to extend (via plugins) editors for other languages. Or adding a new object to the variable explorer so that it can be shown/edited with etc etc etc... this does not really exists and is what I was talking about. This is actually where I think we should make an effort to have a clean and stable API.

**Comment by Nodd** [comment]
We agree then: the parts where we need a clean and stable API are the parts where it's harder to do ! 
Also in this case I think the code is the best documentation. Written documentation should only explain the layout of the code so that anyone can navigate in it.

**Comment by goanpeca** [comment]
Cool, yes, we need to retake the writing `README.md` on each folder.... ;-).

I think we can have an example plugin project as a repo in github so people can make a copy of it and start from there.

**Comment by techtonik** [comment]
It is better to have a public API generator and track how it changes over time automatically. Then slowly carve stable or official-official API into some most used namespaces.

**Comment by techtonik** [comment]
By "generator" I really mean "scanner".

**Comment by ccordoba12** [comment]
My quick thoughts about this discussion:

1. About flexibility: I think that letting Spyder to be extended by other plugins is fine, but making (for example) codeeditor to be replaced by another editor component (like the one of PyQode) is way too much work for very little (or zero) gain. I simply won't accept something like that to be merged. Spyder has already too many moving parts to add a moving part of this kind! ;-)

2. About the *initial* public API (as defined by @Nodd): If someone can create a PR for it, I'd be really grateful. I'm not sure what's needed to be done here because I haven't created a new plugin from scratch :-)

3. About the *second* public API: I'd like if we could be pragmatical about it. We are not (at least not me) software engineers, so we don't need to break our heads defining something without knowing the needs of plugin creators. I'd just like to create the API according to the needs (or at least proposals) of them. I know, this sounds still organic, but most of the time planning things with too much care just leads to wasted time and rigid designs. I want things to depend on concrete proposals and not on some imagined scenarios :-)

**Comment by blink1073** [comment]
@Nodd, I think you are uniquely qualified to make the plugin API.  I would suggest making the "dock" optional for plugins that do not wish to provide one.  Perhaps a wiki would be a good place to hash this out?

**Pull request merged**
