### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by wojnilowicz**
## Description of Changes

Translated many Spyder menu entries to Polish because there was no Polish translation at all.

### Issue(s) Resolved

None

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
Łukasz Wojniłowicz

### CODE REVIEW

**Comment by goanpeca** [comment]
@wojnilowicz thanks for working on this

Would you be interested in working on more translations? The spyder team is now using https://crowdin.com/project/spyder to make the process easier for traslators and proofreeades.

**Comment by wojnilowicz** [comment]
> @wojnilowicz thanks for working on this

You're welcome.

> Would you be interested in working on more translations? The spyder team is now using https://crowdin.com/project/spyder to make the process easier for traslators and proofreeades.

I would like to work on more translations, but I would like it to be hassle free. I'm already happy with GitHub, and would not like to drudge in any review process.

Are you OK with accepting my translations through GitHub?

**Comment by wojnilowicz** [comment]
Bump.

**Comment by goanpeca** [comment]
@wojnilowicz 

>Are you OK with accepting my translations through GitHub?

Sure thing, no problem, Crowdin is easier for most audience but you are free to do it in a PR 👍 

Thanks for the help! (sorry for the delay!)

**Comment by wojnilowicz** [comment]
You said "no problem" but did not merge my PR. Is there any reason for that or you've just simply forgotten?

**Pull request closed without merging**
