### PR TITLE
Python LSP Server 1.9.0 has been released

### PR DESCRIPTION
**Pull request by penguinpee**
Set PyLSP upper bound to `<= 1.9.0`.

### CODE REVIEW

**Comment by dalthviz** [comment]
Hi @penguinpee thank you for your interest in contributing to Spyder! We will be releasing Spyder 5.5.0 shortly with the `python-lsp-server` constraint updated. To update the constraints for the `python-lsp-server` and other dependendencies we need to do further changes than the ones you did here so I will be closing this PR as superseded by https://github.com/spyder-ide/spyder/pull/21502

If you are interested in following up the 5.5.0 release or have any questions regarding the release you can check: https://github.com/spyder-ide/spyder/issues/21440

For further info about what steps we follow to do releases and how to contribute to Spyder you can check: 

* Release Guide: https://github.com/spyder-ide/spyder/blob/master/RELEASE.md
* Contribution Guide: https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md

Thank you again!

**Comment by penguinpee** [comment]
Thanks! Looking forward to the upcoming `5.5.0` release. Is there some roadmap somewhere regarding the plans for `6.x`?

**Comment by dalthviz** [comment]
No problem! Regarding a roadmap, we have https://github.com/spyder-ide/spyder/wiki/Roadmap (although is kind of outdated to be honest). For Spyder 6 (currently the `master` branch) we have some info in the announcements template for  alphas/betas (https://github.com/spyder-ide/spyder/blob/master/Announcements.md#alphabetarc-release) and the changelog (https://github.com/spyder-ide/spyder/blob/master/changelogs/Spyder-6.md). We also have some level of organization of things to do on GitHub milestones (https://github.com/spyder-ide/spyder/milestones) although that needs some prioritization and its subject to change at any moment.

Not sure if we have any other place where we are keeping info about Spyder 6 🤔. Just in case, pinging @ccordoba12 since maybe he can give a better picture about the plan behind Spyder 6. Also, now that I think about it, should we update the Roadmap wiki page @ccordoba12 ?

**Comment by ccordoba12** [comment]
> Just in case, pinging @ccordoba12 since maybe he can give a better picture about the plan behind Spyder 6

For now we're aiming to release Spyder 6 in three or four months. We're still ironing out several things, but you're welcome to test our alphas and report errors back.

> Also, now that I think about it, should we update the Roadmap wiki page @ccordoba12 ?

I'm not sure about it. Perhaps we should update it with our plans for Spyder 6.

**Comment by penguinpee** [comment]
> For now we're aiming to release Spyder 6 in three or four months. We're still ironing out several things, but you're welcome to test our alphas and report errors back.

That sounds great and would be right in time for the release of Fedora 40. 39 was released yesterday. We have `6.0.0a1` in rawhide (Fedora development branch). `6.0.0a2` is currently blocked due to the new `pyuca` dependency. I submitted that for review. But it needs a full license review for all the Unicode licenses.

Anyway, thanks for the insight (also to @dalthviz).

**Comment by penguinpee** [comment]
> > For now we're aiming to release Spyder 6 in three or four months. We're still ironing out several things, but you're welcome to test our alphas and report errors back.
> 
> That sounds great and would be right in time for the release of Fedora 40. 39 was released yesterday. We have `6.0.0a1` in rawhide (Fedora development branch). `6.0.0a2` is currently blocked due to the new `pyuca` dependency. I submitted that for review. But it needs a full license review for all the Unicode licenses.
> 
> Anyway, thanks for the insight (also to @dalthviz).

Apologies for asking in a closed ticket. But since the latest information I'm able to find is in this ticket, I felt this might be okay.

We are four month further and Fedora 40 is closing in on the final freeze before release, which will happen in about a month. As the package maintainer I need to take a decision on what version will be shipped in Fedora 40. Currently, we are still at 6.0.0a1. But I have everything lined up to update to 6.0.0a4. That's still a pre-release, but one I'm willing to maintain if there's a good chance of Spyder 6 being released within the coming two to three month.

Could you provide an update please?

**Pull request closed without merging**
