### PR TITLE
PR: Completely disable Kite provider (Completions)

### LINKED ISSUE #16595: Installing Kite takes forever
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
installing co-pilot takes forever on linux (ubuntu).
On my Win PC copilot successfully installed, the procedure was rather quick.
When I tried to do the same in my Linux Mint PC (Spyder5) -> I clicked Tool -> install Kite.
Now it started downloading a gondzillion of packages. I am waiting for 30 mins, the download is still ongoing?

Why do you do that ? It is already painful enough to keep the pace with the latest versions, now if each install would take hours, 
it is rather discouraging using spyder platform

### What is the expected output? What do you see instead?

1. Comprehensive single-package install and not 1000000000000 small packages to download to enable the copilot
2. Enable a simple install from conda, when one can see, what system actually does while downloading

## Versions

* Spyder version: 5.0.5 None
* Python version: 3.9.7 64-bit
* Qt version: 5.9.7
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-159-generic

### LINKED ISSUE #17108: How to remove Kite from Spyder completely
I want to remove all traces of the Kite plugin from Spyder installations completely to prevent it from ever nagging me to install or configure it.  

[![enter image description here][1]][1]
I don't trust it, and I don't want it anywhere on my machine.  

The Kite plugin has a history of being untrustworthy and monitors people's coding activity on their servers and examines one's source code "in order to improve the Kite product".  [https://news.ycombinator.com/item?id=14836653&p=2][2] 

Whether the realtime monitoring from their servers is true or not, I don't want installed it anywhere on my machine.  It is intrusive and interferes with coding.  The Python Language Server gives me all the coding hints and suggestions that I need.  

WHAT I TRIED: 

I tried deactivating it from Spyder Preferences... Advanced dialog box and restarting it (as shown below).  However, this does not remove it completely from the interface or the installation.  It appears on the menu after disabling it.  

WHAT I NEED: 

Remove it from the Spyder v4 and Spyder v5 installer distribution or conda package.  If Kite is willing to make the Kite Team Server completely free open source so anyone can install the AI engine(s) locally completely offline, completely free forever of all monetary charges or obligations, without ever contacting their servers for any reason, then I would let it stay.  I don't want a "freemium" edition installed either.  However, Kite is a commercial product and AFAIK, they have not made their AI code completion server engine(s) free open source.  

Does anyone know how to remove this suspicious and commercial product from the Spyder v4 and Spyder v5 installation and installers, so it never appears in any Spyder edition?

  [1]: https://i.stack.imgur.com/eGjoy.png
  [2]: https://news.ycombinator.com/item?id=14836653&p=2
  [3]: https://i.stack.imgur.com/Z0Io5.png

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

- Kite reached end-of-life last year, so we don't need to support it anymore.
- This does the minimal changes to disable Kite for now. After 5.3.0 is released, we can see how to remove it from our codebase.

### Issue(s) Resolved

Fixes #17108.
Fixes #16595.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @ccordoba12

### CODE REVIEW

**Review by dalthviz — APPROVED** [review]
Checked on Windows and seems like is working (no kite elements are being shown or launched and I can get completions) LGTM :+1:

**Comment by andfoy** [comment]
Shouldn't we remove the Kite source files?

**Comment by ccordoba12** [comment]
> Shouldn't we remove the Kite source files?

Yep, that's the idea but for a later release. For now @dalthviz and I decided that, given that we don't have much time available before the 5.3.0 release, the simplest thing we can do is to make the minimal changes to completely disable Kite. And that's what I did in this PR.

**Comment by dalthviz** [comment]
What do you think @andfoy ? Also let me know if you want to merge this or if I should do it once you approve

**Comment by andfoy** [comment]
I think it is ready to merge!

**Pull request merged**
