### PR TITLE
PR: Move Help plugin to a module

### PR DESCRIPTION
**Pull request by rlaverde**
First PR of the spyder modularization, the idea is to move each plugin, its widgets and utilities to a separate folder and follow the same structure for internal and external plugins

Example:

```
spyder/
    plugins/
        help/
            plugin.py
            confpage.py
            __init__.py
            utils/
                 exampleutils.py
            widgets/
                examplewigdet.py
```

`utils` and `wigdets` could be directories or just one file depending of the complexity

### CODE REVIEW

**Comment by rlaverde** [comment]
This is ready, and looks like this:

```
help/
├── confpage.py
├── __init__.py
├── plugin.py
├── tests/
│   └── test_help.py
├── utils/
│   ├── conf.py
│   ├── __init__.py
│   ├── js/
│   ├── sphinxify.py
│   ├── sphinxthread.py
│   ├── static/
│   ├── templates/
│   └── tutorial.rst
└── widgets.py

```

**Comment by ccordoba12** [comment]
@goanpeca, what do you say?

**Comment by ccordoba12** [comment]
Ok, let's merge this to keep things going on.

**Comment by goanpeca** [comment]
@ccordoba12 sphinxthread.py we could move this to use the workers :-) once we I get the pygments syntax PR merged

**Comment by ccordoba12** [comment]
Sure, no problem with that.

**Pull request merged**
