### PR TITLE
PR: Avoid that code analysis tree collapses on selection

### PR DESCRIPTION
**Pull request by oscargus**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

In the current master, the tree with code analysis issues collapses on selection:
beforefix

After this PR, no collapse:
afterfix

### Issue(s) Resolved

It does not solve #9564 but at least mitigates one of the issues mentioned there.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

Oscar Gustafsson/oscargus

### CODE REVIEW

**Comment by oscargus** [comment]
After checking the test reports, I must say that it is not really clear how my changes caused failing tests all over... I would even be tempted to say that I doubt the code change caused them...

**Comment by jitseniesen** [comment]
> I would even be tempted to say that I doubt the code change caused them...

@oscargus I think you are right, my PR fails with the same error.

**Comment by ccordoba12** [comment]
@oscargus, please rebase or merge with master to fix the errors in our tests.

**Comment by oscargus** [comment]
Thanks! Still some errors which I think is unrelated:

Travis 2.7 and 3.7 with conda
```
spyder/app/tests/test_mainwindow.py::test_lock_action 
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

Travis 3.6 with conda
```
Traceback (most recent call last):
  File "/home/travis/build/spyder-ide/spyder/spyder/plugins/editor/lsp/manager.py", line 244, in send_request
    client.perform_request(request, params)
  File "/home/travis/build/spyder-ide/spyder/spyder/plugins/editor/lsp/client.py", line 327, in perform_request
    _id = handler(params)
  File "/home/travis/build/spyder-ide/spyder/spyder/plugins/editor/lsp/decorators.py", line 42, in wrapper
    _id = self.send(method, params, kind)
  File "/home/travis/build/spyder-ide/spyder/spyder/plugins/editor/lsp/client.py", line 270, in send
    self.zmq_out_socket.send_pyobj(msg)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/zmq/sugar/socket.py", line 606, in send_pyobj
    return self.send(msg, flags=flags, **kwargs)
  File "/home/travis/miniconda/envs/test/lib/python3.6/site-packages/zmq/sugar/socket.py", line 395, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq/backend/cython/socket.pyx", line 725, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 772, in zmq.backend.cython.socket.Socket.send
  File "zmq/backend/cython/socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Socket operation on non-socket
```

Same problems on the cancelled and failing Azure pipeline tests, respectively.

**Comment by ccordoba12** [comment]
Please merge with master to get a new set of fixes for our tests.

**Comment by oscargus** [comment]
Fewer and fewer failures. Still seems to be a problem with `ZMQError` for Windows tests on Azure pipelines though:

```
Qt exceptions in virtual methods:
________________________________________________________________________________
Traceback (most recent call last):
  File "D:\a\1\s\spyder\plugins\editor\lsp\manager.py", line 244, in send_request
    client.perform_request(request, params)
  File "D:\a\1\s\spyder\plugins\editor\lsp\client.py", line 327, in perform_request
    _id = handler(params)
  File "D:\a\1\s\spyder\plugins\editor\lsp\decorators.py", line 42, in wrapper
    _id = self.send(method, params, kind)
  File "D:\a\1\s\spyder\plugins\editor\lsp\client.py", line 270, in send
    self.zmq_out_socket.send_pyobj(msg)
  File "C:\Miniconda\envs\test\lib\site-packages\zmq\sugar\socket.py", line 606, in send_pyobj
    return self.send(msg, flags=flags, **kwargs)
  File "C:\Miniconda\envs\test\lib\site-packages\zmq\sugar\socket.py", line 395, in send
    return super(Socket, self).send(data, flags=flags, copy=copy, track=track)
  File "zmq\backend\cython\socket.pyx", line 725, in zmq.backend.cython.socket.Socket.send
  File "zmq\backend\cython\socket.pyx", line 772, in zmq.backend.cython.socket.Socket.send
  File "zmq\backend\cython\socket.pyx", line 247, in zmq.backend.cython.socket._send_copy
  File "zmq\backend\cython\socket.pyx", line 242, in zmq.backend.cython.socket._send_copy
  File "zmq\backend\cython\checkrc.pxd", line 25, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Unknown error
```

(I do not fully understand how some PRs seems to pass without these issues and some not...)

**Comment by ccordoba12** [comment]
> (I do not fully understand how some PRs seems to pass without these issues and some not...)

Unfortunately some tests are very flaky, so they need to be run several times. Please don't worry about them.

**Comment by oscargus** [comment]
> Unfortunately some tests are very flaky, so they need to be run several times. Please don't worry about them.

OK, good to know for possibly later contributions!

**Pull request merged**
