### PR TITLE
PR: Remove unmaintained pytest-ordering package

### PR DESCRIPTION
**Pull request by bnavigator**
## Description of Changes

pytest-ordering is not maintained and broken:
https://github.com/ftobia/pytest-ordering/issues/73

This PR removes it. Tests should be written in a way that they are independent of each other.

Alternatively, if the order of tests is really needed, you may consider using forked and maintained https://github.com/pytest-dev/pytest-order with more concise mark names.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: bnavigator

### CODE REVIEW

**Comment by ccordoba12** [comment]
> Alternatively, if the order of tests is really needed, you may consider using forked and maintained https://github.com/pytest-dev/pytest-order with more concise mark names.

You're welcome to help us migrate our tests to `pytest-order`. Otherwise, you'll have to wait until we have time to do this because things are working fine for us with Pytest 5 (our current requirement).

**Comment by bnavigator** [comment]
I reverted the removal and replaced with marks from pytest-order instead.

Conda does not have pytest-order yet :(

**Comment by ccordoba12** [comment]
> I reverted the removal and replaced with marks from pytest-order instead.

Thanks for your help @bnavigator!

> Conda does not have pytest-order yet :(

I added the requirement to our own Anaconda channel to fix that in the meantime.

**Review by ccordoba12 — APPROVED** [review]
Thanks @bnavigator!

**Review by ccordoba12 — APPROVED** [review]

**Pull request merged**
