### PR TITLE
Fixed 'send_workspace_folders_change' parameters for python-language-server

### LINKED ISSUE #11654: Fix request_params in send_workspace_folders_change
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [x] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted Spyder
    * [x] Reset preferences with ``spyder --reset``
    * [x] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Ticket creation suggest by @goanpeca [here](https://github.com/palantir/python-language-server/pull/749#issuecomment-591103381).

The [python-language-server](https://github.com/palantir/python-language-server/) call for `m_workspace__did_change_workspace_folders` changed in [pyls#749](https://github.com/palantir/python-language-server/pull/749).

The parameters changed according to microsofts language-server-protocol spec for [`DidChangeWorkspaceFolders`](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWorkspaceFolders).

In fact the `request_params` must be changed in [spyder/spyder-ide/workspace.py](https://github.com/spyder-ide/spyder/blob/47726b4d3d297b4bfbe6351905b6c44ef2b71e93/spyder/plugins/completion/languageserver/providers/workspace.py#L67) to

```
        request_params = {
            'event': {
                'added': added_folders,
                'removed': removed_folders
             }
        }
```

### What steps reproduce the problem?

1.  Use python-language-server 0.32 if released
2.  Try `send_workspace_folders_change`

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

### PR DESCRIPTION
**Pull request by zerocewl**
Fixed `send_workspace_folders_change` parameters for code completion with python-language-server 0.32 

Depending PR in python-language-server: [#749](https://github.com/palantir/python-language-server/pull/749)

## Description of Changes

* adapted `request_params` in `send_workspace_folders_change` according to [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_didChangeWorkspaceFolders) of language client and changes in python-language-server
* adapted required python-language-server version

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #11654

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12 this should go against 4.x branch?

**Comment by andfoy** [comment]
@zerocewl This requires a merge with upstream in order to fix CIs

**Comment by andfoy** [comment]
@ccordoba12 I think we should close this one, as #12812 supersedes it

**Comment by ccordoba12** [comment]
Closing in favor of #12812.

**Pull request closed without merging**
