### PR TITLE
PR: Update ArrayEditor to correct deprecated Numpy operator

### PR DESCRIPTION
**Pull request by GKosiba**
Changed numpy boolean subract operator '-' to np.logical_xor. As suggested in the numpy deprec warning.
Tested locally with no error originally described in #4663

### CODE REVIEW

**Comment by ccordoba12** [comment]
Is this backwards compatible? I mean, does it work with previous Numpy versions?

**Comment by ccordoba12** [comment]
And of course. thanks a lot for your contribution!!

**Comment by jitseniesen** [comment]
What about when the array loaded in the variable explorer does not have boolean entries?

**Comment by GKosiba** [comment]
Sorry, didn't have a lot of time yesterday, but that wasn't a fix.
Essentially this line is scaling the hue of each index in the pop-up 'array' window relative to the maximum value in the array. 

This new edit calculates this scaling factor (max-value)/(max-min) with max as float each time. The issue only occurs for boolean with the deprecated minus operator but float of 0 or 1 minus value of 0 or 1 gives the same value for the scaling factor and was converted to float anyways in the next line.

Tested with bool and non-bool array types and older numpy versions.

**Comment by ccordoba12** [comment]
@jitseniesen, do you approve this one?

**Comment by jitseniesen** [comment]
@GKosiba Looks good; but one detail: could you please add a short comment explaining why the conversion to `float` is there? e.g. "convert to float to handle bool arrays". I am afraid the conversion will puzzle us later.

**Comment by GKosiba** [comment]
@ccordoba12 @jitseniesen Comment added

**Comment by ccordoba12** [comment]
Thanks @GKosiba for your contribution and @jitseniesen for reviewing it.

This is going in!

**Pull request merged**
