### PR TITLE
PR: Update conda-based installers

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

* Added `StartupWMClass` to Linux desktop file. This obviates the need to change the name of the desktop file in the post-install script.
* Minor CI workflow updates

### CODE REVIEW

**Comment by mrclary** [comment]
@dalthviz @ccordoba12 I'm having trouble getting the Windows test to work properly; perhaps you guys have some insight.

The following should execute the `exe` installer from the `bash` command line in silent mode:
```bash
$ cmd.exe /C start /wait "<path to exe>" /S
```
I've successfully tested on my Windows VM (with bash shell), but can't get it working in CI. From the logs it appears that `cmd.exe` is executed but the executable path is not resolved properly: the `cmd.exe` banner is printed but the installer does not run.

**Comment by ccordoba12** [comment]
> The following should execute the exe installer from the bash command line in silent mode

I can see that you're not using a Bash shell to run the installer tests on Windows (i.e. there's no `shell: bash` in the `Test Installer Application` step). And I think the default shell used by Github Actions on Windows is `cmd`.

**Comment by mrclary** [comment]
> I can see that you're not using a Bash shell to run the installer tests on Windows (i.e. there's no `shell: bash` in the `Test Installer Application` step). And I think the default shell used by Github Actions on Windows is `cmd`.

Hmm. For the `build-installers` job I am using a default shell `defaults: run: shell: bash -l {0}`, and the `Test Application Bundle` step is a bash script. And in the same step I've confirmed `[[ -e "$PKG_FILE" ]] && echo "Installer exists" || echo "Installer does not exist"` successfully reports that the `$PKG_FILE` exists while running in Windows.

**Comment by ccordoba12** [comment]
Ok, sorry for the noise.

**Comment by mrclary** [comment]
> Ok, sorry for the noise.

No worries, thanks for looking at it.

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @mrclary!

**Pull request merged**
