### PR TITLE
PR: Fix completion order for lower/upper case entries

### LINKED ISSUE #10109: Incorrect Kite completions ordering
Kite completions are not ordered correctly. See the following example in Spyder:

image

The completions ordering returned by the Kite engine should be maintained, as in the following example from VS Code:

Screen Shot 2019-08-29 at 9 31 47 AM

### PR DESCRIPTION
**Pull request by andfoy**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)
* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Fixed completion entries order depending on the first letter of the word to complete.

ezgif com-video-to-gif(10)

### Issue(s) Resolved

Fixes #10109

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@andfoy

### CODE REVIEW

**Comment by ccordoba12** [comment]
@andfoy, a test is missing for this.

**Comment by ccordoba12** [comment]
Another thing @andfoy: there are two repeated entries for `import` in the screenshot you uploaded above: one for keywords (the first one) and one for text (the last one).

**Comment by andfoy** [comment]
> Another thing @andfoy: there are two repeated entries for import in the screenshot you uploaded above: one for keywords (the first one) and one for text (the last one).

It is strange, because when I inspect the entries supplied to the completion widget, there's a single entry.

**Comment by andfoy** [comment]
@ccordoba12 Kite returns an "import " (note the space at the end) completion

**Comment by ccordoba12** [comment]
> Kite returns an "import " (note the space at the end) completion

Ok, I understand that now. Thanks for taking a look at it.

**Pull request merged**
