### PR TITLE
PR: [Do not merge!] Line endings and .gitattributes

### LINKED ISSUE #2335: SNAFUed linefeeds between 2.3 and master
I tried to transplant some changes from `master` to branch and got nasty linefeed conflict through the whole file. I guess that bd13f67058fa4e247 is the culprit. Carlos, can you clarify what's going on?

In particular:

1. what you was trying to fix?
2. why the file ended up with mixed linefeeds?
3. and why did you choose to have different linefeeds for master and for branch?
4. and why did you choose CRLF linefeeds for master?

I am pretty concerned about that, because the history is messed up, it spoils the blame and gives me a headaches with version control system that's already complicated enough.

The perfectionist in me prefers that we rewrite/rebase the history to use unix linefeeds while importing to git.

Ping @ccordoba12.

### PR DESCRIPTION
**Pull request by Nodd**
Fixes #2335

----

Here is the result after normalizing end of lines by adding a `.gitattributes` file (see #2335).

This PR is not to be merged, a new clean PR would have to be made, this is just an example.

With this I'll be first in the repo stats in category *huge commit* and *most modified lines*! :laughing:

### CODE REVIEW

**Comment by goanpeca** [comment]
We should set a date for this

**Comment by Nodd** [comment]
Well *someone* should stop creating so many new PR so that we can freely break everything with line endings ! :stuck_out_tongue_winking_eye: 

More seriousely, the PR itself is very easy to recreate. I'll put the steps here for reference (to be done from a clean repo):
1. Create `.gitattributes` witht the following content:
```
# Set the default behavior, in case people don't have core.autocrlf set.
* text=auto
```
2. Commit the file
3. Remove every files from git index: `git rm --cached -r .`
4. Restore the repo: `git reset --hard`
5. Commit every changed files: `git add . && git commit -m "Normalize all the line endings"`

(Meh, the list number is restarted after the code block...)

These steps are taken from https://help.github.com/articles/dealing-with-line-endings/#per-repository-settings.

**Comment by goanpeca** [comment]
If we set a date, we can stop making PRs :-p.

**Comment by SylvainCorlay** [comment]
I would really like this to get in after the new icons since I modify over 60 files. It will be a pain to rebase.

**Comment by goanpeca** [comment]
Any tentative roadmap for the icons?

**Comment by SylvainCorlay** [comment]
- I pushed some changes where icons are called via a simple icon manager. Next commit will be re-enabling the old theme using the same icon names and having an option in the preferences to choose for the theme. Then it should be merge-able. 
- I would prefer not to get into too much bikeshedding over individual icon design besides the main toolbars and improve the Spyder font incrementally. There are over 160 icon names overall.

**Comment by goanpeca** [comment]
Sure, as long as a simple icon manager is in place we can merge and improve from there, otherwise we will never merge or progress

**Comment by SylvainCorlay** [comment]
I want to make a non backward compatible change to qtawesome and reflect it in the pr as well (Make the list of icons be pargs rather than an array in case of a stack).

**Comment by ccordoba12** [comment]
@Nodd, this PR only changes line endings, right? We must not touch blanks at all because that will make things a real nightmare for current contributors.

I read somewhere that there's a simple way to rebase a PR so as to make line endings compatible with `gitattributes`, but I don't remember which one was :-)

**Comment by Nodd** [comment]
@SylvainCorlay The plugin modifications modifies 40+ files, I fully understand your point!

@ccordoba12 Yes, it only changes line endings.
But in #2335 many of us were in favor of normalizing the repo, including blank space. Why is it more problematic for the blank spaces than the line endings ?

**Comment by blink1073** [comment]
I'm in favor of razed earth on the trailing whitespace.  I've had to undo so many PR changes where my editor trimmed trailing whitespaces.

**Comment by techtonik** [comment]
> I'm in favor of razed earth on the trailing whitespace. I've had to undo so many PR changes where my editor trimmed trailing whitespaces. 

The proper way is to that option to Spyder, so that it doesn't save modified lines with trailing whitespaces.

**Comment by goanpeca** [comment]
@nodd, we should close this, right?

I still think is a good idea, but could we tackle it in small pieces? and then activate the `.gitattrributes`

**Comment by ccordoba12** [comment]
@Nodd, what's your final word on this one? Should we close it or not?

**Comment by Nodd** [comment]
I agree with @goanpeca, no one wants a big PR modifying almost every file in the repo for maodifications on whitespace that are not visible anyway. We should first fix the files little by little, then add .gittattributes or travis checks (or both).
Maybe it should be taken into account in the roadmap or something, and guidelines for code style (do we have one?) should state that we'll get there little by little.

In the meantime I'm closing it, it's not mergeable anyway.

**Comment by techtonik** [comment]
> Maybe it should be taken into account in the roadmap or something, and guidelines for code style (do we have one?) should state that we'll get there little by little.

+1 for LF milestone and guidelines with Travis style checker for commits with modified lines.

**Comment by goanpeca** [comment]
@Nodd yes we do... its called the wiki and you can search for info there :laughing:

Ok... it is not super complete but it is a starting point, what should the guideline say??

https://github.com/spyder-ide/spyder/wiki/Dev%3A-Coding-Style

**Comment by goanpeca** [comment]
@spyder-ide/core-developers is there a way to add a check on linefeed and spaces only on added or modified lines in git? like the diff only?

**Comment by Nodd** [comment]
I opened up an issue for the checks.
The wiki states what we want, but doesn't talk about keeping trailing whitespaces to not clutter PRs or things like this, or how we want to migrate towards a clean codebase.

**Comment by goanpeca** [comment]
Well the general not so intrusive approach is... make sure the new code does not introduce spaces or problems and adapt the surrounding code up to a defined limit for cleaning. Like this we start to get patches of clean code.

I am more than willing to make single file PRs where we do line and import cleanup.

**Pull request closed without merging**
