### PR TITLE
PR: Fix 1D Numpy arrays edition in the Variable Explorer

### LINKED ISSUE #5014: BUG: Error editing element of numpy array in variable explorer
## Description

**What steps will reproduce the problem?**
1. Enter the following in the editor
```python
import numpy as np
b = np.arange(4)
```

2. Open `b` in variable explorer

3. Double click on the first element and change it from 0 to 5

4. Click OK

5. Got this error report pop up

  File "/Users/measejm1/anaconda/envs/python3_general/lib/python3.6/site-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 384, in setEditorData
    text = from_qvariant(index.model().data(index, Qt.DisplayRole), str)
  File "/Users/measejm1/anaconda/envs/python3_general/lib/python3.6/site-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 253, in data
    value = self.get_value(index)
  File "/Users/measejm1/anaconda/envs/python3_general/lib/python3.6/site-packages/spyder/widgets/variableexplorer/arrayeditor.py", line 247, in get_value
    return self.changes.get((i, j), self._data[i, j])
IndexError: too many indices for array

**What is the expected output? What do you see instead?**
Expected the first element to be changed to 5 in the workspace

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.0
* Qt Versions: 5.6.2, PyQt5 5.6 on Darwin

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.1.3 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.12.1 (OK)
sphinx >=0.6.6   :  1.5.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.0.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
sympy >=0.7.3    :  1.0 (OK)
cython >=0.21    :  0.25.2 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #5014

### CODE REVIEW

**Comment by goanpeca** [comment]
@andfoy can we write a test for this that covers the 1D 2D case and handles this regression ?

**Comment by goanpeca** [comment]
Just to double check @andfoy did the test fail without the fix :-p ?

**Comment by andfoy** [comment]
I didn't test it under the actual scenario, let me check

**Comment by andfoy** [comment]
It seems that is passing successfully for some reason

**Comment by goanpeca** [comment]
@andfoy thats the magic of regression testing :-), test should fail without the fix ;-)

**Comment by andfoy** [comment]
So what's happening with #5014?

**Pull request merged**
