### PR TITLE
PR: Backport PR #4210

### PR DESCRIPTION
**Pull request by ccordoba12**
Backport PR #4210 to the 3.x branch.

### CODE REVIEW

**Comment by rlaverde** [comment]
I has a little error due to a typo, could you fix it before merging? https://github.com/spyder-ide/spyder/pull/4210#discussion_r103460937

**Comment by ccordoba12** [comment]
@github, are your webhooks dead or what? Our tests are not starting with new commits :-)

**Comment by ccordoba12** [comment]
@rlaverde, do you approve this one

**Comment by rlaverde** [comment]
> @rlaverde, do you approve this one?

Yes, thanks for implementing my comments :smile:

**Pull request merged**
