### PR TITLE
Update French translations

### LINKED ISSUE #2190: Update French translations for 2.3.3
@SylvainCorlay or @Nodd, can you help me with this one? The sooner it'd be the better because this is the last thing to do before releasing 2.3.3

Please remember to submit the PR against the **2.3** branch, and not against master.

### PR DESCRIPTION
**Pull request by SylvainCorlay**
I did not translate `notebook`. I don't fell like using the translation would make sense in the current context.
I still have a doubt on whether I should translate `DataFrame` or not. 

Fixes #2190

### CODE REVIEW

**Comment by ccordoba12** [comment]
I think leaving `notebook` and `DataFrame` is fine (I left them in Spanish).

@goanpeca would you mind to take a quick look at this one?

**Comment by SylvainCorlay** [comment]
OK, then I will rebase and use `DataFrame` as well.

**Comment by goanpeca** [comment]
Looks good :+1:

**Comment by goanpeca** [comment]
what happened here?
```
"It was not possible to convert this notebook. The error is:\n"
 "\n"
 msgstr ""
+"Impossible de convertir ce notebook:\n"
+"\n"
```
The translation of "The erros is:??

**Comment by SylvainCorlay** [comment]
I just thought that having something like `L'erreur est:` sounded weird. I was hesitating between nothing and `Message d'erreur:` 

Actually `It was not possible to convert this notebook. The error is:\n`  is a bit verbose, just as something to be displayed before the exception message.

**Comment by goanpeca** [comment]
`L'erreur est:` sounds horrible! haha

`Message d'erreur:` much better, but here you are the native so you decide on that, otherwise the rest seemed fine :+1

**Comment by SylvainCorlay** [comment]
Rebased. Now using `DataFrame` in French and added `Message d'erreur`...

**Comment by ccordoba12** [comment]
Great!! Thanks for this!

**Pull request merged**
