### PR TITLE
PR: Fix the same font in Preferences and update action icons (Online Help)

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

A preview:

image

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by goanpeca** [comment]
Looks good! Let me check on my mac :-)

**Comment by ccordoba12** [comment]
I asked @dalthviz if we could use in the Online Help the same font we're using in Help. He'll try to do that next week.

**Comment by goanpeca** [comment]
Ok, let me know when I can test this @dalthviz

**Comment by dalthviz** [comment]
@goanpeca @ccordoba12 I think this is ready for a review

**Comment by goanpeca** [comment]
Ok @dalthviz checking now

**Comment by ccordoba12** [comment]
@dalthviz, I have one question: is the font in the Online Help automatically updated when you change our rich text font in Preferences?

**Comment by dalthviz** [comment]
It should take the new font but you will need to reload the online help to see the change or request a new page (click a link to request new html) I think

**Comment by goanpeca** [comment]
>It should take the new font but you will need to reload the online help to see the change or request a new page (click a link to request new html) I think

Could then just trigger the refresh action?

**Comment by ccordoba12** [comment]
I agree. We should do that automatically.

**Pull request merged**
