### PR TITLE
PR: Fix "Show in external file explorer" for non-existing file (Windows)

### PR DESCRIPTION
**Pull request by rear1019**
## Description of Changes

See commit message for details.

PS: The same action in right-click menu of editor’s tabs is possibly affected as well.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

rear1019

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @rear1019, thanks for your help with this! You said:

> PS: The same action in right-click menu of editor’s tabs is possibly affected as well.

Do you plan to check, and if failing fix, that as part of this pull request?

**Comment by rear1019** [comment]
> Hey @rear1019, thanks for your help with this! You said:
> 
> > PS: The same action in right-click menu of editor’s tabs is possibly affected as well.
> 
> Do you plan to check, and if failing fix, that as part of this pull request?

Just confirmed that the patch also fixes the action in the right-click menu of editor’s tabs (the button in the right corner of the tabbar displays the same menu object).

**Comment by ccordoba12** [comment]
Great! Thanks for confirming that @rear1019!

**Review by ccordoba12 — APPROVED** [review]
Thanks for your help with this @rear1019!

**Pull request merged**
