### PR TITLE
PR: Cleanup test_mainwindow tests

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
@impact27, do you think this is ready? I mean, it seems this PR makes the main window tests a bit flaky.

**Comment by impact27** [comment]
I think this is read. I think the flaky tests are mainly ipythonconsole, which is addressed in #10464.
What makes you say that the tests are flaky in mainwindow?

In travis the failure are:
`spyder/plugins/editor/widgets/tests/test_introspection.py::test_hide_widget_completion` always fails once
`spyder/plugins/ipythonconsole/comms/tests/test_runcell.py::test_runcell[False]` 1 time
`spyder/plugins/editor/widgets/tests/test_introspection.py::test_completions` 1 time
`spyder/plugins/projects/tests/test_plugin.py::test_filesystem_notifications` 1 time

The only one in `test_mainwindow.py` is:
`spyder/app/tests/test_mainwindow.py::test_report_comms_error` 1 time (l.2041)

in azure:
`spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py` segfaults
`spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py::test_cython_client` fails once

**Comment by ccordoba12** [comment]
> What makes you say that the tests are flaky in mainwindow?

Because you closed and opened this PR above. Sorry, I didn't check the logs.

**Comment by impact27** [comment]
I did that because circleci failed. I think this is unrelated

**Pull request merged**
