### PR TITLE
PR: Save project recent files as relative paths in workspace.ini

### LINKED ISSUE #5491: Relative paths in workspace.ini to make projects moveable
## Description of your problem

**What steps will reproduce the problem?**

1. Add a new project `Projects > New project...`
2. Open some files.
3. Close Spyder.
4. Copy the whole project's directory to another computer to a different path (or have it synced with other means to different directories, e.g. `/home/mm/Software/Project` and `/home/MickeyMouse/Work/Software/Project` for your home and work computers).
5. Open the project on the other computer.

**What is the expected output? What do you see instead?**

I would like to see the same files opened automatically on both computers when opening the project, but the `.spyproject/workspace.ini` file stores the full paths in `[main]recent_files`. If the paths were stored relative to `.spyproject/..` (the project's base directory), it would be possible to move the project to a different location.

**Please provide any additional information below**

There seems to be two related bugs: #1133 and #1343. Maybe more?

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.5.2 64bits
* Qt Version: 5.5.1
* PyQt Version: 5.5.1
* Operating system: Linux Mint 18.2 Cinnamon 64-bit

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:

IPython >=4.0    :  6.1.0 (OK)
cython >=0.21    :  None (NOK)
jedi >=0.9.0     :  0.10.2 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
numpy >=1.7      :  1.12.0 (OK)
pandas >=0.13.1  :  0.19.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pyflakes >=0.6.0 :  1.6.0 (OK)
pygments >=2.0   :  2.2.0 (OK)
pylint >=0.25    :  1.7.2 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
rope >=0.9.4     :  0.10.7 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
sympy >=0.7.3    :  1.0 (OK)

### PR DESCRIPTION
**Pull request by Keou0007**
## Description of Changes

* When closing a project, recent_files are written to workspace.ini relative to project root_path
* Relevant tests changed to expect the recent files fetched from workspace.ini to be relative paths from project root

This allows better portability of projects. Project directories can be moved, or stored in different locations on different systems, and opening the project will still successfully open all the recent files into tabs.

### Issue(s) Resolved

Fixes #5491

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Shannon Keough

### CODE REVIEW

**Comment by ccordoba12** [comment]
Please merge with master to get a new set of fixes for our tests.

**Comment by ccordoba12** [comment]
@goanpeca, please review @Keou0007's work.

**Comment by Keou0007** [comment]
@goanpeca Do I need to do anything with this now? I got a notification saying you've assigned it to me, but merging is blocked for me because I'm not authorised.

**Comment by goanpeca** [comment]
>@goanpeca Do I need to do anything with this now? I got a notification saying you've assigned it to me, but merging is blocked for me because I'm not authorised.

No need, we will merge this tomorrow :-)

Thanks!

**Comment by ccordoba12** [comment]
Thanks a lot @Keou0007 for your contribution!

**Pull request merged**
