### PR TITLE
PR: Fix background color of information icon in File Switcher

### LINKED ISSUE #9442: Information icon in File Switcher is not themed under the dark theme
### Issue Report Checklist

Originally discussed on #8068 .

Under the dark theme, the "information" icon in the file switcher is still not themed, as seen in #8616 .

image

## Versions

* Spyder version: 4.0.0 latest ``master``
* Python version: 3.7.3
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1 x64

### Dependencies

```
qdarkstyle 2.6.8
```

### PR DESCRIPTION
**Pull request by juanis2112**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Removed  background and border color to information icon in file switcher so that it uses MAIN_FG_COLOR. 

Screen Shot 2019-05-30 at 5 50 13 PM

### Issue(s) Resolved

Fixes #9442 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

Juanis2112

### CODE REVIEW

**Comment by ccordoba12** [comment]
@juanis2112, this doesn't look on Linux:

Selección_005

(and please also check how it looks on Windows).

So you need to adjust things for each operating system.

**Comment by ccordoba12** [comment]
@juanis2112, please address my previous comment. As you can see, the information icon is almost not visible on Linux (although it's fine on macOS, according to your first screenshot).

And you also need to check how things look on Windows.

**Comment by juanis2112** [comment]
@ccordoba12  Sorry I missed the last comment. I will check it now

**Comment by ccordoba12** [comment]
No worries :+1:

**Comment by dalthviz** [comment]
@juanis2112 @ccordoba12 this is a preview on Windows just in case:

info

**Comment by ccordoba12** [comment]
Ok, thanks @dalthviz! So things look well everywhere, except in KDE (which is my Linux desktop environment). But I think that's a very small detail for @juanis2112 to invest more time on it.

**Pull request merged**
