### PR TITLE
PR: Add Rtree and other fixes for the macOS app

### LINKED ISSUE #14243: Add wheel for rtree to Mac installer
We don't declare `rtree` as a dependency in our `setup.py` because it's a binary package and doesn't have wheels in PyPI.

So to add it to the Mac app we'd have either to find a Mac wheel for it (easy) or to compile it in Github Actions (hard).

@mrclary, could you take a look at this one?

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

Snippets are now fully functional in the macOS application. It turns out that we don't need a wheel for Rtree, but just need to include the `spatialindex` libraries in the `py2app` setup file.

Also fixed issue (since PR #14332) where macOS app and bootstrap (non-conda) fail to launch with error
```python
Traceback (most recent call last):
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/status.py", line 336, in update_envs
    self.update_interpreter()
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/status.py", line 398, in update_interpreter
    self.value = self._get_env_info(self._interpreter)
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/widgets/status.py", line 386, in _get_env_info
    import pdb; pdb.set_trace()
KeyError: 'internal'
```

### Issue(s) Resolved

Fixes #14243

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@mrclary

### CODE REVIEW

**Comment by mrclary** [comment]
@ccordoba12, FYI

**Comment by ccordoba12** [comment]
Thanks! I was planning to work on the environments issue this weekend (I already have an idea on how to solve it).

**Comment by mrclary** [comment]
The dmg creation has always been plagued by `hdiutil` timeout and OpenGL issues, but only on GitHub ci and never on my local machine. These don't seem to have an adverse affect on the final output; nevertheless I've tried to resolve them, but have been unsuccessful. I've tried patching `dmgbuild` to use `sudo` as well as `-verbose`, neither of which revealed anything.

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary for your help with this!

**Pull request merged**
