### PR TITLE
Add 'Show in finder' option in file explorer

### PR DESCRIPTION
**Pull request by impact27**

### CODE REVIEW

**Comment by andfoy** [comment]
@impact27 Thanks for your contribution, however, you must take in account that the ```open``` command is not available on other OS like Linux and Windows

**Comment by andfoy** [comment]
This should be of your interest:

```python
def open_file(filename):
    if sys.platform == "win32":
        os.startfile(filename)
    else:
        opener = "open" if sys.platform == "darwin" else "xdg-open"
        subprocess.call([opener, filename])
```

**Comment by impact27** [comment]
Sure but then it should not be called "open in finder" but open in file explorer? Anyway I added a verification for the os (OSX is Darwin) so It should only appear on mac.

**Comment by impact27** [comment]
Maybe open in external file explorer?

**Comment by andfoy** [comment]
I agree that it should be called ``Open in File Explorer``

**Comment by andfoy** [comment]
@impact27 Can you rebase and compare this PR against ``3.x`` branch?

**Comment by impact27** [comment]
I am unsure what you want me to do. Should I open a new PR with https://github.com/impact27/spyder/tree/3.x?
Regarding window and linux, I am not sure how to "Show in external explorer" and I don't have these OS to test. Maybe the feature can be added for mac and more work can be done later to add Window and Linux compatibility?

**Comment by ccordoba12** [comment]
@impact27, thanks a lot for your contribution.

> Should I open a new PR with https://github.com/impact27/spyder/tree/3.x?

If you want your contribution to be part of Spyder 3.2, yes, you need to reopen your PR against that branch. However, if you don't mind to wait until Spyder 4 for others to use this, then you can leave things as they are.

Note: Spyder 4 is at least 6 months away to be released, it could be more.

**Comment by goanpeca** [comment]
@ccordoba12 closing this one?

**Comment by ccordoba12** [comment]
Yep. @impact27, we'll merge your other PR, and then internally merge it with master.

Thanks a lot for your patience with our internal procedures.

**Pull request closed without merging**
