### PR TITLE
PR: Include QDarkStyle as an explicitly installed dep for the dev builds in the Contributing Guide

### PR DESCRIPTION
**Pull request by leportella**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based this PR on the latest version of the correct branch (master or 3.x)
* [ ] Followed [PEP 8](https://www.python.org/dev/peps/pep-0008/) code style
* [ ] Ensured this pull request hasn't eliminated unrelated blank lines/spaces,
      modified the ``spyder/defaults`` directory, or added new icons/assets
* [ ] Wrote at least one-line docstrings following PEP 257for any new functions
* [ ] Added at least one unit test covering the changes, if at all possible
* [x] Described the changes and the motivation for them below
* [ ] Noted what issue(s) this pull request resolves, creating one if needed
* [ ] Included a screenshot, if this PR makes any visible changes to the UI

## Description of Changes

I was following the `CONTRIBUTING` file to contribute to Spyder and after doing all the installation using the `conda`s commands, I still ended up with dependencies problems. Specifically, I had trouble with the `QDarkStyle` package. After I run the command `pip install -r requirements/requirements.txt` it worked. So, I added a line saying that if the user had trouble with dependencies he/she should run this command, to fix it. 

### Issue(s) Resolved
No issues on this

Fixes #

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
> Specifically, I had trouble with the QDarkStyle package. 

You just needed to install QDarkStyle (``pip install qdarkstyle``), presumably.

> pip install -r requirements/requirements.txt

The problem is this will install/update all the dependencies using ``pip``, which is a recipe for problems especially if the user runs it in existing environment that may have older versions than the ``pip`` ones, especially  `` base``.

The basic issue here is the dependencies for the development Spyder are different from those for the latest beta; right now that is the case since we have PyLS, QDarkStyle, etc. as deps for Spyder dev but not beta 1, which was released a long time ago. Instead of this change, we should instead just add the necessary dep(s) to the line that already tells the user to explicitly install PyLS. Of course, this won't be an issue anymore in a week or two when Beta 2 is released and we'll have to update this anyway, so with only a few reports of this I'm not sure its worth doing but if you want to go ahead.

**Comment by leportella** [comment]
I understand the problem of adding the requirements. Sorry! I just added it on the dependencies. Hope it is right :)

**Comment by CAM-Gerlach** [comment]
@leportella For a neater commit history, since the change is so trivial and the first commit is entirely redundant, can you make the change in one commit (squash them, ``rebase -i`` then edit or fixup, ``git reset HEAD~2`` then commit again, etc)? And while your at it, if you don't mind starting the commit with a capital letter per convention. Thanks!

**Comment by ccordoba12** [comment]
Closing in favor or PR #8299.

**Pull request closed without merging**
