### PR TITLE
Fixed Solarized Theme Colour Constrast

### PR DESCRIPTION
**Pull request by grantcarthew**
## Description of Changes

I added the solarized colour themes a few years ago. Ref: https://github.com/spyder-ide/spyder/pull/3534

The colour contrast was off.
I fixed it.

* [n/a ] Wrote at least one-line docstrings (for any new functions)
* [n/a ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

## Dark Old
image

## Dark New
image

## Light Old
image

## Light New
image

### Issue(s) Resolved

Fixes #
Fixed colour contrast in the Solarized Light and Dark colour themes.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

Grant Carthew

### CODE REVIEW

**Comment by grantcarthew** [comment]
How do you add the screen shots guys? I have them here.

**Comment by goanpeca** [comment]
Hi @grantcarthew thanks for working on this.

You can drag and drop the image into the box where you write the message, whait for it to upload and then make the comment.

**Comment by grantcarthew** [comment]
Too late. Put them here: https://imgur.com/a/FhURkr8

**Comment by goanpeca** [comment]
Gave you a hand ;-) 

Let's wait for the tests to finish and this should be good to merge.

**Comment by grantcarthew** [comment]
The top images had the dark old/new the wrong way around. I've fixed it.

**Comment by goanpeca** [comment]
@grantcarthew could you please create a new PR that creates a branch on your fork and uses the 4.x branch as base. That way we can include your fixes as part of Spyder 4 and not 5 (to be released on 2021)

Something like:

assuming you have added the upstream remote on your fork like:

```
git add remote upstream https://github.com/spyder-ide/spyder.git
```

You could do something like:
```
git checkout 4.x
git pull upstream 4.x
git checkout -b fix/solarized-colors
# Apply the fixes
git add .
git commit -m "Fixed Solarized Theme Colour Constrast"
git push origin fix/solarized-colors
```

Thanks!

**Pull request closed without merging**
