### PR TITLE
Make run-cell icons pixel-perfect

### PR DESCRIPTION
**Pull request by SylvainCorlay**
pixel-perfect-cell

The new icon is pixel-perfect at the same sizes as font awesome. The horizontal lines for the cell borders are thinner but if they cast a shadow at 16px size, it will be inwards w.r.t the cell.

### CODE REVIEW

**Comment by goanpeca** [comment]
@SylvainCorlay probably I have asked about this, but just to be sure

Are the grey lines on the cell border (top and bottom) really that necessary ?

**Comment by SylvainCorlay** [comment]
> Are the grey lines on the cell border (top and bottom) really that necessary ?

Yes, the yellow background is almost undistinguishable from the grey without it.

**Comment by ccordoba12** [comment]
I'm +1. Thanks a lot @SylvainCorlay!

@goanpeca?

**Comment by goanpeca** [comment]
ok

**Pull request merged**
