### PR TITLE
Increase time to detect if an IPython kernel is alive

### LINKED ISSUE #3444: Reports of Kernel Death are greatly exagerated
## Description of your problem

**What steps will reproduce the problem?**
1. launch a new Ipython console
2. during a few seconds, "kernel death" messages are displayed
   kernel_death_20160922
3. all is going back in order without human intervention, but for 4 Kernel death message there are 4 "[1]" lines displayed in the new Ipython console
   kernel_death_20160922b

**What is the expected output? What do you see instead?**
- no, or much less  reports of "Kernel Death"

**Please provide any additional information below**
- it's more frequent if the pc is slow or busy
## Versions and main components
- Spyder Version:3.0.0-master of 2016-09-21 ("b8")
- Python Version: any (3.4)
- Operating system: Windows 10
## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  2.0.0b4 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.19.0rc1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pyflakes >=0.6.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.6.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #3444.

----

@dalthviz, could you check if this increase is enough for you, given that you're experiencing this problem locally? Thanks :-)

### CODE REVIEW

**Comment by ccordoba12** [comment]
@stonebig, could you check this too?

**Comment by dalthviz** [comment]
Yep, is enough for me, no more `kernel died. Restarting...`.  I tested the change in Spyder `3.1.0.dev0` with python `2.7.12` and `3.5.2` and my specs are Windows 8 64 bits, ram 8 Gb, and a Intel Core i5-4210U Processor.

**Comment by stonebig** [comment]
hi @ccordoba12 , at first cold start of Winpython-3.5 64 bit after cold start of the slow pc ... no message

==> good for me

**Comment by stonebig** [comment]
wouldn't it be rather 3.0.2 ?

**Comment by ccordoba12** [comment]
> wouldn't it be rather 3.0.2 Milestone ?

Yep, I agree :-)

**Comment by gorbatov** [comment]
My spyder is unusable because of "Kernel died, restarting" version 3.0.1 windows10.
This msg continously appears and no end
Should I change to version 3.1.5 what i need to do.

**Comment by stonebig** [comment]
current branch of spyder-3.x solves the issue.

**Pull request merged**
