### PR TITLE
PR: Use qdarkstyle subrepo in macOS app

### LINKED ISSUE #15053: qdarkstyle.colorsystem requirement missing
### What steps will reproduce the problem?

`qdarkstyle.colorsystem` seems to be missing from the macOS app, causing it to fail to launch.

```python
(spy-build) >> dist/Spyder.app/Contents/MacOS/Spyder --debug-info=verbose
Traceback (most recent call last):
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/__boot__.py", line 106, in <module>
    _run()
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/__boot__.py", line 84, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/Spyder.py", line 3, in <module>
    start.main()
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/start.py", line 223, in main
    from spyder.app import mainwindow
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/mainwindow.py", line 73, in <module>
    from spyder.app import tour
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/app/tour.py", line 38, in <module>
    from spyder.utils.qthelpers import add_actions, create_action
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/utils/qthelpers.py", line 35, in <module>
    from spyder.utils.icon_manager import ima
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/utils/icon_manager.py", line 23, in <module>
    from spyder.utils.palette import QStylePalette, SpyderPalette
  File "/Users/rclary/Documents/Python/spyder/installers/macOS/dist/Spyder.app/Contents/Resources/lib/python3.9/spyder/utils/palette.py", line 12, in <module>
    from qdarkstyle.colorsystem import Blue, Gray
ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'
2021-03-29 18:12:37.424 Spyder[28804:44576512] Spyder Error
```

I don't know why this does not manifest when bootstrapping. Please advise.

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

Use the `qdarkstyle` subrepo on pull requests in the pipeline build of the macOS application.

### Issue(s) Resolved

Fixes #15053

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@mrclary

### CODE REVIEW

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary for your help with this!

**Comment by mrclary** [comment]
@ccordoba12, thanks for fixing the typo.

**Comment by ccordoba12** [comment]
Is the app working well for you? Unfortunately we don't have much time to test it before Thursday (the day of the final release), so it'd be great if you could let us know about that.

**Comment by mrclary** [comment]
I've only been doing spot checking so far (#15053 and #14917). I'll start using the artifact from this PR. I'll post any new issues I discover, but otherwise assume that it is good.

**Comment by Xnac** [comment]
Please reopen the issue, in Linux (ubuntu TLS 20.4) We have:
(base) nac@10SAE:~$ spyder
Traceback (most recent call last):
  File "/home/nac/miniconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/app/start.py", line 210, in main
    from spyder.app import mainwindow
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 72, in <module>
    from spyder.app import tour
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/app/tour.py", line 37, in <module>
    from spyder.utils.qthelpers import add_actions, create_action
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/utils/qthelpers.py", line 34, in <module>
    from spyder.utils.icon_manager import ima
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/utils/icon_manager.py", line 23, in <module>
    from spyder.utils.palette import QStylePalette, SpyderPalette
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/utils/palette.py", line 12, in <module>
    from qdarkstyle.colorsystem import Blue, Gray
ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'

**Comment by mrclary** [comment]
@Xnac, your error is due to an older version of qdarkstyle. Spyder 5 requires qdarkstyle>=3.0.2

**Comment by Xnac** [comment]
I was qdarkstyle>=3.0.2. I dwngraded for Spyder spyder=4.2.5

The following packages will be DOWNGRADED:

  qdarkstyle                             3.0.2-pyhd3eb1b0_0 --> 2.8.1-py_0
  spyder-kernels                       2.0.1-py38h06a4308_0 --> 1.10.2-py38h06a4308_0

**Comment by Xnac** [comment]
(base) nac@10SAE:~$ spyder
Traceback (most recent call last):
  File "/home/nac/miniconda3/bin/spyder", line 11, in <module>
    sys.exit(main())
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/app/start.py", line 210, in main
    from spyder.app import mainwindow
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 72, in <module>
    from spyder.app import tour
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/app/tour.py", line 37, in <module>
    from spyder.utils.qthelpers import add_actions, create_action
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/utils/qthelpers.py", line 34, in <module>
    from spyder.utils.icon_manager import ima
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/utils/icon_manager.py", line 23, in <module>
    from spyder.utils.palette import QStylePalette, SpyderPalette
  File "/home/nac/miniconda3/lib/python3.8/site-packages/spyder/utils/palette.py", line 12, in <module>
    from qdarkstyle.colorsystem import Blue, Gray
ModuleNotFoundError: No module named 'qdarkstyle.colorsystem'
(base) nac@10SAE:~$ conda list
# packages in environment at /home/nac/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
alabaster                 0.7.12             pyhd3eb1b0_0  
appdirs                   1.4.4                      py_0  
argh                      0.26.2                   py38_0  
arrow                     0.13.1                   py38_0  
astroid                   2.5              py38h06a4308_1  
async_generator           1.10               pyhd3eb1b0_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.6              pyhd3eb1b0_0  
babel                     2.9.0              pyhd3eb1b0_0  
backcall                  0.2.0              pyhd3eb1b0_0  
binaryornot               0.4.4              pyhd3eb1b0_1  
black                     19.10b0                    py_0  
bleach                    3.3.0              pyhd3eb1b0_0  
brotlipy                  0.7.0           py38h27cfd23_1003  
ca-certificates           2021.1.19            h06a4308_1  
certifi                   2020.12.5        py38h06a4308_0  
cffi                      1.14.5           py38h261ae71_0  
chardet                   4.0.0           py38h06a4308_1003  
click                     7.1.2              pyhd3eb1b0_0  
cloudpickle               1.6.0                      py_0  
colorama                  0.4.4              pyhd3eb1b0_0  
conda                     4.10.0           py38h06a4308_0  
conda-package-handling    1.7.2            py38h03888b9_0  
cookiecutter              1.7.2              pyhd3eb1b0_0  
cryptography              3.4.7            py38hd23ed53_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 5.0.6              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
diff-match-patch          20200713                   py_0  
docutils                  0.17             py38h06a4308_1  
entrypoints               0.3                      py38_0  
expat                     2.3.0                h2531618_2  
flake8                    3.9.0              pyhd3eb1b0_0  
fontconfig                2.13.1               h6c09931_0  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   py38_1  
glib                      2.68.0               h36276a3_0  
gst-plugins-base          1.14.0               h8213a91_2  
gstreamer                 1.14.0               h28cd5cc_2  
icu                       58.2                 he6710b0_3  
idna                      2.10               pyhd3eb1b0_0  
imagesize                 1.2.0              pyhd3eb1b0_0  
importlib-metadata        3.10.0           py38h06a4308_0  
importlib_metadata        3.10.0               hd3eb1b0_0  
inflection                0.5.1            py38h06a4308_0  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.22.0           py38hb070fc8_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
isort                     5.8.0              pyhd3eb1b0_0  
jedi                      0.17.2           py38h06a4308_1  
jeepney                   0.6.0              pyhd3eb1b0_0  
jinja2                    2.11.3             pyhd3eb1b0_0  
jinja2-time               0.2.0              pyhd3eb1b0_2  
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                      py_2  
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_core              4.7.1            py38h06a4308_0  
jupyterlab_pygments       0.1.2                      py_0  
keyring                   22.3.0           py38h06a4308_0  
lazy-object-proxy         1.6.0            py38h27cfd23_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                h2531618_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
markupsafe                1.1.1            py38h7b6447c_0  
mccabe                    0.6.1                    py38_1  
mistune                   0.8.4           py38h7b6447c_1000  
mypy_extensions           0.4.3                    py38_0  
nbclient                  0.5.3              pyhd3eb1b0_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
openssl                   1.1.1k               h27cfd23_0  
packaging                 20.9               pyhd3eb1b0_0  
pandoc                    2.12                 h06a4308_0  
pandocfilters             1.4.3            py38h06a4308_1  
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pathspec                  0.7.0                      py_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pip                       21.0.1           py38h06a4308_0  
pluggy                    0.13.1           py38h06a4308_0  
poyo                      0.5.0              pyhd3eb1b0_0  
prompt-toolkit            3.0.17             pyh06a4308_0  
psutil                    5.8.0            py38h27cfd23_1  
ptyprocess                0.7.0              pyhd3eb1b0_2  
pycodestyle               2.6.0              pyhd3eb1b0_0  
pycosat                   0.6.3            py38h7b6447c_1  
pycparser                 2.20                       py_2  
pydocstyle                6.0.0              pyhd3eb1b0_0  
pyflakes                  2.2.0              pyhd3eb1b0_0  
pygments                  2.8.1              pyhd3eb1b0_0  
pylint                    2.7.4            py38h06a4308_1  
pyls-black                0.4.6                hd3eb1b0_0  
pyls-spyder               0.3.2              pyhd3eb1b0_0  
pyopenssl                 20.0.1             pyhd3eb1b0_1  
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.17.3           py38h7b6447c_0  
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.5                h7579374_1  
python-dateutil           2.8.1              pyhd3eb1b0_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.36.2             pyhd3eb1b0_0  
python-slugify            4.0.1                      py_0  
pytz                      2021.1             pyhd3eb1b0_0  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    5.4.1            py38h27cfd23_1  
pyzmq                     20.0.0           py38h2531618_1  
qdarkstyle                3.0.2              pyhd3eb1b0_0  
qstylizer                 0.1.10             pyhd3eb1b0_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 1.0.2              pyhd3eb1b0_0  
qtconsole                 5.0.3              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
readline                  8.1                  h27cfd23_0  
regex                     2021.4.4         py38h27cfd23_0  
requests                  2.25.1             pyhd3eb1b0_0  
rope                      0.18.0                     py_0  
rtree                     0.9.4                    py38_1  
ruamel_yaml               0.15.100         py38h27cfd23_0  
secretstorage             3.3.1            py38h06a4308_0  
setuptools                52.0.0           py38h06a4308_0  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0           py38h06a4308_0  
snowballstemmer           2.1.0              pyhd3eb1b0_0  
sortedcontainers          2.3.0              pyhd3eb1b0_0  
sphinx                    3.5.3              pyhd3eb1b0_0  
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0  
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0  
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0  
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0  
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0  
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0  
spyder                    5.0.0            py38h06a4308_0  
spyder-kernels            2.0.1            py38h06a4308_0  
sqlite                    3.35.4               hdfb4753_0  
testpath                  0.4.4              pyhd3eb1b0_0  
text-unidecode            1.3                        py_0  
textdistance              4.2.1              pyhd3eb1b0_0  
three-merge               0.1.1              pyhd3eb1b0_0  
tinycss                   0.4             pyhd3eb1b0_1002  
tk                        8.6.10               hbc83047_0  
toml                      0.10.2             pyhd3eb1b0_0  
tornado                   6.1              py38h27cfd23_0  
tqdm                      4.59.0             pyhd3eb1b0_1  
traitlets                 5.0.5              pyhd3eb1b0_0  
typed-ast                 1.4.2            py38h27cfd23_1  
typing_extensions         3.7.4.3            pyha847dfd_0  
ujson                     4.0.2            py38h2531618_0  
unidecode                 1.2.0              pyhd3eb1b0_0  
urllib3                   1.26.4             pyhd3eb1b0_0  
watchdog                  1.0.2            py38h06a4308_1  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
wheel                     0.36.2             pyhd3eb1b0_0  
whichcraft                0.6.1              pyhd3eb1b0_0  
wrapt                     1.12.1           py38h7b6447c_1  
wurlitzer                 2.1.0            py38h06a4308_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.31.0             pyhd3eb1b0_0  
zeromq                    4.3.4                h2531618_0  
zipp                      3.4.1              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3

**Comment by ccordoba12** [comment]
@Xnac, please don't post your comments on random PRs. Instead, please go to issue #15113.

**Comment by ccordoba12** [comment]
If you have problems with Spyder 5 and conda, please open a new issue instead.

**Pull request merged**
