### PR TITLE
WIP: PR: Include user's local PYTHONPATH from .bash_profile

### LINKED ISSUE #14843: Ability to use PYTHONPATH from user bash_profile in macOS application
It would be nice to be able to import the PYTHONPATH from a user's `bash_profile` to replace/append to Spyder's PYTHONPATH Manager.

The issue is that many users may require setting PYTHONPATH in their `bash_profile` for other purposes, but the macOS application cannot make use of this, thus users may be required to manage PYTHONPATH in two locations: in `bash_profile` as well as in Spyder's PYTHONPATH Manager.

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Retrieved PYTHONPATH from user's local .bash_profile at startup of the mainwindow and when PYTHONPATH Manager is launched.

### Issue(s) Resolved

Fixes #14843

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@mrclary

### CODE REVIEW

**Comment by mrclary** [comment]
@steff456, okay, here is the basic working functionality.
At the mainwindow creation (at application launch) when the python path is loaded from `SPYDER_PATH`, the user's local `PYTHONPATH` is also merged in. Similarly when the PYTHONPATH Manager is opened.

However, there are few things we need to consider.
* Are there considerations for Linux and Windows platforms? I've left a placeholder in the `spyder.utils.programs.add_user_pythonpath` function.
* There should be a preference that allows the user to toggle the functionality. I think this should be in the PYTHONPATH Manager, but that will require changing the user interface and adding another Spyder preference.
* How should this behave with regard to adding/deleting paths? For example, if the local `PYTHONPATH` is merged in, and the user later removes paths, local `PYTHONPATH` paths will be added back upon restarting the application or launching the PYTHONPATH Manager. We may not want this behavior.

Another option might be to have a simple button in the PYTHONPATH Manager that merges in the user's local `PYTHONPATH`, and not have it merged in automatically. But this would mean they have to do that any time their `.bash_profile` changed. Or maybe this option in conjunction with second bullet above?

What do you think?
Ping @ccordoba12

**Comment by ccordoba12** [comment]
Hey @mrclary, please move your PR to master because we're not going to have more releases for Spyder 4.

**Comment by mrclary** [comment]
@ccordoba12, I've rebased onto master and changed the PR target to master.
Should I rebase all outstanding PRs onto latest master? Will there be a 5.x branch? Please advise.

**Comment by ccordoba12** [comment]
> @ccordoba12, I've rebased onto master and changed the PR target to master.

Thanks!

> Should I rebase all outstanding PRs onto latest master?

Yes, please do.

> Will there be a 5.x branch?

Yes, it will be. I'll create it after I release the first Spyder 5 version. For now, all PRs that we merge directly to master will be part of Spyder 5.0.0.

**Pull request closed without merging**
