### PR TITLE
Fix heartbeat in introspection client/server

### PR DESCRIPTION
**Pull request by blink1073**

### CODE REVIEW

**Comment by blink1073** [comment]
Not sure why "appveyor" is failing:

```
%CMD_IN_ENV% %APPVEYOR_BUILD_FOLDER%\continuous_integration\appveyor\modules_test.bat
--- Testing C:\projects\spyder\spyderlib\dependencies.py ---
Traceback (most recent call last):
  File "C:\projects\spyder\spyderlib\dependencies.py", line 13, in <module>
    from spyderlib.utils import programs
ImportError: No module named 'spyderlib'
Command exited with code 1

**Comment by ccordoba12** [comment]
Don't worry about it. It seems an update in conda-build broke our testing scripts in AppVeyor.

I'm fixing it right not :-)

**Comment by ccordoba12** [comment]
@blink1073 please rebase. I fixed the problem in master :-)

**Comment by ccordoba12** [comment]
I can confirm that this really fixes the freezes in Mac! Thanks a lot @blink1073!

**Comment by blink1073** [comment]
🎉, keep out, damn 🐛 🐛 🐛

**Comment by ccordoba12** [comment]
:+1: :+1:

**Pull request merged**
