### PR TITLE
PR: Fix quotes and traceback lines in runcell

### LINKED ISSUE #8242: Double Quotes at the begining or end of the a code cell breaks runcell
## Problem Description

runcell sends the code to the kernel formatted as a `"""` string. So `""""` through an error

## To Reproduce

1. put `"Hello World"` in a code cell 
2. run the code cell

### Paste Traceback/Error Below (if applicable)

```python-traceback

runcell('','/home/bcolsen/Documents/projects/bcp/cong_ebeam/untitled1.py')
  File "<ipython-input-138-196bcb471293>", line 28
    "hello""""
              
^
SyntaxError: EOL while scanning string literal

--Run Cell Error--
Please use only through Spyder's Editor; shouldn't be called manually from the console
```

## Versions

* Spyder version: master
* Python version: 3.6
* Qt version: 
* PyQt version: 
* Operating System name/version:

### LINKED ISSUE #8244: Runcell traceback line number off by one for every code block it's after
## Problem Description

The code line in the traceback for runcell is off by one extra line for every `if:`, `for:` and `def:` block it is after.

Run this in runcell:
```python
if True:
    pass
yo
```
Get line 4 instead of 3:
```python-traceback
Traceback (most recent call last):

  File "<ipython-input-2-a843736064be>", line 4, in <module>
    yo

NameError: name 'yo' is not defined
```

## Versions

* Spyder version: master
* Python version: 3.6
* Qt version: 
* PyQt version: 
* Operating System name/version:

### PR DESCRIPTION
**Pull request by bcolsen**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based this PR on the latest version of the correct branch (master or 3.x)
* [x] Followed [PEP 8](https://www.python.org/dev/peps/pep-0008/) code style
* [x] Ensured this pull request hasn't eliminated unrelated blank lines/spaces,
      modified the ``spyder/defaults`` directory, or added new icons/assets
* [x] Wrote at least one-line docstrings following PEP 257for any new functions
* [x] Added at least one unit test covering the changes, if at all possible
* [x] Described the changes and the motivation for them below
* [x] Noted what issue(s) this pull request resolves, creating one if needed
* [x] Included a screenshot, if this PR makes any visible changes to the UI

### Developer Certificate of Origin Affirmation

By submitting this Pull Request or typing my name below, I affirm the
[Developer Certificate of Origin](https://developercertificate.org/)
with respect to both the content of the contribution itself and this post,
and understand I am releasing it under Spyder's MIT (Expat) license.

## Description of Changes

Added a new line to the end of the code to separated the triple quotes of run cell and removed the `rstrip()` calls.

Also removed the code that added a new line after every key word block. This code seems to indicate that it is necessary to have the code run in the console but this dosen't seem to be needed in the ipython console. This code was changing the traceback line numbers.

### Issue(s) Resolved

Fixes #8244 
Fixes #8242

### CODE REVIEW

**Comment by bcolsen** [comment]
`test_shortcutssummary_texts` is the test failure. I tested on my set up and it seems flaky. I had to turn flaky up to 5 or it would still fail sometimes.

**Comment by ccordoba12** [comment]
> I tested on my set up and it seems flaky. I had to turn flaky up to 5 or it would still fail sometimes.

Please add to it the `@flaky(max_runs=10)` decorator, so it gets run 10 times by pytest.

**Comment by jnsebgosselin** [comment]
> test_shortcutssummary_texts is the test failure. I tested on my set up and it seems flaky. I had to turn flaky up to 5 or it would still fail sometimes.

Yeah, this test needs to be reworked a little. It should not be too difficult. I'll propose something.

**Comment by jnsebgosselin** [comment]
Ok no, it is simpler than that and I think you should do it in this PR @bcolsen . Simply change `Escape` by `Esc` here and it should be OK :

https://github.com/spyder-ide/spyder/blob/master/spyder/widgets/tests/test_shortcutssummary.py#L63

**Comment by bcolsen** [comment]
Thanks @jnsebgosselin. I'll look at this tonight.

**Comment by bcolsen** [comment]
@ccordoba12 This is ready for review. @jnsebgosselin 's fix worked

**Pull request merged**
