### PR TITLE
PR: Update MathJax to its latest version

### LINKED ISSUE #9357: Help Panel: LaTeX rendering is unreadable when using dark theme
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
When a docstring renders LaTeX as part of its body, it is rendered on black by default, this causes readability problems when the dark theme is used, as it is not possible to read the rendered formulas.

### What steps reproduce the problem?

1. Import torch
2. Request help for ```torch.nn.AdaptiveAvg2D``` using help shortcut

### What is the expected output? What do you see instead?
imagen

## Versions

* Spyder version: 4.0 beta2
* Python version:  3.7
* Qt version: 5.9
* PyQt version: 5.9
* Operating System name/version: Ubuntu 18.04

### PR DESCRIPTION
**Pull request by steff456**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

image

Update MathJax for making visible the docstrings that are rendered with Latex. 

### Issue(s) Resolved

Fixes #9357

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
Steff456

### CODE REVIEW

**Comment by ccordoba12** [comment]
@steff456, this looks good, but most Mathjax files you added have mode `755` (i.e. executable) instead of `644` (i.e. read/write). Please change so that all Mathjax files are `644`.

**Comment by ccordoba12** [comment]
Did you just only update MathJax and that fixed the problem? Or did you also make some adjustments to the CSS of the Help plugin?

**Comment by steff456** [comment]
> Did you just only update MathJax and that fixed the problem? Or did you also make some adjustments to the CSS of the Help plugin?

By only updating MathJax the issue was solved!

**Comment by ccordoba12** [comment]
> By only updating MathJax the issue was solved!

Nice to hear!! Thanks @steff456!

**Pull request merged**
