### PR TITLE
PR: Fix simple typo in docstring

### LINKED ISSUE #11140: Simple typo: witdh -> width
# Issue Type

[x] Bug (Typo)

# Steps to Replicate

1. Examine spyder/plugins/plots/widgets/figurebrowser.py.
2. Search for `witdh`.

# Expected Behaviour

1. Should read `width`.

### PR DESCRIPTION
**Pull request by timgates42**
Closes #11140

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for your contribution! We'd like to include it in our next release in the Spyder 4 series. For that, please make your branch to derive from our `4.x` branch (instead of master), with the following command:

    git checkout bugfix/typo_width
    git rebase --onto 4.x master bugfix/typo_width
    git push -f origin bugfix/typo_width

If you decline to do that, your work will be part of Spyder 5, to be released much later in 2020.

**Comment by timgates42** [comment]
No problem - Thanks! Will do.

**Comment by timgates42** [comment]
Ok thanks @ccordoba12 update the branch onto 4.x - do you want the PR to target 4.x too?

**Comment by ccordoba12** [comment]
> update the branch onto 4.x

Thanks!

>  do you want the PR to target 4.x too?

I changed the base of this PR to 4.x myself, but thanks for asking.

**Pull request merged**
