### PR TITLE
PR: Use custom CSS when serving docs for the Online Help

### LINKED ISSUE #9696: Online Help pane doesn't support the dark theme
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

imagen

## Versions

* Spyder version: 4.0beta2
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Windows 8.1

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

A preview:

image

### Issue(s) Resolved

Fixes #9696 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by goanpeca** [comment]
@dalthviz could we also provide a different font? (that is in line with the spyder fontS?)

**Comment by goanpeca** [comment]
Also is there a way we can install the buttons?

**Comment by dalthviz** [comment]
> @dalthviz could we also provide a different font? (that is in line with the spyder fontS?)
I think so
>Also is there a way we can install the buttons?
If you mean style them, yep I think a class can be created to change colors, font, size, etc.

Although if the styling needs to me more detailed probably we will need to redo the `HTMLDoc` class, and the redo will need to have a Python 2 and a Python 3 version

**Comment by ccordoba12** [comment]
> and the redo will need to have a Python 2 and a Python 3 version

Please implement this for Python 3 because there's little sense in investing more time for Python 2.

**Comment by dalthviz** [comment]
I think this is ready @ccordoba12 :+1:

**Comment by goanpeca** [comment]
BTW this is looking awesome :-) !

Is the light theme also being updated to look nice as well?

This part still looks a bit crowded, any chance of adding some padding @dalthviz?

image

**Comment by dalthviz** [comment]
>Is the light theme also being updated to look nice as well?

yep @goanpeca 

image

>This part still looks a bit crowded, any chance of adding some padding @dalthviz?

Sure, but padding between which elements? (inputs vs links or maybe the inputs vs the banner or maybe both?)

**Comment by goanpeca** [comment]
- [ ] Vertical spacing between links and buttons
- [ ] Vertical spacing between buttons and banner
- [ ] Could we align the links to the right?

**Comment by goanpeca** [comment]
Awesome work @dalthviz !

**Pull request merged**
