### PR TITLE
PR: Fix German translation of "preferences"

### PR DESCRIPTION
**Pull request by bnavigator**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)
* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Change the German translation of "preferences" from "Voreinstellungen" (="defaults") to "Einstellungen". This is the correct translation commonly used in other software.

If this is not the correct way of changing translations, please advice to sign up and approve a translator role in crowdin or just change it there on your own.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: bnavigator

### CODE REVIEW

**Comment by goanpeca** [comment]
@bnavigator in theory it is fine to do it here, but it is much better, easier for most users and devs (even ones used to work with PRs) to use crowdin so I would encourage you to (if that is ok with you) to sign https://crowdin.com/project/spyder

Also, no need in general to add the compiled files, as we will do that before a release as part of the release process.

Thanks!

**Comment by ccordoba12** [comment]
> Also, no need in general to add the compiled files, as we will do that before a release as part of the release process.

In this case I think it is, given that we don't plan to update our translations before 4.1.2.

But as @goanpeca said, for next time please use Crowdin.

**Comment by ccordoba12** [comment]
@alexschw, do you agree with this change?

**Comment by bnavigator** [comment]
I made the same changes in Crowdin now. I am not familiar yet with the tool. Is there a history? Are my saves already commited? Hopefully this will not create merge conflicts with this PR now? Close this without merging and wait for the update from Crowdin?

**Comment by goanpeca** [comment]
Here they are updated 

https://github.com/spyder-ide/spyder/pull/11825

**Comment by bnavigator** [comment]
Okay then we can close here.

**Comment by goanpeca** [comment]
Thanks for your help!

**Comment by ccordoba12** [comment]
> Here they are updated #11825

Yeah, but for 4.1.0. New strings have been introduced in 4.1.1 and 4.1.2

**Comment by goanpeca** [comment]
>Yeah, but for 4.1.0. New strings have been introduced in 4.1.1 and 4.1.2

Will update them later today

**Comment by ccordoba12** [comment]
Please wait until Friday afternoon, so we can have the string you're going to add for the PyLS fix.

**Comment by bnavigator** [comment]
Was not included in #12083. Reopening to track the issue.

**Comment by ccordoba12** [comment]
There's no need of this. Closing again.

**Pull request closed without merging**
