### PR TITLE
PR: Change deprecated funtion QInputDialog.getInteger for QInputDialog.getInt

### LINKED ISSUE #3519: Cannot set Maximum Number of Recent Files
## Description

**What steps will reproduce the problem?**

1. File
2. Open Recent ...
3. Maximum Number of Recent Files ...

**What is the expected output? What do you see instead?**
Expect: Ability to set number of files.
Output: 
  File "C:\Users\David\Anaconda2\lib\site-packages\spyder\plugins\editor.py", line 1718, in change_max_recent_files
    mrf, valid = QInputDialog.getInteger(editorstack, _('Editor'),
AttributeError: type object 'QInputDialog' has no attribute 'getInteger'

**Please provide any additional information below**
Please see above.

## Version and main components

* Spyder Version: 3.0.0 
* Python Version: 2.7.12
* Qt Versions: 5.6.0, PyQt5 5.6 on Windows

## Dependencies
```
pyflakes >=0.5.0 :  1.3.0 (OK)
pep8 >=0.6       :  1.7.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
numpy >=1.7      :  1.11.1 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
rope >=0.9.4     :  0.9.4 (OK)
jedi >=0.8.1     :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
sympy >=0.7.3    :  1.0 (OK)
pylint >=0.25    :  1.5.4 (OK)

```

### PR DESCRIPTION
**Pull request by rlaverde**
Fixes #3519 

This also was causing error in maximum lines in console and history deep

### CODE REVIEW

**Comment by ccordoba12** [comment]
This looks good to me, thanks @rlaverde!

**Comment by goanpeca** [comment]
@ccordoba12 this means that this no longer works with qt4 ?

**Comment by ccordoba12** [comment]
Don't worry, this function was introduced in Qt 4.5 :-)

**Comment by goanpeca** [comment]
ah ok

**Comment by rlaverde** [comment]
@ccordoba12 You're welcome :)

**Comment by goanpeca** [comment]
:+1:

**Pull request merged**
