### PR TITLE
PF: Fix kite logo for OSX

### LINKED ISSUE #10442: The kite logo on the status bar is pixelated on retina display:
The kite logo on the status bar is pixelated on retina display:

Screen Shot 2019-10-17 at 11 23 07

### PR DESCRIPTION
**Pull request by goanpeca**
#### Before
Screen Shot 2019-10-21 at 21 58 03

#### After
Screen Shot 2019-10-21 at 21 55 57

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

The kite logo was being scaled as a pixmap and then passed to the icon which would distrot the icon for scale factor that did not adjust to specific ratios. I edited the Kite logo images (in SVG) so that the image includes a padding, like most of the Font Awesome icons. I based the size to 16 and left a padding of 1, which results in a kite logo of 14px (effective) height. This removes the need to pass a custom scale factor, and since the icon is used as is, it does not get distorted.

As an extra for this PR I removed the padding o the layout between icons and text which results in a better UI and reduced status widgets total width.

### Issue(s) Resolved

Fixes #10442 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by ccordoba12** [comment]
@goanpeca, could you describe what was the previous problem?

**Comment by goanpeca** [comment]
Updated

**Comment by goanpeca** [comment]
>Maybe we need to decrease a little bit the height of the icon (leaving some space between the image itself and the canvas vertically)

The image is now a 16x16 and the actual Icon is occupying 14px. With the previous scale factor it was 13.6px, so this is close enough and already has the padding you suggest @dalthviz.

Or are you asking for something different 🙃 ?

**Comment by dalthviz** [comment]
Basically that's it, yep. It looked for me a little bit bigger that's all. Besides that this LGTM :+1:

**Comment by goanpeca** [comment]
>It looked for me a little bit bigger that's all. 

Yes, it is 0.4 px bigger :-p. Sharp eye ;-)

**Comment by goanpeca** [comment]
Failing tests are unrelated

**Pull request merged**
