### PR TITLE
PR: Update readme and organize badges

### PR DESCRIPTION
**Pull request by goanpeca**
- Reorganize badges for build and project status
- Include Quantified Code badge
- Include Gitter chat bagde

image

### CODE REVIEW

**Comment by ccordoba12** [comment]
My replies:

* Please remove the Quantified Code badge. IMHO, the badge doesn't have meaningful information (at least for regular users, who are the primary target of our README).
* Please remove PyPi downloads. That's broken for now and who knows when it's going to be fixed.
* The *Project details* should go before *Build status* because it has information for users instead of devs.
* Please remove the CircleCi badge and add it instead in its corresponding PR.

**Comment by ccordoba12** [comment]
What happened here? Why did you close it?

**Comment by goanpeca** [comment]
On your comments:
>Please remove the Quantified Code badge. IMHO, the badge doesn't have meaningful information (at least for regular users, who are the primary target of our README).

It does, it conveys that the codebase is following some quality standards and makes issues in the codebase visible. The idea is to be transparent, as with the covergae despite it being low we give visibility to it and that in turns will steer the project to increasing coverage. Same with quantified code.

> Please remove PyPi downloads. That's broken for now and who knows when it's going to be fixed.

Ok

>The Project details should go before Build status because it has information for users instead of devs.

Makes sense

> Please remove the CircleCi badge and add it instead in its corresponding PR.

I will but please enable circle ci, it is kinda if a bummer that you just shut it down. I can have it working real quick (I have enable circle ci on several projects now... anaconda-client, conda-manager, navigator...)

**Comment by ccordoba12** [comment]
> It does, it conveys that the codebase is following some quality standards and makes issues in the codebase visible.

Ok, then it's fine to have it :-p

>  ... please enable circle ci

I don't have time to deal with another CI service right now. Besides, after a long time, Travis and AppVeyor are working really well now, so I don't want to touch them.

Sorry, I know it's a bummer, but let's just focus on get 3.0 out of the door for now.

----

Please do my couple of suggested changes to merge this one :-)

**Comment by ccordoba12** [comment]
I'll merge this one and do my suggested changes in master :-)

**Pull request merged**
