### PR TITLE
PR: Implement mouse XButton navigation in the editor

### LINKED ISSUE #15948: [Enhancement] Support XButton1 and XButton2
## Enhancement Description

My Mouse has two extra buttons, Forward and backward (for example in a browser).
The related Keyboard-Events are XButton1 (Back) and XButton2 (Forward).

I'd expect them to issue the same event as the ALT+Left or ALT+Right Key-Combination does.
This would improve source code browsing a lot.

Thanks!

### PR DESCRIPTION
**Pull request by maurerle**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

I added navigation with XButtons (the typical extra two buttons on a mouse used for browsing backward and forward) in the code editor.
This improves code browsing if the mouse has this ability.

I don't know if this is testable and how, as it only adds a new trigger which is forwarded to the one in the EditorStack.

### Issue(s) Resolved

Fixes #15948

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Florian Maurer

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @maurerle, thanks a lot for your contribution! To have it in one of the next releases in the Spyder 5 cycle, please make your branch to derive from our `5.x` one (instead of `master`), with the following commands:

    git checkout 5.x
    git checkout feature/xbutton
    git rebase --onto 5.x master feature/xbutton
    git push -f origin feature/xbutton

You need to do the same for the other pull requests that you opened today. More details about our development process are available in our [Contributing guide](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md).

**Comment by maurerle** [comment]
Thank you!
I updated all my contributions. Could you please review them and give feedback?

**Comment by ccordoba12** [comment]
I don't have much free time these days, but I'll ask @dalthviz (one of our core developers) to take a look at them.

**Review by dalthviz — APPROVED** [review]
Thank you @maurerle for this! Checked locally and is working. Quite nice improvement in the navigation experience if you have a mouse with extra buttons on the side indeed :+1:

**Pull request merged**
