### PR TITLE
PR: Constrain setuptools for macOS standalone installer

### PR DESCRIPTION
**Pull request by mrclary**
Constrain `setuptools<70.0.0` for macOS standalone installer to resolve "ImportError: cannot import name 'packaging' from 'pkg_resources'".

Also, missed a macos-11 spec on PR #22102.

### CODE REVIEW

**Comment by mrclary** [comment]
@ccordoba12, hopefully we're done playing whack-a-mole!

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary!

**Comment by ccordoba12** [comment]
This is not necessary for master, right?

**Comment by mrclary** [comment]
Correct; this is not necessary for master.

**Pull request merged**
