### PR TITLE
PR: Decrease the amount of didChange requests (Editor)

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by impact27** [comment]
This PR:
```
>>> timeit.timeit("PyQt5.QtTest.QTest.keyClick(spy.window.editor.get_focus_widget(), PyQt5.QtCore.Qt.Key_Enter)", number=1000, globals={"spy":spy, "PyQt5": PyQt5})
15.291292299999995
```
5.x
```
>>> timeit.timeit("PyQt5.QtTest.QTest.keyClick(spy.window.editor.get_focus_widget(), PyQt5.QtCore.Qt.Key_Enter)", number=1000, globals={"spy":spy, "PyQt5": PyQt5})
23.352510600000002
```

~50% faster line return in an empty file

**Comment by andfoy** [comment]
Looks good to me, however I have a question regarding the deletion of several  `document_did_change` calls, these are required to ensure that the document is synchronized between the client and the server.

**Comment by impact27** [comment]
> Looks good to me, however I have a question regarding the deletion of several `document_did_change` calls, these are required to ensure that the document is synchronized between the client and the server.

`self.textChanged.connect(self.document_did_change)` will call `self.document_did_change` whenever the document is modified. Do you know of any way the document can be modified without emitting `textChanged`?

**Comment by andfoy** [comment]
Thanks for the clarification @impact27

**Review by ccordoba12 — APPROVED** [review]
Thanks @impact27! This is a great improvement!!

**Pull request merged**
