### PR TITLE
PR: Fixes to improve compatibility with PySide2

### PR DESCRIPTION
**Pull request by rear1019**
## Description of Changes
Various Fixes to improve compatibility with PySide2. This time some fixes for tests are included: We have looked into running the testsuite with PySide2 and this PR contains “low-hanging fruit” fixes. There are still failures which we haven’t looked into yet (we possibly will some day).

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

rear1019

### CODE REVIEW

**Review by ccordoba12 — COMMENTED** [review]
Thanks for these improvements @rear1019! They look good to me, so please rebase or merge with 5.x to get the fixes in PR #19564. Then I'll merge.

**Comment by rear1019** [comment]
> Thanks for these improvements @rear1019! They look good to me, so please rebase or merge with 5.x to get the fixes in PR #19564. Then I'll merge.

Rebased

**Comment by ccordoba12** [comment]
The failure seems valid this time.

**Comment by dalthviz** [comment]
Hi again @rear1019 , could you rebase again on top of the latest 5.x? Hopefully this time that will make the checks pass

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @rear1019 for your continued help to improve our PySide2 support!

**Pull request merged**
