### PR TITLE
PR: Change style of border around thumbnail of current plot

### LINKED ISSUE #21046: Improve highlighting of current plot
<!---   *** BEFORE SUBMITTING: PASTE CLIPBOARD HERE TO COMPLETE YOUR REPORT ***   ---!>

Not so much a bug, but more of a request for improvement. When browsing through a large number of plots, it is barely possible to tell which plot we are currently viewing. Instead of a very thin light blue frame, I would recommend a thicker red line for emphasis. Thanks a lot!

### PR DESCRIPTION
**Pull request by jitseniesen**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions) **N/A**
* [x] Added unit test(s) covering the changes (if testable) **N/A**

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Change the border around the thumbnail of the current plot in the Plots pane to 3px wide and gray (`COLOR_TEXT_3`) for clarity and consistency with the overall styling. This style was suggested in [this comment](https://github.com/spyder-ide/spyder/issues/21046#issuecomment-1825936157).

Screenshot after the change in dark theme:

plots-pr-dark

Screenshot after the change in light theme:

plots-pr-light

### Issue(s) Resolved

Fixes #21046

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Jitse Niesen

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks @jitseniesen for your work on this! I think the new border style looks quite good in the light theme but not so much in the dark one.

@conradolandia, what do you think?

**Comment by jitseniesen** [comment]
This is what it looks like with Gray.B70 in dark mode:

plots-pr2-dark

**Comment by conradolandia** [comment]
I am thinking we should go back to the blue. Preserving the line thickness, but going back to the blue color we had before. That will look good in both the dark and light theme.

**Comment by jitseniesen** [comment]
I am not certain that my previous screenshot was correct. This is what it really looks like with Gray.B70:

plots-pr3-dark

This is the original blue color, but with 3px thickness instead of the original 2px thickness. I think it is clearer than before and thus an improvement.

plots-pr4-dark

Same in light mode:

plots-pr4-light

**Comment by ccordoba12** [comment]
> This is the original blue color, but with 3px thickness instead of the original 2px thickness. I think it is clearer than before and thus an improvement.

I think so too. So, I propose that we should go with this option instead.

@conradolandia, what do you think?

**Comment by conradolandia** [comment]
I think this option works fine enough, yes.

**Comment by jitseniesen** [comment]
Great, I squashed the commits in one, as it is basically a one-character change now.

**Review by ccordoba12 — APPROVED** [review]
Thanks @jitseniesen!

Note: The error in our test suite is unrelated to this.

**Comment by jmshon-ssu** [comment]
Please unsubscribe me.
Thanks,
________________________________

**Pull request merged**
