### PR TITLE
PR: Fix unblock comments

### LINKED ISSUE #4313: "unblockcomment" incompatible with "automatically remove trailing spaces"
## Description of your problem

**What steps will reproduce the problem?**
For example, there are codes:
"""
import numpy as np

def test():
    return 1

test()
"""
1. Enable the feature "Automatically remove trailing spaces when saving files"
2. blockcomment (ctl+4) the piece of codes above
2. save the file (ctl+s)
3. unblockcomment (ctl+5)

**What is the expected output? What do you see instead?**
The expected output is
"""
import numpy as np

def test():
    return 1

test()
"""
However, we see
“”“
import numpy as np
\# def test():
    return 1
\# test()
”“”
**Please provide any additional information below**
It seems like the enabled feature (removing trailing spaces) removes the newline character when saving the file.

## Versions and main components

* Spyder Version: 3.1.3
* Python Version: 2.7.12
* Qt Version:
* PyQt Version:
* Operating system: Ubuntu 16.04

## Dependencies

Please go to the menu entry `Help > Optional Dependencies` (or
`Help > Dependencies`), press the button `Copy to clipboard`
and paste the contents below:
jedi =0.9.0      :  0.9.0 (OK)
matplotlib >=1.0 :  1.5.3 (OK)
nbconvert >=4.0  :  4.2.0 (OK)
numpy >=1.7      :  1.11.1 (OK)
pandas >=0.13.1  :  0.18.1 (OK)
pep8 >=0.6       :  1.7.0 (OK)
psutil >=0.3     :  4.3.1 (OK)
pyflakes >=0.5.0 :  1.3.0 (OK)
pygments >=2.0   :  2.1.3 (OK)
pylint >=0.25    :  1.5.4 (OK)
qtconsole >=4.2.0:  4.2.1 (OK)
rope >=0.9.4     :  0.9.4 (OK)
sphinx >=0.6.6   :  1.4.6 (OK)
sympy >=0.7.3    :  1.0 (OK)

### PR DESCRIPTION
**Pull request by timhoffm**
Fixes #4313.

### CODE REVIEW

**Comment by timhoffm** [comment]
The pep8 checker above moans about the line length. I would be reluctant to wrap in the above case.

Do you have a policy for the line length? I've noticed that most code sticks to ~80 chars, but there are some exceptions.

While we're at it, do you have a documented code style? I've not found anything on this.

**Comment by jnsebgosselin** [comment]
@ccordoba12 I've tested it locally and this is working as expected. Maybe this should be rebased to the 3.x branch since this is a bug fix?

Maybe a test should also be added to test this feature?

**Comment by ccordoba12** [comment]
> Maybe this should be rebased to the 3.x branch since this is a bug fix?

Yes, I think so too. @timhoffm, please follow these instructions to perform the rebase:

https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md#changing-base-branch

Also, please fix the style issues reported by Pep8speaks.

**Comment by timhoffm** [comment]
@ccordoba12, I've fixed the pep8.

Any idea why AppVeyor sometimes hangs at the test `spyder/plugins/tests/test_ipythonconsole.py::test_console_import_namespace`? For the first commit 2.7 hung but 3.6 ran. Now, with no change but some extra line breaks 2.7 ran, but 3.6 hung. I suspect this is not related to my code.

**Comment by ccordoba12** [comment]
@timhoffm, the failure was unrelated to your work. Thanks a lot for your contribution!

**Pull request merged**
