### PR TITLE
PR: Update Windows installer assets URL to add previous installation validation

### LINKED ISSUE #17025: Code Analysis error in the Windows installer when overwriting installation with a new installer version
### What steps will reproduce the problem?

Starting Code Analysis results in error message.

### Traceback
```python-traceback
pylint error:

Traceback (most recent call last):
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 193, in _run_module_as_main
  File "D:\obj\windows-release\37amd64_Release\msi_python\zip_amd64\runpy.py", line 85, in _run_code
  File "C:\Program Files\Spyder\pkgs\pylint\__main__.py", line 9, in <module>
    pylint.run_pylint()
  File "C:\Program Files\Spyder\pkgs\pylint\__init__.py", line 24, in run_pylint
    PylintRun(sys.argv[1:])
  File "C:\Program Files\Spyder\pkgs\pylint\lint\run.py", line 279, in __init__
    linter.load_default_plugins()
  File "C:\Program Files\Spyder\pkgs\pylint\lint\pylinter.py", line 579, in load_default_plugins
    checkers.initialize(self)
  File "C:\Program Files\Spyder\pkgs\pylint\checkers\__init__.py", line 133, in initialize
    register_plugins(linter, __path__[0])
  File "C:\Program Files\Spyder\pkgs\pylint\utils\utils.py", line 198, in register_plugins
    module.register(linter)
  File "C:\Program Files\Spyder\pkgs\pylint\checkers\unsupported_version.py", line 85, in register
    linter.register_checker(UnsupportedVersionChecker(linter))
  File "C:\Program Files\Spyder\pkgs\pylint\lint\pylinter.py", line 723, in register_checker
    self.msgs_store.register_messages_from_checker(checker)
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_definition_store.py", line 39, in register_messages_from_checker
    self.register_message(message)
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_definition_store.py", line 44, in register_message
    message.msgid, message.symbol, message.old_names
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_id_store.py", line 44, in register_message_definition
    self.check_msgid_and_symbol(msgid, symbol)
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_id_store.py", line 81, in check_msgid_and_symbol
    self._raise_duplicate_symbol(msgid, symbol, existing_symbol)
  File "C:\Program Files\Spyder\pkgs\pylint\message\message_id_store.py", line 90, in _raise_duplicate_symbol
    raise InvalidMessageError(error_message)
pylint.exceptions.InvalidMessageError: Message id 'W1601' cannot have both 'apply-builtin' and 'using-f-string-in-unsupported-version' as symbolic name.

```

## Versions

* Spyder version: 5.2.1 
* Python version: 3.7.9
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.0.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree                  :  None (OK)
IPython >=7.6.0               :  7.30.1 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.8.9 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.4.0 (OK)
nbconvert >=4.0               :  6.3.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
paramiko >=2.4.0              :  2.8.1 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.10.0 (OK)
pylint >=2.5.0                :  2.12.2 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.3.2;<1.4.0          :  1.3.3 (OK)
pylsp_black >=1.0.0           :  1.0.1 (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.2.1;<5.3.0      :  5.2.2 (OK)
qtpy >=1.5.0                  :  1.11.3 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  59.6.0 (OK)
sphinx >=0.6.6                :  4.3.1 (OK)
spyder_kernels >=2.2.0;<2.3.0 :  2.2.0 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog                      :  2.1.6 (OK)
zmq >=17                      :  22.3.0 (OK)

# Optional:
cython >=0.21                 :  0.29.25 (OK)
matplotlib >=2.0.0            :  3.5.1 (OK)
numpy >=1.7                   :  1.19.3 (OK)
pandas >=1.1.1                :  1.3.5 (OK)
scipy >=0.17.0                :  1.7.3 (OK)
sympy >=0.7.3                 :  1.9 (OK)
```

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Adds a validation for previous installations with the Windows installer. Before launching the installer a validation for an old installation is run. If an old installation is detected a messagebox appears to ask the users if they want to launch the uninstaller:

imagen

Clicking Sí/Yes:

imagen

Depends on https://github.com/spyder-ide/windows-installer-assets/pull/6 and a new release (0.0.5)

Note: After the uninstall the installer needs to be relaunched to do the install

### Issue(s) Resolved

Fixes #17025 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by ccordoba12** [comment]
Could show add a screenshot to the description above the see how this new functionality looks?

**Comment by ccordoba12** [comment]
Thanks @dalthviz! What happens if the user clicks `No`? Does the installation process abort?

**Comment by dalthviz** [comment]
Yes, the installation process exits @ccordoba12

**Comment by ccordoba12** [comment]
Ok, great! That's what I'd like to enforce too, but I wanted to check with your before proceeding.

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz! Great work here.

**Pull request merged**
