### PR TITLE
PR: Show icon instead of text for small widths and clear found results correctly in Find/Replace widget

### LINKED ISSUE #20476: Buttons in find and replace widget jump around for small editor widths
### What steps will reproduce the problem?

1 - Use master
2 - create a file containing `aaaa`
3 - search and replace `aa` to `bb`
4 - the buttons are jumping around! :
Screenshot 2023-02-04 at 10 26 42
Screenshot 2023-02-04 at 10 26 50
Screenshot 2023-02-04 at 10 26 58

This makes it really annoying to replace many occurrences as you have to adjust the mouse every time

## Versions

* Spyder version: 6.0.0.dev0 dc630ab62 (pip)
* Python version: 3.10.8 64-bit
* Qt version: 5.15.5
* PyQt5 version: 5.15.7
* Operating System: Darwin 22.2.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.3.0     :  0.3.0 (OK)
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.0.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  7.34.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.16.0 (OK)
keyring >=17.0.0              :  23.9.3 (OK)
nbconvert >=4.0               :  7.1.0 (OK)
numpydoc >=0.6.0              :  1.4.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.2 (OK)
pygments >=2.0                :  2.13.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.3 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.1;<1.8.0          :  1.7.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.1 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.5.0.dev0 (OK)
qtpy >=2.1.0                  :  2.2.1 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  65.4.1 (OK)
sphinx >=0.6.6                :  5.2.3 (OK)
spyder_kernels >=2.4.2;<2.5.0 :  3.0.0.dev0 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.9 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  0.29.32 (OK)
matplotlib >=3.0.0            :  3.6.1 (OK)
numpy >=1.7                   :  1.23.3 (OK)
pandas >=1.1.1                :  1.5.0 (OK)
scipy >=0.17.0                :  1.9.2 (OK)
sympy >=0.7.3                 :  1.11.1 (OK)
```

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

- This prevents that the widget buttons change position when users replace text with it and the number of matches start to change. The number is shown in the button's tooltip in that case, as shown below:

    number_matches_icon

- Clear found results when clicking on the clear action, I noticed this bug while working on Spyder.

    clear_matches

### Issue(s) Resolved

Fixes #20476.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Review by dalthviz — APPROVED** [review]
Thanks @ccordoba12 ! Checked locally on Windows and seems like this is working :+1:

As a side note, while testing I noticed a behavior in the find functionality. When you change files you don't get the number of matches updated. Is that an issue or improvement worthy to check here too? Or maybe a new issue should be created for that? Or maybe is that the desired behavior already?

**Review by impact27 — APPROVED** [review]
Looks good to me

**Comment by ccordoba12** [comment]
> As a side note, while testing I noticed a behavior in the find functionality. When you change files you don't get the number of matches updated. Is that an issue or improvement worthy to check here too? Or maybe a new issue should be created for that? Or maybe is that the desired behavior already?

Very good UI catch @dalthviz! I fixed it in my last commit and added a new test for that functionality.

**Comment by dalthviz** [comment]
Checked locally the new changes and seems like they are working :+1: Should we merge this @ccordoba12 @impact27 ?

**Comment by ccordoba12** [comment]
Yeah, I think it's ready.

**Comment by ccordoba12** [comment]
Merging because I haven't heard any objections in the last couple of days about it.

Thanks @dalthviz and @impact27 for the review!

**Pull request merged**
