### PR TITLE
PR: Detect unavailable dependencies for special consoles

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Show error message for special consoles when dependencies (`matplotlib`, `sympy`, `cython`) are unavailable.

Selección_016

### Issue(s) Resolved

Part of #11357 
Depends on spyder-ide/spyder-kernels#198

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, please solve the merge conflict on this one so I can merge it. I'm sorry but I forgot about this PR until I was testing this functionality right now.

**Comment by ccordoba12** [comment]
@dalthviz, it seems your last commit introduced a lot of flakyness in the IPython console tests, so I think you should need to revert it.

**Comment by goanpeca** [comment]
Is this ready @dalthviz ?

**Comment by ccordoba12** [comment]
I'm going to improve the error message a bit, then it'll be ready.

**Pull request merged**
