### PR TITLE
PR: Add cp1251 (default Russian) encoding on Windows to be recognized by the Editor

### LINKED ISSUE #5552: Explicitly stated default Russian encoding on Windows not recognized
The default Russian encoding on Windows (cp1251) is not recognized in spite of being explicitly
stated in the first line of the file.

**What steps will reproduce the problem?**
I open a file with the first line reading
    
    # -*- coding: cp1251 -*-

**What is the expected output? What do you see instead?**
I expect it to be opened in Windows-1251 encoding
I get it opened in LATIN-1-GUESSED instead.

**Please provide any additional information below**
There're "iso8859-5" and "koi8-r" for Russian, but on Windows the default encoding is cp1251 (Windows-1251), which is significantly different from both.

When there're enough characters for the autodetection to work, everything is fine, but when there're just a couple of words I get the behaviour described above.

## Versions and main components

* Spyder Version: 3.2.5 32 bits
* Python Version: 3.6.2
* Qt Version: 5.9.1
* PyQt Version: 5 5.9
* Operating system: Windows 7

## Dependencies

IPython >=4.0 : 6.2.1 (OK)
cython >=0.21 : None (NOK)
jedi >=0.9.0 : 0.11.0 (OK)
nbconvert >=4.0 : 5.3.1 (OK)
numpy >=1.7 : None (NOK)
pandas >=0.13.1 : None (NOK)
pycodestyle >=2.3: 2.3.1 (OK)
pyflakes >=0.6.0 : 1.6.0 (OK)
pygments >=2.0 : 2.2.0 (OK)
pylint >=0.25 : 1.7.4 (OK)
qtconsole >=4.2.0: 4.3.1 (OK)
rope >=0.9.4 : 0.10.7 (OK)
sphinx >=0.6.6 : 1.6.4 (OK)
sympy >=0.7.3 : None (NOK)

### PR DESCRIPTION
**Pull request by axil**
Fixes #5552

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for your contribution. This is going to be part of Spyder 4, to be released next year, unless you create a new pull request against our `3.x` branch.

**Comment by rlaverde** [comment]
You could move this to 3.x  branch following these instructions https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md#changing-base-branch

**Comment by axil** [comment]
Done

**Comment by ccordoba12** [comment]
Thanks!

**Pull request merged**
