### PR TITLE
PR: Remove gettext scripts separated into their own repo

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
### Pull Request Checklist

* [x] Read and followed this repo's [Contributing Guidelines](https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md)
* [x] Based your PR on the latest version of the correct branch (master or 3.x)
* [x] Followed [PEP8](https://www.python.org/dev/peps/pep-0008/) for code style
* [x] Ensured your pull request hasn't eliminated unrelated blank lines/spaces,
      modified the ``spyder/defaults`` directory, or added new icons/assets
* [x] Described your changes and the motivation for them below

## Description of Changes

Removed the gettext_*.py scripts in the root, since they've been moved to their own repo. Marked [WiP] so as not to merge until that repo is set up properly.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks @CAM-Gerlach! Let's wait for @jnsebgosselin to fix our tests before merging this one.

**Comment by jnsebgosselin** [comment]
I'm in the process of rebasing #7790, this should be done shortly.

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12 and @jnsebgosselin ; standing by to rebase once that's done.

**Comment by jnsebgosselin** [comment]
My PR address only part of the problem it seems. There is another test that needs fixing :
`spyder/plugins/tests/test_ipythonconsole.py::test_auto_backend`
I really don't know why it is segfaulting.

**Comment by CAM-Gerlach** [comment]
@jnsebgosselin I've seen that one segfault seemingly randomly maybe 1/10 times on Travis in the past...

**Comment by ccordoba12** [comment]
Failures in Travis were already fixed.

**Comment by CAM-Gerlach** [comment]
Thanks @ccordoba12 !

**Pull request merged**
