### PR TITLE
PR: Update org.spyder_ide.spyder.appdata.xml

### PR DESCRIPTION
**Pull request by kevinsmia1939**
## Description of Changes

Update metadata for release date and version in org.spyder_ide.spyder.appdata.xml

This simply keep the version and release date update for any service that use the appdata file.

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
Kavin Teenakul

### CODE REVIEW

**Review by ccordoba12 — APPROVED** [review]
Thanks for your help @kevinsmia1939!

**Comment by ccordoba12** [comment]
@meeseeksdev please backport to 6.x

**Comment by dalthviz** [comment]
@ccordoba12 should updating this file be part of the steps over `RELEASE.md` ?

**Comment by ccordoba12** [comment]
Yes, that's a very good idea! You can either add that additional instruction when updating our Changelog for 6.0.1 or opening an extra PR just for that (up to you).

**Pull request merged**
