### PR TITLE
PR: Add translation for Simplified Chinese

### PR DESCRIPTION
**Pull request by kingmo888**
`spyder/config/base.py`:add:'zh_CN': u'简体中文',
creat new folder 'spyder/locale/zh_CN/LC_MESSAGES/'

### CODE REVIEW

**Comment by kingmo888** [comment]
the error is :

> spyder/tests/test_dont_use.py::test_dont_use[isinstance\(.*,.*str\)-exclude_patterns0-Don't use builtin isinstance() function,use spyder.py3compat.is_text_string() instead] PASSED
spyder/tests/test_dont_use.py::test_dont_use[^[\s\#]*\bprint\(((?!file=).)*\)-exclude_patterns1-message1] 
./continuous_integration/circle/test-qt5.sh || ./continuous_integration/circle/test-qt5.sh || ./continuous_integration/circle/test-qt5.sh died unexpectedly


however, I didn't change any detials in this file whose path is "spyder/tests/test_dont_use.py".

**Comment by ccordoba12** [comment]
Thanks a lot for this!!

Don't worry about the error, it's completely unrelated to your work.

**Comment by ccordoba12** [comment]
@kingmo888, question: would you be available in the future to keep updating this translation?

Besides, I'd like to let you know that since you did your translation against our `master` branch, it'll be available only when we release Spyder 4 (in six months or so). I hope that's ok for you.

**Comment by kingmo888** [comment]
@ccordoba12 
3Q, I will be update the translation when spyder has been update.

**Comment by ccordoba12** [comment]
Thanks a lot for your efforts! This will be part of Spyder 4, to be released early next year.

**Pull request merged**
