### PR TITLE
PR: Change colors for tour dialog in light mode

### LINKED ISSUE #14203: Spyder 4.2 tour dialog box not respecting light theme from previous spyder
### What steps will reproduce the problem?

Starting Spyder 4.2 for the first time after upgrading from 4.1.5 where a light colour scheme theme was used, the new tour dialog box displays low contrast black text on a black background.

## Versions

* Spyder version: 4.2.0 
* Python version: 3.7.9
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0            :  1.4.0 (OK)
chardet >=2.0.0                 :  3.0.4 (OK)
cloudpickle >=0.5.0             :  1.6.0 (OK)
diff_match_patch >=20181111     :  20200713 (OK)
intervaltree >=3.0.2            :  3.1.0 (OK)
IPython >=4.0                   :  7.18.1 (OK)
jedi =0.17.2                    :  0.17.2 (OK)
jsonschema >=3.2.0              :  3.2.0 (OK)
nbconvert >=4.0                 :  5.6.1 (OK)
numpydoc >=0.6.0                :  1.1.0 (OK)
paramiko >=2.4.0                :  2.7.2 (OK)
parso =0.7.0                    :  0.7.0 (OK)
pexpect >=4.4.0                 :  4.8.0 (OK)
pickleshare >=0.4               :  0.7.5 (OK)
psutil >=5.3                    :  5.7.2 (OK)
pygments >=2.0                  :  2.6.1 (OK)
pylint >=1.0                    :  2.6.0 (OK)
pyls >=0.36.1;<1.0.0            :  0.36.1 (OK)
pyls_black >=0.4.6              :  0.4.6 (OK)
pyls_spyder >=0.1.1             :  0.1.1 (OK)
qdarkstyle >=2.8                :  2.8.1 (OK)
qtawesome >=0.5.7               :  0.7.2 (OK)
qtconsole >=4.7.7               :  4.7.7 (OK)
qtpy >=1.5.0                    :  1.9.0 (OK)
rtree >=0.8.3                   :  0.9.4 (OK)
setuptools >=39.0.0             :  49.6.0.post20200814 (OK)
sphinx >=0.6.6                  :  3.2.1 (OK)
spyder_kernels >=1.10.0;<1.11.0 :  1.10.0 (OK)
three_merge >=0.1.1             :  0.1.1 (OK)
watchdog >=0.10.3               :  0.10.3 (OK)
zmq >=17                        :  19.0.1 (OK)

# Optional:
cython >=0.21                   :  0.29.21 (OK)
matplotlib >=2.0.0              :  3.3.1 (OK)
numpy >=1.7                     :  1.19.1 (OK)
pandas >=1.1.1                  :  1.1.1 (OK)
scipy >=0.17.0                  :  1.5.2 (OK)
sympy >=0.7.3                   :  1.6.2 (OK)

# Spyder plugins:
spyder_notebook                 :  0.3.0 (OK)
spyder_terminal                 :  0.4.2 (OK)
```

### PR DESCRIPTION
**Pull request by juanis2112**
## Description of Changes
 
* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Changed colors  pf background and buttons in the tour dialog for Spyder's light mode

Screenshot 2020-12-10 at 9 45 20 AM

### Issue(s) Resolved

Fixes #14203 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
Juanis2112

### CODE REVIEW

**Comment by juanis2112** [comment]
When we designed the tour dialog we didn't actually take into account the colors for the light mode. What do you think about this @isabela-pf. I used two of the colors of the palette for the buttons.

**Comment by isabela-pf** [comment]
Thanks for catching this! It got buried in a to do list somewhere. 

I think in meetings we had talked about still having buttons having light text on dark buttons in light mode (like shown in [#13](https://github.com/spyder-ide/ux-improvements/issues/13)) with buttons being `#1A72BB` and `#60798B`. That would look like this:
Screen Shot 2020-12-09 at 1 46 00 PM

**Comment by ccordoba12** [comment]
@isabela-pf, I really like your suggestion!

@juanis2112, please rebase on top of the latest `4.x` to get to our tests.

**Comment by juanis2112** [comment]
Thanks @isabela-pf. I updated the screenshot according to the latest changes and rebased @ccordoba12.

**Review by ccordoba12 — DISMISSED** [review]
Great job @juanis2112!

And thanks @isabela-pf for your help to select the appropriate colors for this.

**Review by ccordoba12 — APPROVED** [review]

**Pull request merged**
