### PR TITLE
PR: More accurate test for text-like files

### LINKED ISSUE #2703: File in Project Explorer is being executed(?) on dbl-click
WinPython-64bit-3.4.3.4
Double-clicking on a file with the following content opens python console with "ImportError: No module named PyQt4"

```python
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 26 11:53:52 2015

@author: автор
"""

from PyQt4 import QtGui
from general import COL, showConsole
from context import *
    
railways = {"Октябрьская Ж.Д.": 1, "Октябрьская": 1,
      "Калининградская Ж.Д.": 2, "Калининградская": 2,
      "Московская Ж.Д.": 3, "Московская": 3,
      "Горьковская Ж.Д.": 4, "Горьковская": 4,
      "Северная Ж.Д.": 5, "Северная": 5,
      "Северо-Кавказская Ж.Д.": 6, "Северо-Кавказская": 6,
      "Юго-Восточная Ж.Д.": 7, "Юго-Восточная": 7,
      "Приволжская Ж.Д.": 8, "Приволжская": 8,
      "Куйбышевская Ж.Д.": 9, "Куйбышевская": 9,
      "Свердловская Ж.Д.": 10, "Свердловская": 10,
      "Южно-Уральская Ж.Д.": 11, "Южно-Уральская": 11,
      "Западно-Сибирская Ж.Д.": 12, "Западно-Сибирская": 12,
      "Красноярская Ж.Д.": 13, "Красноярская": 13,
      "Восточно-Сибирская Ж.Д.": 14, "Восточно-Сибирская": 14,
      "Забайкальская Ж.Д.": 15, "Забайкальская": 15,
      "Дальневосточная Ж.Д.": 16, "Дальневосточная": 16}
```

### PR DESCRIPTION
**Pull request by Qlogin**
Fixes #2703 

----

In UTF-8 one character can be represented by multiple bytes. If such bytes have not been placed in the same chunk (CHUNKSIZE=1024), function 'is_text_file' from encoding.py will fail on this input.
Solution is to use IncrementadDecoder.

It is possible that issue #2703 is related to this fix. Since the file attached to issue is determined as binary, spyder tries to open it with external program (console) (instead of editing)

### CODE REVIEW

**Comment by ccordoba12** [comment]
@Qlogin, thanks for your work on fixing this problem. Could you upload a file that's showing the error you're reporting here?

----

@blink1073, you introduced the `is_text_file` function, so could you give a quick review to this PR?

**Comment by blink1073** [comment]
I think it looks sound, thanks @Qlogin!

**Comment by Qlogin** [comment]
@ccordoba12, sorry, I've used GitHub not so long. All I could is to attach archive with test file.
[test.zip](https://github.com/spyder-ide/spyder/files/97318/test.zip)

**Comment by goanpeca** [comment]
@blink1073 / @ccordoba12  is this ready for merging?

**Comment by blink1073** [comment]
I think so.

**Comment by ccordoba12** [comment]
Thanks a lot for your fix @Qlogin!! I verified that this fixes the reported problem in #2703 :-)

**Pull request merged**
