### PR TITLE
PR: Add autocomplete to the debugger

### LINKED ISSUE #288: Code completion doesn't work in the debugger
_From [mproel...@googlemail.com](https://code.google.com/u/105494983286078857315/) on 2010-08-12T04:07:56Z_

Hi,

when starting a debug session, and being in a function the code completition doesn't show up a local variable that you have defined. Example:

def test():
    print "hello world"

test()

run a debug session, when being at print ... type
(Pdb) !var = 13
(Pdb) v<tab> #var doesn't show up
(Pdb) var
13

For global variables it works fine (e.g. do the same at line test())

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=288_

### LINKED ISSUE #9939: Autocomplete in ipdb
## Problem Description
When using the debugger, there is no autocomplete, unlike while otherwise using the console. 
I think it is surprising to the user that the console is behaving differently while debugging and while not debugging.

### What steps reproduce the problem?
1. type : `abba = 1` in the console
2. on the next line, `ab<tab>` gives a list of `abba` and `abs`
3. launch a debugger
4. type : `abba = 1`
5. on the next line, `ab<tab>` gives `ab    `

### What is the expected output? What do you see instead?
I would expect the autocomplete to work while debugging as well. 

## Versions

* Spyder version: 4.0.0.dev0 b7844ba66
* Python version: 3.7.3
* Qt version: 5.12.3
* PyQt5 version: 5.12.2
* Operating System: Darwin 18.7.0

### Dependencies

```
pygments >=2.0    :  2.3.1 (OK)
qdarkstyle >=2.6.4:  2.6.5 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
psutil >=0.3      :  5.6.1 (OK)
pyls >=0.27.0     :  0.27.0 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
numpy >=1.7       :  1.16.2 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29.6 (OK)
qtconsole >=4.5.0 :  4.5.1 (OK)
IPython >=4.0     :  7.3.0 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
pylint >=0.25     :  2.3.1 (OK)
```

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

autocomplete

Added a call to the autocomplete widget while debugging.

This depends on the communication with the kernel from PR #9343, as the kernel normally doesn't process messages while debugging.

### Issue(s) Resolved

Fixes  #288

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
Impact27

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for this @impact27!! This is a huge improvement!

I'll try to review and merge all your pending pull requests in beta5.

**Comment by ccordoba12** [comment]
@impact27, please merge with master to get the latest fixes to our tests.

**Comment by impact27** [comment]
It won't work because this needs https://github.com/spyder-ide/spyder-kernels/pull/133

**Comment by impact27** [comment]
I am not sure why `spyder/plugins/ipythonconsole/tests/test_ipythonconsole.py::test_console_complete` is failing. It looks like `abs` is not detected? This test pass on my mac.

**Comment by impact27** [comment]
Retrigger after #10314

**Pull request merged**
