### PR TITLE
PR: Simplify find replace, add highlight by default and update colors

### LINKED ISSUE #1869: Find/Replace color should be configurable. From Theme maybe?
_From [phyo.arkarlwin](https://code.google.com/u/phyo.arkarlwin/) on 2014-06-24T19:17:20Z_

Currently , using Find highlight color mess up with dark background, making text unable to read.

Should it read from Mark Occourence color of current scheme?

Or 

Another Custom setting for schema?

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1869_

### LINKED ISSUE #7247: Find and Replace stops highlighting any matches if any change is made in the Editor
## Problem Description

Often, I'll want to highlight all occurrences of a certain name, in order to modify, check something, or otherwise take action at or around instances of it. This would appear to be a prototypical use case of Find/Replace's highlighting feature; however, an apparent bug makes it almost useless—the highlighting won't stick if even one character is added, deleted or modified in the editor, whether or not in or near (even in a different line) any matched result,  In one stroke, this prevents most if not nearly all the use cases for highlighting I can think of, at least that aren't filled by double-clicking on a name, and is unlike other editors (e.g. NP++, Eclipse etc) where the highlighting sticks around until either the user turns it off or the Find/Replace dialog is closed.

### What steps reproduce the problem?

1. Enter any text in the "Find" field with one or more matches
2. Enable the Highlighting option in that dialog
3. Enter, delete any text anywhere in the active editor

Poof, highlighting vanishes.

## Proposed Solutions

I haven't yet dug into the code, but any quick suggestions as to why this is happening, and if there are any major obstacles to fixing it?

## Package Versions

* Spyder version: 3.2.8 
* Python version: 3.6.4
* Qt version: 5.6.2
* PyQt5 version: 5.6
* Operating system: Windows 8.1

### Dependencies

```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.22.0 (OK)
numpy >=1.7      :  1.14.0 (OK)
sphinx >=0.6.6   :  1.7.2 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.11.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.27.3 (OK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.2.1 (OK)
pylint >=0.25    :  1.8.2 (OK)
```

### LINKED ISSUE #10429: Include highlight color of 'Find' matches in syntax coloring preferences
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* x ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

In the 'Spyder Dark' theme, when enabling 'highlight matches' in Find in the editor, the matches are shown with a bright pink background, which is difficult to read. It would be nice if this color was included in the syntax coloring preferences

### What steps reproduce the problem?

1. Select the 'Python Dark' syntax coloring scheme.
2. Ctrl+F  Find some keyword
3. Enable 'highlight matches' on the Find toolbar

## Versions

* Spyder version: 3.3.6
* Python version: 3.7.3
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Ubuntu 18.04

### Dependencies

```
IPython >=4.0     :  7.6.1 (OK)
cython >=0.21     :  0.29.12 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.1.0 (OK)
nbconvert >=4.0   :  5.5.0 (OK)
numpy >=1.7       :  1.16.4 (OK)
pandas >=0.13.1   :  0.24.2 (OK)
psutil >=0.3      :  5.6.3 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.4.2 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.5.1 (OK)
rope >=0.9.4      :  0.14.0 (OK)
sphinx >=0.6.6    :  2.1.2 (OK)
sympy >=0.7.3     :  1.4 (OK)
```

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)
* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Changes

- Added placeholder texts (`Find` `Replace`)
- Remove the unnecessary `Replace with` word. 
- Make both find/replace text boxes uniform (Same length)
- Update the color for match results (using unmatched braces color from theme)
- Update the highlight color of match results (no matches is highlighted with unmatched braces color from theme if no matches are found)
- Remove the textedit background coloring if no matches found in regex (it was really not providing much help). Instead added the unmatched_parens color from theme as the text color (not the background)
- Always highlight changes, remove "Highlight" toggle button. Why would anyone not want the matches to be highlighted ???
- Shorten texts for replace texts
- Add live update of matches if editor is updated and the widget is visible

#### Before

Screen Shot 2019-11-30 at 19 14 13

#### After

Screen Shot 2019-11-30 at 19 13 30

#### Workflow

**Dark**
find-dark

**Light**
find-light

**Live updates**
find-live

### Issue(s) Resolved

Fixes #7247
Fixes #10429
Fixes #1869

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
@CAM-Gerlach this should fix the issue. 

@ccordoba12 @jnsebgosselin I also took the liberty of doing some changes that I think were really needed. The find replace widget really needed some love.

Please let me know what you think. I still need to check some tests that are failing due to some changes.

**Comment by goanpeca** [comment]
Some other things to consider. Probably the find replace widget should store the options on the config so that on subsequent restarts they are toggled by default. Someone using regex all the time should not have to press that button on every Spyder session.

Should this be global? (all find/replace widgets?) or should this be stored by plugin? (Editor, consoles etc...)

**Comment by goanpeca** [comment]
>The always-on highlighting cases huge hangs on larger files. All I had open was mainwindow.py (and the default Spyder temp file), and I started typing "logging" in the find box and spyder hung/froze for well over 30 seconds before it became responsive again.

Ok, need to optimize this process, it should not block, but indeed a problem!

>Maybe consider dropping or replacing the checkmarks? They don't really correspond to the actions being taken.

Agreed!

>Change "Selection" to "In Selection" to be much more clear about what this does; this confused me initially and always bothered me

Agreed

> I'd suggest using the actual "Occurrence" color instead of the "unmatched parens" color for several reasons: First, it is, well, the actual occurrence color, what users would expect to see highlighted, Second, the unmatched parents color is identical or similar to the pylint error color, making it impossible to distinguish them in the sidebar, as well as with red highlighted portions that indicate the syntax triggering the error. Finally, "red" (the default in Spyder Dark) is UI-speak for "bad", which doesn't match what this is doing. The only downside is then there isn't a clear distinction between double-click occurrences and F&R color, though given they do the same thing I'm not sure how much users are going to be using them at the same time, and they can still tell them apart based on the matches. If this is a concern, you can make it a different opacity and/or use the "matched parenthesis" color which avoids most of the problems of the unmatched one, though not all of them.

Occurrence serves a different purpose, but yeah they could be the same.

**Comment by CAM-Gerlach** [comment]
> Occurrence serves a different purpose, but yeah they could be the same.

Right, I discuss that in my comment, but they are very close conceptually esp. compared to unmatched paren color.

**Comment by goanpeca** [comment]
>The always-on highlighting cases huge hangs on larger files. 

I guess if there are mote that "X" number of matches we should not highlight them, now we need to define a sensible number, 100? 500? 1000?

**Comment by CAM-Gerlach** [comment]
> I guess if there are mote that "X" number of matches we should not highlight them, now we need to define a sensible number, 100? 500? 1000?. This way we highglight by default but do not block the interface if too many matches are found :-)

I'd suggest a little different approach better suited to the actual problem. Users may want every match highlighted in some cases even with a large number of matches; the problem really is that the matches update constantly with every letter typed and the first character is going to match a ton of stuff in larger files, while this doesn't correspond to what the user actually cares to see (they only want to see the matches to their actual desired expression once they finish typing).

To ensure that only the matches the user wants to see are highlighted, I'd instead impose a e.g. 500 or 1000 ms textbox idle delay (this wouldn't need to be user-configurable, you can just set it to whatever ensures good performance and UX) before starting to highlight matches (other than the first one), similar to what we have for completion. Then, the user can type their expression and have all the other info update in real-time, while once they are done typing (or pause to see the results), the highlighting kicks in.

This helps things in two ways: first, the highlights aren't drawn on shorter character sequences that are likely to result in exponentially more matches unless the user actually wants them to (stops/pauses typing), and the highlights aren't redrawn with every character typed, only when the user actually wants to see them. However, the user still has full and final control over what gets highlighted and it doesn't limit it in that respect.

**Comment by goanpeca** [comment]
Ok, I have an idea. I will try to only paint the visible selections, this should make this work for most use cases. For the cases where the visible screen contains too many (>500 ?) selections we can just not show them.

**Comment by CAM-Gerlach** [comment]
@goanpeca That's even better; I was going to suggest that but I assumed it wasn't easily done. Will there be substantial visible latency or unresponsiveness when scrolling the screen, as additional highlights are drawn? If so, maybe if there is less than some small number of matches, e.g. 20 or 50, you can just draw all of them? Will highlight locations still be indicated in the thin side panel next to the scroll bar so users can scroll to find them (a significant use case), just not actually drawn in the editor text area itself?

**Comment by goanpeca** [comment]
>  Will highlight locations still be indicated in the thin side panel next to the scroll bar so users can scroll to find them (a significant use case), just not actually drawn in the editor text area itself?

Yes

**Comment by ccordoba12** [comment]
@goanpeca, could you finish this one so we can include it for 4.0.2? I think it's a pretty good addition and it also fixes important issues too.

**Comment by goanpeca** [comment]
>could you finish this one so we can include it for 4.0.2? I think it's a pretty good addition and it also fixes important issues too.

I will try, it might take longer than expected!

**Comment by CAM-Gerlach** [comment]
Hey @goanpeca , this was a major improvement and I thought it was almost done, except for a fix to the performance issues (which should hopefully be solvable with either the changes already introduced in the recent PR to only draw the decorations in the visible portion of the screen, as you suggested here, and if needed a keyboard idle delay of ~500-1000 ms before updating, as we do for on the fly completion. Is there a reason it was closed?

**Comment by goanpeca** [comment]
Hi @CAM-Gerlach. I am not working on this anymore. It was not almost done. Someone else can pick the work I started.

Cheers!

**Comment by ccordoba12** [comment]
I don't understand why you removed the branch associated to this PR. I just reopened it because, as @CAM-Gerlach said, this is very important and we'd like to finish it (I was not expecting it for you to do it).

Could you push your changes again? Thanks.

**Comment by goanpeca** [comment]
> I don't understand why you removed the branch associated to this PR. 

I did not notice, I was doing branch cleanup and this branch has been stale for like 7 months and I did not realize.

> I just reopened it because, as @CAM-Gerlach said, this is very important and we'd like to finish it (I was not expecting for you to do it). 

Sure, will push it back.

**Comment by ccordoba12** [comment]
Closing because this was superseded by PR #20049.

**Pull request closed without merging**
