### PR TITLE
WIP: Add automatic introduction of docstrings for class

### LINKED ISSUE #11924: Feature request: Automatic docstring generation for classes
Automatic docstring generation for functions is very useful and has already been implemented in #4936. Could it be done for classes too?

### PR DESCRIPTION
**Pull request by ok97465**
## Description of Changes

* [X] Wrote at least one-line docstrings (for any new functions)
* [X] Added unit test(s) covering the changes (if testable)

* [X] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Functionality of PR
- write arguments of __init__ to Parameters section of class docstring
- write class variables to Attributes section of class docstring
- write method names to Methods section of class docstring

Todo
* [ ] add google doc style
* [ ] add sphinx doc style

Peek 2020-03-31 22-46

### Issue(s) Resolved

Fixes #11924

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ok97465** [comment]
I'm not sure that all users like PR. I think it would be better to add on/off options for PR or to reduce the functionality of the PR.

I'll go ahead or close it according to your opinions.

**Comment by ccordoba12** [comment]
@CsatiZoltan, we'd value your feedback since you were the one that requested for it.

**Comment by goanpeca** [comment]
@ok97465 cool!

regarding:
>I think it would be better to add on/off options for PR or to reduce the functionality of the PR.

You mean like: 

- [ ] include class attributes
- [ ] include under methods
- [ ] include dunder methods
?

**Comment by CsatiZoltan** [comment]
Really nice. Some remarks:
- "The docstring for a class should summarize its behavior and list the *public* methods and instance variables." As far as I know, `__repr__` is not a public method.
- I would allow choosing in the Preferences whether to activate class docstrings and if yes, choose among numpy, sphinx and google styles.
- In case of numpy-style docstring, I would also allow in the Preferences to choose whether to document the parameters of `__init__` in the class (as it can be seen in the animation above) or within the `__init__` method itself.
   "The `__init__` method may be documented in either the class level docstring, or as a docstring on the `__init__` method itself. Either form is acceptable, but the two should not be mixed. Choose one convention to document the `__init__` method and be consistent with it."

Again, these are suggestions for the future.

**Comment by goanpeca** [comment]
@ccordoba12 should we think about moving this functionality to the PyLS since it has some sort of "suggestions"functionality?

Thoughts @andfoy ?

**Comment by andfoy** [comment]
I agree with @goanpeca as well, this should belong to the PYLs, maybe as a completion snippet

**Comment by ok97465** [comment]
> @ok97465 cool!
> 
> regarding:
> 
> > I think it would be better to add on/off options for PR or to reduce the functionality of the PR.
> 
> You mean like:
> 
> * [ ]  include class attributes
> * [ ]  include under methods
> * [ ]  include dunder methods
>   ?

Yes, exactly. :smile:

**Comment by Richardk2n** [comment]
May I ask, why this was closed? As far as I know snippets, as suggested by @andfoy, where rejected as a solution for function and method docstrings when they were proposed by @goanpeca in  #4936 as they cannot provide the requested functionality. As this is pretty much the same situation, i cannot see, why and how they would work here? Back then @ok97465 wrote the code for the function and method docstrings, which works great, and what he did here looks quite promising already. So is there any reasons to abandone this?

**Comment by andfoy** [comment]
Hi @Richardk2n, this PR was closed since the proposed changes are incompatible with the snippets machinery, since now, Spyder depends completely on the pyls now. Please free to open an issue on the pyls-spyder repository, so we can take a look at it!

**Pull request closed without merging**
