### PR TITLE
PR: Improve design of Kite dialog

### PR DESCRIPTION
**Pull request by juanis2112**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Improve design of dialog according to https://github.com/spyder-ide/ux-improvements/issues/32

Screenshot for MacOS:
Screenshot 2021-02-09 at 7 48 11 PM

Screenshot for Windows:
WhatsApp Image 2021-02-09 at 8 15 36 PM

Screenshot for Linux (Binder)
image

### Issue(s) Resolved

Fixes spyder-ide/ux-improvements#32

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
Juanis2112

### CODE REVIEW

**Comment by juanis2112** [comment]
@dalthviz can you please test this on Windows and post a screenshot here?

**Comment by juanis2112** [comment]
\show binder

**Comment by dalthviz** [comment]
@juanis2112 seems like the font size is quite big (at least for my setup/screen with 1366 x 768)

image

**Comment by isabela-pf** [comment]
Ideally, I'd like a little more space between the image and the text (whether the dialog gets a little wider or the image a little smaller is fine with me), but this has my approval even as the other display and/or OS changes are made.

Thanks for working on this @juanis2112!

**Review by isabela-pf — DISMISSED** [review]

**Comment by juanis2112** [comment]
> Ideally, I'd like a little more space between the image and the text (whether the dialog gets a little wider or the image a little smaller is fine with me), but this has my approval even as the other display and/or OS changes are made.
> 
> Thanks for working on this @juanis2112!

Thanks @isabela-pf I posted a new screenshot with more spacing between the image and the text. Please let me know what you think.

**Comment by juanis2112** [comment]
> @juanis2112 seems like the font size is quite big (at least for my setup/screen with 1366 x 768)
> 
> image

Thanks for testing @dalthviz. Can you test again please? I posted a screenshot in my initial comment but just to make sure can you post how it looks in your computer.
(Sorry for the white edges in the windows screenshot, it's a matter of the computer I was using but it should not happen)

**Comment by dalthviz** [comment]
@juanis2112 this how it looks for me with the latest changes:

image

The only thing I see is that there is a space at the beginning of the link (which I think is caused because there is a space inside the `a` tag in the message instead of outside)

**Comment by isabela-pf** [comment]
> Thanks @isabela-pf I posted a new screenshot with more spacing between the image and the text. Please let me know what you think.

I like that amount of spacing better, thank you! Is that different than the spacing between image and text for the tour dialog?

**Comment by ccordoba12** [comment]
> I like that amount of spacing better, thank you!

Yeah, me too, the dialog looks nicer that way. Thanks @juanis2112 for making that change.

**Comment by juanis2112** [comment]
> > Thanks @isabela-pf I posted a new screenshot with more spacing between the image and the text. Please let me know what you think.
> 
> I like that amount of spacing better, thank you! Is that different than the spacing between image and text for the tour dialog?

The spacing was set automatically in the tour dialog in Mac and for windows and linux it is less technically but since the image is wider, it doesn't look like the space in the kite's dialog is bigger.

**Review by isabela-pf — DISMISSED** [review]

**Review by ccordoba12 — COMMENTED** [review]
This looks pretty good @juanis2112. I tested it locally and like it a lot.

Last comments before merging:

* Please remove the `welcome` method of `KiteInstallation`.
* Please also remove the `welcome` keyword arg of `setup` in the same class.

**Comment by juanis2112** [comment]
I think you mean from the KiteInstallerDialog class.

**Comment by ccordoba12** [comment]
> I think you mean from the KiteInstallerDialog class.

Right, sorry for the confusion. You got the idea anyways  :+1:

**Review by ccordoba12 — APPROVED** [review]
Thanks @juanis2112 and @isabela-pf for your work on this one. It's a great improvement!

**Pull request merged**
