### PR TITLE
PR: FIX: remove cls parameter from generated docstring

### PR DESCRIPTION
**Pull request by trollodel**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

I simply check for the 'cls' parameter in the same way of 'self' is done.

This is necessary for [classmethods](https://docs.python.org/3/library/functions.html#classmethod) where the cls parameter is well-known, as the self parameter.

### Issue(s) Resolved

None.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: trollodel

### CODE REVIEW

**Comment by trollodel** [comment]
I'm going to close this PR because it's outdated, and it doesn't receive a review.
If there is some interest, I may decide to recreate it.

**Comment by ccordoba12** [comment]
Hey @trollodel, sorry for not reviewing your PR on time. This work seems valuable to me, so we'd be glad to merge it if you reopen it again.

**Comment by trollodel** [comment]
This PR was made for 4.x, should I recreate it for another branch? In any case, this needs a rebase and to check if it's still working.

**Comment by ccordoba12** [comment]
Please make your new PR against the 5.x branch so we can include it in our next release.

**Comment by trollodel** [comment]
Superseded by #17607.

**Pull request closed without merging**
