### PR TITLE
PR: Fix opening recent projects

### PR DESCRIPTION
**Pull request by kai3341-effectivesoft**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)
* [ ] Included a screenshot (if affecting the UI)

"Open recent project" function didn't work

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks for your contribution. This will be part of our next release (3.3.3)

**Comment by jnsebgosselin** [comment]
@ccordoba12 This addresses the bug documented in Issue #8450, which was fixed in PR #8452 for the master branch.

It was decided to not fix this for the 3.x branch as discussed in https://github.com/spyder-ide/spyder/pull/8452#issuecomment-448275977.

If we now decide to fix this, I think it would be better to use the same approach as that used in PR #8452.

**Comment by ccordoba12** [comment]
Thanks for your contribution @kai3341-effectivesoft. Unfortunately @jnsebgosselin is right and we need to backport PR #8452 to the `3.x` branch.

I'll do that myself because I plan to release 3.3.3 this weekend.

**Comment by joeyCorea** [comment]
@kai3341-effectivesoft - is this the problem where, if you choose an item from "Recent Projects", it always opens the last project on the list?

**Comment by kai3341-effectivesoft** [comment]
@joeyCorea exactly. The last opens always because it was something wrong with closures

**Comment by joeyCorea** [comment]
Thanks for fixing, @kai and thanks in advance for releasing, @Carlos

**Comment by joeyCorea** [comment]
Can confirm, Recent Projects is back in action!

**Pull request closed without merging**
