### PR TITLE
PR: Migrate the symbol switcher to use the LSP information

### LINKED ISSUE #14221: Move symbol switcher to use LSP symbols
Right now we're extracting symbols to show in the switcher using the Python syntax highlighter, which degrades performance in the Editor for large files.

The plan is to remove that functionality and populate the switcher using the LSP symbols instead.

### PR DESCRIPTION
**Pull request by andfoy**
## Description of Changes
This PR enables the symbol switcher to use the information provided by the `textDocument/symbols` LSP call.

* [ ] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

#### **Symbol switcher in Python**

Peek 17-11-2020 16-27

#### **Symbol switcher in other LSP languages (Elixir)**

Peek 17-11-2020 16-28

### Issue(s) Resolved

Fixes #14221 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @andfoy

### CODE REVIEW

**Review by ccordoba12 — COMMENTED** [review]
This looks pretty good, thanks @andfoy! As part of this PR, please also remove the detection of symbols that we're doing in the Python syntax highlighter (`PythonSH`), present in `spyder/utils/syntaxhighlighters.py`.

**Comment by ccordoba12** [comment]
> As part of this PR, please also remove the detection of symbols that we're doing in the Python syntax highlighter (PythonSH), present in spyder/utils/syntaxhighlighters.py

On a second thought, please ignore this comment. I'll address it myself after we merge this PR.

**Comment by ccordoba12** [comment]
One important thing I forgot to mention before is that (for consistency) the symbol switcher needs to show the same symbols displayed in the Outline. So if the user has deactivated the option `Display variables and attributes` we must not display them in the switcher either. And same applies to `Show  special comments` and `Group code cells`.

**Comment by ccordoba12** [comment]
> And the same applies to Show special comments and Group code cells

I think you forgot the last sentence of my comment above, i.e. please also apply those Outline options to the symbol switcher too.

**Comment by andfoy** [comment]
> I think you forgot the last sentence of my comment above, i.e. please also apply those Outline options to the symbol switcher too.

I'm working on it!

**Comment by ccordoba12** [comment]
Oh, so sorry. I thought you forgot about it.

**Comment by andfoy** [comment]
@ccordoba12 I think this one is ready

**Review by ccordoba12 — APPROVED** [review]
Thanks @andfoy, looks good to me now.

**Pull request merged**
