### PR TITLE
PR: Split all plugins into their own modules

### LINKED ISSUE #4591: Split all plugins to be in their own modules
An issue to keep track of spyder modularization:

- [x]  Help #4548
- [x]  Online Help #4565
- [x]  Variable Explorer #4557 
- [x]  Find in Files #4569
- [x]  Editor #4975
- [x]  Outline explorer #4812
- [x] IPython Console #5206
- [x] Internal Console #5207
- [x] History #4593
- [x]  Projects (project explorer) #5214
- [x]  Explorer #4974
- [x] Working Directory ~(will be merged with explorer?)~ #5219 
- [x] Preferences module #5216
- [x] Fix error in variableexplorer (https://github.com/spyder-ide/spyder/pull/5206#issuecomment-329018836) #5263

External plugins (spyder_breakpoints, spyder_breakpoints, spyder_io_hdf5, spyder_profiler, spyder_pylint)

- [x] Move back to the plugins folder (also change them to follow the same folder structure): #5276
- [x] merge translations #5438

Other things:
- [x] Merge with master and move new files (after 4.0beta2 release) #7725 

Other ideas (to further discuss):
- Add `PLUGIN_CLASS` to  internal plugins, and load them as external plugins are loaded

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #4591.

With this PR all our internal plugins will have the same structure as the ones developed outside Spyder (e.g. `spyder-terminal`, `spyder-notebook`, etc).

We hope this will help outside contributors to better understand how Spyder works and simplify the development of each plugin too.

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
@ccordoba12 If you are moving the files anyway, you are harmonizing them all to LF newlines right?

**Comment by ccordoba12** [comment]
It'll break merging with 3.x, so no, sorry.

**Comment by CAM-Gerlach** [comment]
Oh, I thought it would do that anyway because of the moves so the LF change wouldn't make things worse, but I guess not. Maybe in the final stages of the 4.0 release process when all the non-trivial PRs are in and the 3.x branch is frozen we can do it for everything, and harmonize the copyright headers at the same time (to be in a standard format, with a beginning copyright year and refined text)? If not, it would have to be for Spyder 5 or after ofc.

**Comment by ccordoba12** [comment]
Ok, this is going in!

**Pull request merged**
