### PR TITLE
PR: Enable sorting by values in Variable Explorer

### LINKED ISSUE #5232: Variable explorer raise error when try to sort dict by values
## Description

**What steps will reproduce the problem?**

1. open a dict in variable explorer
2. try to sort dict by values
3. 

**What is the expected output? What do you see instead?**
i want a sorted dict,but change nothing,then raise this error

**Please provide any additional information below**

  File "/home/shanjie/miniconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 250, in fetchMore
    self.rows_loaded + items_to_fetch)
  File "/home/shanjie/miniconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 179, in set_size_and_type
    for index in range(start, stop) ]
  File "/home/shanjie/miniconda3/lib/python3.6/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 179, in <listcomp>
    for index in range(start, stop) ]
IndexError: list index out of range

## Version and main components

* Spyder Version: 3.2.1 
* Python Version: 3.6.1
* Qt Versions: 5.6.2, PyQt5 5.6 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.5.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.2 (OK)
rope >=0.9.4     :  0.9.4-1 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.2.2 (OK)
nbconvert >=4.0  :  5.2.1 (OK)
sympy >=0.7.3    :  1.1.1 (OK)
cython >=0.21    :  0.26 (OK)
qtconsole >=4.2.0:  4.3.0 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.6.4 (OK)

```

### LINKED ISSUE #5294: Variable Explorer: sort by values not working
## Description of your problem

**What steps will reproduce the problem?**

1. create a simple list `[1, 3, 2]`
2. open it in the variable explorer
3. click on header to sort by value: it does not sort the list
(sorting by `Index`, `Size` or `Type` works fine)

**What is the expected output? What do you see instead?**
It should sort the list

## Versions and main components

* Spyder Version: 3.2.3
* Python Version: 3.6

### PR DESCRIPTION
**Pull request by Prikers**
Fixes #5294 
Fixes #5232

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @Prikers thanks for working on this :-)

**Comment by Prikers** [comment]
Maybe I should have done that against 3.x though :disappointed:

**Comment by goanpeca** [comment]
You can fix it if that is the case, no worries, lets check with @ccordoba12 to see wha he thinks?

**Comment by ccordoba12** [comment]
@Prikers, please read our Contributing guide to see how to move your branch to 3.x:

https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md

**Comment by Prikers** [comment]
@ccordoba12 ok, will do!
However I cannot figure out why the test is failing, it seems unrelated to this PR

**Comment by ccordoba12** [comment]
@Prikers, rebasing against the latest `3.x` should fix the error in Circle.

**Comment by ccordoba12** [comment]
@Prikers, what would happen now if, as part of a list or a dict, there's a Numpy array or a Dataframe? I mean, in that case sorting should be disabled, right?

**Comment by Prikers** [comment]
@ccordoba12 nothing happens when trying to sort objects that cannot be ordered. Here are some tests:
```python
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': [1, 2, 3], 'B': [3, 2, 1]})
arr = np.random.random((10, 10))

normal_list = [1, 4, 5, 8, 9, 1, 3, 2]
obj_list = [df, arr, 4, 5, 'A']
serie = df.A

obj_dict = {'df': df, 'arr': arr, 'int': 1, 'str': 'A'}
normal_dict = {'A': 1, 'B': 2, 'C': 4, 'D': 3}
mixt_dict = {'A': '1', 'B': 2, 'C': 4, 'D': 3}
```
sorting
It is the same behaviour as for `size` for example. Is that the expected behavior? Or should we actually make the header not clickable at all? (maybe in another PR then)

**Comment by ccordoba12** [comment]
> Is that the expected behavior?

Yes, it is. I just wanted to know if your changes are not introducing an error in that case.

**Comment by goanpeca** [comment]
@Prikers please check gitter :-)

**Comment by Prikers** [comment]
I am sorry guys, I will need your help once again. I had rebased this branch to 3.x and it worked. But then I pushed two more commits (`fix for #5232` and `testing`) and now it fails. I do not understand why github thinks I am trying to merge with master... (`Prikers  wants to merge 4 commits into spyder-ide:master`). I am obviously missing something...

image

**Comment by jitseniesen** [comment]
Maybe the issue is that (perhaps in addition to `git rebase`), you also need to rebase on the github website. Press the "Edit" button on the top of this page, next to the title of the PR, and then change the base branch and hope that all goes well (if not, it may be easier to start afresh). See https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/

**Comment by Prikers** [comment]
Thanks @jitseniesen! I tried to close the PR and open it again but it does not seem to force the rebuild of continuous integration tests. 
I may indeed need to start a new PR from scratch

**Pull request merged**
