### PR TITLE
PR: Make regex fully functional when using find & replace 

### LINKED ISSUE #3249: Regex is not fully functional when using to find&replace
I want to use the following regex
`\["([a-z_]*)"\]`
and want to replace it with 
`.\1`
to change pars["delta_s"] to pars.delta_s or similar. This does work on some lines but not on all. The regular expression is met, but somehow Spyder fails to actual replace the string. More importantly, when clicking Replace/find the cursor does not (always) jump to the next hit but skips one hit. If then replace/find is clicked again it jumps bakc to the one it skipped before

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #3249

### CODE REVIEW

**Comment by ccordoba12** [comment]
@andfoy, there are a couple of style failures in CircleCI. Please fix them :-)

**Comment by andfoy** [comment]
@ccordoba12 It was a classic PEP8 error :)

**Comment by goanpeca** [comment]
Any chance we take this opportunity to make a test that checks this problem?

**Comment by ccordoba12** [comment]
@goanpeca, it's not easy to add a test for this because it lies in the interaction between the find/replace widget and the Editor. However, I manually tested that things are working as expected now :-)

**Pull request merged**
