### PR TITLE
PR: Generalice previous is_instance test to search others avoided patterns

### LINKED ISSUE #4161: Create a test for finding print statements in the code
Very often PRs leave a print statement behind, as part of the initial testing. A test that looks for print statements and fails if it does find it would be very helpful.

@rlaverde we could generalize the regex check you did, to find generic code snippets. What do you think?

### PR DESCRIPTION
**Pull request by rlaverde**
Fixes #4161 

-------------
I added the test but there's a lot of prints in the code, should I change them?

I put this in the 4.0 milestone because the `is_instance`test was merged in master

### CODE REVIEW

**Comment by ccordoba12** [comment]
You need to skip test files from your search

**Comment by ccordoba12** [comment]
Also, could we backport these changes to the 3.1.x branch?

**Comment by ccordoba12** [comment]
Could you rebase this PR against 3.1.x instead? I think it's very important to have this test working on our bugfix branch instead.

**Comment by rlaverde** [comment]
> Could you rebase this PR against 3.1.x instead? I think it's very important to have this test working on our bugfix branch instead.

Yes, I'll do it

Also this is missing something, the `max_allowed` variable isnt the best way to skip that wanted prints, instead I'm going to add a comment `# spyder: test_skip` to lines that should be skipped

**Comment by ccordoba12** [comment]
Ok, good idea!

**Comment by rlaverde** [comment]
@ccordoba12 This is ready, I open other PR backporting these changes to 3.1.x

@goanpeca I didn't tokenize for detecting prints into string, I improve the regex instead.

**Comment by ccordoba12** [comment]
I'm closing this one in favor of #4226 because that one is created against our lowest branch.

Once #4226 is merged, I'll merge it against `3.x` and `master` on my side and push changes directly to Github (that's what I'm doing for all PRs so far).

**Pull request closed without merging**
