### PR TITLE
Replace obsolete setTextColor method by setForeground in qtreewidgetitem

### LINKED ISSUE #2305: Profiling error
## Description

* *What steps will reproduce the problem?*
   1. Run a script with a profiler

* *What is the expected output? What do you see instead?*

I see this in the internal console:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 253, in <lambda>
    self.finished(ec, es))
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 318, in finished
    self.show_data(justanalyzed=True)
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 339, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 427, in load_data
    map(lambda x: x.calc_callees().stats, stats_indi)
  File "/usr/lib/python2.7/site-packages/spyderplugins/widgets/profilergui.py", line 427, in <lambda>
    map(lambda x: x.calc_callees().stats, stats_indi)
AttributeError: 'NoneType' object has no attribute 'stats'
```

* *Please provide any additional information below*

## Version and main components

* Spyder Version:  3.0.0dev 
* Python Version:  2.7.9
* Qt Version    :  4.8.6, PyQt4 (API v2) 4.11.3 on Linux

## Optional dependencies

pyflakes >=0.5.0:  0.8.1 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=3.0   :  3.0.0 (OK)
zmq >=13.0.0    :  14.5.0 (OK)
pandas >=0.13.1 :  0.16.0 (OK)
sphinx >=0.6.6  :  1.2.3 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.10.2 (OK)
jedi >=0.8.1    :  0.8.1 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  1.4.3 (OK)

### PR DESCRIPTION
**Pull request by dhoegh**
Fixes #2305

---

@Nodd could you check if this fixes your problem?

### CODE REVIEW

**Comment by ccordoba12** [comment]
@Nodd, could you test @dhoegh fix please?

**Comment by goanpeca** [comment]
@Nodd ?

**Comment by goanpeca** [comment]
@dhoegh can we have a more explanatory title for this PR?

**Comment by Nodd** [comment]
Now I have 
```
Traceback (most recent call last):
  File "/home/joseph/prog/spyder.git/spyderplugins/widgets/profilergui.py", line 253, in <lambda>
    self.finished(ec, es))
  File "/home/joseph/prog/spyder.git/spyderplugins/widgets/profilergui.py", line 318, in finished
    self.show_data(justanalyzed=True)
  File "/home/joseph/prog/spyder.git/spyderplugins/widgets/profilergui.py", line 340, in show_data
    self.datatree.show_tree()
  File "/home/joseph/prog/spyder.git/spyderplugins/widgets/profilergui.py", line 467, in show_tree
    self.populate_tree(self, self.find_callees(rootkey))
  File "/home/joseph/prog/spyder.git/spyderplugins/widgets/profilergui.py", line 540, in populate_tree
    child_item.setTextColor(2, QColor(cum_time_dif[1]))
AttributeError: 'TreeWidgetItem' object has no attribute 'setTextColor'
```
And the name and total time of the first function appear in the table, so it's already better !

**Comment by dhoegh** [comment]
@Nodd thank you for testing, I will debug further in the weekend when I have some time off from the master thesis.

**Comment by dhoegh** [comment]
@nood I am not able to reproduce your result on ubuntu 14.10 `Python 2.7.8 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.2 on Linux` do you have any idea what could be wrong?

**Comment by dhoegh** [comment]
Every thing seems to work fine on my side with this pr's branch, byt on master I am able to reproduce your error reported in #2305 
```
>>> Traceback (most recent call last):
  File "/media/hoegh/8CA055F2A055E2EE/Users/Hoegh/Documents/spyder/spyderplugins/widgets/profilergui.py", line 253, in <lambda>
    self.finished(ec, es))
  File "/media/hoegh/8CA055F2A055E2EE/Users/Hoegh/Documents/spyder/spyderplugins/widgets/profilergui.py", line 318, in finished
    self.show_data(justanalyzed=True)
  File "/media/hoegh/8CA055F2A055E2EE/Users/Hoegh/Documents/spyder/spyderplugins/widgets/profilergui.py", line 339, in show_data
    self.datatree.load_data(self.DATAPATH)
  File "/media/hoegh/8CA055F2A055E2EE/Users/Hoegh/Documents/spyder/spyderplugins/widgets/profilergui.py", line 427, in load_data
    map(lambda x: x.calc_callees().stats, stats_indi)
  File "/media/hoegh/8CA055F2A055E2EE/Users/Hoegh/Documents/spyder/spyderplugins/widgets/profilergui.py", line 427, in <lambda>
    map(lambda x: x.calc_callees().stats, stats_indi)
AttributeError: 'NoneType' object has no attribute 'stats'
```

**Comment by dhoegh** [comment]
@goanpeca could you see if you can find any problems with the profiler on this branch, because I can't reproduce what @Nodd sees on either linux/windows with 2.7 or 3.4.

**Comment by goanpeca** [comment]
@dhoegh sorry for the delay, I tested your branch on win7 py2.7 and py3.4 and it seems to be working fine :+1:

**Comment by Nodd** [comment]
Aha, `setTextColor` is obsolete: http://doc.qt.io/qt-4.8/qtreewidgetitem-obsolete.html
Since I use Qt5, it was removed but it is still present in Qt4.8 to keep compatibility.

**Comment by dhoegh** [comment]
@Nodd I have pushed a new commit where `setTextColor` is changed to `setForeground`. Can you verify this solves you problem with the profiler completely?

**Comment by Nodd** [comment]
It works, thanks !

**Comment by goanpeca** [comment]
Merging then?

**Comment by dhoegh** [comment]
Great, then this is good to merge:)

**Comment by goanpeca** [comment]
Thanks for working on this @dhoegh.

---

@ccordoba12, this should be ready for merging

**Comment by ccordoba12** [comment]
@Nodd, thanks a lot for the review and for testing ;-)

**Pull request merged**
