### PR TITLE
PR: Add german auto translation

### PR DESCRIPTION
**Pull request by goanpeca**
### Issue(s) Resolved

Related to https://github.com/spyder-ide/spyder/issues/10672

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @be-we, I added automatic (google) translation so you could start reviewing the work when you have some time :-)

Thanks!

**Comment by alexschw** [comment]
Hey @goanpeca, I reviewed the translations you made. Is it possible for me update the files in this PR, or do I need to open a new one?

**Comment by ccordoba12** [comment]
Hey @alexschw, thanks a lot for your interest in helping us with this!

You can continue with @goanpeca's work in your own fork of Spyder by entering these commands in a terminal:

- `git remote add goanpeca https://github.com/goanpeca/spyder.git`
- `git fetch goanpeca`
- `git checkout trans/de`

After that you can commit your fixes and improvements, then you need to do

- `git push origin trans/de`

and create a new PR out of that branch. As soon as you do that, we'll close this one.

As a final note, please read https://github.com/spyder-ide/spyder/issues/10672#issuecomment-557757911 to know how much time you have to submit your work.

**Comment by ccordoba12** [comment]
Closing in favor of #10859.

**Pull request closed without merging**
