### PR TITLE
PR: Reorganize preferences entry for the Editor

### PR DESCRIPTION
**Pull request by ccordoba12**
**Before:**

Selección_025

Selección_026

----

**After:**

Selección_027

Selección_028

Selección_029

Selección_030

**Note**: All `Advanced Settings` are displayed in the last screenshot.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Merging this to keep things moving. @CAM-Gerlach, please open a new PR if you want to change the strings I added here (I think the only ones are the `Docstring type` and `Annotations` labels).

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Possibly some small tweaks, but nothing egregious. I've been planning to do a UI strings cleanup pass prior to the Spyder 4 release (and translations) anyway, so if needed I'll catch it then. Thanks!

**Comment by ccordoba12** [comment]
Given that we're going to have a lot of new strings for Spyder 4, my plan is to update them before each of the following betas to give translators time to catch up.

So if you could start to review strings for the most important things we've added so far (new console types and new preferences, I don't know what else), that'd be great.

**Comment by CAM-Gerlach** [comment]
Okay, sure. Do you have an approximate deadline to give the translators enough time before Beta 2, so I can schedule my time accordingly (given I have a large backlog of work at the moment)? Thanks!

**Comment by ccordoba12** [comment]
We'll try to have everything ready (i.e. before translations) by the end of this month.

**Pull request merged**
