### PR TITLE
PR: Update core dependencies for 6.0.0.alpha2

### LINKED ISSUE #21257: Spyder 6.0 alpha2 release
This is an issue for the new Spyder 6 alpha2 release.

New dependencies:

- [x] `fzf` to provide fuzzy search functionality for the project files in the Switcher. This can only be added to our Conda and Binder requirement files.
- [x] `fcitx-qt5` to add input support for Chinese, Japanese and Korean on Linux (see issue #4120). Again, this package is only available in Conda-forge. 
- [x]  `spyder-kernels` to 3.0b2, pending release.

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* `spyder-kernels` supported version was updated to be `>=3.0.0b2,<3.0.0b3`.
* Update `spyder-kernels` subrepo and point it to `spyder-ide/spyder` `master` branch (not sure why but it was pointing to a `remove_locals_inspection` branch?)

### Issue(s) Resolved

Fixes #21257

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by dalthviz** [comment]
Note: Last commit was meant to update the subrepos cache so the installers build could be done. However, even with the change, I had to rerun the installers workflow manually since there is no dependency between it and the one that caches the subrepos. Rechecking #21212, maybe I will need to revert that last commit and instead what should be done is to run the cache subrepo workflow manually? Is there a procedure to update the cached subrepos that I'm missing to follow? What do you think @mrclary ?

**Comment by mrclary** [comment]
> Note: Last commit was meant to update the subrepos cache so the installers build could be done. However, even with the change, I had to rerun the installers workflow manually since there is no dependency between it and the one that caches the subrepos. Rechecking #21212, maybe I will need to revert that last commit and instead what should be done is to run the cache subrepo workflow manually? Is there a procedure to update the cached subrepos that I'm missing to follow? What do you think @mrclary ?

@dalthviz, I'll have to think about this. I didn't consider the situation where both subrepo cache and installer workflows were triggered by the same event, in which case the installer workflow needs to follow the cache workflow. Perhaps I made a mistake in creating the separate workflow.

I think for now you did the correct procedure: both workflows triggered by the pull-request, but the installer workflow fails due to cache miss; after cache workflow completes, rerun failed installer workflow.

**Comment by ccordoba12** [comment]
@mrclary, so can we merge this one so that @dalthviz can proceed with the release?

**Comment by ccordoba12** [comment]
Ok, thanks @mrclary! Then @dalthviz, please remove or rename your last commit so I can merge this PR.

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz!

**Pull request merged**
