### PR TITLE
PR: Fix Variable Explorer pandas KeyError in macOS App

### LINKED ISSUE #14542: Opening Dataframe in Variable Explorer not working with packaged 4.2.1 dmg version of Spyder
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [x] Tried basic troubleshooting (if a bug/error)
    * [x] Restarted console 

- [ ] Spyder

    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Get an error when attempting to open a pandas Dataframe from the Variable Explorer:
image

### What steps reproduce the problem?

1. Run a script output a pandas Dataframe.
2. Open Pandas DataFrame from the variable explorer (double-clicking or right-click)
3. 

### What is the expected output? What do you see instead?
Open's new window showing the DataFrame as in previous version of Spyder

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.2.1
* Python version: 3.9.1 64-bit
* Qt version: 5.12.1
* PyQt version: 5.12.3
* Operating System name/version: Darwin 20.2.0 (Mac OS Big Sur) 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

* include `pandas` outside zip location
* additional build cleanup

### Issue(s) Resolved

Fixes #14542 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@mrclary

### CODE REVIEW

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary, looks good to me.

**Comment by vancromy** [comment]
@mrclary Thanks for the very quick fix! Was just having a quick look at the setup.py and noticed you're declaring global variables including package names and what should or should not be included in the build. In terms of compatibility with future versions of Spyder, does this mean these lists will always have to be manually updated for each release as and when dependencies change? I'm wondering if there is a more dynamic way of doing this or linking to perhaps a central place where @ccordoba12 declares dependencies? 

I'm an absolute newbie when it comes to proper open source development so disregard this comment if it isn't so relevant in this case :)

**Comment by mrclary** [comment]
@vancromy, you are correct that presently these package lists are manually curated. I think that a dynamic list would be a preferred paradigm, but at present I don't know how this can be accomplished.

`py2app` analyzes the source code and compiles an import tree in order to determine what packages/modules need to be included in the build. But it has three parameters for adjusting included packages: `includes`, `excludes`, `packages`. `includes` is used to ensure that a package is included and is used for packages such as `numpy`, `matplotlib`, which are not used by Spyder directly and therefore not detected by `py2app`. `excludes` ensures that a package is _not_ included.

`packages` controls _where_ a package is installed in the app. Similar to a standard Python installation, `py2app` puts packages in the app into two possible folders: .../python3.9 or .../python39.zip. The default location is in the zip folder; this only contains compiled code (.pyc files) and no source code, so it makes for a smaller footprint. `packages` ensures that specified packages are installed in the .../python3.9 folder and not the .../python39.zip folder. This mechanism exists because some packages don't play nice when placed in the zip folder. The issue encountered for a particular package is listed in the docstring of `setup.make_app_bundle`. These packages have to be placed in .../python3.9 _not_ .../python39.zip, and this list can only be curated manually.

**Comment by ccordoba12** [comment]
> linking to perhaps a central place where @ccordoba12 declares dependencies?

We already have that in our `setup.py`:

https://github.com/spyder-ide/spyder/blob/f2f4d818c34a2bad565f53c94d5016436724cdb1/setup.py#L202-L241

But, as @mrclary explained above, the process of building the installer is different from the one to create a regular Python package.

**Comment by vancromy** [comment]
@mrclary Thanks for the really nice explanation! :) Makes absolute sense. I guess I just wanted to raise it so that the spyder-devs are aware of a need to double-check the lists for each release. 

Keep up the great work!

**Pull request merged**
