### PR TITLE
PR: Enable line stripping by default

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes

I missed this before the merging of https://github.com/spyder-ide/spyder/pull/8734

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
I'm not sure if this is the right thing to do because it could be confusing to newbies.

@bcolsen, @goanpeca, what do you think about this?

**Comment by bcolsen** [comment]
> I'm not sure if this is the right thing to do because it could be confusing to newbies.

I agree that it might be confusing having white space removed without an explicit command. Even the the removal of the automatic indentation on blank line makes it more difficult to to insert new code into those spaces later on.

In general I would categorize this as a code style feature, and I personally I don't think that code style features should be on by default. Programming is already too picky for the average person so we shouldn't make it even more picky.

**Comment by goanpeca** [comment]
Yes, I agree that this might be too unexpected for newbies :-|

**Comment by ccordoba12** [comment]
Thanks for the input guys. Sorry @impact27 but this could really be a lot for newbies.

**Pull request closed without merging**
