### PR TITLE
Improve plot pane

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes
Add saving figures in different formats and add interactive figures (only during first draw)

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #
plot
12211

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by impact27** [comment]
One problem with this approach is that the plots take more time to render as there is 4x more plots to render (svg + pdf + jpeg + png). What do you think? Should we limit ourselves to 1 that the user can coose, or is the slower plotting time acceptable?

**Comment by jnsebgosselin** [comment]
> 
> 
> One problem with this approach is that the plots take more time to render as there is 4x more plots to render (svg + pdf + jpeg + png). What do you think? Should we limit ourselves to 1 that the user can choose, or is the slower plotting time acceptable?

That and this may also increase the memory footprint of the plugin substantially.

Also, does this PR completely remove the ability to render svg images directly in the plot plugin? If I understand correctly, if there is no png in the data received by the console then nothing is plotted? If that is the case, I'm not sure I like that.

**Comment by bcolsen** [comment]
We could just use the svg file by default and convert to other formats on save from the svg. 

On the flip side we could use (potentially) even more ram and place QtWebEngine element in the tabs and use the webagg (notebook) backend. (This could also give us all the other web based plotting libraries)

https://matplotlib.org/3.1.3/gallery/user_interfaces/embedding_webagg_sgskip.html

**Comment by impact27** [comment]
> Also, does this PR completely remove the ability to render svg images directly in the plot plugin? If I understand correctly, if there is no png in the data received by the console then nothing is plotted? If that is the case, I'm not sure I like that.

The idea is that they would _always_ be png in the data. The kernel would send png + something else. The png can be used as a thumbnail and the something else can be saved to file. This means that we don't need to render pdf or svg in the plot pane. svg are rasterised anyway now. This adds 100ms of processing time to create both instead of just one and increases the memory footprint a bit (~factor two if we select just one other extension)

**Comment by jnsebgosselin** [comment]
> We could just use the svg file by default and convert to other formats on save from the svg.

The problem is that the `QSvgRenderer ` doesn't support all svg features, so we would have to use another svg rendered to do this properly. See See https://github.com/spyder-ide/spyder/issues/9987.

Personnally, I think we should only send the format that is specified by the user in the `inline backed format` preference and limit the saving format option that the ones that are supported by the renderer we are using.

**Comment by jnsebgosselin** [comment]
> 
> 
> > Also, does this PR completely remove the ability to render svg images directly in the plot plugin? If I understand correctly, if there is no png in the data received by the console then nothing is plotted? If that is the case, I'm not sure I like that.
> 
> The idea is that they would _always_ be png in the data. The kernel would send png + something else. The png can be used as a thumbnail and the something else can be saved to file. This means that we don't need to render pdf or svg in the plot pane. svg are rasterised anyway now. This adds 100ms of processing time to create both instead of just one and increases the memory footprint a bit (~factor two if we select just one other extension)

Even when plots are not produced with matplotlib?

What if we want to load images in the plot plugin directly from a source other than the kernel?

**Comment by impact27** [comment]
> Personnally, I think we should only send the format that is specified by the user in the `inline backed format` preference and limit the saving format option that the ones that are supported by the renderer we are using.

What about sending `png` + the `inline backed format` so there is no rendering required and we can accept any format?

**Comment by impact27** [comment]
> Even when plots are not produced with matplotlib?

You are right, I think the svg processing should stay then and be used if no png is avilable.

> What if we want to load images in the plot plugin directly from a source other than the kernel?
You would need to load a version of the image we can render + any version you want to save

**Comment by jnsebgosselin** [comment]
> 
> 
> > Personnally, I think we should only send the format that is specified by the user in the `inline backed format` preference and limit the saving format option that the ones that are supported by the renderer we are using.
> 
> What about sending `png` + the `inline backed format` so there is no rendering required and we can accept any format?

Rendering from a svg results in a better onscreen image quality than from a png because of the scaling.

I agree that svg rendering is not ideal currently due to what was discussed in #9987, but I hope that one day either `QSvgRenderer ` will be improved or that we will use a better svg renderer in Spyder, which should solve those issues.

**Comment by ccordoba12** [comment]
> I agree that svg rendering is not ideal currently due to what was discussed in #9987, but I hope that one day either QSvgRenderer will be improved or that we will use a better svg renderer in Spyder, which should solve those issues.

We can use a QWebView to render svg's, as I suggested above. That should be really simple to do.

**Comment by jnsebgosselin** [comment]
> 
> 
> > I agree that svg rendering is not ideal currently due to what was discussed in #9987, but I hope that one day either QSvgRenderer will be improved or that we will use a better svg renderer in Spyder, which should solve those issues.
> 
> We can use a QWebView to render svg's, as I suggested above. That should be really simple to do.

This is worth a try.

In my opinion, I think the problem here is that this PR is addressing two topics that should be adressed/discussed separately:

1 - Display plot in the plots plugin even when the backend isn't set to inline.
2 - Improvement/refactoring of the rendering and saving format in the plot plugin.

**Comment by jnsebgosselin** [comment]
> 
> 
> > > I agree that svg rendering is not ideal currently due to what was discussed in #9987, but I hope that one day either QSvgRenderer will be improved or that we will use a better svg renderer in Spyder, which should solve those issues.
> > 
> > 
> > We can use a QWebView to render svg's, as I suggested above. That should be really simple to do.
> 
> This is worth a try.
> 
> In my opinion, I think the problem here is that this PR is addressing two topics that should be adressed/discussed separately:
> 
> 1 - Display plots produced with matplotlib in the plots plugin even when the backend isn't set to inline.
> 2 - Improvement/refactoring of the rendering and saving format in the plot plugin.

**Comment by bcolsen** [comment]
> We can use a QWebView to render svg's, as I suggested above. That should be really simple to do.

Would this allow webagg and all the other web visualizations or would we need  QWebEngine for that?

I looks like QWebView can save rendered bitmaps.

**Comment by ccordoba12** [comment]
> Would this allow webagg and all the other web visualizations or would we need QWebEngine for that?

No, that requires a different plugin. Plots will be in charge of handling plots and not anything else.

**Comment by jnsebgosselin** [comment]
> 
> 
> > We can use a QWebView to render svg's, as I suggested above. That should be really simple to do.
> 
> Would this allow webagg and all the other web visualizations or would we need QWebEngine for that?
> 
> I looks like QWebView can save rendered bitmaps.

Are you suggesting to use `WebAgg` to embed a fully interactive matplotlib plot? If that is the case, I'm not sure I agree with this idea. Embedding interactive matplotlib canvas into Spyder GUI looks nice on paper, but because of scaling, it's going to be horrible to use. I much much prefer to have my interactive matplotlib plots to pop up in independent, floating free windows that respect faithfully the size and scaling of the plots I have created.

**Comment by goanpeca** [comment]
>but because of scaling, it's going to be horrible to use. I

@jnsebgosselin could you elaborate on this a bit?

**Comment by jnsebgosselin** [comment]
> 
> 
> > but because of scaling, it's going to be horrible to use. I
> 
> @jnsebgosselin could you elaborate on this a bit?

You can't scale an interactive matplotlib figure like you do for a svg or a png. Let's say you produce a nice 8 x 4i nches matplotlib figure with a complex layout. This same interactive figure is going to look horrible in Spyder after we resized it so that it fits into, lets say, a 500 x 400 pixels panel. The fontsize, line thickness, marker size, margins, etc. won't scale when we resize the figure. The layout of the whole figure is going to look very bad.

We could make it work, maybe, by rigging some gui events with methods like `tight_layout`, etc, but still, I think it would only work well for very simple figure layouts.

To illustrate my point, in the image below we can see a figure I've produced with matplotlib. You can see how it looks in the plots plugin and how it looks in a Qt5 matplotlib figure manager in its original size. I have then resized (manually) the manager so that the size of the figure fits that of the plots plugin. You can see how it looks... very bad. Embedding an interactive matplotlib figure in a GUI works well if the layout of the figure is specifically engineered to fit in that specific GUI, otherwise, chances are it's going to look bad.

Does it make any sense? In my opinion, embedding interactive matplotlib figures in a Spyder panel is not as simple as it may look and not as cool as we may think...

image

**Comment by goanpeca** [comment]
Understood! Thanks for the thorough explanation.

**Comment by bcolsen** [comment]
@goanpeca @jnsebgosselin Sorry for the late reply and off topic here but scaling could be solved if we use page rendering zoom the webview.

The issue @jnsebgosselin describes is true if we resize the figure, which would result in a mess as he shows. Instead however we can leave the figure size unchanged and create a webview large enough for the figure and then use the webview zoom feature to scale the whole page. The matplotlib webagg backed is entirely pixel based so the plots only scale as well as a png image but that's currently what we are using.

Gif of changing the figure size and then zooming a plot in a web browser instead:

PLot_zoom

**Comment by jnsebgosselin** [comment]
It sounds pretty interesting. As soone as I have time, I think I'll give it a try unless someone beat me to it :P.

**Comment by impact27** [comment]
I will close this PR as the code is specific to matplotlib.

**Comment by ccordoba12** [comment]
> I will close this PR as the code is specific to matplotlib.

I don't understand your reasoning @impact27. The Plots pane only works with Matplotlib at the moment (and I think that won't change in the future).

**Comment by impact27** [comment]
> > I will close this PR as the code is specific to matplotlib.
> 
> I don't understand your reasoning @impact27. The Plots pane only works with Matplotlib at the moment (and I think that won't change in the future).

Not really, it works with any png or svg displayed in the console. This PR would break this behaviour.

**Pull request closed without merging**
