### PR TITLE
PR: Add functionality run to and from current line to editor

### PR DESCRIPTION
**Pull request by rhkarls**
## Description of Changes
This PR adds functionality to run all lines either above or below the current cursor position.
If there is interest from the Spyder team to have this functionality I'd be happy to continue to work on this PR (see suggested todo list below).

This feature is available in other IDEs, for example VS Code with interactive python and R-Studio.
Currently the implementation in this WIP PR is identical to VS Code and R-Studio as it sends all the lines above or below the cursor verbose to the editor. An alternative is also to silently execute the lines not to fill the console.

Todo list
* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes
* [x] Included a screenshot or animation 
* [ ] Icons for the menu items (perhaps something along the lines of mdi.ArrowCollapseDown  with a play icons)
* [ ] Keyboard short cuts for the menu items?
   * Currently Shift+F9 for "run to line" and CTRL+F9 for "run from line". Set for testing purposes 
* [ ] Naming of functionality in UI (e.g. "Run to line/Run from beginning to line/Run lines above?)

spyder_run_lines_from_cursor

### Issue(s) Resolved

Adds feature suggested in #16431

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @rhkarls

### CODE REVIEW

**Comment by dalthviz** [comment]
Hi @rhkarls thanks for your interest in adding new functionalities to Spyder! From my side seems like a good idea :+1:
 however what do you think @spyder-ide/core-developers ?

**Comment by mrclary** [comment]
I think it's a good idea.

**Comment by rhkarls** [comment]
Thanks a lot - I will work on getting this ready when I have time in between traveling. Would be great to get some feedback on keyboard shortcuts and naming in the UI at a later stage

**Comment by rhkarls** [comment]
The mac tests seem to fail due to some conda env issues and using python 2.7 (?). Otherwise this is ready for the most part I think - see todo list on top, and would be nice with a review.

**Comment by mrclary** [comment]
@ccordoba12, could the failing mac tests be due to some changes we made regarding mamba and conda-forge?

**Comment by dalthviz** [comment]
@rhkarls could you do a rebase on top of the latest `5.x` branch to see if that helps with the failing tests ?

**Comment by rhkarls** [comment]
Cheers @dalthviz ! Seems that the fast mac test froze though. Due to my mediocre git skills I managed to do a merge, but looks clean. To do a proper rebase as you suggested, what git commands should be issued? What I did now was 

    git checkout add-feature-run_to_from_line
    git pull upstream 5.x
    git push origin add-feature-run_to_from_line

**Review by ccordoba12 — APPROVED** [review]
This is a great addition! Thanks @rhkarls for your help to implement this and your patience to get it merged.

**Pull request merged**
