### PR TITLE
PR: Fix showing signatures in the IPython console after an open paren

### PR DESCRIPTION
**Pull request by ccordoba12**
This is a regression of PR #9301.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Can you help me with that (tomorrow, I mean)? I don't have time to devise one right now, but I consider it very important to avoid this in the future.

You can push it to this branch instead of opening a new PR.

**Comment by goanpeca** [comment]
Ok will do

**Comment by goanpeca** [comment]
Added a test to check the regression @ccordoba12

**Comment by goanpeca** [comment]
I think this test needs the help plugin since that is where the actual call to get the signature is. No?

**Comment by ccordoba12** [comment]
Nop, calltips are handled by the console alone. And we already have a test for displaying help from the IPython console. It's called `test_get_help_ipython_console` and it's present in `test_mainwindow.py`.

**Comment by ccordoba12** [comment]
I think this ready. Thanks a lot @goanpeca for your help with this one!!

**Comment by goanpeca** [comment]
Thanks, I now understand why I thought the help plugin was involved. `help.py` name tripped me off 😆

**Comment by ccordoba12** [comment]
Yeah, that's not a good name for things, but it's the one we decided to use.

**Pull request merged**
