### PR TITLE
PR: Change error report dialog to enter issue description before submitting it

### LINKED ISSUE #5247: Improve interface to report errors
It seems browsers only accept a limited number of characters in the status bar, and so there are several issues reported by our users that end up being incomplete.

So, instead of that, we should use the Github API to create new issues:

https://developer.github.com/v3/issues/#create-an-issue

@rlaverde, please take care of this one.

### PR DESCRIPTION
**Pull request by rlaverde**
Fixes #5247.

----

It looks like this, the ok button is activated when each text has more than 10 words, this has to be improved because it isn't obvious how the ok button will be activated

Also a button to dismiss and don't show the dialog again should be added 

spectacle p15381

### CODE REVIEW

**Comment by goanpeca** [comment]
@rlaverde how about using a `placeholderText` ?

**Comment by jitseniesen** [comment]
Is the second field useful? The answer to the question "What do you see instead" is always: an unhandled exception error box.

**Comment by rlaverde** [comment]
> how about using a placeholderText ?

Instead of labels or for indicate that the text should be minimum 10 words length?

>Is the second field useful? The answer to the question "What do you see instead" is always: an unhandled exception error box.

Yes, should I remove the second filed? or only the second question?

**Comment by goanpeca** [comment]
>how about using a placeholderText ?
>Instead of labels or for indicate that the text should be minimum 10 words length?

I don't think we should say it hs to be a minimum length, but we can say. `This field needs to include a description before you can send the report`

**Comment by goanpeca** [comment]
But I insist again this (issue reporting automatically) is a terrible idea and does not scale well.

**Comment by rlaverde** [comment]
> I don't think we should say it hs to be a minimum length, but we can say. This field needs to include a description before you can send the report

Yes I like that, and maybe a label that indicate that the text should be longer

>But I insist again this (issue reporting automatically) is a terrible idea and does not scale well.

I agree with you, but it's better to be flooded with issues with a description, that with empty issues 🙈 

Maybe the solution, is to improve spyder logging system #5326 and use a different service for automate issues reports

**Comment by goanpeca** [comment]
>Maybe the solution, is to improve spyder logging system #5326 and use a different service for automate issues reports

Yes indeed that is the right solution

**Comment by ccordoba12** [comment]
> should I remove the second filed? or only the second question?

I agree with @jitseniesen: we should remove that field.

----

@rlaverde, please add

    1.
    2.
    3.

to the first field. And a placeholder text suggested by @goanpeca (or maybe a label over the field would be better).

**Comment by ccordoba12** [comment]
My suggestions to finish this one:

1. Remove the two panels and only leave one.
2. Use an instance of CodeEditor with Markdown and the same color scheme of the Editor to enter text.
3. Add a button to dismiss the dialog during an entire session.

**Comment by rlaverde** [comment]
This is how it looks like:

spectacle e18905

spectacle q18925

**Comment by goanpeca** [comment]
@rlaverde I suggest the following:

1. Get rid of the additional text editor with the 1 2 3
2. Change the Submit to github to `Create New Issue`
3. Create a copy to clipboard button so users can copy `the template` + `the system details` + `the error content`
4. The link that opens the create new github should erase the body message and add a generic title "Spyder Error Report". Its important to erase the body otherwise the template would allow them to report an issue with some prefilled empty content.!
5. If we got rid of the `Hide details` button the UI would be less crowded

`Create New Issue | Ok | Dismiss`

**Comment by Prikers** [comment]
What is the difference between `OK` and `Dismiss` in this dialog widget?

**Comment by ccordoba12** [comment]
Great point @Prikers! @rlaverde, I think we should remove `Ok` and only leave `Dismiss`.

`Dismiss` means *don't show this dialog during this session*. @Prikers, is that something that can be grasped from `Dismiss`?

**Comment by Prikers** [comment]
@ccordoba12 yes that what I'd expect from a `Dismiss` button. I was indeed thinking that `Ok` could be removed as it does not bring a lot of value compared to `Dismiss`.

**Comment by rlaverde** [comment]
Now it looks like this:

spectacle a15172

**Comment by goanpeca** [comment]
@Prikers suggested we used Dismiss instead of Ok, (they are probably doing the same thing now?)

Thoughts @ccordoba12, @rlaverde ?

**Comment by rlaverde** [comment]
I thought we were adding something to copy the content, a context menu, a left click on the message, a Copy to clipboard button ?

I change the message of the dialog, adding another button will be an extra click

- @Prikers suggested we used Dismiss instead of Ok, (they are probably doing the same thing now?)

I removed the `Ok` button, leaving the `Dimiss` button

**Comment by goanpeca** [comment]
- @rlaverde all the text in Note should be italic, not just the Note.
- If the user accidentally replaces the clipboard with something, it should be possible to copy with one mouse click, so if there is no button, now the user has to select a text, and press a key or make 2 mouse clicks, which in case of user errors (very common) is still better to have an easy way of copying. The copy button does not need to be in line with the other buttons, it can be located within the editor frame.

**Comment by rlaverde** [comment]
@goanpeca Doing what you suggest is not possible in a normal `QDialog`, I'll have to rewrite it to allow a button with a different position

**Comment by goanpeca** [comment]
@rlaverde the embeded editor cannot be a widget that contains a button annd the editor?

**Comment by rlaverde** [comment]
>the embeded editor cannot be a widget that contains a button and the editor?

That isn't an embebed editor, is the Show details functionality of the `QDialog`

**Comment by goanpeca** [comment]
Hmm ok

**Comment by ccordoba12** [comment]
@CAM-Gerlach, this is how the dialog looks now

seleccion_001

and how the report looks on Github

seleccion_002

After pasting the contents, you'll get this:

seleccion_003

----

Of course, this is to have an initial version on top of which you can add the rest of your improvements. What do you think?

**Comment by ccordoba12** [comment]
New screenshot with the initial label text made more emphatic:

seleccion_001

**Comment by ccordoba12** [comment]
Last version, with a monospace font and a better color scheme:

seleccion_001

**Comment by ccordoba12** [comment]
I think this is ready! In my last commits I made the header on the description field read-only, so users are unable to remove it.

I also remove the listing (`1. 2. 3.`) because it doesn't work with a read-only header.

**Comment by jitseniesen** [comment]
The button should read "Dismiss" :smile:

**Comment by ccordoba12** [comment]
> The button should read "Dismiss"

Fixed. Thanks for noticing it!

**Comment by ccordoba12** [comment]
This turned out to be really big, but I think it's finally ready!

**Pull request merged**
