### PR TITLE
PR: Add German translation

### PR DESCRIPTION
**Pull request by be-we**
It's finally done!

The German translation for
- Spyder,
- Breakpoints Plugin,
- Profiler Plugin,
- Pylint Plugin
is complete and added to base.py.

I've found some typos in the English source strings. Search for 'TYPO in source' within my translation comments.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for this!! Since you did this PR against our `master` branch, this is going to be part of Spyder 4, to be released early next year.

I hope you're ok with that.

**Comment by goanpeca** [comment]
We could use the @rlaverde rebase onto thinguie to make it available on 3.x?

**Comment by ccordoba12** [comment]
I don't think so. There are different strings on master, and at different locations, so this has to go to master.

**Comment by ccordoba12** [comment]
> Have you seen the typo remarks within my translation comments?

Yep, thanks for noticing them. We'll fix them for Spyder 3.2.

**Comment by goanpeca** [comment]
Rebase needed?

**Comment by ccordoba12** [comment]
@be-we, I solved the merge conflict using Github's web interface, so don't worry about it.

I'll merge your PR after our tests pass. Thanks a lot for this, it's a great contribution!

**Comment by ccordoba12** [comment]
This is the eight language Spyder is translated to, yay!!

**Comment by ccordoba12** [comment]
The failure in Circle is unrelated to this, so merging.

**Comment by be-we** [comment]
I see you like the new translation.

**Pull request merged**
