### PR TITLE
PR: Purge workflow cache weekly

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

Workflow cache is purged every Sunday at 4:10 UTC.
All unit tests are then run on the latest master commit.
This will result in testing environments being resolved and cached, and verified with possible updates to indirect dependencies.

### CODE REVIEW

**Comment by mrclary** [comment]
@ccordoba12, I tested this using a manual dispatch on my fork. The cache is purged as expected and all tests pass.

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary!

**Comment by ccordoba12** [comment]
@mrclary, the Windows tests are failing after cleaning the cache:

https://github.com/spyder-ide/spyder/actions/runs/11311341843/job/31458679329

Could you take a look at that? Thanks!

**Comment by mrclary** [comment]
Hmm... not sure what is going on here. This is not failing on our tests, but on the "Post create pip test environment" step, i.e. at the teardown process.
```
Error: EPERM: operation not permitted, unlink 'C:\Users\runneradmin\micromamba\pkgs\libzlib-1.3.1-h2466b09_2\zlib.dll'
```
It is the same error for all failed tests, and only for Windows. I don't know what could be causing this or how to fix it. Could it be a bug with `setup-micromamba@v1` github action?

**Comment by mrclary** [comment]
@ccordoba12, I still don't know what is causing the error. I've rerun the Windows tests several times without success, however rerunning with debug enabled caused success. 🤷🏼‍♂️ . I suspect that we will have the same issue again when the cron is triggered.

**Pull request merged**
