### PR TITLE
PR: Improve unfold_if_colapsed logic to consider nested blocks

### LINKED ISSUE #12485: Collapsed code search bug
### What steps will reproduce the problem?

if i have collapsed function in class and i try to find something in code, and this can be found inside that function, the whole class collapses.

Also related big bug - if i have collapsed functions, after some actions their names no more highlited as collapsed and clicking arrow button again "collapses" again already collapsed code.

## Versions

* Spyder version: 4.1.2 
* Python version: 3.7.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.10 (OK)
qdarkstyle >=2.8               :  2.8.1 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.3 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.4 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.3 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)
```

### PR DESCRIPTION
**Pull request by andfoy**
## Description of Changes
This PR unfolds all the nested code folding blocks when a search result lands inside of them.

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Peek 09-12-2020 19-07

### Issue(s) Resolved

Fixes #12485 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @andfoy

### CODE REVIEW

**Review by ccordoba12 — COMMENTED** [review]
Great job @andfoy! Thanks a lot for it!

I only have one question for you: is it possible to give focus to the portion of the file that contains the searched text after the unfold happens?

In your screenshot it's possible to see that you need to scroll to manually find the result after the region was unfolded.

**Comment by andfoy** [comment]
@ccordoba12, the last commit should have addressed this last issue

Peek 10-12-2020 17-48

**Comment by ccordoba12** [comment]
Thanks for that @andfoy! One last thing though: is it possible to highlight the match after the region is centered? I think that's the last thing to make searches in folded regions work as they do in regular ones.

**Comment by andfoy** [comment]
@ccordoba12, the rehighlight issue should be fixed on the latest commit:

Peek 11-12-2020 16-49

**Review by ccordoba12 — APPROVED** [review]
Now everything is working flawlessly, thanks a lot @andfoy!

**Pull request merged**
