### PR TITLE
New file directory

### LINKED ISSUE #9162: Set editor working directory to be the same as the console working directory
### Issue Report Checklist

* [ x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
This is a small irritation for me, but I can't find a way to solve it. Thanks in advance for any suggestions.

 I would like the editor working directory (the default save location for new .py files) to be the same as the working directory of the **currently active console**.  Instead, the editor working directory seems to default to either my home directory or the last directory I saved a file in, which results in my regularly saving files in the wrong directory.  I can't seem to find any settings related to the editor working directory.  

What I want is for the paths circled in green to be updated whenever the console working directory (red) is changed (see the image below), whether that change comes from navigation or from switching consoles.  

Untitled

### What steps reproduce the problem?

1. Save a file in the current console working directory (directory 1)
2. Change the current console working directory to a new directory (directory 2)
3. Open a new .py file and save.  

### What is the expected output? What do you see instead?
I would expect the default save directory to be (directory 2).  Instead, the default save directory is (directory 1).  

### Paste Traceback/Error Below (if applicable)

```python-traceback

N/A

```

## Versions

* Spyder version: 3.3.4
* Python version: 3.6
* Qt version: 5.9.7
* PyQt version: 5.9.2
* Operating System name/version: Windows 10 Home

### Dependencies

```
IPython >=4.0     :  7.4.0 (OK)
cython >=0.21     :  0.29.6 (OK)
jedi >=0.9.0      :  0.13.3 (OK)
matplotlib >=2.0.0:  3.0.3 (OK)
nbconvert >=4.0   :  5.4.1 (OK)
numpy >=1.7       :  1.14.5 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
pycodestyle >=2.3 :  2.5.0 (OK)
pyflakes >=0.6.0  :  2.1.1 (OK)
pygments >=2.0    :  2.3.1 (OK)
pylint >=0.25     :  2.3.1 (OK)
qtconsole >=4.2.0 :  4.4.3 (OK)
rope >=0.9.4      :  0.12.0 (OK)
sphinx >=0.6.6    :  1.8.5 (OK)
sympy >=0.7.3     :  1.3 (OK)

```

### PR DESCRIPTION
**Pull request by Akashtyagi08**
## Description of Changes

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Earlier on creating a new file, its default directory was set as the directory of previous file, which doesn't seems so logical.
Now, if its not a project, a new file's default directory is set as the current working directory.

## Before
earlier

## After
after

### Issue(s) Resolved

Fixes #9162 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by Akashtyagi08** [comment]
@goanpeca  Let me know if any improvements are required.

**Comment by goanpeca** [comment]
Hi @Akashtyagi08 thanks a lot for your contribution. I will review in the next couple of days. 

Cheers!

**Comment by goanpeca** [comment]
One issue I see is all these commits. We should be seeing only the one you made.


Screen Shot 2020-05-04 at 20 00 07

How did you create this PR?

**Comment by bcolsen** [comment]
Looks like it needs to be re-based on 4.x 

@Akashtyagi08 see here: https://github.com/spyder-ide/spyder/wiki/Dev:-Github-Workflow#rebasing  Only change the master to 4.x.  

The rest of the page is a good read as well.

**Comment by goanpeca** [comment]
@Akashtyagi08 it seems your fork of spyder is outdated so you will need to do something like:

```
git checkout 4.x
git pull upstream 4.x
git push origin 4.x

git checkout -b enh/new-file-dir
# Make your changes
git add .
git commit -m "Change default directory for new files"
git push origin enh/new-file-dir
```

Please create a new PR, I will close this one, as it

**Pull request closed without merging**
