### PR TITLE
PR: fix not decorated slots connected to 'triggered' and 'clicked' signals

### LINKED ISSUE #2900: 'Commit' command in File explorer not working in Spyder 3.0.0b2
Spyder 3.0.0b2
Python 2.7.11 64bits, Qt 5.4.1, PyQt5 5.4.1 on Darwin

After clicking the 'Commit' context menu in File explorer, the following error appeared:

```python
Traceback (most recent call last):
  File "/Users/shenggao/anaconda/lib/python2.7/site-packages/spyderlib/widgets/explorer.py", line 279, in <lambda>
    self.vcs_command(fnames, 'commit'))
  File "/Users/shenggao/anaconda/lib/python2.7/site-packages/spyderlib/widgets/explorer.py", line 683, in vcs_command
    for path in sorted(fnames):
TypeError: 'bool' object is not iterable
```

So I tried to print out the arguments passed to the ``vcs_command`` method, 
```python
    def vcs_command(self, fnames, action):
        """VCS action (commit, browse)"""
        print fnames, action
        ....
```
... and got this:
```python
False commit
```

### PR DESCRIPTION
**Pull request by Qlogin**
Cause 'QAction::triggered' and 'QAbstractButton::clicked' signals has default parameter 'checked=False' all slot-function without decorator '@Slot()'  (e.g. lambdas) should have first parameter 'checked'.

But PySide always passes no arguments to these slots in spite of signals definiton, therefore first parameter of slots should have default value.

Fixes #2900

### CODE REVIEW

**Comment by Qlogin** [comment]
this will fix issue #2900

**Comment by ccordoba12** [comment]
Thanks for your contribution and sorry for the delay in coming back to you.

Please change all lines in `configdialog` that appear as

    if API == 'pyqt':

to look like

    if not API == 'pyside':

so that your changes apply to both PyQt4 and PyQt5.

**Comment by Qlogin** [comment]
Done, @ccordoba12 !
Also, I have done the same checks for API in other files that I had changed before.

**Comment by ccordoba12** [comment]
Everything seems right. Thanks for your contribution!

**Pull request merged**
