### PR TITLE
PR: Improve splash screen blurriness and add high resolution Windows ico file

### LINKED ISSUE #16236: New Splash Screen misbehaves on dark backgrounds
## Problem Description

When one has a dark background (the darker the more noticeable), and one starts spyder, the splash screen has an annoying "jump" at the left side of the image as illustrated below :

new_spyder_splash_on_dark_background

### What is the expected output?
Same behavior as at the right side of the image

## Versions
```
* Spyder version: 5.1.1 None
* Python version: 3.9.6 64-bit
* Qt version: 5.12.9
* PyQt5 version: 5.12.3
* Operating System: Linux 5.11.0-27-generic
```
## Dependencies
```

# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  1.6.0 (OK)
cookiecutter >=1.6.0          :  1.7.3 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.6.0               :  7.26.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.0 (OK)
jsonschema >=3.2.0            :  3.2.0 (OK)
keyring >=17.0.0              :  23.0.1 (OK)
nbconvert >=4.0               :  6.1.0 (OK)
numpydoc >=0.6.0              :  1.1.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.2 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.8.0 (OK)
pygments >=2.0                :  2.9.0 (OK)
pylint >=2.5.0                :  2.9.6 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0          :  1.2.1 (OK)
pylsp_black >=1.0.0           :  None (OK)
qdarkstyle =3.0.2             :  3.0.2 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.0.3 (OK)
qtconsole >=5.1.0             :  5.1.1 (OK)
qtpy >=1.5.0                  :  1.9.0 (OK)
rtree >=0.9.7                 :  0.9.7 (OK)
setuptools >=49.6.0           :  49.6.0.post20210108 (OK)
sphinx >=0.6.6                :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0 :  2.1.0 (OK)
textdistance >=4.2.0          :  4.2.1 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.3 (OK)
xdg >=0.26                    :  0.27 (OK)
zmq >=17                      :  22.2.0 (OK)

# Optional:
cython >=0.21                 :  0.29.24 (OK)
matplotlib >=2.0.0            :  3.4.2 (OK)
numpy >=1.7                   :  1.21.1 (OK)
pandas >=1.1.1                :  1.3.1 (OK)
scipy >=0.17.0                :  1.7.1 (OK)
sympy >=0.7.3                 :  1.8 (OK)
```

### PR DESCRIPTION
**Pull request by isabela-pf**
## Description of Changes
Addresses the blurriness for high resolution screens as reported in [ux-improvements #61](https://github.com/spyder-ide/ux-improvements/issues/61). Big thanks to @steff456 and @andfoy for testing this and figuring out all the Qt stuff even though they didn't want to make the PR themselves. 🌻 

- [x] Make splash screen less blurry
- [x] Make application icon less blurry

* [x] ~~Wrote at least one-line docstrings (for any new functions)~~
* [x] ~~Added unit test(s) covering the changes (if testable)~~

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes [ux-improvements #61](https://github.com/spyder-ide/ux-improvements/issues/61)
Fixes #16236

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
isabela-pf

### CODE REVIEW

**Review by dalthviz — COMMENTED** [review]
Hi @isabela-pf @steff456 just in case this is what I'm seeing after installing Spyder with the Windows installer from this PR in a screen I have that goes up to 1920 x 1080:

menu

splash

bar

**Comment by ccordoba12** [comment]
@dalthviz, so is everything working as expected? Also, do the screenshots come from our installer?

**Comment by dalthviz** [comment]
@ccordoba12 I think so and yes those screenshots are with the 'Lite' Spyder from the installer that I downloaded from this PR. However, since I'm not good in terms of checking the differences between resolution and things like that I guessed that doing some screenshots to be checked here could be better to see if the expected behavior is happening.

**Review by steff456 — APPROVED** [review]
We just did the last check of this PR in a high resolution screen with both the installer and the conda installation and both the icon and the splashscreen are looking great!

@ccordoba12 this is ready to merge

**Comment by ccordoba12** [comment]
Thanks @isabela-pf, @steff456 and @andfoy for your hard work on this one!

Merging away (at last!)

**Pull request merged**
