### PR TITLE
[WIP] PR: Added option to execute in a new console

### LINKED ISSUE #9365: Run command with "Execute in a new dedicated console" option
### What steps will reproduce the problem?

I request either changing the behaviour of the Run command with the "Execute in a dedicated console" option or adding a new option to be able to create a new dedicated console for each run, due to the below reasons. If Spyder allows this like PyCharm does, it would be very helpful! Currently only solution I found is to manually create a new console and run on it, which is not practical and I sometimes forget create and waste the running time duration of the script.

1. For data analysis, algorithm development and debugging, I often need to interactively compare by running the same script with different parameters or changing parts of its codes. Therefore multiple consoles for different versions of the same script should stay open to be able to do various comparisions.

2. Since the Run command does not make a kernel reset, modules are reloaded without removing already loaded modules. As far as I know it is still not posible to remove loaded modules, though the variables can be cleared by an option. This can cause serious memory problem after running multiple times if a loaded module consumes considerable memory (happens with some of my scripts as they load data in memory)

## Versions

* Spyder version: 3.3.4 
* Python version: 3.6.6
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-50-generic

### Dependencies

```
IPython >=4.0     :  6.5.0 (OK)
cython >=0.21     :  None (NOK)
jedi >=0.9.0      :  0.12.1 (OK)
matplotlib >=2.0.0:  2.2.2 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
numpy >=1.7       :  1.15.0 (OK)
pandas >=0.13.1   :  0.23.3 (OK)
psutil >=0.3      :  5.4.6 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pyflakes >=0.6.0  :  2.0.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
pylint >=0.25     :  1.9.2 (OK)
qtconsole >=4.2.0 :  4.3.1 (OK)
rope >=0.9.4      :  0.10.7 (OK)
sphinx >=0.6.6    :  1.7.6 (OK)
sympy >=0.7.3     :  None (NOK)
```

### PR DESCRIPTION
**Pull request by oscargus**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Added an option to run in a new console. As seen, numbers are added similar to `Console` to keep track of the different instances of the same file. The run in dedicated console works exactly as before (changing to that will execute the code in the first of the "new" consoles for that file).

runinnewconsole

Tests still to be added.

### Issue(s) Resolved

Fixes #9365

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Oscar Gustafsson/@oscargus

### CODE REVIEW

**Comment by drive-buss** [comment]
image

Maybe adding a button at the red circle to let running the active file in this console would be a nice addition.

**Comment by drive-buss** [comment]
image

It might be nice to add a button (red circle) in the ipython console to run the current active file in this console.

**Comment by oscargus** [comment]
@drive-buss not sure if I follow. How would this differ from "Execute in current console"?

**Comment by drive-buss** [comment]
> 
> 
> @drive-buss not sure if I follow. How would this differ from "Execute in current console"?

No difference, that's the reason I deleted my comment!!

**Comment by goanpeca** [comment]
Is this still valid @ccordoba12 ?

**Comment by ccordoba12** [comment]
It seems @oscargus lost interest in keep contributing to Spyder, so let's close it for now.

**Pull request closed without merging**
