### PR TITLE
PR: Show the number of matches in the Find/Replace widget

### LINKED ISSUE #4001: Ctrl+F should show the number of appearances in the file as #current/#total
For example:

a e i o u **a** e a e i  

Ctrl+F -> "a" 2/3

### PR DESCRIPTION
**Pull request by mariacamilaremolinagutierrez**
It now looks like this:

image

image

---------------------------------

Edit:
Fixes #4001.

### CODE REVIEW

**Comment by mariacamilaremolinagutierrez** [comment]
I'm still having trouble to calculate the position of the current search because of how the find is done. If you could give me please some insight I would really appreciate it!

**Comment by goanpeca** [comment]
@mariacamilaremolinagutierrez what is this PR fixing (add the `Fixes #NNN to the PR description comment on the top)

**Comment by ccordoba12** [comment]
@dalthviz, please rebase and finish this one.

**Comment by dalthviz** [comment]
@ccordoba12 this PR has an issue already created? I can't find it. 
Preview:

With a match:
imagen

Without a match:
imagen

**Comment by ccordoba12** [comment]
I saw an issue about it but I can't find it right now.

I like it! @goanpeca, what do you say?

**Comment by ccordoba12** [comment]
@dalthviz, a test is missing. Please add one.

**Comment by goanpeca** [comment]
I like it :-p, can't find the issue either, @dalthviz go ahead and create one?

**Comment by ccordoba12** [comment]
@dalthviz, in your screenshots there's too much space between the matches text and the previous/next buttons. Please fix that.

**Comment by ccordoba12** [comment]
I like @mariacamilaremolinagutierrez screenshots better :-)

**Comment by dalthviz** [comment]
Ok :+1: although I left that space for stuff like this:

imagen

To have a fixed size that doesn't make the search text box resize when the label is long.

**Comment by ccordoba12** [comment]
I think it's better to resize the search dialog.

@goanpeca?

**Comment by goanpeca** [comment]
>I think it's better to resize the search dialog

:+1:

**Comment by ccordoba12** [comment]
@dalthviz, is this ready?

**Comment by dalthviz** [comment]
@ccordoba12 yep :+1:

**Pull request merged**
