### PR TITLE
PR: Fake release

### PR DESCRIPTION
**Pull request by mrclary**
DO NOT MERGE THIS PR!

- This is a retroactive fix for #18661 for [5.3.2](https://github.com/spyder-ide/spyder/releases/tag/v5.3.2) only.
- This is a retroactive fix for #18776 for [5.3.2](https://github.com/spyder-ide/spyder/releases/tag/v5.3.2) only.

Manually replace the 5.3.2 release macOS artifacts with the artifacts from this PR.

### CODE REVIEW

**Comment by mrclary** [comment]
@ccordoba12, so CI ran with the fix and I verified that the new artifact works (https://github.com/spyder-ide/spyder/actions/runs/2674779006).
However, I realized that the merge state had the wrong version, so I had to revert `__init__.py` with the correct version number. This will trigger all the test workflows. If any of them fail, I think we can safely ignore them, and just verify that the macOS installer builds are good.

**Comment by ccordoba12** [comment]
> so CI ran with the fix and I verified that the new artifact works

Great! Thanks for your prompt help with that!

> However, I realized that the merge state had the wrong version, so I had to revert __init__.py with the correct version number.

I don't understand: so the artifacts in this PR have the right Spyder version or not?

**Comment by mrclary** [comment]
> I don't understand: so the artifacts in this PR have the right Spyder version or not?

I'm checking right now. Stand by.

**Comment by mrclary** [comment]
Confirmed. These artifacts have the correct 5.3.2 version number. I downloaded the full version and confirmed that everything is working.
https://github.com/spyder-ide/spyder/actions/runs/2677440607

**Comment by ccordoba12** [comment]
Ok, good to know.

**Comment by ccordoba12** [comment]
Thanks a lot @mrclary!

**Comment by mrclary** [comment]
In response to #18776, I've reopened this PR.

I've found the issue: the QtWebEngineProcess.app within the Qt frameworks must have the `runtime` options flag for notarization, which breaks it.

I believe that the solution is to add the `com.apple.security.cs.disable-executable-page-protection` entitlement to its signature. See https://forum.qt.io/post/526704.

If the artifact is successful, I'll replace the existing release artifact as I did before.

Thanks all for your patience as I work out these code signing quirks 😊

**Comment by mrclary** [comment]
As of this post, the 5.3.2 artifacts have been replaced with ones where QtWebEngine should be working properly.

**Comment by ccordoba12** [comment]
> Thanks all for your patience as I work out these code signing quirks

Thanks for your lighting fast response to solve these issues!

**Pull request closed without merging**
