### PR TITLE
Fix zlib segmentation fault in Anaconda 3.4 Linux

### PR DESCRIPTION
**Pull request by blink1073**
The problem is described in https://github.com/ContinuumIO/anaconda-issues/issues/272.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Should we backport this PR to the stable branch too?

**Comment by blink1073** [comment]
It does not happen in the conda version of Spyder (2.3.2), oddly enough.  Perhaps it has to do with running from `bootstrap.py`?

**Comment by blink1073** [comment]
I verified that running from `bootstrap.py` is what makes the difference.

**Comment by blink1073** [comment]
Well, I found it!  We were improperly importing `Qt` in `QtCore.py`.

**Comment by blink1073** [comment]
I'd say port this change back because who knows what other subtle bugs might arise.

**Comment by goanpeca** [comment]
Why don't we make the `Qt` shim a dependency of Spyder instead of a core component? 

Many applications could benefit from it (I will use it for the stand alone version of the CondaPackageManager) and in cases like this, we could just recommend updating the dependency (and update spyder requirements) and not update Spyder completely (as this kind of changes would require a new quick release 2.3.4 for instance... ). 

It would also make the code base cleaner.

I will upload a package in PyPi for this (**QtPy** yes... cutie pie) to use in my other projects.

**Comment by goanpeca** [comment]
Also, should not we update the qt part to use it like Qt5, instead of making it look like Qt4? 

Qt5 split `QtWidgets` and `QtGui`, so maybe we should do the same (for future proofing) like what Colin did on [pyqode.qt](https://github.com/pyQode/pyqode.qt).

**Comment by blink1073** [comment]
See also https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/qt_compat.py

**Comment by goanpeca** [comment]
Will do

**Comment by ccordoba12** [comment]
@goanpeca I don't think we should move our shim to an external package. Almost all projects I know of have their shims as part of their source code.

Besides, this is the first error I've seen with our shim in all my time with Spyder! :-)

**Comment by blink1073** [comment]
I agree with keeping it here.  We used the matplotlib shim in scikit-image because matplotlib is already a dependency.

**Comment by goanpeca** [comment]
:+1:

**Pull request merged**
