### PR TITLE
PR: [WIP] Test IPython console

### PR DESCRIPTION
**Pull request by petebachant**
I am trying to create a failing test to detect issue #2679 or #2696. Currently this does not work. Since this is over my head, I'm looking for some feedback on where to turn next. I suppose this is also working towards #2268.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for this @petebachant. @goanpeca, could you take a look at this one?

**Comment by goanpeca** [comment]
@petebachant thanks for this ! we really need to improve our (non existent  :wink: test codebase).

I think we want to have tests close to the tested feature, so I guess in this case, we would need to move this test inside `spyderlib/plugins/tests` what do you think?

**Comment by petebachant** [comment]
Looking at some other projects, e.g. IPython and pandas, you're right. They do put tests for subpackages inside `{subpackage}/tests`. I will move that at least. Any ideas on how I might simulate opening an IPython console without ever creating the main window? Or is this something that should be done by opening the full app, and using some other testing tools to click the appropriate buttons?

**Comment by goanpeca** [comment]
We could use pytest-qt, are you familiar?

**Comment by petebachant** [comment]
I've used pytest a little but mainly Nose. I will look into pytest-qt when I have time again!

**Comment by ccordoba12** [comment]
@petebachant, the way we integrate with the qtconsole is going to be changed drastically after PR #2878 is merged, so I'm closing this for now.

Please feel free to open a new PR after that that one is merged.

**Pull request closed without merging**
