### PR TITLE
PR: Set OpenGL backend before the QApplication is created

### LINKED ISSUE #11227: set_options_opengl is called too late
https://github.com/spyder-ide/spyder/blob/26504d5ed48fdaa28b76cf72962859d4fdbce0cf/spyder/app/mainwindow.py#L3651

It needs to get called before the application is created. This means, before the splash screen.

The whole block that gets the options needs to be imported sooner, but importing
```
spyder.apps.cli_options
```
might be expensive to load

In either case, without moving it forward, Qt warns the user

Attribute Qt::AA_UseSoftwareOpenGL must be set before QCoreApplication is created.

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #11227 

@dalthviz, please help me to finish this PR. The idea is to set the OpenGL implementation we use before we create `MAIN_APP`, i.e. below this point:

https://github.com/spyder-ide/spyder/blob/26504d5ed48fdaa28b76cf72962859d4fdbce0cf/spyder/app/mainwindow.py#L99-L104

The only problem is that I don't know how to capture our command line options at that point. That's the tricky part of this work.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, did you test your solution to see if it avoids the error reported on issue #11227 when using PyQt 5.12?

**Comment by dalthviz** [comment]
Nop @ccordoba12 , I will setup a test env to check and I will let you know if works with that PyQt version

**Comment by dalthviz** [comment]
@ccordoba12 I don't see the warning message when running Spyder using PyQt 5.12, so I think this is ready  :+1:

**Comment by ccordoba12** [comment]
Great, thanks for extra verification @dalthviz!

**Pull request merged**
