### PR TITLE
PR: Improve implementation and UI of console envs menu (IPython console/Main interpreter) 

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

- The IPython console and Main interpreter plugins have repeated functionality to keep track of conda/pyenv envs in the system. This PR consolidates that in Main interpreter, which now emits a signal that the IPython console connects to to display info related to those envs.
- To do that it was necessary to move almost all functionality of the Main interpreter status bar widget to its container.
- Show custom envs (i.e. those manually added by users in Preferences) in the console envs menu. That's important for people that don't use conda/pyenv for env management.
- Break console envs menu into sections or submenus with the following actions:
  - Default, which shows the default and internal (i.e. same as Spyder) envs. In case they are the same, the internal env is not shown.
  - Conda envs
  - Pyenv envs.
  - Custom envs.
- Except for the first section, the others are added if there are two or more envs per category. Also, submenus are used if the user has more than 20 envs and more than one category of envs.

### Visual changes

IPython console envs menu

| Before | After |
| - | - |
| imagen | imagen |

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @ccordoba12

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, this is ready for review. Since I have to move code around in several places, I suggest that you take a look at these changes one commit at a time.

**Comment by dalthviz** [comment]
Gave this a check and seems like the menu is working as expected :+1: Also, just in case, an idea that came to my mind while checking this is to use submenus instead of sections (so `Consoles > New console in environment > pyenv/conda/custom`). In my current setup I have a lot of conda envs but just a couple pyenv/custom envs and I have to go all the way down to get them:

menu_envs

However, the status bar is not showing anything at all or showing a different env name for completions. So, having over preferences the default interpreter selected, I see on Spyder start an empty completions status bar: 

image

If I start changing the interpreter preference between a custom interpreter and the default one, I end up with completions refering with a different interpreter than the default one even when I have set the preferences to just use the default one again:

image

The tooltip though is showing the correct path to the selected interpreter:

image

Also, I'm not totally sure to follow the reason to move the main interpreter container to be inside the `widgets` module, maybe the container is now also a widget? From what I see seems like it still is a `PluginMainContainer` 🤔

**Comment by ccordoba12** [comment]
> Also, just in case, an idea that came to my mind while checking this is to use submenus instead of sections (so Consoles > New console in environment > pyenv/conda/custom). In my current setup I have a lot of conda envs but just a couple pyenv/custom envs and I have to go all the way down to get them

That's a great idea @dalthviz! I implemented it in my last commit like this: if the user has more than 20 envs and there are at least two categories (conda/pyenv/custom) with one env or more, then we submenus. If not, we use a single menu with sections.  

> * However, the status bar is not showing anything at all or showing a different env name for completions. So, having over preferences the default interpreter selected, I see on Spyder start an empty completions status bar
> * If I start changing the interpreter preference between a custom interpreter and the default one, I end up with completions refering with a different interpreter than the default one even when I have set the preferences to just use the default one again
> * The tooltip though is showing the correct path to the selected interpreter

My idea for a follow-up PR (to be created after after this one) is to remove the current Completions status bar widget, along with the Main Interpreter one, and leave a single widget that will show the interpreter of the current console (so, that widget will be similar to the Matplotlib status one).

I decided to do that for three reasons:

* Now that users will be able to easily open consoles in any environment, it makes little sense to show the default interpreter in the status bar.
* The completions and default interpreters were almost always the same. So, it doesn't make sense to have two of them.
* This problem is similar to the one we had in Spyder 3 with the directory shown in the Working Directory toolbar. At that time we were showing a global directory, and that was really confusing to users. After we decided to show the `cwd` of the current console, that confusion disappeared.

> Also, I'm not totally sure to follow the reason to move the main interpreter container to be inside the widgets module, maybe the container is now also a widget? From what I see seems like it still is a PluginMainContainer 🤔

I think you're right. Technically, `PluginMainContainer` is a widget because it inherits from `QWidget`. But it's not a real widget, i.e. as a dialog or button. So, I reverted that change.

**Comment by dalthviz** [comment]
> I implemented it in my last commit like this: if the user has more than 20 envs and there are at least two categories (conda/pyenv/custom) with one env or more, then we submenus. If not, we use a single menu with sections.

Gave this another check and seems like things for the menus are working with the extra conditional rendering idea (subsections vs submenus) :+1: The only thing that I'm not sure if needs something to be done is the handling of empty submenus. So for example if I have 20+ conda envs and one custom env I'm seeing something like:

console_menu_envs

Maybe if no envs are available in a particular submenu, that submenu should be shown in a disabled state?

> My idea for a follow-up PR (to be created after after this one) is to remove the current Completions status bar widget, along with the Main Interpreter one, and leave a single widget that will show the interpreter of the current console (so, that widget will be similar to the Matplotlib status one).

I have been thinking about that and the final result makes sense. Still, is kind of weird to leave things in an incoherent/broken state (even if is just while waiting for an immediate follow up PR). So, although is just a mere review process principles technicallity, I would say I can't approve this PR (like literal leave it approved on the GitHub interface). Anyhow, I won't stop you from merging this so feel free to do so when you think is ready :+1:

**Comment by ccordoba12** [comment]
> Maybe if no envs are available in a particular submenu, that submenu should be shown in a disabled state?

Good idea. I amended my second to last commit to implement that, so please check again.

> I have been thinking about that and the final result makes sense. Still, is kind of weird to leave things in an incoherent/broken state (even if is just while waiting for an immediate follow up PR).

You're right. That's why I decided to remove the Completions status bar widget in my last commit.

**Review by dalthviz — APPROVED** [review]
Thanks @ccordoba12 ! Gave this a new check and seems like things are working as expected :+1: However, I'm not seeing the menu in a disabled state, in fact, I'm literally not seeing the menu (the `pyenv` menu in this case). That works for me although seemed worthy to mention just in case that wasn't what you were aiming for:

image
 
Anyhow, I will leave this approved so feel free to merge as soon you think this is ready :+1:

**Comment by ccordoba12** [comment]
> ! Gave this a new check and seems like things are working as expected 👍

Great!

> However, I'm not seeing the menu in a disabled state, in fact, I'm literally not seeing the menu (the pyenv menu in this case).

That's by design. We only show submenus that have at least one env listed in them. Since you have no Pyenv envs, that's why the menu doesn't show up for you.

----

There's one small issue in your gifs though: they don't show a `Default` entry above the `Internal / Conda: spyder-dev (Python 3.9.19)` one. And that entry should be available because it's the interpreter set in Preferences,

I tried to reproduce that on my Windows VM but I was unable to. So, could you post a screenshot of your `Preferences > Python interpreter page`? Also, please post the value of `get_conf("executable", section="main_interpreter")` to check what's saved there.

**Comment by dalthviz** [comment]
> There's one small issue in your gifs though: they don't show a Default entry above the Internal / Conda: spyder-dev (Python 3.9.19) one. And that entry should be available because it's the interpreter set in Preferences,
>
>I tried to reproduce that on my Windows VM but I was unable to. So, could you post a screenshot of your Preferences > Python interpreter page? Also, please post the value of get_conf("executable", section="main_interpreter") to check what's saved there.

image

image

**Comment by ccordoba12** [comment]
Thanks for the extra info @dalthviz! I was able to reproduce and fix the problem I mentioned above with it.

**Pull request merged**
