### PR TITLE
Failed sip import blocks fallback to PySide

### LINKED ISSUE #2649: PySide can not be used on 2.3
If PyQt4 is not installed, `sip` is also unavailable, so import fails earlier that a try/except block that sets PySide as a fallback.

### PR DESCRIPTION
**Pull request by techtonik**
Fixes #2649

### CODE REVIEW

**Comment by ccordoba12** [comment]
I'm going to merge this but I'm not going to do a new 2.3 release in a couple of months.

**Comment by ccordoba12** [comment]
Probably a couple of weeks, given issue #2652.

**Comment by goanpeca** [comment]
LGTM :+1:

**Comment by techtonik** [comment]
Thanks for review. JFYI, I don't have access to merge it. And it should be backported to master too.

**Comment by ccordoba12** [comment]
@techtonik, don't worry, I'll forward port it to `master`. Thanks for this, by the way :-)

**Comment by techtonik** [comment]
Awesome! While you are at it, can you also merge https://github.com/spyder-ide/docrepr/pull/7 - I have an interesting follow-up to it. =)

**Comment by ccordoba12** [comment]
Ok, I'll do it in a couple of minutes :-)

**Comment by techtonik** [comment]
@ccordoba12 here is it - https://github.com/spyder-ide/docrepr/pull/8 - take a look. =)

**Comment by ArthurZ** [comment]
Anaconda Launcher reports I have ver 2.3.7 installed and when I start it I am seeing an error:
Please check Spyder installation requirements: PyQt4 4.6+ (or PySide 1.2.0+) is required.
I am on Windows 7.
Starting Spyder from the Start menu makes it run, but it is ver. 2.3.6
Note: I attempted to conda update -all and was getting linking errors I ignored.

**Comment by techtonik** [comment]
@ArthurZ it is better if you create a separate issue.

**Comment by ArthurZ** [comment]
Thank you @techtonik, submitted, https://github.com/spyder-ide/spyder/issues/2794

**Pull request merged**
