### PR TITLE
PR: Move language funcs into a subfolder

### PR DESCRIPTION
**Pull request by goanpeca**
All the files on the repo root create a bit of a mess...

### CODE REVIEW

**Comment by malliwi88** [comment]
Nice!! :) more order on the repo.

**Comment by ccordoba12** [comment]
@goanpeca, +1 for this, but I have some comments:

1. Did you move these language scripts or just added them as new files? It would seem you added them because the GH doesn't report the move :-)
2. Did you test that these scripts are still working after the move? I hadn't moved them before because they assume the Spyder modules are in the same directory as the one they are located in.
3. You did this PR against master, so it can't be marked for 3.1.

**Comment by goanpeca** [comment]
@ccordoba12, hmmmm true, I will move them and then make the changes.

Actually on OSX these scripts dont work :-|, (but because some files are not found) I will check on linux or win ;-)

**Comment by ccordoba12** [comment]
Closing because these files are going to be moved to a new repo.

**Pull request closed without merging**
