### PR TITLE
PR: Change pane tabs design

### PR DESCRIPTION
**Pull request by jsbautista**
## Description of Changes

Change design of pane tabs for them to look different to the tabs of the console and editor

A preview:

* Tab selected:
image

* Hover over tab not selected:
image

* Scroll buttons when there is not enough space to show all the tabs
image

### Issue(s) Resolved

Fixes https://github.com/spyder-ide/ux-improvements/issues/4

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
@jsbautista

### CODE REVIEW

**Comment by jsbautista** [comment]
Preview: 
tabpages

**Comment by ccordoba12** [comment]
Hey @jsbautista and @dalthviz, thanks for your work on this! Since I saw the design you decided to implement when I took a look at this PR some days ago, I also decided to resurrect some code I worked on two years ago to try to implement this feature.

Now I think I have a result closer to what was discussed on spyder-ide/ux-improvements#4:

image

so I think we should use that instead.

I'm sorry if you invested too much time on this and for not informing you about my efforts before. I just wasn't sure if I could do better than what you've done here.

**Comment by dalthviz** [comment]
Is there already a PR to link as the one that supersedes this one @ccordoba12 ?

**Comment by ccordoba12** [comment]
See PR #21133.

**Comment by dalthviz** [comment]
Closing as superseded by https://github.com/spyder-ide/spyder/pull/21133

**Pull request closed without merging**
