### PR TITLE
Spyder 3 icon theme changes

### PR DESCRIPTION
**Pull request by SylvainCorlay**
As per the suggestions in #2527.
- IP: for the ipython logo
- keyboard icon for the keyboard shortcuts
- a new icon for coloring theme, it is not a palette, but an eyedropper. The advantage is that it is a font-awesome icon.
- question-circle icon for the object inspector.

options

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
I have not change the command promt / terminal icon yet because it is used in different places, I need to be sure of what to replace.

**Comment by ccordoba12** [comment]
Great job! Any thoughts @goanpeca?

**Comment by goanpeca** [comment]
Looks cool ! :+1:

**Comment by SylvainCorlay** [comment]
Now using the Python logo for the console config session as asked by Carlos. Ready to get in.

**Comment by ccordoba12** [comment]
I have one suggestion: the `IP:` icon seems a bit too big next to text to its right. Could you make it a bit smaller?

**Comment by SylvainCorlay** [comment]
In that instance only or all the time? The former would require adding a special entry in the icon manager, and I thought the problem with the previous one was that it was too thin...

**Comment by ccordoba12** [comment]
What about this: framing the `IP:` symbol inside a (transparent) rectangle with the top and bottom borders a bit thicker, that represents the console? I mean, something very similar to our current IPython icon :-)

**Comment by SylvainCorlay** [comment]
Well, that is not very "flat design" like font-awesome icons.

**Comment by ccordoba12** [comment]
I don't understand what you mean. The icon would be similar to

http://fortawesome.github.io/Font-Awesome/icon/behance-square

or

http://fortawesome.github.io/Font-Awesome/icon/google-plus-square/

i.e. text inside a square (rectangle in our case) but with the colors inverted.

**Comment by ccordoba12** [comment]
Another example:

http://fortawesome.github.io/Font-Awesome/icon/git-square/

Maybe we can create our IPython icon as these ones (to follow FontAwesome aesthetics :-), i.e. a white `IP:` over a black rectangular background.

**Comment by SylvainCorlay** [comment]
OK, I see what you mean. I will add something like this.

**Comment by SylvainCorlay** [comment]
@ccordoba12 done!
config

**Comment by SylvainCorlay** [comment]
Merge?

**Comment by ccordoba12** [comment]
The IPython icon is a bit blurry when used in our console tabs:

seleccion_001

Can you do something about it? I say it because the other icons look crystal clear ;-)

**Comment by SylvainCorlay** [comment]
It is probably due to an icon size in the tabs that is not pixel perfect...

**Comment by ccordoba12** [comment]
So merge? Or could you take a look at the icon size on tabs to see if we can use 16x16 icons there?

**Comment by SylvainCorlay** [comment]
I can check, but I will be very busy this week.

**Comment by ccordoba12** [comment]
Ok, merging then ;-)

**Pull request merged**
