### PR TITLE
Print git revision and branch in bootstrap.py instead of mercurial

### PR DESCRIPTION
**Pull request by Nodd**
bootstrap.py still searched for a mercurial revision number. Now it uses git.

I added the search for the branch name.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@Nodd, this one failed, according to travis

**Comment by Nodd** [comment]
Forgot about python3 compatibility... Travis is really useful ! :smile:

**Comment by Nodd** [comment]
Now Travis is happy !

**Comment by ccordoba12** [comment]
Getting the current git branch is not working in Python 3 (or at least is not shown after running `bootstrap`), but it's working fine in Python 2.

The branch I'm working on is `(detached from nodd/git-revision)`, after running `git checkout nodd/git-revision`. I don't know if this matters, but I'm mentioning it in case it's important :-)

**Comment by Nodd** [comment]
It should work now, and the code is clearer too.

**Comment by ccordoba12** [comment]
Have you tested this PR on Windows? If not, could you do it to see if there are no problems there?

**Comment by goanpeca** [comment]
I tested on windows, seems to be working fine

**Comment by ccordoba12** [comment]
Great, thanks @goanpeca. Merging then ;-)

**Pull request merged**
