### PR TITLE
PR: Change ScrollFlagArea panel to use panel API

### PR DESCRIPTION
**Pull request by rlaverde**
- Migration of ScrollFlagArea to panels folder.
- Use panel API.
- Move some functions from the CodeEditor to ScrollFlagArea class.

This is a continuation of the decoupling of code editor panels.

### CODE REVIEW

**Comment by rlaverde** [comment]
There are come style errors in circleCI but don't correspond with edited lines, (I deleted some lines and the lines that now correspond with their numeration are being analyzed)

should I fix that errors?

**Comment by goanpeca** [comment]
hmmm I will file an issue on ciocheck. I think we can ignore for now

**Comment by ccordoba12** [comment]
Is this ready?

**Comment by rlaverde** [comment]
> Is this ready?

Yes :smile:

**Pull request merged**
