### PR TITLE
PR: Fix folding and make some performance improvements (Editor)

### PR DESCRIPTION
**Pull request by ccordoba12**
### For folding
- Fix removing a selection that starts or ends in a folded line (this was totally broken).
- Remove folded regions when pressing `Delete` or `Backspace` in a folded line. I took this idea from VSCode.
- Update folding decorations in the visible buffer. Before we were doing it in the visible region, but that prevents to quickly show folded regions when scrolling a file.
- Update folding in a thread. Although this doesn't avoid computing folding in the main thread (due to the GIL), it'll help to do it in an external process (I'll do that in a follow up PR to not make this one bigger).
- Check that folded regions in the visible buffer are updated correctly by UI inspection. We need to do this because the algorithm to update folding fails sometimes (we'll be able to improve that algorithm after folding is computed in an external process).
- Make folded lines appear as read-only to users, i.e. users won't be able to edit them. They'll only be able to delete them by pressing the Delete or Backspace keys.
- Expand test suite to cover the new fixes.

### Other improvements
- Update scroll flags in a thread.
- Prevent updating scroll flags if the cursor is being moved, e.g. when typing.
- Avoid computing some unnecessary operations for code snippets.
- Fix reporting errors that come from PyLSP (this was broken too). 

### Visual changes

**Use chevron icons in the folding panel and move it to be next to the code**

The last part preserves the UI we have in Spyder 5, which I think is the right one.

Before | After
-- | --
imagen | imagen

**Preserve syntax highlighting for folded lines and extend their background color to the full width of the editor**

I took this idea from VSCode.

Before | After
-- | --
imagen | imagen

**Fix style of the folding panel in the light theme**

Before | After
-- | --
imagen | imagen

### Issue(s) Resolved

Part of #21637.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @ccordoba12

### CODE REVIEW

**Review by jitseniesen — APPROVED** [review]
Thanks for keeping the commit history so clean. It meant that I could fairly easily steps through the commit instead of viewing all the hundreds of lines at once.

I have only a couple of minor comments, some general, some specific to the code. I'm happy for you to merge after you have had a look at what I wrote.

* Pressing `Tab` on a folded line indents the whole folded region (this is fine), but it also selects the folded region (this is a bit weird). Pressing `Shift`+`Tab` un-indents only the first line of the folded region. I don't think this is intentional. It's a bit of a boundary case, though, so not  that important.
*  The folding indicator no longer changes colour when you hover above them. That's not a problem as far as I am concerned.
* > Remove folded regions when pressing Delete or Backspace in a folded line. I took this idea from VSCode.

  This means that the editor acts as if the whole folded region is selected if you are on a folded line. The user can't edit a folded line (unless they unfold), they can only delete  the whole folded region. I find that surprising, which is not good. On the other hand, I never use folding so I don't have an intuition, and if VSCode does this then the UX is probably not too bad. Thus I'm fine with this.

* > Preserve syntax highlighting for folded lines and extend their background color to the full width of the editor

  The disadvantage is that before it was obvious when a region was folded, but now it is less so. I guess the chevron should be enough of a sign for users.

**Comment by ccordoba12** [comment]
Thanks for the review @jitseniesen! About your comments:

> Pressing Tab on a folded line indents the whole folded region (this is fine), but it also selects the folded region (this is a bit weird). Pressing Shift+Tab un-indents only the first line of the folded region. I don't think this is intentional. It's a bit of a boundary case, though, so not that important.

I was not aware of that and it was not intended. So, I made that pressing Tab and Shift+Tab in a folded line do nothing.

> The user can't edit a folded line (unless they unfold), they can only delete the whole folded region. I find that surprising, which is not good.

The problem is that if we allow editing folded lines, the editor could be left in an inconsistent state in the sense that the new results coming from the LSP could not include the current line as folded. That's why folded lines are like read-only ones.

> On the other hand, I never use folding so I don't have an intuition, and if VSCode does this then the UX is probably not too bad. Thus I'm fine with this.

Ok, thanks for the remark.

> The disadvantage is that before it was obvious when a region was folded, but now it is less so. I guess the chevron should be enough of a sign for users.

A point in favor of that change is that folded lines are now highlighted to the editor's full width. So you can spot them while moving up and down more easily. And this is also what VSCode does, i.e. it preserves syntax highlighting in folded lines.

**Comment by jitseniesen** [comment]
> > The user can't edit a folded line (unless they unfold), they can only delete the whole folded region. I find that surprising, which is not good.
> 
> The problem is that if we allow editing folded lines, the editor could be left in an inconsistent state in the sense that the new results coming from the LSP could not include the current line as folded. That's why folded lines are like read-only ones.

I mean, if I move the cursor to a folded line and then I press for instance `x`, then the whole folded region is deleted and the letter `x` is added to the next line. If you want folded lines to be like read-only ones (which I'd agree with), then I'd expect that pressing `x` on a folded line does nothing.

**Comment by ccordoba12** [comment]
> I mean, if I move the cursor to a folded line and then I press for instance x, then the whole folded region is deleted and the letter x is added to the next line. If you want folded lines to be like read-only ones (which I'd agree with), then I'd expect that pressing x on a folded line does nothing.

Ok, that's a good point and I also agree with it. I'll implement it before merging this PR.

**Comment by ccordoba12** [comment]
I think this one is finally ready. @jitseniesen, if you find additional issues with folding please open a new issue and I'll address them in a follow-up PR.

**Pull request merged**
