### PR TITLE
PR: Ensure no source files have useless shebangs

### PR DESCRIPTION
**Pull request by musicinmybrain**
## Description of Changes

Removes shebang lines (`#!`) from three non-executable scripts within the `spyder/` package, and sets the executable bit on `tools/rm_whitespace.py`.

* [ ] Wrote at least one-line docstrings (for any new functions) **N/A**
* [ ] Added unit test(s) covering the changes (if testable) **N/A**

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/)) **N/A**

There is no value in having a shebang (`#!`) line in a file that does not have the executable bit set in its filesystem permissions, even if it is script-like (has a “main routine” or other interesting side effects).

Accordingly, shebang lines are removed from three non-executable files within the `spyder/` package.

For `tools/rm_whitespace.py`, I chose to make it executable instead of removing the shebang line. However, the opposite approach of removing the shebang and expecting people to continue to run it as `python tools/rm_whitespace.py` is reasonable too, and I’m happy to amend the PR if that’s preferred.

### Issue(s) Resolved

**N/A**

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: `musicinmybrain`/Benjamin A. Beasley

### CODE REVIEW

**Comment by ccordoba12** [comment]
@musicinmybrain, would you like to see this in our next Spyder version? I'm asking because any PR done against our master branch is for Spyder 6, to be released before the end of the year.

**Comment by musicinmybrain** [comment]
> @musicinmybrain, would you like to see this in our next Spyder version (5.5.0)? I'm asking because any PR done against our master branch is for Spyder 6, to be released before the end of the year.

It’s not essential, but I don’t see any reason not to include it in 5.5.0. If I open a PR against `5.x`, will the change also be pulled forward into `master` as a matter of course?

**Comment by ccordoba12** [comment]
> If I open a PR against 5.x, will the change also be pulled forward into master as a matter of course?

Yes, but you don't need to open a new PR. You can move your branch to 5.x directly here. For that, please run the following commands:

    git checkout 5.x
    git checkout
    git rebase --onto 5.x master useless-shebangs
    git push -f origin useless-shebangs

After that you need to change the base branch for your PR as described here:

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

**Comment by musicinmybrain** [comment]
> Yes, but you don't need to open a new PR. You can move your branch to 5.x directly here.

Done; thanks!

**Comment by ccordoba12** [comment]
Closing and reopening to make our test suite run.

**Review by ccordoba12 — APPROVED** [review]
Thanks @musicinmybrain!

Note: The failures when building our Linux installer are probably related to the base branch change.

**Pull request merged**
