### PR TITLE
Added Russian translation. Updated POT file

### PR DESCRIPTION
**Pull request by burrbull**
I had updated spydelib.pot with xgettext.
Added russian translation (~ 85% of strings).

### CODE REVIEW

**Comment by ccordoba12** [comment]
@burrbull, thanks a lot for your contribution. I have two questions for you:

1. Do you plan to finish the translation? I mean, right now we're some three months away of releasing Spyder 3.0 (which will contain this translation) so there's plenty of time for you to finish it :-)
2. Can we count on you to keep updating the translation in the future?

**Comment by burrbull** [comment]
1. I'll try.
2. Difficult question. Maybe.
I'd never translated programms and I haven't much experience in this work.

**Comment by ccordoba12** [comment]
About 2.: The most difficult part is the first translation. After that, updating a translation is a matter of half an hour of your time per each of our releases. And we do a new release every two months or so.

However, if you're not committed to update this translation, I'm afraid I'd have to decline your work because none of us speak Russian and the translation can get outdated very easily after a couple of releases :-)

**Comment by burrbull** [comment]
I understood.
I'll do all in my power.
If I have free time I'll make the Ukrainian too.

**Comment by goanpeca** [comment]
Awesome :+1: thanks a lot for the help :-)

**Comment by goanpeca** [comment]
I updated the translators section of the wiki.

https://github.com/spyder-ide/spyder/wiki/Dev:-Translations

**Comment by burrbull** [comment]
How to update PR?

**Comment by ccordoba12** [comment]
You need to add more commits to your branch (in this case your `master` branch :-).

**Comment by burrbull** [comment]
Reverse question. How to remove excess commits from PR?

**Comment by ccordoba12** [comment]
@burrbull, given that you merged with master several times, you can't *squash* commits (that's how removing commits is called in git :-).

Please merge with master again to make our tests pass (I fixed them a couple of days ago).

**Comment by Qlogin** [comment]
@burrbull, I've reviewed your translations and correct some mistakes (misprints).
Also, I've made some suggestions for better understanding of translated sentences.
[spyderlib.po.txt](https://github.com/spyder-ide/spyder/files/212668/spyderlib.po.txt)

@ccordoba12, I can help to keep updating Russian translation in the future, if @burrbull won't have enough time.

**Comment by ccordoba12** [comment]
@Qlogin, thanks a lot for offering your help. Should I merge then so you can send us your improvements in another PR?

I really prefer that instead of me committing your changes directly to master, but I'll do what you prefer :-)

**Comment by goanpeca** [comment]
@Qlogin thanks a bunch for the help. I keep the wiki updated with current translators, I hope you dont mind me adding you to the list.

Cheers

https://github.com/spyder-ide/spyder/wiki/Dev:-Translations

**Comment by Qlogin** [comment]
@ccordoba12, I thought that @burrbull can look at the changes, choose some (or all) and commit it in current PR. He has made the whole work. Some of my changes are just rewording.
But if you are ready to merge right now, I'll create another PR and ask Andrey to approve improvements (to avoid "edit war").

**Comment by ccordoba12** [comment]
@Qlogin, I think a separate PR with your improvements is the best strategy (as I said :-). So I'm merging this PR.

@burrbull, thanks a lot for your contribution and for your interest in making Spyder available to a bigger audience!

**Pull request merged**
