### PR TITLE
PR: Add french translations

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Related to #10672

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca @jnsebgosselin

### CODE REVIEW

**Comment by goanpeca** [comment]
@jnsebgosselin this is the scan of the french translations. 

Please download https://poedit.net/ and fire away by clicking on the `spyder/locale/fr/LC_MESSAGES/spyder.po` file

Thanks a lot!

**Comment by jnsebgosselin** [comment]
Ok excellent, thanks. I will work on this this weekend.

**Comment by goanpeca** [comment]
@jnsebgosselin you should be able to push changes to this branch

**Comment by goanpeca** [comment]
@jnsebgosselin did you have some time to go over these?

I want to update the workflow of translations so we can have an automatic pre-translation using google, then it is much much easier to correct an existing po file.

Also this will allow for the creation of new language po files that already populate all strings so the translators only need to review and not actually start from scratch.

Let me know if you hav some work done to wait for your push or if I can do this today.

**Comment by jnsebgosselin** [comment]
@goanpeca Go ahead. Since I saw you were working on it, I did not want to risk duplicating the effort, so I was waiting. I will review after the strings are Google translate filled.

**Comment by jnsebgosselin** [comment]
@goanpeca sorry for bothering you with this but did you had time to work on the Google thing you mentioned earlier?

**Comment by goanpeca** [comment]
>@goanpeca sorry for bothering you with this but did you had time to work on the Google thing you mentioned earlier?

@jnsebgosselin there you go. Now we have automated trans with google :-) (so those strings were generated automatically)

**Comment by goanpeca** [comment]
@jnsebgosselin did you manage to take a look at this 🙃 ?

**Comment by jnsebgosselin** [comment]
It is on my list. I will try to go over this tomorrow, sorry for the delay.

**Comment by ccordoba12** [comment]
@jnsebgosselin, @goanpeca, thanks a lot for your help with this! There are some new strings we added in rc3 that need to be translated too.

I uploaded new translation files just now. So please merge this branch with master and fix the merge conflicts.

**Comment by jnsebgosselin** [comment]
Ok thanks. I will take care of this.

**Comment by jnsebgosselin** [comment]
@goanpeca There was a lot of conflicts in the file. I just realized that the script you use to add Google translation seemed to have messed up a little bit the line wrapping of most of the content of the po file. 

Is this something that we need to worry about?

**Comment by jnsebgosselin** [comment]
For example:

image

The line declaration where the strings are found in the Spyder codebase are also now all on one line, which caused a lot of conflicts when I merged this.

image

**Comment by goanpeca** [comment]
>Is this something that we need to worry about?

Please check were the original string was and the translation to see if it is found.

>The line declaration where the strings are found in the Spyder codebase are also now all on one line, which caused a lot of conflicts when I merged this.

I think that is not an issue.

Please check

**Comment by jnsebgosselin** [comment]
Spyder French doesn't start on commit 0132f6ea36b481863af45e0688ff9eb7ad68dfe6 (Add auto translations from google).

I get the following error:

```python
Traceback (most recent call last):
  File "C:\Users\User\spyder\spyder\app\mainwindow.py", line 3716, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\User\spyder\spyder\app\mainwindow.py", line 3557, in run_spyder
    main.setup()
  File "C:\Users\User\spyder\spyder\app\mainwindow.py", line 924, in setup
    self.completions = CompletionManager(self)
  File "C:\Users\User\spyder\spyder\plugins\completion\plugin.py", line 91, in __init__
    plugin_client = Plugin(self.main)
  File "C:\Users\User\spyder\spyder\plugins\completion\kite\plugin.py", line 49, in __init__
    self.installation_thread)
  File "C:\Users\User\spyder\spyder\plugins\completion\kite\widgets\install.py", line 287, in __init__
    self._integration_widget = KiteIntegrationInfo(self)
  File "C:\Users\User\spyder\spyder\plugins\completion\kite\widgets\install.py", line 75, in __init__
    .format(kite_url=KITE_SPYDER_URL))
ValueError: unmatched '{' in format spec
```

**Comment by jnsebgosselin** [comment]
> > The line declaration where the strings are found in the Spyder codebase are also now all on one line, which caused a lot of conflicts when I merged this.
> 
> I think that is not an issue.
> 
> Please check

This is working

image

**Comment by goanpeca** [comment]
Ok this is good! I will try to fix that then!

**Comment by jnsebgosselin** [comment]
> 
> 
> > Is this something that we need to worry about?
> 
> Please check were the original string was and the translation to see if it is found.

This is also working.

However, it adds a *lot* of unnecessary changes to the PR and will cause some headaches when merging. I had to resolve over 100 conflicts to make this work.

image

**Comment by jnsebgosselin** [comment]
ooooook @goanpeca. The line wrapping issues are not caused by your script. It's an option in PoEdit that needs to be unchecked.

image

**Comment by jnsebgosselin** [comment]
Ah wonderful, now that I've fixed the line wrapping thing, I only have 8 conflicts to fix! :D

I wish I had found that out yesterday before fixing all those conflicts XD

**Comment by goanpeca** [comment]
>Ah wonderful, now that I've fixed the line wrapping thing, I only have 8 conflicts to fix! :D
>I wish I had found that out yesterday before fixing all those conflicts XD

😆

**Comment by goanpeca** [comment]
We will give crowdin a Try for 4.1 (send you an invite)

**Comment by jnsebgosselin** [comment]
> 
> 
> We will give crowdin a Try for 4.1 (send you an invite)

Ok, I will check that out, after I'm done with the revision for 4.0

**Comment by ccordoba12** [comment]
Sorry for the hassle but this needs a new merge with master. I needed to update our translations again to fix issue #10884.

**Comment by jnsebgosselin** [comment]
@ccordoba12 Ok, the french translation is mostly completed here. I will try to go over it one last time tonight if I have the time.

I've fixed a lot of errors, but there is more remaining. From now on, I will use the french version of Spyder so that I can fix them along the way.

**Comment by goanpeca** [comment]
>I've fixed a lot of errors, but there is more remaining. From now on, I will use the french version of Spyder so that I can fix them along the way.

Awesome :-)

**Comment by ccordoba12** [comment]
@goanpeca, @jnsebgosselin, how close are you from finishing this one?

**Comment by jnsebgosselin** [comment]
For my part, I think this is ready. I have translated/revised all the new strings and corrected a bunch of old ones.

There is surely some errors remaining, but I think I can correct them in another PR. As I said, I will start working with Spyder in French so that I can correct them along the way as I'm working.

Maybe @goanpeca will want to do a final revision though.

**Comment by goanpeca** [comment]
>Maybe @goanpeca will want to do a final revision though.

I fully trust you as a native :-p, I would probably write sfranish anyway 😆

**Pull request merged**
