### PR TITLE
PR: Handle execute command response (LSP)

### LINKED ISSUE #16343: No handler for workspace/executeCommand request
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [x] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [x] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [x] Tried the other applicable steps from the Troubleshooting Guide
* [x] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When a ``workspace/executeCommand`` request is made to the completions plugin, the spyder doesn't handle the response from the executed command. This unexpected behavior happens due to the fact that there is no handler method defined for this request as the spyder's LSP completion plugin architecture requires.

### What steps reproduce the problem?

1.  Make a ``workspace/executeCommand`` request with a command to the completion plugin to a language server that sends the response from the command;
2. Spyder ignores the response.

### What is the expected output? What do you see instead?

It is expected that the spyder allows catching the response for the executed command as specified by the [Language Server Protocol](https://microsoft.github.io/language-server-protocol/specifications/specification-current/):

> The arguments are typically specified when a command is returned from the server to the client. Example requests that return a command are textDocument/codeAction or textDocument/codeLens.  <br><br>*Response*:  <br>* result: ``any`` | ``null``  <br>* error: code and message set in case an exception happens during the request. 

## Versions

* Spyder version: 5.1.1 None
* Python version: 3.8.11 64-bit
* Qt version: 5.12.10
* PyQt5 version: 5.12.3
* Operating System: Windows 10

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0              :  1.4.0 (OK)
chardet >=2.0.0                   :  4.0.0 (OK)
cloudpickle >=0.5.0               :  1.6.0 (OK)
cookiecutter >=1.6.0              :  1.7.3 (OK)
diff_match_patch >=20181111       :  20200713 (OK)
intervaltree >=3.0.2              :  3.1.0 (OK)
IPython >=7.6.0                   :  7.27.0 (OK)
jedi >=0.17.2;<0.19.0             :  0.18.0 (OK)
jsonschema >=3.2.0                :  3.2.0 (OK)
keyring >=17.0.0                  :  23.1.0 (OK)
nbconvert >=4.0                   :  6.1.0 (OK)
numpydoc >=0.6.0                  :  1.1.0 (OK)
paramiko >=2.4.0                  :  2.7.2 (OK)
parso >=0.7.0;<0.9.0              :  0.8.2 (OK)
pexpect >=4.4.0                   :  4.8.0 (OK)
pickleshare >=0.4                 :  0.7.5 (OK)
psutil >=5.3                      :  5.8.0 (OK)
pygments >=2.0                    :  2.10.0 (OK)
pylint >=2.5.0                    :  2.10.2 (OK)
pyls_spyder >=0.4.0               :  0.4.0 (OK)
pylsp >=1.2.1;<1.3.0              :  1.2.1 (OK)
pylsp_black >=1.0.0               :  None (OK)
qdarkstyle =3.0.2                 :  3.0.2 (OK)
qstylizer >=0.1.10                :  0.2.1 (OK)
qtawesome >=1.0.2                 :  1.0.3 (OK)
qtconsole >=5.1.0                 :  5.1.1 (OK)
qtpy >=1.5.0                      :  1.10.0 (OK)
rtree >=0.9.7                     :  0.9.7 (OK)
setuptools >=49.6.0               :  52.0.0.post20210125 (OK)
sphinx >=0.6.6                    :  4.1.2 (OK)
spyder_kernels >=2.1.0;<2.2.0     :  2.1.0 (OK)
textdistance >=4.2.0              :  4.2.1 (OK)
three_merge >=0.1.1               :  0.1.1 (OK)
watchdog >=0.10.3                 :  2.1.5 (OK)
zmq >=17                          :  22.2.1 (OK)

# Optional:
cython >=0.21                     :  None (OK)
matplotlib >=2.0.0                :  None (OK)
numpy >=1.7                       :  1.21.2 (OK)
pandas >=1.1.1                    :  1.3.2 (OK)
scipy >=0.17.0                    :  1.7.1 (OK)
sympy >=0.7.3                     :  1.8 (OK)

# Spyder plugins:
spyder_f_language.plugin 1.4.dev0 :  1.4.dev (OK)

```

### PR DESCRIPTION
**Pull request by hlouzada**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Added a *method* that handles the response of the ``workspace/executeCommand`` request to the *WorkspaceProvider*.
This is required due to the current architecture of the *Completions* plugin's *lsp provider* that requires handlers to properly receive the response of the requests.

### Issue(s) Resolved

Fixes #16343

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @hlouzada

### CODE REVIEW

**Comment by ccordoba12** [comment]
Hey @hlouzada, thanks for your contribution! Do you need this for a language server you're integrating with Spyder?

I say it because other than handling the response (which I think is fine), you're not doing anything else with it.

**Comment by hlouzada** [comment]
> Hey @hlouzada, thanks for your contribution! Do you need this for a language server you're integrating with Spyder?

Yes, but this can be also used by other languages servers.

> I say it because other than handling the response (which I think is fine), you're not doing anything else with it.

The spyder needs to handle the response as is, and the specific command handler (in my specific case, in a plugin using completion API), can do something with the request's result. The main reason for doing this is that the response can be anything so any specific use for the response must be individually implemented for each *command* (as specified by the LSP).

A use case can be a request with a command that formats the document in a specific way, and the result is the ``TextEdit`` for these changes. As well as, a command that calculates the time complexity of a code segment and its result is a string with the running time.

**Comment by ccordoba12** [comment]
Ok, thanks for the explanation @hlouzada.

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @hlouzada!

**Pull request merged**
