### PR TITLE
PR: Show error when trying to sort dataframe with duplicate columns

### LINKED ISSUE #5225: Error when trying to sort dataframe with duplicate columns
## Description

**What steps will reproduce the problem?**

1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

  File "/usr/local/lib/python3.5/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 562, in sortByColumn
    if not self.model().sort(index, sort_order):
  File "/usr/local/lib/python3.5/dist-packages/spyder/widgets/variableexplorer/dataframeeditor.py", line 312, in sort
    kind='mergesort')
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/frame.py", line 3196, in sort_values
    str(by))
ValueError: Cannot sort by duplicate column cv1

## Version and main components

* Spyder Version: 3.2.3 
* Python Version: 3.5.3
* Qt Versions: 5.7.1, PyQt5 5.7 on Linux

## Dependencies
```
pyflakes >=0.6.0 :  1.6.0 (OK)
pycodestyle >=2.3:  2.3.1 (OK)
pygments >=2.0   :  2.2.0 (OK)
pandas >=0.13.1  :  0.20.3 (OK)
numpy >=1.7      :  1.13.1 (OK)
sphinx >=0.6.6   :  1.6.3 (OK)
rope >=0.9.4     :  0.10.7 (OK)
jedi >=0.9.0     :  0.10.2 (OK)
psutil >=0.3     :  5.3.1 (OK)
nbconvert >=4.0  :  5.3.1 (OK)
sympy >=0.7.3    :  None (NOK)
cython >=0.21    :  None (NOK)
qtconsole >=4.2.0:  4.3.1 (OK)
IPython >=4.0    :  6.1.0 (OK)
pylint >=0.25    :  1.7.2 (OK)

```

### PR DESCRIPTION
**Pull request by Prikers**
Fixes #5225 

----

This is a proposal to fix #5225.
It simply adds an error message with the pandas' error displayed. Is that what you meant @ccordoba12?

### CODE REVIEW

**Comment by ccordoba12** [comment]
Yep, it is. Thanks @Prikers!

**Comment by Prikers** [comment]
Travis-CI is failing on the Variable Explorer widget tests but it does not seem related to this PR. It passed just before I removed some whitespaces to make pep8 happy. Should I restart the build?

**Comment by jnsebgosselin** [comment]
@Prikers It failed with PYQT4. It happens, often I might say. I restarted the test.

**Comment by Prikers** [comment]
Thanks @jnsebgosselin. I saw it was only on PyQt4 but I did not know it was a known/recurrent issue 😄

**Comment by jnsebgosselin** [comment]
It is still failing. It's not the common segfault error that sometimes happens. There seems to be actually an error that is raised in one of the test: `ERROR at setup of test_texteditor`

**Comment by ccordoba12** [comment]
I skipped the test in PyQt4 and Python 3, and now our tests pass without problems.

I really don't know what was the cause of the failure, sorry :-/

**Pull request merged**
