### PR TITLE
Add some indentation tests

### PR DESCRIPTION
**Pull request by Nodd**
I added some tests to check for the indentation function.

It is motivated by a new but that was introduced lately, the cursor is placed at the same column as an opened parenthesis even if no text is entered after the parenthesis (this is my last commented test case).

## TODO:
- [ ] Add more non-regressiàon tests
- [ ] Correct failed tests
- [ ] Add new failed tests and correct them

This way of testing works but isn't practical at all, it would be really better to use libs like pytest for this. Those tests don't need the QApplication to run, only its creation so it doesn't have the same problem other tests have. Some hints were stated in #2268

### CODE REVIEW

**Comment by goanpeca** [comment]
@nodd, dont we need a QApplication to start a widget?

**Comment by Nodd** [comment]
You need a QApplication but not necessarily .exec_().

**Comment by Nodd** [comment]
I understood the difference I had between my tests and the editor, I forgot to set the language. Now I can focus on fixing the tests.
When #3120 I'll integrate these tests with pytest.

**Comment by goanpeca** [comment]
Sure, I am waiting on @ccordoba12 on doing some cleaning of the travis scripts to get the tests going :-p,

**Comment by Nodd** [comment]
@goanpeca I updated the PR to use pytest (without pytest-qt, it was not necessary in my case). Any comments ?

**Comment by ccordoba12** [comment]
@Nodd, merging with master should fix the failures on Travis and AppVeyor :-)

Is there anything else to do here?

**Comment by Nodd** [comment]
I should add the case from #3214 as KnownFail.
I should also try to fix the failing tests, but that can be left for another PR (by someone else maybe :watch: )

**Comment by ccordoba12** [comment]
Please add the failure of #3214 so I can merge it :-)

You can add other tests later.

**Comment by Nodd** [comment]
Here you go !
The problem is not about adding test case, it's about fixing the failing ones !

**Comment by Nodd** [comment]
I rebased on master, I hope it'l fix the failing tests.

**Comment by ccordoba12** [comment]
@Nodd, is this one ready to be merged?

**Comment by Nodd** [comment]
@ccordoba12 Yes, I merge it.

**Pull request merged**
