### PR TITLE
Comment grouping and comment style

### LINKED ISSUE #11980: faulty outline on method organization
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

Say you have a class with many methods, and the methods can be 'grouped' by adding
`### Marker` at the beginning of a line between 2 'sections' of methods, then the `outline` is picking up on this, however the indentation (and the distinguishing between method and function) is not correct.

### What steps reproduce the problem?

copy the following code fragment in a file, and look at what 'Outline' is making of it 

```
# -*- coding: utf-8 -*-

class demo(object):
    
    def __init__(self):
        pass
    
    def foo(self):
        pass
    
### bars 1
    def bar10(self):
        pass
    
    def bar11(self):
        pass
    
    def bar12(self):
        pass

### bars 2
    def bar20(self):
        pass
    
    def bar21(self):
        pass
    
    def bar22(self):
        pass
```

### What is the expected output? What do you see instead?

`# bars 1` and `# bars2` should reside one level deeper, under their `demo` class, and recognized as methods instead of functions now.

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.1
* Python version: Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
* IPython version: IPython 7.13.0 (but probably not related)
* Qt version: 5.9.6
* PyQt version: PYQT_CONFIGURATION = {'sip_flags': '-t WS_WIN -t Qt_5_9_6'}
* Operating System name/version: WIN10 (probably the same on OSX and Linux, but not tested by me yet)

### Dependencies

```

# Mandatory:
atomicwrites >=1.2.0           :  1.3.0 (OK)
chardet >=2.0.0                :  3.0.4 (OK)
cloudpickle >=0.5.0            :  1.3.0 (OK)
diff_match_patch >=20181111    :  20181111 (OK)
intervaltree                   :  None (OK)
IPython >=4.0                  :  7.13.0 (OK)
jedi =0.15.2                   :  0.15.2 (OK)
nbconvert >=4.0                :  5.6.1 (OK)
numpydoc >=0.6.0               :  0.9.2 (OK)
paramiko >=2.4.0               :  2.7.1 (OK)
parso =0.5.2                   :  0.5.2 (OK)
pexpect >=4.4.0                :  4.8.0 (OK)
pickleshare >=0.4              :  0.7.5 (OK)
psutil >=5.3                   :  5.7.0 (OK)
pygments >=2.0                 :  2.6.1 (OK)
pylint >=0.25                  :  2.4.4 (OK)
pyls >=0.31.9;<0.32.0          :  0.31.9 (OK)
qdarkstyle >=2.8               :  2.8 (OK)
qtawesome >=0.5.7              :  0.7.0 (OK)
qtconsole >=4.6.0              :  4.7.1 (OK)
qtpy >=1.5.0                   :  1.9.0 (OK)
rtree >=0.8.3                  :  0.9.3 (OK)
sphinx >=0.6.6                 :  2.4.0 (OK)
spyder_kernels >=1.9.0;<1.10.0 :  1.9.0 (OK)
watchdog                       :  None (OK)
zmq >=17                       :  18.1.1 (OK)

# Optional:
cython >=0.21                  :  0.29.15 (OK)
matplotlib >=2.0.0             :  3.1.3 (OK)
numpy >=1.7                    :  1.18.1 (OK)
pandas >=0.13.1                :  1.0.2 (OK)
scipy >=0.17.0                 :  1.4.1 (OK)
sympy >=0.7.3                  :  1.5.1 (OK)

```

### PR DESCRIPTION
**Pull request by bcolsen**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

I still need a test, but if it looks like it does what we want(I like it) then I'll write a test.

This code relies on the indentation level of the comments in the code giving the user maximum flexibility to fold in whatever(perhaps horrible) way they want. It seem to be inline with how @nerohmot was using them in #11980.

I didn't fix the function definitions inside an if/for/try statement block. That will added a lot additional recursions to the cb0baed2ode and other than in a `if __name__  = "__main__"` block results is strange code.

### Edited for commit `b0baed2`:
I changed the start of a fold to `# <<` or `# region` (I personally don't like this but it's what other editors (vscode/pycharm use) and the end of a fold region to be the end of the parent block or an end fold comment `# >>` or `# endregion`.

Header comment `# ##` will not fold the code but will still be grouped according to it's indentation level because otherwise we would have to guess and reading users minds is too tricky ;-)

Non style compliant symbols are also accepted like `###`, `#<<` or `#region`
#### Before:
image
#### After:
image

### Issue(s) Resolved

Fixes #11980

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: bcolsen

### CODE REVIEW

**Comment by bcolsen** [comment]
Now the only `# ##>`  comments fold all though `# >>` might be better.

 `# ##` comments to not fold at the same code level (it will still fold if the it is at a lower indent level) but they cancel a fold at a previous same level.

Current behaviour:

image

**Comment by bcolsen** [comment]
I changed the start of a fold to `# <<` or `# region` (I personally don't like this but it's what other editors (vscode/pycharm use) and the end of a fold region to be the end of the parent block or an end fold comment `# >>` or `# endregion`.

Header comment `# ##` will not fold the code but will still be grouped according to it's indentation level because otherwise we would have to guess and reading users minds is too tricky ;-)

Non style compliant symbols are also accepted like `###`, `#<<` or `#region`

image

**Comment by bcolsen** [comment]
This is ready for some user testing for thoughts and general ideas.  If we are happy I can make the tests.

@nerohmot Would this cover the use case that you originally had in mind?

**Comment by nerohmot** [comment]
@bcolsen, yes, I think this would do the trick of "organizing" :-) 
Hope the tests can be un-blocked, so I can give it a "real world" test drive :-)

**Comment by bcolsen** [comment]
I have added test and they are passing!

This is ready for review.

**Comment by bcolsen** [comment]
/binder

Some testing code:

```python
# << Section 1
class demo1(object):
    def __init__(self):
        pass

    def foo(self):
        pass

    # << bars 1
    def bar10(self):
        pass

    def bar11(self):
        pass

    def bar12(self):
        # >> comm 0
        pass

    # << bars 2
    def bar20(self):
        # << comm 1
        # ## comm 10
        pass

    def bar21(self):
        # ## comm 1
        pass

    def bar22(self):
        pass
# >>

class demo2(object):
    # ## init
    def __init__(self):
        pass

    def foo(self):
        pass

    # >>> bars 1

    def bar10(self):
        pass

    if True:
        def bar11(self):
            pass

    def bar12(self):
        pass


# region Section 3
class demo3(object):
    # #### bars 001
    def __init__(self):
        pass

    def foo(self):
        pass
# endregion

# ## Main
x = 3
# << Main 1
y = 4
    # << Sub 1
message = "Hello"
mess = "World"
ex = "!"
# endregion

class demo4(object):
    def __init__(self):
        pass

    def foo(self):
        pass
```

**Comment by ccordoba12** [comment]
This work needs to be redone in pyls-spyder to work with the LSP architecture used by recent versions of the Outline explorer.

So, I'm afraid we'll have to close it. Sorry for not reviewing it on time @bcolsen.

**Pull request closed without merging**
