### PR TITLE
PR: Avoid comments to generate pep8 warnings - bis

### LINKED ISSUE #1785: Spyder comments (Ctrl+1 and Ctrl+4) generate pep8 warnings
_From [bentkows...@gmail.com](https://code.google.com/u/114523486630528179401/) on 2014-04-07T06:47:08Z_

Spyder Version:  2.2.5
Python Version:  2.7.5+
Qt Version    :  4.8.4, PyQt4 (API v2) 4.10.3 on Linux
IPython >=0.13  :  0.13.2 (OK)
matplotlib >=1.0:  1.2.1 (OK)
pep8 >=0.6      :  1.5.4 (OK)
pyflakes >=0.5.0:  0.8.1 (OK)
pylint >=0.25   :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2.2 (OK)
sympy >=0.7.0   :  0.7.3 (OK) 

* What steps will reproduce the problem?

  1. I updated Spyder2 and the whole bundle around it (rope, pylint, sphinx etc.) with PIP -U [...]
  2. It seems there as some update to PEP8 guidelines regarding commenting with #  (PEP8 E265).
  3. Say, I have commented a line:

         #somefunc(arg1, arg2)

     I get a warning "E265 block comment should start with '# '". Adding a space:

         # somefunc(arg1, arg2)

     removes the warning. Ctr+4 adds a line:

         #===================================

     at the beginning and end of the block commented out. This brings a warning as well.

* What is the expected output? What do you see instead?

  No false positive error message. 

* Please provide any additional information below

  Probably it's not a problem for people using software deposited in repos, but with time it will come up.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1785_

### PR DESCRIPTION
**Pull request by Ericvulpi**
Still attempts to fix #1785. 

Comment function :
Adds the comment string (# for Python) plus a space, after the indent, just before the text

Uncomment function :
Removes the comment string and removes one space if there is one after the comment string and if the indent length is not an even number std indent length (to avoid breaking code)

### CODE REVIEW

**Comment by Ericvulpi** [comment]
This follows previous PR : https://github.com/spyder-ide/spyder/pull/4651

I'm giving it another try, more to get some feedback than to provide final solution

I see 2 main choices that should be discussed (maybe depending on which version of Spyder is the target) :
- When "commenting" several lines, should the comment string be added at a single position (lost to the left among the selected lines) or at the indent of each line => second solution is the one implemented in this PR
- When "uncommenting", I've proposed a check on the indent length : if it's an even number of std indent length then no space is removed to avoid breaking code. This may have the following side effect, as far as I can see :
    - break asci logo
    - mess with some alignment of bracket when a function is too long to fit on one line and has been split on multiple lines

Also, any advice on how to write proper code or do pull request is welcome (i'm new at this :)

**Comment by ccordoba12** [comment]
@Ericvulpi, thanks for the extra effort. I'm leaving this for 3.2.1 because we're about to release 3.2 and (unfortunately) we don't have time to review your work.

**Comment by Ericvulpi** [comment]
No rush.
And as @bcolsen mentioned, this may have to wait for 4.0 if the solution still breaks some code

**Comment by ccordoba12** [comment]
@Ericvulpi, sorry, but @dalthviz is working on a new way to add comments to the Editor for Spyder 4 (in PR #3958) and he's going to solve #1785 as part of that effort.

**Comment by Ericvulpi** [comment]
No problem, PR #3958 looks like a more thorough solution

**Pull request closed without merging**
