### PR TITLE
PR: Update python-lsp-server subrepo and change CI Python versions

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* Currently the `python-lsp-server` subrepo is pointing to the v1.6.0 tag (was needed to prevent errors on the CI tests while also being able to build the conda-based installers). This makes the subrepo point again to the develop branch
* Change the Python version we use to test to Python 3.8 and Python 3.10

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by dalthviz** [comment]
Note: Needs changes on the `python-lsp-server` (be sure the `autoimport` plugin is actually disabled by default)

**Comment by ccordoba12** [comment]
@dalthviz, please sync our subrepo with my branch on this PR: https://github.com/python-lsp/python-lsp-server/pull/300. I verified locally that it fixes our tests here.

**Comment by ccordoba12** [comment]
Thanks for this @dalthviz! This is almost ready, except for the new problem of `test_no_update_outline`, which is consistently failing on Linux and Python 3.10 using pip packages. What do you propose to do about it?

**Comment by dalthviz** [comment]
Will check what is happening. Also seems like an error is being triggered somewhere beside the test failing due to the assert?- https://github.com/spyder-ide/spyder/actions/runs/3449114058/jobs/5785585197#step:15:6037 :

```
Traceback (most recent call last):
  File "/home/runner/work/spyder/spyder/spyder/api/widgets/auxiliary_widgets.py", line 57, in changeEvent
    self.sig_window_state_changed.emit(self.windowState())
TypeError: SpyderWindowWidget.sig_window_state_changed[WindowStates].emit(): argument 1 has unexpected type 'WindowStates'
```

**Comment by ccordoba12** [comment]
> Also seems like an error is being triggered somewhere beside the test failing due to the assert?

Ok, I think that could be the source of the test failure at the end. You can try to change the signature of `sig_window_state_changed` from

```python
sig_window_state_changed = Signal(Qt.WindowStates)
```

to

```python
sig_window_state_changed = Signal(object)
```

and the same for the Slot argument of `OutlineExplorerWidget._handle_undocked_window_state`. That should solve the problem.

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz for your work on this!

Note: The failures in our tests are only related to the conda-based installers.

**Pull request merged**
