### PR TITLE
PR: Fix editor tab switcher vertical position

### LINKED ISSUE #9506: The vertical position of the tab switcher dialog window is wrong in Spyder 4
## Problem Description

The position of the tab switcher dialog window is wrong in Spyder 4 because we need to take into account the height of the filename `QLablel` that was added at the top of the editor in a previous PR.

image

I was about to fix this as part of PR #9452 but then I decided it would be better to do this in another PR, so that the issue and fix does not go unnoticed for the sake of properly documenting things.

## Versions

* Spyder version: Spyder 4.0.0.dev0 (Commit: 64a9d6ad9) 
* Python version: Python 3.7.1 64-bit
* Qt version: Qt 5.9.6
* PyQt version: PyQt5 5.9.2
* Operating System name/version: Windows 10

### PR DESCRIPTION
**Pull request by jnsebgosselin**
## Description of Changes

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

image

### Issue(s) Resolved

Fixes #9506

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Jean-Sébastien Gosselin

### CODE REVIEW

**Comment by goanpeca** [comment]
@jnsebgosselin I do not use this switcher much. How do I trigger it :-| ?

**Comment by jnsebgosselin** [comment]
> 
> 
> @jnsebgosselin I do not use this switcher much. How do I trigger it :-| ?

It is with the shortcut `Ctrl + Tab`.

**Comment by jnsebgosselin** [comment]
Mmmh, I just realized that PR https://github.com/spyder-ide/spyder/pull/9400 didn't take into account the file switcher... so that is probably why it is not working for you on macOS because the file switcher triggering is short-circuited by the changes made in PR #9400.

**Comment by jnsebgosselin** [comment]
I think the `go_to_next_file` and `go_to_previous_file` you added [here](https://github.com/spyder-ide/spyder/pull/9400/files#diff-36807ba8f009af540ab6f82a4dc31802R2759) should call the fileswitcher instead of circling through the tabs.

Circling through the editor tabs is handled by the `cycle to next file` and `cycle to previous file` shortcut, whose default key combination are `Ctrl + PgDwn` and `Ctrl + PgUp`. 

image

**Comment by goanpeca** [comment]
>It is with the shortcut Ctrl + Tab.

Ahh that is why. Actually I am not sure how the page up page down is triggered on OSX :-p 

Hmm I will need to open an issue to fix that!

**Comment by goanpeca** [comment]
@jnsebgosselin could you do me a favor an open an issue about this problem and assign it to me? We can discuss there what we can do

I can work on it in a couple of hours.

In the meantime I think this PR is fine :-)

**Comment by jnsebgosselin** [comment]
> 
> 
> @jnsebgosselin could you do me a favor an open an issue about this problem and assign it to me? We can discuss there what we can do
> 
> I can work on it in a couple of hours.
> 
> In the meantime I think this PR is fine :-)

Yes, no problem.

**Comment by ccordoba12** [comment]
Thanks a lot @jnsebgosselin!

**Pull request merged**
