### PR TITLE
Add 3,5,6,7,8 spaces as options in indentation of the Editor

### LINKED ISSUE #1730: 2 or 4 spaces, not 3
_From [oliver.k...@gmail.com](https://code.google.com/u/115151849108725075229/) on 2014-02-18T01:48:07Z_

Spyder Version:  2.2.5
Python Version:  2.7.5
Qt Version    :  4.8.4, PyQt4 (API v2) 4.9.6 on Windows
pyflakes >=0.5.0:  0.7.3 (OK)
pep8 >=0.6      :  1.4.6 (OK)
IPython >=0.13  :  1.1.0 (OK)
rope >=0.9.2    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.2 (OK)
matplotlib >=1.0:  1.3.1 (OK)
sympy >=0.7.0   :  0.7.4 (OK)
pylint >=0.25   :  1.0.0 (OK)

in
preferences -> editor -> advanced settings -> indentation characters
there are the options to use tabs, 2 spaces or 4 spaces.
However, I use 3 spaces in all of my sources (not only python). 
Even if the whole python community agree that only 2 or 4 spaces are valid, I still use 3.
There are so many versions: 2,3,4 spaces, tabs, and one need to configure
the editors all the time to use 3 spaces, and reformat code all the time,
etc etc etc. So I decided: I USE 3 SPACES.
Simple but tragic, that makes spyder COMPLETELY USELESS for me.
I like spyder a lot and will still use it, but in combiation with
a different editor or a workaround.
I would highly appreciate to have the option to use 3 spaces.
If this issue was already discussed, then sorry for the duplication, i didn't find an issue about three spaces.

_Original issue: http://code.google.com/p/spyderlib/issues/detail?id=1730_

### PR DESCRIPTION
**Pull request by goanpeca**
Fixes #1730 

---

# Screenshot
image

### CODE REVIEW

**Comment by Nodd** [comment]
Hi, I'm mister nitpick !

I'd use a qspinbox for this instead of a combobox.
If you want to keep a qcombobox i'd put them in reverse order (but with tabs still at the end).

**Comment by goanpeca** [comment]
hey mr nitpick long time no see :)

keeping the combo, will change the order

:+1:

**Comment by goanpeca** [comment]
@Nodd done

image

**Comment by Nodd** [comment]
Maybe "Tabulation" or "Tabulations" instead of "tab" ?

**Comment by goanpeca** [comment]
Sure M. Nitpick, will make the change

**Comment by goanpeca** [comment]
image

**Comment by goanpeca** [comment]
@ccordoba12 , @Nodd ?

**Comment by ccordoba12** [comment]
LGTM :+1:, merging!

**Pull request merged**
