### PR TITLE
PR: Announce that Anaconda stopped funding Spyder and add Open Collective URL

### PR DESCRIPTION
**Pull request by goanpeca**
Add open collective urls and links on README

https://opencollective.com/spyder

---

To see how it looks [click this](https://github.com/goanpeca/spyder/blob/516e6f0573e07a758c9cca03959a275d4d578cf2/README.md)

screen shot 2017-11-20 at 17 05 57

screen shot 2017-11-20 at 17 06 04

### CODE REVIEW

**Comment by ccordoba12** [comment]
I'm going to rework this a little bit before merging. I hope to do it tomorrow.

**Comment by ccordoba12** [comment]
@goanpeca, what do you think about the text I added?

Please also take a look at

https://github.com/spyder-ide/spyder/wiki/Anaconda-stopped-funding-Spyder

**Comment by goanpeca** [comment]
@ccordoba12 looks good, feel free to merge :-)

**Comment by ccordoba12** [comment]
It seems Appveyor is having problems because there are several bulds queued since yesterday, so I'm merging this one without waiting for it.

**Pull request merged**
