### PR TITLE
PR: Add Wrap lines checkbox to source menu

### LINKED ISSUE #7997: Include toggable "Wrap lines" checkbox in Source menu for easy access
## Problem Description

Currently, "Wrap lines" is buried deep within the Preferences and only available from there, whereas it is nearly always accessible from the toolbar (or at very least a top-level menu) in most other editors/IDEs, and I toggle it quite frequently in such editors, second only to the "Show blank spaces", which is currently menu-bound. Therefore, both certainly deserve a place on the "Source" (or "Edit") toolbar, as the latter are ideal for functions frequently toggled on or off and where observing the status is helpful.

### PR DESCRIPTION
**Pull request by arteagac**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Implemented checkbox for "Wrap lines" in the Source menu. I tested it and this properly synchronizes with the Editor Preferences.
image

### Issue(s) Resolved

Fixes #7997

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
arteagac

### CODE REVIEW

**Comment by maurerle** [comment]
It would be very cool to merge this?
Should I readd that commit and create a PR to merge it into 5.x

I would also add the short cut `Alt+Z` to the action as it is quite common?

**Comment by dalthviz** [comment]
Thanks for your interest in this @maurerle ! What do you think @arteagac (and sorry for such a late response 😅 )? Is it okay if @maurerle takes the commit here, and moves it to 5.x? Or would you like to work on this again and update it to be based on the 5.x branch? Let us know!

**Comment by arteagac** [comment]
Hi @dalthviz and @maurerle,  

Sure, @maurerle can go ahead and take the commit and move it to 5.x.

**Comment by ccordoba12** [comment]
Thanks @arteagac for being ok with that! I'm going to close your pull request in favor of #20090 then.

**Pull request closed without merging**
