### PR TITLE
PR: Change size of splash screen

### LINKED ISSUE #16006: Splash screen can take a lot of space in low resolution screens
When starting Spyder in my laptop screen (1366 x 768) the splash looks like this (kind of big):

image

However in my secondary screen (1920×1080) the splash looks better:

image

### PR DESCRIPTION
**Pull request by juanis2112**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Changed the size of the splash screen because it looks too big.

This is the size it is with this PR but I will post some other options in the comments.

Screenshot 2021-07-14 at 12 12 34 PM

### Issue(s) Resolved

Fixes #16006

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by juanis2112** [comment]
This is the original size for me:
Screenshot 2021-07-14 at 12 13 19 PM

At 550:
Screenshot 2021-07-14 at 12 12 53 PM

At 500: (My preferred option and the one that this PR sets)
Screenshot 2021-07-14 at 12 12 34 PM

At 450: 
Screenshot 2021-07-14 at 12 12 11 PM

At 400:
Screenshot 2021-07-14 at 12 11 50 PM



@ccordoba12 @steff456 @isabela-pf @andfoy and @dalthviz please let me know which one you prefer.

**Comment by isabela-pf** [comment]
I vote for 500! Thank you for working on this @juanis2112!

**Comment by steff456** [comment]
I like 500 and 550, the 400s options look a little bit too small

**Comment by ccordoba12** [comment]
500 looks good to me too, thanks @juanis2112!

Since we all agree on that size and is the one set on this PR, let's merge it.

**Review by ccordoba12 — APPROVED** [review]
Thanks @juanis2112!

**Pull request merged**
