### PR TITLE
PR: Add regex to highlight decorators

### LINKED ISSUE #3608: Syntax highlighting of decorators
In many code editors and in the ipython qtconsole decorators are highlighted with a specific color but not in spyder editor. It would be nice if they were.

### PR DESCRIPTION
**Pull request by rlaverde**
Fixes #3608

---

I fixed it in a really simple way, I reused instance decorator, is that ok? or should I add a new color theme color for decorators?

### CODE REVIEW

**Comment by goanpeca** [comment]
What does pygments call decorators? does it give it a different meaning/name?

**Comment by ccordoba12** [comment]
@rlaverde, could you post a screenshot?

@goanpeca, we don't use for Python files. We have our highlighter for them :-)

**Comment by rlaverde** [comment]
@ccordoba12 
decorartors

**Comment by goanpeca** [comment]
@ccordoba12 and @Nodd are you ok with this?

**Comment by ccordoba12** [comment]
Yep, merging. Thanks @rlaverde!

**Pull request merged**
