### PR TITLE
PR: Split Editor module

### PR DESCRIPTION
**Pull request by rlaverde**
~This is not ready~, I move editor files and create a new structure without the sourcecode folder (avoiding it to be really nested)

```
editor/
├── api
│   └── __init__.py
│   ├── decoration.py           (was sourcecode/api/decoration.py)
│   ├── folding.py              (was sourcecode/api/folding.py)
├── __init__.py
├── plugin.py                   (was plugins/editor.py)
├── tests
│   └── __init__.py
├── utils
│   ├── __init__.py
│   ├── codeeditor.py           (was utils/sourcecode.py)   xxx don't move
│   ├── decoration.py           (was sourcecode/utils/decoration.py)
│   ├── editor.py               (was utils/editor.py)
│   ├── folding.py              (was sourcecode/folding.py)
│   ├── kill_ring.py            (was sourcecode/kill_ring.py)
│   ├── languages.py            (part of utils/sourcecode.py)
│   ├── terminal.py             (was sourcecode/terminal.py)
│   └── tests
│       ├── __init__.py
│       └── test_codeeditor.py  (was utils/tests/test_sourcecode.py)    xxx don't move
└── widgets
    ├── base.py                 (was sourcecode/base.py)
    ├── codeeditor.py           (was sourcecode/codeeditor.py)
    ├── editor.py               (was widgets/editor.py)
    ├── __init__.py
    └── tests
        ├── __init__.py
        ├── test_autocolon.py   (was sourcecode/tests/test_autocolon.py)
        ├── test_autoindent.py  (was sourcecode/tests/test_autoident.py)
        ├── test_editor.py      (was widgets/tests/test_editor.py)
        ├── test_folding.py     (was sourcecode/tests/test_folding.py)
        └── test_panels.py      (was sourcecode/tests/test_panels.py)
```

@ccordoba12 @goanpeca What do you think of this new structure?

### CODE REVIEW

**Comment by ccordoba12** [comment]
Wow! You went after our white whale!! Good luck with this ;-)

**Comment by goanpeca** [comment]
@rlaverde I really like the structure :-)

**Comment by goanpeca** [comment]
@rlaverde why these tests

│   └── tests
│       ├── __init__.py
│       └── test_codeeditor.py   (was utils/tests/test_sourcecode.py)

inside utils?

**Comment by rlaverde** [comment]
@goanpeca these test are for `utils/codeeditor.py` should I rename them? maybe `test_utils_codeeditor.py`

**Comment by goanpeca** [comment]
@rlaverde yes, so it is clearer :-)

**Comment by rlaverde** [comment]
> these test are for utils/codeeditor.py should I rename them? maybe test_utils_codeeditor.py

I didn't move these files, they are general utilities for working with files and filenames (used also in the console), I just move a part that is related to the languages to editor/utils/languages.py

**Comment by rlaverde** [comment]
Also I think that the white whale es ready 😄, waiting the tests to pass 🙈

**Comment by rlaverde** [comment]
The errors mention my pep8speaks are caused for `# analysis:ignore`
```
from spyder.plugins.editor.widgets.base import TextEditBaseWidget  # analysis:ignore
from spyder.plugins.editor.widgets.codeeditor import Printer # analysis:ignore
```
how should I fix them?

**Comment by ccordoba12** [comment]
> how should I fix them?

Don't worry about them. The Editor still needs further splitting, as we talked about before.

Please focus on make our tests to pass.

**Comment by ccordoba12** [comment]
I didn't think I'd see this day ;-)

Great work @rlaverde! Merging away.

**Pull request merged**
