### PR TITLE
PR: Pressing Enter in the "Replace with" entry of Find/Replace replaces the currently selected text

### LINKED ISSUE #4010: Pressing Enter in the "Replace with" entry of Find/Replace should replace the currently selected text
This comes from this SO post:

http://stackoverflow.com/questions/35662566/how-do-you-use-replace-in-spyder

and here it is an screenshot of the problem

seleccion_001

So when a user has focused the *Replace with* filed and press `Enter`, we should replace *parsed* with *foo* and move to the next occurrence. Currently pressing `Enter` does nothing.

This is very similar to the way *Find* works, i.e. when you press `Enter`, we automatically move users to the next occurrence.

@andfoy, this one is for you :-)

### PR DESCRIPTION
**Pull request by andfoy**
Fixes #4010

### CODE REVIEW

**Comment by ccordoba12** [comment]
@andfoy, great work! But from now on I'm going to ask you all to add tests for all PRs you do.

So please add a test for this one :-)

**Comment by ccordoba12** [comment]
@andfoy, this needs a merge with `3.x` to solve it. Please do it so I can merge it :-)

**Comment by andfoy** [comment]
@ccordoba12 This PR is ready to go!

**Comment by ccordoba12** [comment]
The failure in Travis is unrelated to this work. I fixed it already in PR #4201.

**Pull request merged**
