### PR TITLE
PR: Migrate RunConfig to Plugin with new API

### LINKED ISSUE #13099: Migrate RunConfig to Plugin with new API

### PR DESCRIPTION
**Pull request by goanpeca**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [x] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #13099

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @goanpeca

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @dalthviz, this one is ready for QA testing. Thanks!

**Comment by goanpeca** [comment]
This is ready for review @ccordoba12

**Comment by goanpeca** [comment]
@dalthviz and @ccordoba12 this one is ready for review.

**Comment by goanpeca** [comment]
>one quick question so I understand things better: why do you think it's important to create a plugin for this config page? Since the plugin API for Run is not used anywhere in this case, it seems unnecessary to me.

Again the idea of generalizing all these things is to be able to have a single way to handle all the things. All plugins are loaded in the same way no matter what. This also applies to config pages.

This "run" plugin is a plugin that depends on the Editor AND the Console so that it can do things, so I think having it as a separate plugin (besides simplifying code in preferences/ and in main window) opens the door to handle in a cleaner way how the console interacts with the editor to run stuff. (like the current implicit dependency the ipyconsole shellwidget has on the editor). This is the plugin that should be in charge of all the Run actions (not the editor). Also the core plugin would override the run action (that would be handled by this plugin). All these things will become apparent with the editor migration.

That is why all the "global preferences" should become a plugin.

**Comment by ccordoba12** [comment]
Ok, thanks for the clarification.

**Pull request merged**
