### PR TITLE
PR: Bump Jedi upper bound to `<0.20.0`

### LINKED ISSUE #21296: Update Jedi dependency upper bound
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [-] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [-] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [-] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
spyder currently sets an upper bound on its jedi dependency of 0.19.0, in several files - `binder/environment.yml`, `external-deps/python-lsp-server/pyproject.toml`, `requirements/main.yml`, `setup.py` and `spyder/dependencies.py` at least. Upstream lsp, which is where this dependency comes from I believe, [bumped it to 0.20.0 recently](https://github.com/python-lsp/python-lsp-server/pull/416) with the note that there "don't seem to be any breaking changes". spyder should probably inherit this bump so it can be used with jedi 0.19.

### What steps reproduce the problem?

1. Try and install spyder with jedi 0.19.

### What is the expected output? What do you see instead?

It fails, but it should be allowed.

## Versions

This is present in current git head and all supported branches.

### PR DESCRIPTION
**Pull request by musicinmybrain**
## Description of Changes

Followed https://github.com/spyder-ide/spyder/issues/21296#issuecomment-1699382983; but since `python-lsp-server` was already updated to at least 1.8.0 in https://github.com/spyder-ide/spyder/commit/2beb128b6c71eb4d4556a2f79cb385a7352d16f9 and https://github.com/spyder-ide/spyder/commit/285ef8a385c29ca7874027f57ab9dc44cbffae97, and since 1.8.0 supports `jedi` 0.19.x, the only necessary change was adjusting the version bounds on `jedi` in Spyder.

* [ ] Wrote at least one-line docstrings (for any new functions) **N/A**
* [ ] Added unit test(s) covering the changes (if testable) **N/A**

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/)) **N/A**

### Issue(s) Resolved

Fixes #21296

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: `musicinmybrain`/Benjamin A. Beasley

### CODE REVIEW

**Comment by musicinmybrain** [comment]
Ugh, how did I pull the wrong subrepo? Fixing and force-pushing…

**Comment by musicinmybrain** [comment]
Fixed. The `5.x` branch was already updated for `python-lsp-server` 1.8.0, so I only needed to change the version bounds for `jedi`.

**Comment by musicinmybrain** [comment]
Hmm, `test_dependencies_for_spyder_dialog_in_sync` is failing. I’m not sure what I missed.

**Comment by ccordoba12** [comment]
Thanks for your help with this @musicinmybrain! You said:

> Hmm, `test_dependencies_for_spyder_dialog_in_sync` is failing. I’m not sure what I missed.

You also need to bump the constraint in `spyder/dependencies.py`

**Comment by musicinmybrain** [comment]
> You also need to bump the Jedi constraint in `spyder/dependencies.py`

Thanks! Amended.

**Review by ccordoba12 — APPROVED** [review]
Thanks @musicinmybrain!

**Pull request merged**
