### PR TITLE
PR: Escape hyphen from update instructions for spyder-kernels (IPython Console)

### LINKED ISSUE #17425: Small bugs in kernel update error screen
Issue is raised in #17353 with updating spyder-kernel in custom environments.

Putting aside the fact that Anaconda doesn't have that version of spyder-kernels yet... there are still two small bugs here on the error screen. 

Firstly, if the required version is 2.2.1, then the error should say 2.2.1 needs installing (not 2.2). Installing 2.2 as suggested still results in the same error which coud be confusing for the user.

Secondly the dash in ``conda install spyder‑kernels=2.2`` doesn't copy in to a Windows terminal correctly (displays a question mark inside a box). A font issue?

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

Use `&hyphen;` instead of plain `-` to prevent copy-pasting an incorrect command following kernel instructions to update

Pinging @jnsebgosselin just in case to check if another approach for this was found

### Issue(s) Resolved

Fixes #17425 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by jnsebgosselin** [comment]
This seems like a very good solution! Thank you for the fix, this is going to make my life easier.

**Comment by jnsebgosselin** [comment]
I've tested locally and it does not solve the problem on my setup unfortunately. The hyphen still gets replaced by a non-breaking hypen when copied to the clipboard.

**Comment by jnsebgosselin** [comment]
http://www.mauvecloud.net/charsets/CharCodeFinder.html
image

**Comment by dalthviz** [comment]
Seems like now the code is the correct one, no? I think for hyphen the code is `&#x2010` while for non-breaking-hyphen is `&#x2011` However, even with that the command is not working for you then 🤔 ?

Something else I was thinking about is that probably we need to add the `-c conda-forge` part since the anaconda default channel goes just up to spyder-kernels 2.2.1

**Comment by jnsebgosselin** [comment]
Oh yeah, you are right. `&#x2010`  is the code for the normal hyphen. It is still not working in the Windows cmd though. I still need to replace the `&#x2010` (0x2010) with a normal `-` (0x2d).

image

**Comment by dalthviz** [comment]
Could you try using `&#45;`?

**Comment by jnsebgosselin** [comment]
Yes, it works with `&#45;`.

I thought it was either the `pre` or `tt` environment that was causing the issue, but it seems it is something else because I tried without these and the hyphen was still replaced by a non-breaking hyphen. Anyway, it does not matter since you seem to have found a good working solution, thanks!

**Comment by jnsebgosselin** [comment]
image

**Comment by dalthviz** [comment]
Awesome! Thanks for the help checking this @jnsebgosselin !

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz and @jnsebgosselin!

**Pull request merged**
