### PR TITLE
Fix DeprecationWarning: explicitly cast to an integer

### LINKED ISSUE #14535: DeprecationWarning: implicit conversion to integers in spyder/widgets/colors.py:78
When running the test suite, I received the following warning:

```python
  <<<PACKAGEDIR>>>/spyder/widgets/colors.py:78: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
    self.lineedit.setMinimumWidth(fm.width(color.name()) * 1.2)
```

Changing this to say
```python
    self.lineedit.setMinimumWidth(int(fm.width(color.name()) * 1.2))
```
should be sufficient to fix this.

### PR DESCRIPTION
**Pull request by juliangilbey**
## Description of Changes

Apply the suggested patch in https://github.com/spyder-ide/spyder/issues/14535

### Issue(s) Resolved

Fixes #14535 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

juliangilbey

### CODE REVIEW

**Comment by ccordoba12** [comment]
This PR is against our `master` branch, so it'd only available in Spyder 5. Are you om with that?

**Comment by juliangilbey** [comment]
It depends how long it will be before 5.0 is released!  Or more seriously, could you not just cherry-pick this tiny patch back to the version 4 branch as well?  Or do I need to submit two pull requests, one against 4.x and one against master?  BTW, the same applies to PR https://github.com/spyder-ide/spyder/pull/14543

**Comment by ccordoba12** [comment]
> Or do I need to submit two pull requests, one against 4.x and one against master?

There's no need of that. You can make your current branch derive from our `4.x` one (instead of `master`), with the following commands:

    git checkout 4.x
    git checkout int-deprecation-patch
    git rebase --onto 4.x master int-deprecation-patch
    git push -f origin int-deprecation-patch

After this PR is merged, we'll merge it to `master` too.

**Comment by juliangilbey** [comment]
Thanks for the instructions @ccordoba12 - I've now rebased onto 4.x as requested.
Best wishes!

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @juliangilbey!

**Pull request merged**
