### PR TITLE
PR: Fix tests due to Pylint 2.14.0 and some test stalling the CI or falling due to leak validations

### LINKED ISSUE #18175: Pylint 2.14.0 code analysis won't work on miniconda conda-forge install on Windows
### What steps will reproduce the problem?

After installing spyder on a enviroment using miniconda and conda-forge channel, the code analysis won't work. It gives the following message: 

---------------------------
Erro
---------------------------
Traceback (most recent call last):
  File "C:\Users\artur\miniconda3\envs\std_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\artur\miniconda3\envs\std_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\__init__.py", line 22, in run_pylint
    from pylint.lint import Run as PylintRun
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\lint\__init__.py", line 19, in <module>
    from pylint.config.exceptions import ArgumentPreprocessingError
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\config\__init__.py", line 27, in <module>
    from pylint.config.environment_variable import PYLINTRC
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\config\environment_variable.py", line 11, in <module>
    PYLINTRC = find_pylintrc()
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\config\find_default_config_files.py", line 90, in find_pylintrc
    for config_file in find_default_config_files():
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\config\find_default_config_files.py", line 66, in find_default_config_files
    user_home = Path.home()
  File "C:\Users\artur\miniconda3\envs\std_env\lib\pathlib.py", line 1143, in home
    return cls(cls()._flavour.gethomedir(None))
  File "C:\Users\artur\miniconda3\envs\std_env\lib\pathlib.py", line 276, in gethomedir
    raise RuntimeError("Can't determine home directory")
RuntimeError: Can't determine home directory

---------------------------
OK   
---------------------------

### Traceback
```python-traceback
pylint error:

Traceback (most recent call last):
  File "C:\Users\artur\miniconda3\envs\std_env\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\artur\miniconda3\envs\std_env\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\__main__.py", line 10, in <module>
    pylint.run_pylint()
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\__init__.py", line 22, in run_pylint
    from pylint.lint import Run as PylintRun
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\lint\__init__.py", line 19, in <module>
    from pylint.config.exceptions import ArgumentPreprocessingError
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\config\__init__.py", line 27, in <module>
    from pylint.config.environment_variable import PYLINTRC
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\config\environment_variable.py", line 11, in <module>
    PYLINTRC = find_pylintrc()
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\config\find_default_config_files.py", line 90, in find_pylintrc
    for config_file in find_default_config_files():
  File "C:\Users\artur\miniconda3\envs\std_env\lib\site-packages\pylint\config\find_default_config_files.py", line 66, in find_default_config_files
    user_home = Path.home()
  File "C:\Users\artur\miniconda3\envs\std_env\lib\pathlib.py", line 1143, in home
    return cls(cls()._flavour.gethomedir(None))
  File "C:\Users\artur\miniconda3\envs\std_env\lib\pathlib.py", line 276, in gethomedir
    raise RuntimeError("Can't determine home directory")
RuntimeError: Can't determine home directory

```

## Versions

* Spyder version: 5.3.1 
* Python version: 3.9.13
* Qt version: 5.15.2
* PyQt5 version: 5.15.4
* Operating System: Windows 10

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.0 (OK)
chardet >=2.0.0               :  4.0.0 (OK)
cloudpickle >=0.5.0           :  2.1.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.0.2 (OK)
IPython >=7.31.1;<8.0.0       :  7.33.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.1 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.6.0 (OK)
keyring >=17.0.0              :  23.5.1 (OK)
nbconvert >=4.0               :  6.5.0 (OK)
numpydoc >=0.6.0              :  1.3.1 (OK)
paramiko >=2.4.0              :  2.11.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.1 (OK)
pygments >=2.0                :  2.12.0 (OK)
pylint >=2.5.0                :  2.14.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.4.1;<1.5.0          :  1.4.1 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.1.10            :  0.2.1 (OK)
qtawesome >=1.0.2             :  1.1.1 (OK)
qtconsole >=5.3.0;<5.4.0      :  5.3.0 (OK)
qtpy >=2.1.0                  :  2.1.0 (OK)
rtree >=0.9.7                 :  1.0.0 (OK)
setuptools >=49.6.0           :  62.3.2 (OK)
sphinx >=0.6.6                :  5.0.1 (OK)
spyder_kernels >=2.3.1;<2.4.0 :  2.3.1 (OK)
textdistance >=4.2.0          :  4.2.2 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.1.8 (OK)
zmq >=22.1.0                  :  23.1.0 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  None (NOK)
numpy >=1.7                   :  1.22.4 (OK)
pandas >=1.1.1                :  1.4.2 (OK)
scipy >=0.17.0                :  None (NOK)
sympy >=0.7.3                 :  None (NOK)
```

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

Test suite revision for failing tests due to:
* Pylint 2.14.0:  Fixes #18175 
* ~jupyter_client 7.3.2: #18174~ 
* ~`openpyxl` and `defusedxml` cause `nbconvert` NOK error on MacOS installers tests (probably `nconvert` is not importable after the addition of those dependencies into the installer build?): #18278~
* Some other failures (leak validations and tests stalling)

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by dalthviz** [comment]
@mrclary do you have any idea why the test for the MacOS installer is failing? It says that is missing nbconvert but chceking the build environment from the action seems like nbconvert 6.5.0 is there 🤔

**Comment by dalthviz** [comment]
Note: Seems like for some reason the errors on the MacOS installer tests started when `openpyxl` and `defusedxml` were added at #18121

**Comment by ccordoba12** [comment]
That's strange because the error has to do with Spyder not being able to find nbconvert.

**Comment by dalthviz** [comment]
Note: Failing Windows installer build and pip related packages installation due to: https://status.python.org/incidents/lgpr13fy71bk

**Review by ccordoba12 — APPROVED** [review]
Thanks a lot @dalthviz for your hard work on this!

**Pull request merged**
