### PR TITLE
PR: Fix height of "Run > Configuration per file" dialog by adding a scrollbar to it

### LINKED ISSUE #13531: Run configuration per file dialog doesn't display complete
### Issue Report Checklist

* [ ] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [ ] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [ ] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [ ] Tried basic troubleshooting (if a bug/error)
    * [ ] Restarted Spyder
    * [ ] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [ ] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description
Run configuration per file dialog is too tall for my screen and I can't scroll down to see the complete information on it.

Screen Shot 2020-08-14 at 1 20 45 AM

I suggest fixing the max height of the dialog to the height of the Spyder's window and adding a scroll bar when it's not fully displayed. 

(It might be a MacOS problem)

### What steps reproduce the problem?

1. 
2. 
3. 

### Paste Traceback/Error Below (if applicable)

```python-traceback

PASTE TRACEBACK HERE

```

## Versions

* Spyder version: 4.1.4
* Python version: 
* Qt version: 
* PyQt version: 
* Operating System name/version: macOS Catalina 

### Dependencies

```
PASTE DEPENDENCIES HERE
```

### PR DESCRIPTION
**Pull request by steff456**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Add a scrollbar to run dialogs so it can be fully visible in small screens

image

image

### Issue(s) Resolved

Fixes #13531 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Steff456

### CODE REVIEW

**Comment by ccordoba12** [comment]
@steff456, please merge with `4.x` to get the latest fixes to our tests.

**Comment by ccordoba12** [comment]
@steff456, I'm not seeing any scrollbar in the `Configuration per file` dialog:

Selección_055

How did you obtain the screenshot above? I mean, it looks a bit different than the dialog because it doesn't have the dropdown on top.

**Comment by steff456** [comment]
The dialog I modified is the one that has as title `run settings for xxxx.py`. This is the one that appears if you hit the run button on the main toolbar.

image

**Review by ccordoba12 — APPROVED** [review]
Thanks @steff456, great work!

**Pull request merged**
