### PR TITLE
PR: Fix shortcuts for several Run and Debugger actions

### LINKED ISSUE #21129: Spyder 6.0.0a1 - New line (ctrl-enter) in console runs cell instead
In Spyder 5, I would use ctrl-enter to create a new line in the console (for multiline code).  However, I can't seem to figure out how to do that in Spyder 6.  Instead, Ctrl-Enter seems to be running a cell of code (the editor keyboard shortcut).

### PR DESCRIPTION
**Pull request by ccordoba12**
## Description of Changes

- Make shortcuts for `Run cell`, `Run cell and advance` and other Run actions, as well as `next`, `continue` and other Debugger actions, local to the Editor again.
- Add a new `SpyderShortcutsMixin` to `spyder.api.shortcuts` and use it to simplify the way shortcuts are registered for widgets. That's necessary when a widget is not a direct child of the one where an action with shortcut was created (e.g. the `EditorStack` with respect to `EditorMainWidget`).
- Add `Ctrl+Shift+D` as the new shortcut to go to the Debugger (and remove that shortcut for the Online Help).
- Change context for array builder shortcuts from `array_builder` to `editor`. That follows the convention already used in the IPython console.
- Fix width of the Debugger breakpoints table at startup (I noticed this problem while testing these changes).
- Remove old code to register shortcuts for widgets.

### Note

There's still a limitation (also present in Spyder 5) with shortcuts registered for widgets: they are not updated after a change in Preferences. I tried to fix that as part of this PR but it requires several changes to the way shortcut options are tracked and notified, so I prefer to leave it for a follow-up one.

### Issue(s) Resolved

Fixes #21129.

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @ccordoba12

### CODE REVIEW

**Comment by ccordoba12** [comment]
@dalthviz, this is ready for review.

**Comment by ccordoba12** [comment]
> Gave this an initial check and seems like there are missing changes to cover shortcuts for plugins like Code Analysis and Profiler?

That's right, I didn't check those shortcuts. But they should be working now, so please test again.

**Comment by dalthviz** [comment]
Note: Could this be related with https://github.com/spyder-ide/spyder/issues/14403 ?

**Comment by ccordoba12** [comment]
Yep, that's mostly the same problem. But in the case of the Editor, the thing is that `EditorStack` and `CodeEditor` are several layers below `EditorMainWidget`, so it's not easy to propagate shortcuts declared on the latter to the first.

And we can't create `Run cell` in `EditorStack`, for instance, because we can have any number of `EditorStack`s. So, the action corresponding to `Run cell` won't be unique.

It's a tricky problem that we have to think better. For now I think what I did is just a stopgap solution.

**Review by dalthviz — APPROVED** [review]
Thanks @ccordoba12 ! Checked locally and seems like things are working, so this LGTM :+1:

**Pull request merged**
