### PR TITLE
Windows taskbar handling

### PR DESCRIPTION
**Pull request by cjrh**
Please see the commit messages.

In short: this PR provides two things when running from *bootstrap* on Windows:

0. Spyder will no longer be grouped with all other python.exe processes on the task bar, i.e. it will appear as its own taskbar entry
0. Spyder will have an application icon. (See the commit message for the details.)

This branch is migrated over from my bitbucket fork. I still need to test that it still works.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for looking at this one. Does your work also solve issue #1983?

**Comment by Twizzledrizzle** [comment]
Hmm, _SetCurrentProcessExplicitAppUserModelID made my spyder crash.

SetCurrentProcessExplicitAppUserModelID however works.

The other commit regarding the icon worked flawlessly

**Comment by cjrh** [comment]
I had a quick look, and I have no idea why I put that underscore in there! Baffling.  Anyway, I'll fix it.  Thanks for taking a look 👍

**Comment by Twizzledrizzle** [comment]
You are welcome! And thanks for your commits, having no icon was distracting :)

**Comment by cjrh** [comment]
I just checked Spyder 2.3.2 (distributed with Anaconda 2.1.0). There is no application icon showing on the running application.  So my icon commit will fix the release version as well. (I was unsure whether the release process added an icon with other resource files in a Windows-specific build process or something similar)

**Comment by TWAC** [comment]
AppUserModelID is already set in another place, perhaps you could modify that instead? (I think this patch will not work pre Windows 7, due to missing error handling)
https://github.com/spyder-ide/spyder/blob/v2.3.3/spyderlib/spyder.py#L454
https://github.com/spyder-ide/spyder/blob/v2.3.3/spyderlib/utils/windows.py#L42

The icon is working for me from bootstrap, with standalone Python 3.4.2 + PyQt4.
Could the problem be due to Anacondas broken SVG support on PyQt? https://github.com/ContinuumIO/anaconda-issues/issues/131

**Comment by cjrh** [comment]
@TWAC Good call on the existing code for `AppUserModelID`.  I did not see that.  The existing code doesn't seem to be working for me, I will figure out why.

I reckon you're also correct with the icon support problem in Anaconda. It seems to be a recurring issue with GUI toolkits: earlier today I had to use a `.gif` in a Tinter app as the application icon (the other choice was xpm...)

**Comment by ccordoba12** [comment]
Any updates on this one? Is this ready for review and merge?

**Comment by cjrh** [comment]
No I still need to do more work on this one.  @TWAC pointed out some stuff I need to check first regarding the setting of `AppUserModelID`. I will try to finish this up before the weekend.

**Comment by ccordoba12** [comment]
Great! Thanks for the update :-)

**Comment by Twizzledrizzle** [comment]
I have tried to look into this without success :(

cjrh have you gotten any further?

**Comment by cjrh** [comment]
@Twizzledrizzle If I understand you correctly from #2297, you are saying that when you run multiple instances of **Spyder**, they each create their own taskbar button, instead of all being grouped together?  I will test to see what this does on my Windows machine.

The reason I created this PR is that when running from `bootstrap.py`, Spyder kept getting grouped with my other **python** executables on the Windows taskbar.

**Comment by cjrh** [comment]
@TWAC I tested again, both with a brand new Python install, and in a venv. Everything seems to be working without my changes, although admittedly I am on a different machine than the one on which I created the PR.

@ccordoba12 I think we should abandon this PR. The task bar grouping thingy is already handled, and the icon thingy seems to be an anaconda packaging issue.

**Comment by goanpeca** [comment]
@ccordoba12 so are we killing this one?

**Pull request closed without merging**
