### PR TITLE
Added Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by manipuladordedados**

### CODE REVIEW

**Comment by ccordoba12** [comment]
@manipuladordedados this is great!! thanks a lot for this! However, if we decide to accept your contribution, you should remain available for each subsequent release from now on to update the translation strings.

Are you ok with that?

**Comment by ccordoba12** [comment]
The problem is none of the core developers speaks Portuguese, hence we'd need to rely on you to update the translation.

**Comment by goanpeca** [comment]
@ccordoba12, how does translation works? I saw some scripts in the repo, how are they used?

Could you make an entry on the wiki for this? Maybe we could add a dev Menu (to the right of the help menu) only available in bootstrap mode to handle this issues (and others)?

**Comment by ccordoba12** [comment]
You need an external program to do the translation (e.g. Poedit on Linux). The scripts just help to update and compile the translation strings, but they rely in some external code from Pierre's that I'd need to move to Spyder to make the process self-contained.

**Comment by manipuladordedados** [comment]
@ccordoba12 Thanks, I'm okay with that :)

**Comment by ccordoba12** [comment]
@manipuladordedados, really good to know! Please add yourself to the our AUTHORS file and then I'll merge :-)

**Comment by manipuladordedados** [comment]
@ccordoba12 Done!

**Comment by ccordoba12** [comment]
Ok, thanks a lot! I tested it on my end and it's working as expected :-)

It was not necessary to open another PR for AUTHORS, but it's fine.

**Pull request merged**
