### PR TITLE
PR: Fix KeyError on autosave

### LINKED ISSUE #11468: Another KeyError while autosaving
### What steps will reproduce the problem?

I have no idea; this only happens while I'm typing, seemingly at random. 

Also, there is a copy anaconda running and it will. not. stop. Task manager can't close it. Powershell in admin mode still doesn't have permission. I want to downgrade to a more stable version but I cannot without rebooting. 

### Traceback
```python-traceback
  File "C:\Users\joven\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 116, in do_autosave
    stack.autosave.autosave_all()
  File "C:\Users\joven\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 375, in autosave_all
    self.maybe_autosave(index)
  File "C:\Users\joven\Anaconda3\lib\site-packages\spyder\plugins\editor\utils\autosave.py", line 335, in maybe_autosave
    orig_hash = self.file_hashes[orig_filename]
KeyError: 'C:\\Users\\joven\\.spyder-py3\\autosave\\optpath.py'
```

## Versions

* Spyder version: 4.0.1 
* Python version: 3.6.5
* Qt version: 5.9.4
* PyQt5 version: 5.9.2
* Operating System: Windows 10

### Dependencies

```
atomicwrites >=1.2.0         :  1.3.0 (OK)
chardet >=2.0.0              :  3.0.4 (OK)
cloudpickle >=0.5.0          :  1.2.2 (OK)
diff_match_patch >=20181111  :  20181111 (OK)
intervaltree                 :  None (OK)
IPython >=4.0                :  7.8.0 (OK)
jedi =0.14.1                 :  0.14.1 (OK)
nbconvert >=4.0              :  5.6.0 (OK)
numpydoc >=0.6.0             :  0.9.1 (OK)
pexpect >=4.4.0              :  4.8.0 (OK)
pickleshare >=0.4            :  0.7.5 (OK)
psutil >=0.3                 :  5.6.3 (OK)
pygments >=2.0               :  2.4.2 (OK)
pylint >=0.25                :  2.4.2 (OK)
pyls >=0.31.2;<0.32.0        :  0.31.7 (OK)
zmq >=17                     :  18.1.0 (OK)
qdarkstyle >=2.7             :  2.8 (OK)
qtawesome >=0.5.7            :  0.6.0 (OK)
qtconsole >=4.6.0            :  4.6.0 (OK)
qtpy >=1.5.0                 :  1.9.0 (OK)
rtree >=0.8.3                :  0.9.3 (OK)
sphinx >=0.6.6               :  2.2.0 (OK)
spyder_kernels >=1.8.1;<2.0.0:  1.8.1 (OK)
watchdog                     :  None (OK)
cython >=0.21                :  None (NOK)
matplotlib >=2.0.0           :  None (NOK)
numpy >=1.7                  :  1.16.5 (OK)
pandas >=0.13.1              :  None (NOK)
scipy >=0.17.0               :  None (NOK)
sympy >=0.7.3                :  None (NOK)
```

### PR DESCRIPTION
**Pull request by jitseniesen**
## Description of Changes

Spyder's autosave system records the hash of the contents of every file which is opened or renamed in the editor, and uses this to decide whether to perform an autosave. According to the bug reports, sometimes (but rarely) a file is opened but no hash recorded, leading to a `KeyError` when autosaving. I have looked but cannot find out how and why this happens.

This PR handles the `KeyError` (more) gracefully by performing an autosave if the original hash is not recorded. This is inefficient because the autosave may not be needed and the autosave file may be the same as the original file. After the file is autosaved once, the hash of the autosave file is used and the file is only autosaved again if it differs, so it is not too inefficient. If Spyder is not quit cleanly, then the next time Spyder is used it will offer to restore the autosave file, even though it may be the same as the original file. All in all, it is better than raising the `KeyError`.

The PR also add a test and a module docstring giving an overview of the autosave system.

### Issue(s) Resolved

Fixes #11468 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Jitse Niesen

### CODE REVIEW

**Comment by jitseniesen** [comment]
The CI error is that test_conda_env_activation fails. The same happens in other PRs so it is very unlikely to be related to this PR.

**Comment by ccordoba12** [comment]
@jitseniesen, @dalthviz is working right now on trying to solve that problem.

**Comment by Rauleman** [comment]
I'm having this problem now, spyder freeze and then I have no option but to quit spyder. I came here because spyder offer me to submite an issue report, but after reading the troubleshooting Guide, here I am. I copy bellow what the internal console says. It seems that you already have a solution to this, but I don't know how to fix it. 
Thank you.

Spyder Internal Console

This console is used to report application
internal errors and to inspect Spyder
internals with the following commands:
  spy.app, spy.window, dir(spy)

Please don't use it to run your code

>>> Traceback (most recent call last):
  File "/home/raul/anaconda3/envs/dashenv/lib/python3.8/site-packages/spyder/plugins/editor/utils/autosave.py", line 116, in do_autosave
    stack.autosave.autosave_all()
  File "/home/raul/anaconda3/envs/dashenv/lib/python3.8/site-packages/spyder/plugins/editor/utils/autosave.py", line 375, in autosave_all
    self.maybe_autosave(index)
  File "/home/raul/anaconda3/envs/dashenv/lib/python3.8/site-packages/spyder/plugins/editor/utils/autosave.py", line 335, in maybe_autosave
    orig_hash = self.file_hashes[orig_filename]
KeyError: '/home/raul/.config/spyder-py3/autosave/Extraction_Tweet_v2.py'

**Comment by ccordoba12** [comment]
This error is already fixed and it'll be part of Spyder 4.1.0, to be released shortly.

**Comment by Rauleman** [comment]
Thank you for your quick answer, what can I do meanwhile?
Can I disable the autosave so it stop crashing?

**Comment by ccordoba12** [comment]
That's correct. That's what you need to do.

**Comment by Rauleman** [comment]
Thank you, I'm really enjoying the new spyder I love it and I was worry to have to go back to a previous version. Keep it up with your amazing work!

**Comment by ccordoba12** [comment]
Thanks for your kind words!

**Pull request merged**
