### PR TITLE
PR: Fix EOL for missed files

### PR DESCRIPTION
**Pull request by mrclary**
It seems that some files were missed in bdfe0b59 (#18691).

If I'm in error, please advise.

### CODE REVIEW

**Comment by impact27** [comment]
I only addressed py files in the spyder folder. Somes files here should not be changed, for example: `external-deps/qdarkstyle/docs/make.bat`

**Comment by ccordoba12** [comment]
I agree with @impact27: batch files should be left out of this. The rest looks good to me.

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary!

**Comment by impact27** [comment]
You should probably add the commit to [.git-blame-ignore-revs]. I wonder why the bat files are showing here, they should be excluded with .gitattributes file

**Comment by ccordoba12** [comment]
@mrclary, please rebase to use the changes to our test suite done in PR #18802.

**Comment by impact27** [comment]
Did you update the commit hash in .git-blame-ignore-revs after the rebase?

**Review by ccordoba12 — APPROVED** [review]
Thanks @mrclary!

**Comment by ccordoba12** [comment]
@impact27, all good?

**Comment by impact27** [comment]
Looks good to me!

**Pull request merged**
