### PR TITLE
PR: Asynchronous introspection for the Editor

### LINKED ISSUE #2407: very slow auto completion with pandas
Hi,
I'm using the latest version of spyder 2.3.4 and pandas 16.0 , both installed with conda. 
Python 3.4.3 64bits, Qt 4.8.6, PyQt4 (API v2) 4.11.3 on Linux

The auto completion works fine on ipython console but in script editor it is extremly slow. Here is an example

import pandas as pd

pd. #<-- this will work fine

df=pd.read_csv('myfile.csv') #<- this will work fine too

df. #<- this would freeze my laptop for about 5 seconds

I noticed that bug only with pandas package and on the editor (again, on ipython console it works fine).

Thank you

### LINKED ISSUE #2724: Editor very slow on Mac Yosemite and El Capitan
## Description

**What steps will reproduce the problem?**
When I try to edit any python file there is a noticeable delay for every keystroke. It's almost unusable. 
The same issue happens with the Anaconda Spyder and the executable downloaded from GitHub.
1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**

## Version and main components

* Spyder Version: 2.3.6 
* Python Version: 2.7.10
* Qt Versions:  4.8.6, PyQt4 (API v2) 4.11.3 on Darwin

## Optional dependencies
```
pyflakes >=0.5.0:  0.9.2 (OK)
pep8 >=0.6      :  1.6.2 (OK)
pygments >=1.6  :  2.0.2 (OK)
IPython >=1.0   :  4.0.0 (OK)
zmq >=2.1.11    :  14.7.0 (OK)
qtconsole >=4.0 :  4.0.1 (OK)
pandas >=0.13.1 :  0.16.2 (OK)
sphinx >=0.6.6  :  1.3.1 (OK)
psutil >=0.3    :  2.2.1 (OK)
rope >=0.9.2    :  0.9.4 (OK)
jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.4.3 (OK)
sympy >=0.7.3   :  0.7.6 (OK)
pylint >=0.25   :  None (NOK)

```

### PR DESCRIPTION
**Pull request by blink1073**
Fixes #2724
Fixes #2407 

----

Perform introspection in separate processes.

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks a lot for thiis!

Tests in AppVeyor are failing, but I don't understand why. They only stop after `run_test.bat`

**Comment by blink1073** [comment]
I can't get spyder to run at all in my Windows 7 VM anymore.  I really hate Windows...

**Comment by blink1073** [comment]
I was able to run the `run_test.bat` script with success on Windows 7.

**Comment by goanpeca** [comment]
Yeiii, @blink1073 is back :-)

Question: will this work enable calling jedi for any given environment? that is, for Spyder working under a given project environment (through conda) can we call jedi for that specific environment?

If not possible what would we need to do?

**Comment by blink1073** [comment]
Right now it uses `sys.executable` to start the process.  Where is the concept of the "current environment" set?  We need use that and get a signal when it changes, so we can restart the plugins in that environment.

**Comment by blink1073** [comment]
I also ran `modules_test.sh` on Windows 7 and that works in this branch.

**Comment by goanpeca** [comment]
@blink1073 could you adapt the code so that the class or function or whatever is called with a specific python interpreter?, and by default we use the `sys.executable` for now, while we get the projects env going?

**Comment by ccordoba12** [comment]
@goanpeca is right, we should use a parameter to define the python version used for completions, and use `sys.executable` by default right now.

@blink1073, I'll see what's happening on Windows :-)

**Comment by ccordoba12** [comment]
@blink1073, even better: could you comment `run_test.bat` in `appveyor.yml` and push here again?

Trying to automatically close the whole app has always been problematic on Windows (Python 2.7 tests always failed because of that) so I think we're going to need to skip that test for now.

**Comment by Nodd** [comment]
The python executaple should be the one defined in the preferences for the console, I think.

**Comment by goanpeca** [comment]
@Nodd how we connect the different information regarding the python executable is beyond the point, the idea is that the widget/plugin receives this as a parameter.

**Comment by blink1073** [comment]
The Appveyor build is timing out *after* already successfully running the new introspection code, so I really have no idea.

**Comment by ccordoba12** [comment]
True, I restarted the build three times and it never ends! Could you skip all tests in the introspection folder to see if `modules_test.bat` ends?

**Comment by blink1073** [comment]
Done.

**Comment by ccordoba12** [comment]
No luck either. It seems this is going to force us to disable `run_test.bat` and `modules_test.bat` on Windows (I hope only temporarily :-)

@blink1073, could you remove the last commit and comment those tests in appveyor.yml? In a later PR I'll try to restore them :-)

**Comment by ccordoba12** [comment]
On a different note, could you explain a how this new architecture works?

I see that now there are plugin servers and clients, but I didn't understand too well how they are started, and how they communicate to each other.

**Comment by ccordoba12** [comment]
After some interactive tests on my side, these are my findings:

1. Tests are passing when I run `python jedi_plugin.py`, etc.
2. However, I can't get completions, info or definitions on the Editor. When running on debug mode, I can see these messages (in case they are important):

    ```
    ...
    Introspection Plugin Loaded: rope
    Introspection Plugin Loaded: jedi
    Introspection Plugin Loaded: fallback
    ...
    finished rope False
    finished jedi False
    ...
    finished fallback False
    ...
    definition request
    sending rope
    sending jedi
    ```

    So it seems things are not working ok because plugins are not finished correctly.

**Comment by ccordoba12** [comment]
Sorry, I had to be more specific: if I run `python {jedi, rope, fallback}.py` I don't get any errors.

But I when I run `python plugin_client.py` I only get an `errored` message in the console, which (I think) shows that the client is not working for me.

**Comment by blink1073** [comment]
What is your setup @ccordoba12?
I'll write up the new architecture tomorrow and include it in the source code.

**Comment by ccordoba12** [comment]
I'm on Linux and PyQt4, using both Python 2.7 and 3.4.

**Comment by blink1073** [comment]
Should be fixed now.

**Comment by ccordoba12** [comment]
Sorry, still not working.

**Comment by blink1073** [comment]
I have no idea, I just tried it on Ubuntu 14.04, Anaconda Python 3.4.

**Comment by blink1073** [comment]
I added a README file.

**Comment by blink1073** [comment]
@ccordoba12, I made the port selection more robust, care to try again?

**Comment by ccordoba12** [comment]
* Sorry, still not working for me (but I really don't know why!).
* Good news is that AppVeyor tests are passing, yay!!
* However, there is a reproducible segfault in Python 3.5 and PyQt5 on Travis (i restarted the build 3 times to be sure). Please try to reproduce it locally and see if you can fix it.

**Comment by blink1073** [comment]
I installed PyQt5 from the spyder-ide channel, but I'm getting this error:

`This application failed to start because it could not find or load the Qt platform plugin "cocoa".`

**Comment by blink1073** [comment]
The last commit instruments the server, can you `python plugin_client.py` and post the resulting `plugin_server_jedi.log` file?

**Comment by ccordoba12** [comment]
I think that error is caused because you have PyQt4 and PyQt5 installed in the same env.

Please remove PyQt4 so that PyQt5 can start correctly.

**Comment by blink1073** [comment]
That worked, no segfaults.

**Comment by ccordoba12** [comment]
Where that file is saved? I can't find it :-)

**Comment by blink1073** [comment]
It should be in the `introspection` directory, assuming you run the code from that directory.

**Comment by blink1073** [comment]
If the file isn't being created at all that means it is dying before the class is even instantiated.

**Comment by ccordoba12** [comment]
I run the code from the root of my clone with

    PYTHONPATH=. python spyderlib/utils/introspection/plugin_client.py

but the file is not created there nor in introspection.

**Comment by blink1073** [comment]
Care to try again?

**Comment by ccordoba12** [comment]
Travis is not segfaulting anymore, but I'm seeing this error now when running the tests in `widgets/editor.py`

```python-traceback
Traceback (most recent call last):

  File "/home/travis/miniconda/lib/python3.5/site-packages/spyderlib/utils/introspection/plugin_client.py", line 115, in run

    conn, _addr = self.sock.accept()

  File "/home/travis/miniconda/lib/python3.5/socket.py", line 195, in accept

    fd, addr = self._accept()

OSError: [Errno 9] Bad file descriptor
```

PyQt5 and PY3.5 combo is the only one failing with this error.

**Comment by blink1073** [comment]
I tried running PyQt5 and Py3.5 in Ubuntu 14.04 and even in the main branch I get cascading Gtk errors and the app crashes.

**Comment by blink1073** [comment]
Actually the whole VM crashes.

**Comment by ccordoba12** [comment]
No luck either, and strace doesn't report reading nor opening `plugin_server_jedi.log`

Could this be happening because I'm running things without having Spyder installed (i.e. with `bootstrap.py`)? I mean, the server could be failing to find Spyder imports because of that :-)

**Comment by blink1073** [comment]
Oh, yes, definitely.

**Comment by ccordoba12** [comment]
Ok, give me a sec to test. In the meantime, please remove the Jedi 0.8.1 pin we have on our Travis scripts (I think in `run_test.sh` ;-)

Also, could you restore `run_test.bat` to see if it passes in AppVeyor?

**Comment by blink1073** [comment]
Okay, I'm working on a fix to the error you saw above as well.

**Comment by ccordoba12** [comment]
:+1: Super!

**Comment by blink1073** [comment]
Fingers crossed...

**Comment by blink1073** [comment]
Travis is happy again, but Appveyor hangs

**Comment by ccordoba12** [comment]
Ok, progress: I tested this with Spyder installed in a venv and I'm getting this when starting Spyder in debug mode:

```
Introspection Plugin Loaded: rope
Introspection Plugin Failed: jedi
[Errno 98] Address already in use
Introspection Plugin Failed: fallback
[Errno 98] Address already in use
```

----

And these are the results of `plugin_server.log`:

```
initialized logger
In main block
sys.argv: ['20128', 'jedi']
Creating server
jedi_plugin
<module 'spyderlib.utils.introspection.jedi_plugin' from '/usr/local/lib/python2.7/dist-packages/spyderlib/utils/introspection/jedi_plugin.pyc'>
<class 'spyderlib.utils.introspection.jedi_plugin.JediPlugin'>
<spyderlib.utils.introspection.jedi_plugin.JediPlugin object at 0x7fe9081c3510>
20128
initialized logger
In main block
sys.argv: ['20128', 'jedi']
Creating server
jedi_plugin
<module 'spyderlib.utils.introspection.jedi_plugin' from '/usr/local/lib/python2.7/dist-packages/spyderlib/utils/introspection/jedi_plugin.pyc'>
<class 'spyderlib.utils.introspection.jedi_plugin.JediPlugin'>
<spyderlib.utils.introspection.jedi_plugin.JediPlugin object at 0x7fe8fba98510>
20128
```

However, I don't have Jedi installed in `/usr/local/lib` but in the venv in `/home/carlos/.virtualenvs/`

----

Still no completions though :-s

**Comment by ccordoba12** [comment]
Yep, but now we have this error in appveyor:

```python-traceback
Traceback (most recent call last):
  File "C:\Python35_64\lib\site-packages\spyderlib\utils\introspection\plugin_client.py", line 115, in run
    conn, _addr = self.sock.accept()
  File "C:\Python35_64\lib\socket.py", line 195, in accept
    fd, addr = self._accept()
OSError: [WinError 10038] An operation was attempted on something that is not a socket
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Python35_64\lib\site-packages\spyderlib\utils\introspection\plugin_client.py", line 117, in run
    if e.args[0] in [errno.ECONNABORTED, errno.EBADFD]:
AttributeError: module 'errno' has no attribute 'EBADFD' 
```

**Comment by blink1073** [comment]
Ah, it looks like we need to pass in some environment variables.

**Comment by ccordoba12** [comment]
New error in appveyor:

```python-traceback
Traceback (most recent call last):
  File "C:\Python35_64\lib\site-packages\spyderlib\utils\introspection\plugin_client.py", line 115, in run
    conn, _addr = self.sock.accept()
  File "C:\Python35_64\lib\socket.py", line 195, in accept
    fd, addr = self._accept()
OSError: [WinError 10038] An operation was attempted on something that is not a socket
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "C:\Python35_64\lib\site-packages\spyderlib\utils\introspection\plugin_client.py", line 117, in run
    badfd = errno.WSAEBADFD if os.name == 'nt' else errno.EBADFD
AttributeError: module 'errno' has no attribute 'WSAEBADFD'
```

**Comment by blink1073** [comment]
I think we manually need to add to PATH based on the executable, basically the equivalent of `source activate`.

**Comment by ccordoba12** [comment]
Yep, I think so too, and also to make this work with `bootstrap` (which is my main way to start Spyder :-)

**Comment by blink1073** [comment]
I think the path setting will take care of that.

**Comment by ccordoba12** [comment]
The same error as before appeared again in Travis, and appveyor is now showing this

```python-traceback
Traceback (most recent call last):
  File "C:\Python35_64\lib\site-packages\spyderlib\utils\introspection\plugin_client.py", line 115, in run
    conn, _addr = self.sock.accept()
  File "C:\Python35_64\lib\socket.py", line 195, in accept
    fd, addr = self._accept()
OSError: [WinError 10038] An operation was attempted on something that is not a socket
```

and also hangs. I think you need to comment again that line in `run_test.bat`.

**Comment by blink1073** [comment]
I added a PYTHONPATH maker, so it may work for you now.  That's it for me today.

**Comment by blink1073** [comment]
Had to skip the full test in `run_test.sh`, but it is passing all CI and running from bootstrap now.

**Comment by davidhalter** [comment]
@blink1073 I found this randomly. Just FYI there's https://github.com/davidhalter/jedi/issues/385 which would introduce async Jedi calls.

**Comment by blink1073** [comment]
Hi David, yep, I had seen that thread but this allows us to be generic and even add plugins for other languages than Python.

**Comment by goanpeca** [comment]
@blink1073 could you explain on why we have

` IntrospectionManager -> Plugin Manager ->`

I have not look at the code in detail but just want to have clarity on those components. The naive initial thought was... cant they be merged into one? and if not, why not :-p?

**Comment by blink1073** [comment]
The only new layers are `PluginClient` and `PluginServer`, which I developed independently to make sure the protocol worked.  Technically, `PluginManager` and `PluginClient` *could* be merged, but I don't see a strong need.

**Comment by ccordoba12** [comment]
@blink1073, now I'm getting this error when running `plugin_client.py`:

```python-traceback
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'
Traceback (most recent call last):
  File "spyderlib/utils/introspection/plugin_client.py", line 150, in <module>
    plugin = PluginClient('jedi')
  File "spyderlib/utils/introspection/plugin_client.py", line 42, in __init__
    self.start()
  File "spyderlib/utils/introspection/plugin_client.py", line 58, in start
    site_path = subprocess.check_output(call % self.executable, shell=True)
  File "/usr/lib/python3.4/subprocess.py", line 616, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '/home/carlos/.virtualenvs/test-ipy3-stable/bin/python -c "import site; print(site.getsitepackages()[0])"' returned non-zero exit status 1
```

**Comment by blink1073** [comment]
Does that command work from your terminal?

**Comment by blink1073** [comment]
@ccordoba12, I updated it to ensure the *current* spyder is the one used in the `QProcess` (same as `bootstrap.py`), so it should fix the problem.

**Comment by blink1073** [comment]
I verified locally that it works with `bootstrap.py` when I don't have the development version installed.

**Comment by blink1073** [comment]
Now also uses `rope` or `jedi` from the current environment, so it does not need to be installed in the other environment.

**Comment by ccordoba12** [comment]
@blink1073, these are my findings after more testing:

1. Good news: after installing Spyder in a conda env, I have completions working on Python 3, yay!!

2. Rope and Jedi entries are missing from the *Dependencies* dialog. Could you fix that?

3. I can get completions for `numpy` when `numpy` is **not** installed in my env. For example, the following code is giving me completions:

    ```python
    import numpy as np
    np.<Tab>
    ```

    - I don't know where these completions are coming from (Jedi's cache?)
    - I must clarify that `numpy` doesn't appear as a completion when you do `import <Tab>`, but if you introduce the above code manually, you'll see the completions :-)

4. I'm getting an error when using the following code

    ```python
    import spyplugins
    spyplugins.ui.pylint.<Tab>
    ```

    The error is

    ```python-traceback
    Traceback (most recent call last):
    File "/home/carlos/miniconda/envs/test-async-py3/lib/python3.5/site-packages/spyderlib/utils/introspection/manager.py", line 143, in _handle_timeout
        self._finalize(self.pending)
    File "/home/carlos/miniconda/envs/test-async-py3/lib/python3.5/site-packages/spyderlib/utils/introspection/manager.py", line 132, in _finalize
        str(response['result'])[:100], delta))
    KeyError: 'result'
    ```

    And if you use PyQt5, the above code makes Spyder crash.

5. This PR is not working for me on Python 2. I'm getting these messages in a console, when I start Spyder in debug mode:

    ```
    Introspection Plugin Loaded: rope
    Introspection Plugin Failed: jedi
    [Errno 98] Address already in use
    Introspection Plugin Failed: fallback
    [Errno 98] Address already in use
    ```

    Even if I modify your code to load only one completion plugin (e.g. rope), Spyder still can't get any completions at all.

6. This is still not working for me with `python bootsrap.py`, but let's leave for another PR.

**Comment by ccordoba12** [comment]
Another issue: `import` completions are not working reliably. If you have `pandas` installed, sometimes I'm getting completions for it and other times I'm getting:

    import pa<Tab>
    import pass

This is probably caused because `import` completions are not working when `rope` is installed and `jedi` is not. Perhaps we should remove those completions for `rope`?

**Comment by ccordoba12** [comment]
Regarding my last comment, this is more precisely what I'm getting:

    import pa<Tab>
    import pass

----

    import pan<Tab>
    import pandas

----

    import p
    import pass
           pow
           print
           property

**Comment by ccordoba12** [comment]
Another problem is that if Spyder crashes, it can't close `plugin_server` correctly. So those process continue to run on the system, and new processes are opened once Spyder is started again.

So something needs to be devised to detect if previous `plugin_server`s are still running, and try to close them before opening new ones.

**Comment by blink1073** [comment]
- I addressed the Python 2.7 and the error.  
- I consider the `import pandas` a separate issue.  
- The external shells also use QProcess, are you not also seeing open processes for them after a crash?

**Comment by ccordoba12** [comment]
@blink1073:

1. Python 2 is working now, great job!!
2. My error **4.** above is fixed, again great job!
3. My error **3.** is still present, please fix it.
4. Tests are failing because of a circular import problem. You added rope and jedi dependencies to `introspection/manager.py`, which is fine.

    But when you run that file independently (as in `python introspection/manager.py`), it calls itself through this line

    ```python
    from spyderlib.utils.introspection.utils import CodeInfo
    ```

    which calls `manager.py` again in `introspection/__init__.py`, through this line

    ```python
    from .manager import IntrospectionManager
    ```

    This line registers dependencies first, and then when you reach dependencies registering again in `manager.py`, there's an error about dependencies already been registered.

----

Regarding your comments:

> I consider the import pandas and numpy a separate issue.

Ok, no problem, but please try to fix it as soon as this PR is merged.

> The external shells also use QProcess, are you not also seeing open processes for them after a crash?

Nop. I simulate a crash using `xkill` and all external consoles are closed correctly but not the completion servers. They remain around after the crash.

**Comment by blink1073** [comment]
I fixed the circular import and added kill handling for POSIX/nt, along with a self-destruct timeout for the plugin processes.

As I said about your error `3`, not for this PR.  I have no idea why bootstrap is not working for you, since I can't replicate it.

**Comment by ccordoba12** [comment]
Thanks a lot for your work on this @blink1073. `plugin_server`'s now are killed a little bit after Spyder dies, so that's great :-)

I didn't understand you correctly, but it's fine to leave the import issues for another PR.

**Comment by ccordoba12** [comment]
I did a quick review to the code, and everything seems fine. Let's merge this so you can start to work on the import issues :-)

**Comment by ccordoba12** [comment]
What's really interesting is that with this new architecture we could easily create plugins to other completion engines. For example, a plugin to an IPython kernel to get completions for variables assigned to numpy arrays, as we discussed previously.

**Comment by goanpeca** [comment]
@spyder-ide/core-developers

**Pull request merged**
