### PR TITLE
Don't use bootstrap on Travis

### PR DESCRIPTION
**Pull request by ccordoba12**
- The idea is **not** to use bootstrap to do our testing, but Spyder installed in a virtual or conda env.
- This way we will detect build and/or installation errors with Travis, as the ones I have to deal with in 2.3.5.

### CODE REVIEW

**Comment by goanpeca** [comment]
If I am not mistaken... I was doing that originally... but somehow was removed in one of the discussions when we first implemented travis.

**Comment by goanpeca** [comment]
why did you remove the test-travis flag??

**Comment by ccordoba12** [comment]
Because I want to call `spyder` (after installing it in a conda-env) instead of `bootstrap`.

The thing is we need to test Spyder as it's installed in `site-packages` and not with `bootstrap`, to avoid blunders as the ones I made in 2.3.5.

Right now I'm testing building and installation manually on each release and each operating system, but I'd like Travis (and later Appveyor) to help me with that :-)

**Comment by ccordoba12** [comment]
By the way, this is just the first of a series of commits, but I want to test them all in Travis to see if I'm doing things correctly :-)

**Comment by goanpeca** [comment]
ok

**Comment by ccordoba12** [comment]
Ok, I think this is ready. With this work we're now building, installing and testing Spyder with the help of `conda` and `conda-build`. I think this is much better than using `bootstrap` because (as I said) previous problems showed up during building and installation, and not with `bootstrap`.

Besides, these changes will also help us to start testing things with `pip`, once I add all our dependencies to `setup.py`.

@goanpeca or @blink1073, if you want to do a review, that'd be great. If not, I'll merge it tomorrow :-)

**Comment by goanpeca** [comment]
:+1:

**Comment by ccordoba12** [comment]
This is not ready yet. My changes will make all PRs with merge conflicts to fail on packaging! I'm developing a better solution now :-)

**Comment by ccordoba12** [comment]
Ok, I think this is finally ready :-)

**Pull request merged**
