### PR TITLE
Fix undefined `backends` when starting IPython kernel

### LINKED ISSUE #3206: Local variable 'backends' referenced before assignment when starting IPython kernel
## Description of your problem

**What steps will reproduce the problem?**

1. Install 3.0.0b3 as per instructions in #2724
2. Start spyder

**What is the expected output? What do you see instead?**

```python
Traceback (most recent call last):
  File "/users/nicolas/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 189, in <module>
    ipk_temp.config = kernel_config()
  File "/users/nicolas/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/start_ipython_kernel.py", line 95, in kernel_config
    if backends[backend_o] == 'inline':
UnboundLocalError: local variable 'backends' referenced before assignment
```

**Please provide any additional information below**

## Versions and main components

* Spyder Version: 3.0.0b3
* Python Version: Python 2.7.11 (anaconda)
* Operating system: OSX 10.11

## Dependencies

jedi >=0.8.1    :  0.9.0 (OK)
matplotlib >=1.0:  1.5.1 (OK)
nbconvert >=4.0 :  4.1.0 (OK)
numpy >=1.7     :  1.10.4 (OK)
pandas >=0.13.1 :  0.18.0 (OK)
pep8 >=0.6      :  1.7.0 (OK)
psutil >=0.3    :  4.1.0 (OK)
pyflakes >=0.5.0:  1.1.0 (OK)
pygments >=1.6  :  2.1.1 (OK)
pylint >=0.25   :  1.5.4 (OK)
qtconsole >=4.0 :  4.2.0 (OK)
rope >=0.9.4    :  0.9.4 (OK)
sphinx >=0.6.6  :  1.3.5 (OK)
sympy >=0.7.3   :  1.0 (OK)

### PR DESCRIPTION
**Pull request by Nodd**
Fixes  #3206.

I couldn't reproduce the error but the fix is quite obvious.

### CODE REVIEW

**Comment by Nodd** [comment]
@nbara @alcrene Could you check if it fixes your problem ?

**Comment by nbara** [comment]
@Nodd Is there a way to integrate your fix from within conda ?

**Comment by Nodd** [comment]
No, the fix is only in a branch in my repo. If you have git, you can clone https://github.com/Nodd/spyder.git, switch to the branch `backend` with  the command `git checkout backend`, then run the script `bootstrap.py`.

**Comment by alcrene** [comment]
Confirmed that the issue is
a) present in your `master` branch;
b) fixed in your `backend` branch.

**Comment by ccordoba12** [comment]
@Nodd, thanks a lot for your prompt response! This is the right fix when using external kernels.

I'll release new `beta3` conda packages that include this fix in a couple of hours. Thanks to @nbara and @alcrene for reporting and for confirming that this PR fixes the problem.

**Comment by ccordoba12** [comment]
Unfortunately, `pip` users will need to wait until I release `beta4`. That's because it's forbidden to upload new packages with the same version to PyPi.

**Comment by Nodd** [comment]
Can you create a version `beta3.1` ?

**Comment by ccordoba12** [comment]
I hope to release `beta4` next weekend :-)

**Pull request merged**
