### PR TITLE
PR: Update splash screen with new logo

### PR DESCRIPTION
**Pull request by isabela-pf**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))
Screen Shot 2021-07-08 at 10 35 43 AM

This replaces the current splash screen with the new logo and a design that follows its guidelines. It will also update the About to credit the photographer, but I am waiting on [#15762](https://github.com/spyder-ide/spyder/pull/15762) to avoid a conflict.

### Issue(s) Resolved

Fixes [spyder-ide/ux-improvements #49](https://github.com/spyder-ide/ux-improvements/issues/49)

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:
isabela-pf

### CODE REVIEW

**Review by steff456 — APPROVED** [review]
It is looking great!

**Comment by isabela-pf** [comment]
Meeting feedback: 
- [ ] Double check the SVG is loading properly
- [ ] Put additional about info on #15762 
- [ ] Make status text 14px

**Comment by ccordoba12** [comment]
Hey @isabela-pf, please merge with `5.x` to fix the failure in our tests, then this should be ready.

**Review by ccordoba12 — APPROVED** [review]
Fantastic work @isabela-pf, thanks!

**Pull request merged**
