### PR TITLE
PR: Add `--no-sandbox` argument for QtApplication

### LINKED ISSUE #20358: Help pane doesn't show anything in rich text mode
### Issue Report Checklist

* [X] Searched the [issues page](https://github.com/spyder-ide/spyder/issues?q=is%3Aissue) for similar reports
* [X] Read the relevant sections of the [Spyder Troubleshooting Guide](https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ) and followed its advice
* [X] Reproduced the issue after updating with ``conda update spyder`` (or ``pip``, if not using Anaconda)
* [ ] Could not reproduce inside ``jupyter qtconsole`` (if console-related)
* [X] Tried basic troubleshooting (if a bug/error)
    * [X] Restarted Spyder
    * [X] Reset preferences with ``spyder --reset``
    * [ ] Reinstalled the latest version of [Anaconda](https://www.anaconda.com/download/)
    * [ ] Tried the other applicable steps from the Troubleshooting Guide
* [X] Completed the **Problem Description**, **Steps to Reproduce** and **Version** sections below

## Problem Description

When inspecting an object, the help pane flashes white shortly and then displays a blank pane.

Peek 2023-01-12 09-28

### What steps reproduce the problem?

1. Installed spyder via `pip install spyder` inside miniconda env (this is the way I usually install spyder)
2. Click on any object and inspect, or press the key combination for inspect
3. same happens in console or editor
4. the online help suffers from the same problem

### What is the expected output? What do you see instead?

Help pane opens with the inspected object rendered in richt text. Instead, it flashes shortly and then displays a blank page. However, when switching to plain text mode, the widget works fine, so it must be a rendering issue, probably with the WebEngine.

* I do remember having this issue before when trying to setup Spyder inside WSL2 some time ago, but I don't remember what the solution was, or if there was any at all. 
* Here I'm using Kubuntu 22.04, so I could imagine that this is due to incompatibilities between the system KDE Qt5 version (`5.15.2`) and spyder Qt5 (`5.15.7`)? 
* I tried downgrading the `PyQtWebEngine` to a lower version, but that only led to Spyder not starting anylonger.
* I tried downgrading to `PyQt5==5.15.2` and `PyQtWebEngine==5.15.2` using `--force-reinstall`, but then PyQtWebEngine would not load

Probably related:
#17751
#18776
#17771 (maybe not)

trying this solutions does not fix the problem:
```
    conda create -n spyder-cf -c conda-forge spyder
    conda activate spyder-cf
    spyder
```

### Paste Traceback/Error Below (if applicable)

No traceback. Also no errors appear in verbose debug mode

## Versions

* Spyder version: 5.4.1  (conda)
* Python version: 3.10.6 64-bit
* Qt version: 5.15.2
* PyQt5 version: 5.15.7
* Operating System: Linux 5.15.0-56-generic

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0          :  1.4.1 (OK)
chardet >=2.0.0               :  5.1.0 (OK)
cloudpickle >=0.5.0           :  2.2.0 (OK)
cookiecutter >=1.6.0          :  2.1.1 (OK)
diff_match_patch >=20181111   :  20200713 (OK)
intervaltree >=3.0.2          :  3.1.0 (OK)
IPython >=7.31.1;<9.0.0       :  8.8.0 (OK)
jedi >=0.17.2;<0.19.0         :  0.18.2 (OK)
jellyfish >=0.7               :  0.9.0 (OK)
jsonschema >=3.2.0            :  4.17.3 (OK)
keyring >=17.0.0              :  23.13.1 (OK)
nbconvert >=4.0               :  7.2.7 (OK)
numpydoc >=0.6.0              :  1.5.0 (OK)
parso >=0.7.0;<0.9.0          :  0.8.3 (OK)
pexpect >=4.4.0               :  4.8.0 (OK)
pickleshare >=0.4             :  0.7.5 (OK)
psutil >=5.3                  :  5.9.4 (OK)
pygments >=2.0                :  2.14.0 (OK)
pylint >=2.5.0;<3.0           :  2.15.10 (OK)
pylint_venv >=2.1.1           :  2.3.0 (OK)
pyls_spyder >=0.4.0           :  0.4.0 (OK)
pylsp >=1.7.0;<1.8.0          :  1.7.0 (OK)
pylsp_black >=1.2.0           :  1.2.1 (OK)
qdarkstyle >=3.0.2;<3.1.0     :  3.0.3 (OK)
qstylizer >=0.2.2             :  0.2.2 (OK)
qtawesome >=1.2.1             :  1.2.2 (OK)
qtconsole >=5.4.0;<5.5.0      :  5.4.0 (OK)
qtpy >=2.1.0                  :  2.3.0 (OK)
rtree >=0.9.7                 :  1.0.1 (OK)
setuptools >=49.6.0           :  65.7.0 (OK)
sphinx >=0.6.6                :  6.1.3 (OK)
spyder_kernels >=2.4.1;<2.5.0 :  2.4.1 (OK)
textdistance >=4.2.0          :  4.5.0 (OK)
three_merge >=0.1.1           :  0.1.1 (OK)
watchdog >=0.10.3             :  2.2.1 (OK)
xdg >=0.26                    :  0.28 (OK)
zmq >=22.1.0                  :  24.0.1 (OK)

# Optional:
cython >=0.21                 :  None (NOK)
matplotlib >=3.0.0            :  3.6.2 (OK)
numpy >=1.7                   :  1.23.5 (OK)
pandas >=1.1.1                :  1.5.2 (OK)
scipy >=0.17.0                :  1.9.3 (OK)
sympy >=0.7.3                 :  None (NOK)
```

### PR DESCRIPTION
**Pull request by tlunet**
## Description of Changes

Add `--no-sandbox` argument when instantiating QtApplication object, in order to avoid a bug linked to Ubuntu 22.04 (see https://discourse.slicer.org/t/extensions-not-showing-anything/23432/5 and https://doc.qt.io/qt-6/qtwebengine-platform-notes.html)

Note sure if this is needed in `manager.py` tho, put it here just for consistency.

### Issue(s) Resolved

Fixes #20358

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: tlunet

### CODE REVIEW

**Comment by jitseniesen** [comment]
I can confirm that this fixes the issue for me when running from source using `python bootstrap.py`.

Good work!

**Comment by tlunet** [comment]
Thanks @jitseniesen, you did pointed me already in the good direction with [your comment on PyQt](https://github.com/spyder-ide/spyder/issues/20358#issuecomment-1418099004) :smiley:

**Comment by jitseniesen** [comment]
@tlunet Nice, to me it indicated that it was too hard a problem for me to solve, so I gave up!

> Btw, should I make this parameter conditional to Linux so the MacOS test can pass ?

I don't see evidence that the MacOS failure has anything to do with your change; in fact, it's not clear at all why the test timed out. I am running it again, see whether it makes a difference.

Say hello to Daniel Ruprecht (I saw SDC and TUHH on your GitHub profile, so I assume you work with him).

**Comment by tlunet** [comment]
Seems not linked to this PR, if I'm not mistaken ? See : https://github.com/spyder-ide/spyder/actions/runs/4088046116/jobs/7049275728

**Comment by ccordoba12** [comment]
> Seems not linked to this PR, if I'm not mistaken ?

Yeah, I don't think it is. I restarted that job to see if it passes a second time.

**Review by ccordoba12 — APPROVED** [review]
Thanks @tlunet for your help digging this problem and proposing a solution for it!

**Comment by matiast1905** [comment]
I had this issue and the PR solved it.

Spyder version:
* Spyder version: 5.4.2  (conda)
* Python version: 3.11.0 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Linux 6.0.12-76060006-generic

Linux Pop!_OS 22.04 LTS

**Pull request merged**
