### PR TITLE
PR: Change default root_path for PyLS and refactor LSP related code

### PR DESCRIPTION
**Pull request by ccordoba12**
* Before we were using HOME by default for `root_path` and that was causing a huge delay when trying to get Rope completions. Now we use an empty dir inside our config one, just like we did in Spyder 3.
* This PR also refactors and renames several methods and constants related to our LSP integration.

@steff456, this should fix the Rope delays you found before. Please try it on your side (by enabling `rope_completion` and disabling `jedi_completion`) and let me know if it works for you or not.

### CODE REVIEW

**Comment by andfoy** [comment]
@ccordoba12 Is everything LSP-related more stable now?

**Comment by steff456** [comment]
@ccordoba12, with this change the rope_completion is working! 

I checked out the completion race and now it is working as expected with this change.

**Comment by ccordoba12** [comment]
> Is everything LSP-related more stable now?

@andfoy, yes, I think it is! We're working now with @steff456 to get feature parity with Spyder 3 and (as you know) making Rope completions work again in the PyLS is a top priority for us.

**Comment by ccordoba12** [comment]
> with this change the rope_completion is working!

Great to hear!! Thanks @steff456 for the confirmation!

**Pull request merged**
