### PR TITLE
PR: Add build for Windows installer with extra packages

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### TODO

- [x] Create executable for Spyder + extra packages
- [x] Fix issue with the `PYTHONPATH`
- [x] Fix issue with the `pyls` and `black` throwing a `DistributionNotFound` error
- [x] ~~Use external-deps in PR builds~~ Use `spyder-kernels` from `external-deps` for PRs
- [x] Jedi issue about invalid interpreter (needs patch version of Jedi `CompiledSubprocess`)
- [x] Improve version definition
- [x] Use Uppercase name in the installer (`spyder` -> `Spyder`)
### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Review by ccordoba12 — COMMENTED** [review]
Thanks @dalthviz! This looks good to me.

What do you think about adding our subrepos to the installers on pull request builds, as it was done in PR #13992?

**Comment by dalthviz** [comment]
I need to check how to do it (maybe the external packages option could be handy for this use case too). Should I do that in this PR too @ccordoba12 ?

**Comment by ccordoba12** [comment]
Yes, I think it's a good idea to do it in this PR.

**Comment by ccordoba12** [comment]
@dalthviz, is this one ready?

**Comment by dalthviz** [comment]
@ccordoba12 I haven't tested the artifacts generated otherwise I think this is done :+1:

**Comment by ccordoba12** [comment]
Ok, please let me know when you have.

**Comment by dalthviz** [comment]
Checking the installers being build, now there is an issue with `black` (independly of the use of the the installation of the `pyls` from the `external-deps` dir or the wheel). Not totally sure why is happening but this is the traceback I'm getting:

```
python Response error: {
'code': -32602,
'message': "pkg_resources.DistributionNotFound: The 'black>=19.3b0' distribution was not found and is required by the application",
'data': {'traceback': [
'  File "C:\\Users\\Daniel\\AppData\\Local\\spyder\\pkgs\\pyls_jsonrpc\\endpoint.py", line 113, in consume\n
    self._handle_request(message[\'id\'], message[\'method\'], message.get(\'params\'))\n', 
'  File "C:\\Users\\Daniel\\AppData\\Local\\spyder\\pkgs\\pyls_jsonrpc\\endpoint.py", line 182, in _handle_request\n
    handler_result = handler(params)\n',
 '  File "C:\\Users\\Daniel\\AppData\\Local\\spyder\\pkgs\\pyls_jsonrpc\\dispatchers.py", line 23, in handler\n
    return method(**(params or {}))\n',
 '  File "C:\\Users\\Daniel\\AppData\\Local\\spyder\\pkgs\\pyls\\python_ls.py", line 209, in m_initialize\n
    processId, _kwargs.get(\'capabilities\', {}))\n', 
'  File "C:\\Users\\Daniel\\AppData\\Local\\spyder\\pkgs\\pyls\\config\\config.py", line 53, in __init__\n
    entry_point.load()\n', 
'  File "C:\\Users\\Daniel\\AppData\\Local\\spyder\\pkgs\\pkg_resources\\__init__.py", line 2446, in load\n
    self.require(*args, **kwargs)\n',
 '  File "C:\\Users\\Daniel\\AppData\\Local\\spyder\\pkgs\\pkg_resources\\__init__.py", line 2469, in require\n
    items = working_set.resolve(reqs, env, installer, extras=self.extras)\n', 
'  File "C:\\Users\\Daniel\\AppData\\Local\\spyder\\pkgs\\pkg_resources\\__init__.py", line 770, in resolve\n
    raise DistributionNotFound(req, requirers)\n']}}
```

**Comment by dalthviz** [comment]
After fixing the issue with black, now a error from jedi appears `jedi.api.environment.InvalidPythonEnvironment: Could not get version information for 'C:\\Users\\Daniel\\AppData\\Local\\spyder\\Python\\python.exe': InternalError("The subprocess C:\\Users\\Daniel\\AppData\\Local\\spyder\\Python\\python.exe has crashed (EOFError('Ran out of input'), stderr=).")`

**Review by ccordoba12 — APPROVED** [review]
Thanks a lot @dalthviz for this! Our Windows installers are working great now!

**Pull request merged**
