### PR TITLE
Fix further freezes because of pyzmq

### PR DESCRIPTION
**Pull request by impact27**
Fixes issue #3223 as the previous fix doesn't work

### CODE REVIEW

**Comment by ccordoba12** [comment]
Issue #3223 was correctly fixed in my tests on Windows, Linux and Mac. But maybe this could help us to fix Issue #3306.

@impact27, are you using OS X?

@blink1073, could you review this one? Is this the right fix for #3306?

**Comment by blink1073** [comment]
This is a good change either way, 👍.  Thanks, @impact27!

**Comment by ccordoba12** [comment]
Should I merge it then @blink1073?

**Comment by blink1073** [comment]
Done :wink:.  I'll run this version overnight.

**Comment by impact27** [comment]
Yes I'm on OSX 10.11.6

**Pull request merged**
