### PR TITLE
Projects Menu

### PR DESCRIPTION
**Pull request by novaya**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

As a user it was convenient  to have some menu options directly in projects plugin. So I added them

### Issue(s) Resolved

Fixes #

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by goanpeca** [comment]
Thanks for your contribution. Could you add a screenshot?

**Comment by novaya** [comment]
> Thanks for your contribution. Could you add a screenshot?

Screenshot from 2020-01-19 12-34-49

**Comment by ccordoba12** [comment]
Thanks for your contribution! We'd like to include it in our next release in the Spyder 4 series. For that, please make your branch to derive from our `4.x` branch (instead of master), with the following command:

    git checkout menu
    git rebase --onto 4.x master menu

If you decline to do that, your work will be part of Spyder 5, to be released much later in 2020.

**Comment by novaya** [comment]
> Thanks for your contribution! We'd like to include it in our next release in the Spyder 4 series. For that, please make your branch to derive from our `4.x` branch (instead of master), with the following command:
> 
> ```
> git checkout menu
> git rebase --onto 4.x master menu
> ```
> 
> If you decline to do that, your work will be part of Spyder 5, to be released much later in 2020.

I created new PR for 4.x: https://github.com/spyder-ide/spyder/pull/11349. I will cancel this PR.

**Pull request closed without merging**
