### PR TITLE
PR: Disable screen resolution change message in macOS and allow to hide it during the current session

### LINKED ISSUE #11846: Popup "A monitor scale change was detected" every few minutes
## Problem Description

After upgrading Spyder to 4.1.0 through conda, Spyder will show a popup stating that a monitor scale change was detected every few minutes. 

In the popup, there is a recommendation "**Enable auto high DPI scaling**" in Spyder preference will be helpful.

However, even if I enable that, and restart my Spyder, the popup still appears every few minutes.

~~**Actually, I have a workaround to this issue, which is **disabling** the _Automatic Graphics Switching_ in  _System Preference_ -> _Energy Saver_ .**~~
I thought it helps, but still the popup keeps appearing.

## Versions

* Spyder version: 4.1.0
* Python version: 3.7.6 64-bit
* Qt version: 5.9.6
* PyQt version: 5.9.2
* Operating System name/version: Darwin 19.3.0

I am using MacBook Pro 2018 with Catalina, and with no external display.

### PR DESCRIPTION
**Pull request by steff456**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Verify the screen mode before generating a warning pop-up of a monitor scale change when using spyder in the fullscreen mode.

### Issue(s) Resolved

Fixes #11846 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Steff456

### CODE REVIEW

**Comment by juliangilbey** [comment]
I've tried applying this patch to my Spyder 4.1.1 installation under Anaconda on a Mac, running Mojave 10.14.6, but I'm still regularly getting the popup.  Perhaps it's because I'm not in full screen mode?

**Comment by ccordoba12** [comment]
@juliangilbey, that's right. This fix only works when Spyder is in full screen mode. But are you saying that you're still getting it in regular mode?

**Comment by goanpeca** [comment]
We need to add a dont show this message again and have it work even after closing and restaring spyder.

**Comment by steff456** [comment]
Now the dialog has a checkbox to hide the message during the current session

image

**Comment by ccordoba12** [comment]
@steff456, we had a chat with @dalthviz half an hour ago and decided to deactivate this message completely in macOS because it's being triggered in a lot of wrong situations (at least according to what our users have said on issue #11846).

I'm sorry for macOS users, but it's not possible for us to give them this warning in a reliable way.

**Comment by MathildeGarrigues** [comment]
Hello,
I am still having the message, even after updating spyder. How should I do to avoid it ? It appears also when I am not in fullscreen.
Thanks in advance for your help

**Comment by ccordoba12** [comment]
This error will be fixed in our next version (4.1.2). In the meantime, please downgrade to our 4.0.1 version with these commands:

    conda install spyder=4.0.1
    conda install spyder-kernels=1.8.1

**Pull request merged**
