### PR TITLE
PR: Add language name to status bar

### PR DESCRIPTION
**Pull request by trollodel**
## Description of Changes

* [x] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Language status

I added the file language name to the status bar.

### Issue(s) Resolved

Related to #638

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: trollodel

### CODE REVIEW

**Comment by andfoy** [comment]
@trollodel, thanks for this great addition! Overall it looks fine, I don't know if @ccordoba12 has any other comment

**Review by andfoy — APPROVED** [review]

**Comment by trollodel** [comment]
I'm going to close this PR because it's outdated, and it doesn't work in the current master. It has an approval (Ironically, this is the [only PR open with an approval](https://github.com/spyder-ide/spyder/pulls?q=is%3Apr+is%3Aopen+review%3Aapproved)).
If there is some interest, I may decide to recreate it.

**Comment by ccordoba12** [comment]
Hey @trollodel, thanks for working on this! I'm very sorry for not reviewing and merging it time. We'd be glad to do it if you'd like to reopen it again.

If not, I'll be willing to take your work, finish it and include it in our next major version (i.e. Spyder 6).

**Comment by trollodel** [comment]
This PR was made for 4.x, should I recreate it for another branch? In any case, this needs a rebase and to check if it's still working.

**Pull request closed without merging**
