### PR TITLE
PR: Support DatetimeIndex in Variable Explorer

### LINKED ISSUE #3380: DatetimeIndex types are not visible in the Variable Explorer
### snippet

import pandas as pd
rng = pd.date_range('10/1/2016', periods=25, freq='bq')
### end snippet

**Matrix above is not violable in variable explorer.**
## Description

**What steps will reproduce the problem?**
1. 
2. 
3. 

**What is the expected output? What do you see instead?**

**Please provide any additional information below**
## Version and main components
- Spyder Version: 2.3.9 
- Python Version: 3.5.1
- Qt Versions:  4.8.7, PyQt4 (API v2) 4.11.4 on Darwin
## Optional dependencies

```
pyflakes >=0.6.0   :  1.0.0 (OK)
pep8 >=0.6         :  1.7.0 (OK)
pygments >=1.6     :  2.1.1 (OK)
IPython >=1.0      :  4.1.2 (OK)
zmq >=2.1.11       :  15.2.0 (OK)
qtconsole >=4.0    :  4.2.1 (OK)
pandas >=0.13.1    :  0.18.1 (OK)
sphinx >=0.6.6     :  1.3.5 (OK)
psutil >=0.3       :  3.4.2 (OK)
rope >=0.9.2       :  0.9.4-1 (OK)
jedi >=0.8.1;<0.9.0:  0.9.0 (NOK)
matplotlib >=1.0   :  1.5.1 (OK)
sympy >=0.7.3      :  0.7.6.1 (OK)
pylint >=0.25      :  None (NOK)

```

### PR DESCRIPTION
**Pull request by jitseniesen**
Support variables of panda's DatetimeIndex type in variable editor, and use the dataframe editor to display them. Fixes #3380.

### CODE REVIEW

**Comment by jitseniesen** [comment]
I actually wrote this a while ago, while we were in freeze for the 3.0 release.

There are a number of places that have to be changed to support a new type in the variable explorer. There are also a number of issues which ask to support more types: #3758, #3562, #2824, #2510, #2355, etc. Can we make it easier to add support for a new type, possibly in a plugin?

**Comment by ccordoba12** [comment]
> Can we make it easier to add support for a new type, possibly in a plugin?

That's my plan for Spyder 4.0 :-) I think we could add a function called `register_object` to `spyder/api/variableexplorer.py` that would take care of doing all you've done here.

But for that we need to restructure how we dispatch objects to viewers in the Variable Explorer code, so it can be easily extended.

**Comment by ccordoba12** [comment]
@jitseniesen, this has conflicts now.

I'm leaving this for Spyder 4.0 because your PR is against master. If you want this for Spyder 3, please redo it against 3.x :-)

**Comment by jitseniesen** [comment]
PR redone against 3.x and conflicts resolved.

**Comment by ccordoba12** [comment]
Thanks a lot! Just in time for 3.1 :-)

**Pull request merged**
