### PR TITLE
PR: Replace `github.py` with `pygithub` package

### LINKED ISSUE #22030: Issue reporter submit to github results in 403 error
## Problem Description

When attempting to submit an issue to Github via the Issue reporter, a 403 error occurs.

### What steps reproduce the problem?

1. Help -> Report issue...
2. Complete text fields as necessary
3. Click Submit to Github

### What is the expected output? What do you see instead?

Should successfully create issue on Github, but instead results in 
Screenshot 2024-04-26 at 8 24 40 PM

## Versions

* Spyder version: 6.0.0a5  (standalone)
* Python version: 3.10.13 64-bit
* Qt version: 5.15.8
* PyQt5 version: 5.15.9
* Operating System: macOS-14.4.1-x86_64-i386-64bit

### Dependencies

```
# Mandatory:
atomicwrites >=1.2.0              :  1.4.1 (OK)
chardet >=2.0.0                   :  5.2.0 (OK)
cloudpickle >=0.5.0               :  3.0.0 (OK)
cookiecutter >=1.6.0              :  2.5.0 (OK)
diff_match_patch >=20181111       :  20230430 (OK)
intervaltree >=3.0.2              :  3.1.0 (OK)
IPython >=8.13.0,<9.0.0,!=8.17.1  :  8.21.0 (OK)
jedi >=0.17.2,<0.20.0             :  0.19.1 (OK)
jellyfish >=0.7                   :  1.0.3 (OK)
jsonschema >=3.2.0                :  4.21.1 (OK)
keyring >=17.0.0                  :  24.3.0 (OK)
nbconvert >=4.0                   :  7.16.0 (OK)
numpydoc >=0.6.0                  :  1.6.0 (OK)
parso >=0.7.0,<0.9.0              :  0.8.3 (OK)
pexpect >=4.4.0                   :  4.9.0 (OK)
pickleshare >=0.4                 :  0.7.5 (OK)
psutil >=5.3                      :  5.9.8 (OK)
pygments >=2.0                    :  2.17.2 (OK)
pylint >=3.1,<4                   :  3.1.0 (OK)
pylint_venv >=3.0.2               :  3.0.3 (OK)
pyls_spyder >=0.4.0               :  0.4.0 (OK)
pylsp >=1.11.0,<1.12.0            :  1.11.0 (OK)
pylsp_black >=2.0.0,<3.0.0        :  2.0.0 (OK)
pyuca >=1.2                       :  1.2 (OK)
qdarkstyle >=3.2.0,<3.3.0         :  3.2.3 (OK)
qstylizer >=0.2.2                 :  0.2.2 (OK)
qtawesome >=1.3.1,<1.4.0          :  1.3.1 (OK)
qtconsole >=5.5.1,<5.6.0          :  5.5.1 (OK)
qtpy >=2.4.0                      :  2.4.1 (OK)
rtree >=0.9.7                     :  1.2.0 (OK)
setuptools >=49.6.0               :  69.0.3 (OK)
sphinx >=0.6.6                    :  7.2.6 (OK)
spyder_kernels >=3.0.0b5,<3.0.0b6 :  3.0.0b5 (OK)
superqt >=0.6.1,<1.0.0            :  0.6.1 (OK)
textdistance >=4.2.0              :  4.5.0 (OK)
three_merge >=0.1.1               :  0.1.1 (OK)
watchdog >=0.10.3                 :  4.0.0 (OK)
zmq >=24.0.0                      :  25.1.2 (OK)

# Optional:
cython >=0.21                     :  3.0.8 (OK)
matplotlib >=3.0.0                :  3.8.2 (OK)
numpy >=1.7                       :  1.26.4 (OK)
pandas >=1.1.1                    :  2.2.0 (OK)
scipy >=0.17.0                    :  1.12.0 (OK)
sympy >=0.7.3                     :  1.12 (OK)
```

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

`github.py` has not been updated for nearly 5 years, and the source repo has not been updated for 1 year. `pygithub` appears to be actively maintained and seems a prudent replacement.

I think it turned out that the 403 error that I reported actually had to do with my personal access token. Nevertheless, upon investigation, it still seems prudent to use `pygithub` instead.

### Issue(s) Resolved

Fixes #22030 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by dalthviz** [comment]
As a quick comment, probably we should remove the `NOTICE.txt` entry related with the previous code handling the GitHub requests at https://github.com/spyder-ide/spyder/blob/1475484b900ad0bf0c8e3f53577ba3b526621a0a/NOTICE.txt#L485-L521

**Comment by dalthviz** [comment]
Gave this a local check and I was unable to create an issue automatically by providing a token. I followed the link to create a token, put in the token in the respective dialog but then I got the following dialog (shown when the issue creation fails):

image

 Checking launching the report error dialog using the test logic from the bottom of `spyder/widgets/reporterror.py` I got some output:

```
Invalid token.
module 'github' has no attribute 'Auth'
``` 

🤔

**Comment by mrclary** [comment]
@dalthviz, thanks for testing this. I found a couple of errors and pushed up corrections.

**Comment by dalthviz** [comment]
Gave this another check but seems like I'm still facing the same issue: I'm still getting the error dialog and adding the extra logger warning to check the generated exception I got the `module 'github' has no attribute 'Auth'` as output):

Could it be that `spyder.widgets.github` is shadowing the `github` module import done to use the `pygithub` package over `spyder.widgets.github.backend`? Maybe changing `spyder.widgets.github` for something like `spyder.widgets.github_utils` could help? 🤔

**Comment by mrclary** [comment]
I'll check on my Windows VM. I'm not seeing any issues on macOS.

**Comment by mrclary** [comment]
@dalthviz, I was able to successfully report an issue from my Windows VM. I'm not sure why you are having an issue. I know this sounds silly, but you did install `pygithub` into your environment, correct?

The only other thing I can suggest is to use
```python
from PyQt5.QtCore import pyqtRemoveInputHook; pyqtRemoveInputHook()
import pdb; pdb.set_trace()
```
inside `backend.py` to interactively inspect `github` prior to line 133.

**Comment by dalthviz** [comment]
>  I was able to successfully report an issue from my Windows VM. I'm not sure why you are having an issue. I know this sounds silly, but you did install pygithub into your environment, correct?

Oh nice! And yep, I installed `pygithub`:

image

> The only other thing I can suggest is to use
> 
> from PyQt5.QtCore import pyqtRemoveInputHook; pyqtRemoveInputHook()
> import pdb; pdb.set_trace()
> 
> inside backend.py to interactively inspect github prior to line 133.
> 

Thanks for the suggestion! Will give it a try but maybe it's just time for me to redo my dev env 😅

**Comment by mrclary** [comment]
> Will give it a try but maybe it's just time for me to redo my dev env 😅

I just redid my dev env today and ran into an issue with `qt-webengine=5.15.9`: Spyder would not launch from bootstrap and just crashes. I had to revert to `qt-webengine=5.15.8`. I don't know if this was a fluke or if it only affects macOS. So just a heads up.

**Comment by dalthviz** [comment]
Gave the pdb check a try and seems like indeed for some reason `spyder.spyder.widgets.github` ends up being used instead of `pygithub`:

image

But thinking about it and since you got to submit an issue, the error in my case is caused most probably since I was trying to test this by directly running the report error dialog file (`spyder/widgets/reporterror.py`) :thinking:

Anyhow, I was able to create some issues like https://github.com/dalthviz/spyder/issues/5 when running from `bootstrap.py` so seems like things are working as expected :+1:

>I just redid my dev env today and ran into an issue with qt-webengine=5.15.9: Spyder would not launch from bootstrap and just crashes. I had to revert to qt-webengine=5.15.8. I don't know if this was a fluke or if it only affects macOS. So just a heads up.

I created a new dev env just in case and on Windows I got `pyqtwebengine 5.15.9` too but Spyder seems to launch fine. I think in the past I have encountered some issues when checking things on my macOS VM that could be related. At that time I think I got a segfault when lauching Spyder and seemed that using the `--no-web-widgets` flag helped 🤔 Maybe it could be worthy to create an issue and test a little bit more macOS and `pyqtwebengine 5.15.9` compatibility?  What do you think @ccordoba12 ?

**Review by dalthviz — APPROVED** [review]
Thanks @mrclary ! Checked locally and seems like things are working as expected :+1:

**Pull request merged**
