### PR TITLE
PR: Update AppVeyor badge in Readme because of move to org account

### LINKED ISSUE #3962: Update Appveyor Badge for new username spyder-ide

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #3962

### CODE REVIEW

**Comment by goanpeca** [comment]
@ccordoba12 did you delete the project already? we might have been able to do this

http://help.appveyor.com/discussions/questions/1444-transfer-project-ownership

To keep the history(although not super important...!)

**Comment by ccordoba12** [comment]
I did, sorry :-/

**Comment by goanpeca** [comment]
You need to update the webhooks

screen shot 2017-01-15 at 12 57 21 pm

With the value in the settings of appveyor

**Comment by goanpeca** [comment]
Its ok, we dont need the history to be honest, I will delete also!

**Comment by ccordoba12** [comment]
Yeah, and I figured AppVeyor guys will take some time to answer and we need to move right now with this.

**Comment by ccordoba12** [comment]
Appveyor is not kicking in, do you know why?

**Comment by goanpeca** [comment]
hmmm no I am out now. will be back in 2 hours. Did you check the webhook setting?

**Comment by ccordoba12** [comment]
Ok, Appveyor seems to be up again, yay!

**Pull request merged**
