### PR TITLE
PR: Add pylint to Travis tests (fixes #2424)

### LINKED ISSUE #2424: Test for mixed line ending changes in Travis
To fix #2335 one of proposed solutions is to automagically convert linefeeds to LF. http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/ This is bad for two reasons:

1. git may mistake
2. Spyder may lose control over linefeeds and mess them up badly

So, an alternative solution would be to add a Travis check for Windows linefeeds.

1. All files for CRLF (commits to master)
2. Only modified files (http://docs.travis-ci.com/user/pull-requests/)

### PR DESCRIPTION
**Pull request by techtonik**
This is ready to be merged for #2424

### CODE REVIEW

**Comment by ccordoba12** [comment]
I don't know what to do about this one :-) If we merge it now, it'll break our testing, unless we merge @Nodd PR first. But that would break all other PR's.

@Nodd, thoughts?

**Comment by techtonik** [comment]
PR#2370 touches too much stuff. This PR addresses only .py files in spyderlib/, so it has less chances to break something that was not detected as binary.

**Comment by Nodd** [comment]
There is no official consensus, but some of us agreed to at least wait for large PRs to be merged before fixing line endings. After this is done, this one can be merged immediately.

**Comment by techtonik** [comment]
@Nodd can you list them there?

**Comment by Nodd** [comment]
Nope, I don't have a complete list. From looking at the opened PRs, I'd say:
#2184 #2367 #2343 #2362 
The other ones either touch 1 or 2 files, or do not touch python files.

**Comment by techtonik** [comment]
I've got a feeling that some of these need to be split into smaller chunks. Huge diffs are hard to review anyway. And rebasing in Git is easier than with HG. I guess we need just to provide instructions how to rebase PRs and normalize linefeeds (if Git diff is not smart enough to do this).

**Comment by techtonik** [comment]
Linefeeds are fixed, but there is still problem with trailing whitespace

**Comment by techtonik** [comment]
Try to merge with this branch and see if there are conflicts?

I've uploaded cmdline tool to fix linefeeds. Should work on Windows/Linux/MacOS/2/3.
https://pypi.python.org/pypi/dos2unix

```
pip install dos2unix
python -m dos2unix <infile> <outfile> 
```
In and out can be the same file. The list of files to be processed http://paste.ubuntu.com/11633504/
or quick and dirty... http://paste.ubuntu.com/11633568/

**Comment by techtonik** [comment]
Another script to strip trailing whitespace. Python 2 only for now.

**Comment by Nodd** [comment]
Uh, the point of this PR was to add test only, not to ix line endings themselves, that's for another one.

Also, did you try autopep8 to fix trailing spaces ?

**Comment by techtonik** [comment]
The point is now to make Travis green and see how to deal with merge conflicts. If Git is smarter than SVN, there should not be any conflicts at all.

And no, I didn't know that autopep8 can fix trailing whitespace.

Also, the merges could become easier if the Spyder had this `won't fix` issue #757 implemented few years ago.

**Comment by Nodd** [comment]
We will use .gitattributes fo fix line endings, so you don't need to bother with them.

**Comment by techtonik** [comment]
@Nodd have you tested that it won't bring merge conflicts?

**Comment by techtonik** [comment]
The last failure can be fixed by upgrading pylint. Where to find those conda packages and how to update pylint there?

**Comment by ccordoba12** [comment]
There is no way this could be merged as it is, and nobody has complained anymore about line endings.

So, I'm closing this pull request. Besides, I don't think I'd be willing to accept a new one that only fixes line endings. It's like big pep8 pull requests, they tend to break stuff in unsuspected ways.

**Pull request closed without merging**
