### PR TITLE
PR: Handle NaT values (Variable Explorer)

### LINKED ISSUE #8329: Error when trying to inspect a 'NaT' in Variable Explorer
### What steps will reproduce the problem?

In [135]: x = df['remove_time'][2]

In [136]: pd.Timestamp.max
Out[136]: Timestamp('2262-04-11 23:47:16.854775807')

In [137]: print(df['remove_time'][2])
NaT

In [138]: x = df['remove_time'][2]

In [139]: 

Then, I click the 'x' in Variable Explorer.

### Traceback
```python-traceback
  File "/home/hechu/anaconda3/lib/python3.7/site-packages/spyder/widgets/variableexplorer/collectionseditor.py", line 615, in setEditorData
    editor.setDateTime(QDateTime(value.date(), value.time()))
  File "pandas/_libs/tslibs/nattype.pyx", line 59, in pandas._libs.tslibs.nattype._make_error_func.f
ValueError: NaTType does not support time
```

## Versions

* Spyder version: 3.3.1 
* Python version: 3.7.0
* Qt version: 5.9.6
* PyQt5 version: 5.9.2
* Operating System: Linux 4.15.0-39-generic

### Dependencies

```
pyflakes >=0.6.0  :  2.0.0 (OK)
pycodestyle >=2.3 :  2.4.0 (OK)
pygments >=2.0    :  2.2.0 (OK)
sphinx >=0.6.6    :  1.8.2 (OK)
rope >=0.9.4      :  0.11.0 (OK)
jedi >=0.9.0      :  0.13.1 (OK)
psutil >=0.3      :  5.4.8 (OK)
nbconvert >=4.0   :  5.3.1 (OK)
pandas >=0.13.1   :  0.23.4 (OK)
numpy >=1.7       :  1.15.1 (OK)
sympy >=0.7.3     :  1.3 (OK)
cython >=0.21     :  0.29 (OK)
qtconsole >=4.2.0 :  4.4.2 (OK)
IPython >=4.0     :  7.1.1 (OK)
matplotlib >=2.0.0:  2.2.3 (OK)
pylint >=0.25     :  2.1.1 (OK)
```

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

### Issue(s) Resolved

Fixes #8329 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Comment by goanpeca** [comment]
Hi @dalthviz thanks for working on this.

It does indeed takes car of the issue, but on editing the value, the edit value takes some default initial datetime. Is this expected/desired @spyder-ide/core-developers ?

pylint

**Comment by dalthviz** [comment]
Yep that's the thing I'm not sure is correct here @goanpeca (that's why I added the `WIP`). As we discussed with @ccordoba12 probably an editor shouldn't be created for such values (no edition should be available for such values)

**Comment by goanpeca** [comment]
>probably an editor shouldn't be created for such values 

One could have a Dataframe with some NaT values, and the user might want to actually put a time in there, so there may be cases where editing and making such changes might make sense, so maybe we could use the current fix and see if someone request them to be editable 🤷 ?

**Comment by ccordoba12** [comment]
> As we discussed with @ccordoba12 probably an editor shouldn't be created for such values (no edition should be available for such values)

I think it could be very confusing from the user perspective (now that I see the gif you posted).

So I changed my mind and now I think we should make those values read-only. @goanpeca, what do you think?

**Comment by goanpeca** [comment]
I think the changes @dalthviz made made it read only, no ?

**Pull request merged**
