### PR TITLE
New Spyder 3 icons for run-cell and run-cell inplace

### PR DESCRIPTION
**Pull request by SylvainCorlay**
runcell

Pixel perfect in 16x16.  This addresses the comments on these icons in #2490.

### CODE REVIEW

**Comment by ccordoba12** [comment]
They're nice! Thanks @SylvainCorlay!

But what about using a different color other than yellow for the selected area? Thoughts?

@goanpeca, do you have something to say?

**Comment by goanpeca** [comment]
Not really :-)

**Comment by SylvainCorlay** [comment]
It is the yellow of the Python logo!

**Comment by SylvainCorlay** [comment]
Rebased.

**Comment by ccordoba12** [comment]
@SylvainCorlay, could you add a border around the white rectangle that represents the file? It's kind of hard to see it with no border :-)

On a second thought, I think yellow is fine to represent cells (after all, that's the color used in Matlab). But could you make it a little bit lighter? I mean, not so yellow?

**Comment by SylvainCorlay** [comment]
Yeah I thought of adding a border or a shadow for the document. For the color, we could use the same as the highlighted cell color in the Spyder syntax coloring theme.

**Comment by ccordoba12** [comment]
+1 to both :-)

**Comment by SylvainCorlay** [comment]
We could actually be super fancy and make certain icon colors depend on syntax coloring theme - for another PR.

**Comment by ccordoba12** [comment]
Sounds cool! But I agree, for another PR.

**Comment by SylvainCorlay** [comment]
New version. 
runcell

The yellow from the Spyder coloring scheme was not distinguishable from the white so I added a cell border.

**Comment by SylvainCorlay** [comment]
@ccordoba12 
- changed the run-setting / run-again icon size and offset.
- changed color on the run-cell.
toolbar

I can change the document shadow to a border in a different PR.

**Comment by ccordoba12** [comment]
@SylvainCorlay, could you change the shadow to a border in this PR? After all, the idea is to provide a much version for our cell icons here, right? ;-)

**Comment by SylvainCorlay** [comment]
It is already clearly better than the current Spyder 3 icons. Just that I foresee a long discussion on the shape of the run-cell icons.

**Comment by SylvainCorlay** [comment]
@ccordoba12 here is the latest screenshot.
spyder

**Comment by SylvainCorlay** [comment]
For IPython

* [y]
* IP[y]
* IP:
* Jupyter

**Comment by ccordoba12** [comment]
Ok, merging this for @SylvainCorlay mental health ;-)

**Comment by SylvainCorlay** [comment]
Yes I liked how @ccordoba12 said that we should actually use the first version after 10 iterations. :smile:

**Pull request merged**
