### PR TITLE
PR: Fix errors with OnlineHelp plugin regarding readonly properties and ModuleScanner errors

### LINKED ISSUE #20866: Error when searching numpy and pandas in Online Help widget
### What steps will reproduce the problem?

Entering `numpy` (or `pandas`) in the Online Help widget search field results in an error similar to the following.
```
numpy.html
AssertionError
```

Also, entering any text in the "Module Index:Topics:Keywords" search field results in an error, for example
```
search?key=bootstrap
OSError: The baseline image directory does not exist. This is most likely because the test data is not installed. You may need to install matplotlib from source to get the test data.
```

Screenshots below illustrate the errors. The last screenshot illustrates successful search of `matplotlib`.
Screenshot 2023-04-24 at 9 23 58 AM
Screenshot 2023-04-24 at 9 25 05 AM
Screenshot 2023-04-24 at 9 23 42 AM

## Versions

* Spyder version: 5.5.0.dev0 00ebc4ad5 (conda)
* Python version: 3.10.10 64-bit
* Qt version: 5.15.6
* PyQt5 version: 5.15.7
* Operating System: Darwin 22.4.0

### Dependencies

```
# Mandatory:
applaunchservices >=0.3.0                        :  0.3.0 (OK)
atomicwrites >=1.2.0                             :  1.4.1 (OK)
chardet >=2.0.0                                  :  5.1.0 (OK)
cloudpickle >=0.5.0                              :  2.2.1 (OK)
cookiecutter >=1.6.0                             :  2.1.1 (OK)
diff_match_patch >=20181111                      :  20200713 (OK)
intervaltree >=3.0.2                             :  3.0.2 (OK)
IPython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0 :  8.12.0 (OK)
jedi >=0.17.2,<0.19.0                            :  0.18.2 (OK)
jellyfish >=0.7                                  :  0.9.0 (OK)
jsonschema >=3.2.0                               :  4.17.3 (OK)
keyring >=17.0.0                                 :  23.13.1 (OK)
nbconvert >=4.0                                  :  7.3.1 (OK)
numpydoc >=0.6.0                                 :  1.5.0 (OK)
parso >=0.7.0,<0.9.0                             :  0.8.3 (OK)
pexpect >=4.4.0                                  :  4.8.0 (OK)
pickleshare >=0.4                                :  0.7.5 (OK)
psutil >=5.3                                     :  5.9.4 (OK)
pygments >=2.0                                   :  2.15.0 (OK)
pylint >=2.5.0,<3.0                              :  2.17.2 (OK)
pylint_venv >=2.1.1                              :  3.0.1 (OK)
pyls_spyder >=0.4.0                              :  0.4.0 (OK)
pylsp >=1.7.2,<1.8.0                             :  1.7.2 (OK)
pylsp_black >=1.2.0                              :  1.2.1 (OK)
qdarkstyle >=3.0.2,<3.2.0                        :  3.1 (OK)
qstylizer >=0.2.2                                :  0.2.2 (OK)
qtawesome >=1.2.1                                :  1.2.3 (OK)
qtconsole >=5.4.2,<5.5.0                         :  5.5.0.dev0 (OK)
qtpy >=2.1.0                                     :  2.3.1 (OK)
rtree >=0.9.7                                    :  1.0.1 (OK)
setuptools >=49.6.0                              :  67.6.1 (OK)
sphinx >=0.6.6                                   :  6.1.3 (OK)
spyder_kernels >=2.4.3,<2.5.0                    :  2.5.0.dev0 (OK)
textdistance >=4.2.0                             :  4.5.0 (OK)
three_merge >=0.1.1                              :  0.1.1 (OK)
watchdog >=0.10.3                                :  3.0.0 (OK)
zmq >=22.1.0                                     :  25.0.2 (OK)

# Optional:
cython >=0.21                                    :  0.29.34 (OK)
matplotlib >=3.0.0                               :  3.7.1 (OK)
numpy >=1.7                                      :  1.24.2 (OK)
pandas >=1.1.1                                   :  2.0.0 (OK)
scipy >=0.17.0                                   :  1.10.1 (OK)
sympy >=0.7.3                                    :  1.11.1 (OK)
```

### PR DESCRIPTION
**Pull request by mrclary**
## Description of Changes

* Added handling of attributes that are classified as "readonly property", consistent with mechanisms in `pydoc.HTMLDoc`. This was the cause for `numpy` and `pandas` errors.
* Added error handling for `ModuleScanner`, consistent with mechanisms existing in `pydoc._url_handler`. This was the cause for keyword search errors.
* Updated unit tests. I believe that the root cause that motivated the skip filters may be the same issues that are remedied here and therefore the filters can be discarded.

### Issue(s) Resolved

Fixes #20866

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ccordoba12** [comment]
Thanks @mrclary for your help with this problem!

@dalthviz, could you take a look at this PR? I think you're the one that knows best how the Online Help works.

**Comment by mrclary** [comment]
So, it appears to me that `pydoc_patch.py` is largely a copy-paste from `pydoc.py`, with some tweaks for css and some other styling. I believe that these issues may have manifested in other projects and `pydoc` was subsequently updated, but, of course we don't get those benefits in `pydoc_patch.py`.

I don't know if anything can be done to better patch `pydoc` so that this doesn't happen again. 🤷🏼 But that will be for someone else at some other time.

**Comment by ccordoba12** [comment]
> But that will be for someone else at some other time.

Agreed.

**Comment by dalthviz** [comment]
>I believe that these issues may have manifested in other projects and pydoc was subsequently updated, but, of course we don't get those benefits in pydoc_patch.py.
>
>I don't know if anything can be done to better patch pydoc so that this doesn't happen again. 🤷🏼 But that will be for someone else at some other time.

Could be worthy to open a new issue about that?

**Review by dalthviz — APPROVED** [review]
Thanks @mrclary ! LGTM :+1:

**Comment by ccordoba12** [comment]
> Could be worthy to open a new issue about that?

I don't think so because we're not planning to take action on it for now.

**Comment by mrclary** [comment]
> > Could be worthy to open a new issue about that?
> 
> I don't think so because we're not planning to take action on it for now.

Oops. Already created it, although I tagged it as wishlist. I can close it if you prefer.

**Comment by ccordoba12** [comment]
Nop, that's fine.

**Pull request merged**
