### PR TITLE
Rename Object Inspector plugin to Help

### LINKED ISSUE #2376: Rename Object Inspector plug-in
I am not sure if Object Inspector is the right name for the inline help / documentation plug-in. What do you think?

### PR DESCRIPTION
**Pull request by ccordoba12**
Fixes #2376

----

This is because **Help** is easier to understand and grasp than **Object Inspector**

### CODE REVIEW

**Comment by ccordoba12** [comment]
Ok, this is ready! :-)

**Comment by goanpeca** [comment]
@ccordoba12 and what about the online help plugin?

**Comment by ccordoba12** [comment]
Yep, we should also rename it to avoid confusions with the new Help plugin.

What name do you propose?

**Comment by goanpeca** [comment]
Online Documentation?

**Comment by ccordoba12** [comment]
Well, it's not precisely *online*, in the sense that's somewhere on the web. It's the documentation generated by `pydoc` :-)

So I don't know about a good name.

**Comment by blink1073** [comment]
`Reference Documentation`?

**Pull request merged**
