### PR TITLE
PR: Finalise kernel shutdown in a thread

### PR DESCRIPTION
**Pull request by impact27**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Wait for shutdown but in a thread to avoid blocking.

### Issue(s) Resolved

Fixes https://github.com/spyder-ide/spyder-kernels/issues/197

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct:

### CODE REVIEW

**Comment by ksunden** [comment]
Can confirm, this does fix the issue I was having

**Comment by ksunden** [comment]
It does work, however I do get an additional error message (with no immidiatly visible side effects):
```
QObject::killTimer: Timers cannot be stopped from another thread
```

**Comment by ccordoba12** [comment]
@ksunden, please let us know if the last @impact27 commit fixed the error message you posted above so we can merge this one.

**Comment by ksunden** [comment]
Yes indeed, the error message is gone

**Pull request merged**
