### PR TITLE
PR: Remove `check_spyder_kernels`

### LINKED ISSUE #17005: Bump/remove outdated `spyder-kernerls` `requirements.py` version validation and Spyder crashing
## Problem Description

Spyder crashes (without error message) when starting after updating to newest version 5.2.0 on Windows with the windows installer, when the python interpretor is set to a version which uses an outdated spyder kernel. 

### What steps reproduce the problem?

set Python interpreter in preferences to python version with outdated spyder kernel. Usually an error message appears in the console in such a situatino. But after the update to 5.2.0, Spyder just crashes without any error message. After Performing a Spyder --reset it started again. After Setting again to another python version, it crashed again.

### What is the expected output? What do you see instead?
Spyder wont start, but crashes. Even when using a wrong spyder-kernel version, the program should start up and display an error message, but it does not, just crashes

## Versions
Spyder 5.2.0
Python Version 3.9
Spyder Kernel Version 2.1.0
Windows 10

### PR DESCRIPTION
**Pull request by dalthviz**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [ ] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Outadated validation for `spyder-kernels` version at `spyder/requirements.py`

### Issue(s) Resolved

Fixes #17005 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: dalthviz

### CODE REVIEW

**Review by ccordoba12 — COMMENTED** [review]
@dalthviz, thanks a lot for looking into this! Instead of fixing `check_spyder_kernels`, I think we should simply remove it.

The thing is added that check in Spyder 3 (if I'm not mistaken) to verify that people didn't have Spyder-kernels 1.0+ installed, which was incompatible. But now that shouldn't be a problem anymore.

**Review by ccordoba12 — DISMISSED** [review]
Looks good to me now, thanks @dalthviz!

**Comment by dalthviz** [comment]
Note: Needs a rebase after https://github.com/spyder-ide/spyder/pull/17015 get merged

**Review by ccordoba12 — APPROVED** [review]
Thanks @dalthviz!

**Pull request merged**
