### PR TITLE
PR: Change of all strings displayed to the user from `Python script` to `Python file`

### PR DESCRIPTION
**Pull request by jsbautista**
## Description of Changes
Change of all strings displayed to the user from "Python script" to "Python file"

### Issue(s) Resolved

Fixes https://github.com/spyder-ide/ux-improvements/issues/29

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: @jsbautista

### CODE REVIEW

**Comment by jsbautista** [comment]
Hi!! @dalthviz

**Comment by ccordoba12** [comment]
Hey @jsbautista, nice to see you here! Please don't worry about the failing tests. That's unrelated to your work, which is exactly what we needed in this case.

**Comment by dalthviz** [comment]
Hi @jsbautista please rebase your branch on top of the latest 5.x to fix the tests. For that you will need to run something like the following (if you already have an `upstream` remote pointing to the spyder-ide/spyder repo):

```
git fetch upstream
git checkout 5.xIssue29
git rebase upstream/5.x
git push -f
```

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @jsbautista!

**Review by dalthviz — APPROVED** [review]
Thanks @jsbautista !

**Pull request merged**
