### PR TITLE
PR: Show the context menu with disabled options in the file explorer when it is empty

### LINKED ISSUE #13004: Right-clicking an empty folder doesn't show the context menu of the Files pane
Entering inside a folder without elements and then right clicking inside it doesn't show the context menu of the Files pane:
explorer1

_Originally posted by @dalthviz in https://github.com/spyder-ide/spyder/pull/12401#issuecomment-642978296_

### PR DESCRIPTION
**Pull request by steff456**
## Description of Changes

* [ ] Wrote at least one-line docstrings (for any new functions)
* [ ] Added unit test(s) covering the changes (if testable)

* [x] Included a screenshot or animation (if affecting the UI, see [Licecap](https://www.cockos.com/licecap/))

Add an empty element to the filenames in case there's not any filename selected in the files explorer. In this way, the context menu will be visible in Windows.

prueba

### Issue(s) Resolved

Fixes #13004 

### Affirmation

By submitting this Pull Request or typing my (user)name below,
I affirm the [Developer Certificate of Origin](https://developercertificate.org)
with respect to all commits and content included in this PR,
and understand I am releasing the same under Spyder's MIT (Expat) license.

I certify the above statement is true and correct: Steff456

### CODE REVIEW

**Comment by steff456** [comment]
@ccordoba12 checking the errors that @dalthviz found, they are also happening on 4.x branch in macOS and Linux.

It happens because there's not any filenames to `move`. Also the absolute and relative path is given from the filenames in the directory. So we wanted to ask you if we will prefer to have only the create option menu available,

image

Or to put the complete context menu with those options not activated?

**Comment by ccordoba12** [comment]
> It happens because there's not any filenames to move. Also the absolute and relative path is given from the filenames in the directory. So we wanted to ask you if we will prefer to have only the create option menu available,

That makes a lot of sense. Please implement that.

**Comment by steff456** [comment]
Now the context menu is disabled and the user can only create new things in all OS

image

**Comment by dalthviz** [comment]
Seems like any action of the ones enabled works @steff456 :/ :

explorer

Maybe all of the actions need at least one element to work inside the directory?

**Pull request merged**
